### ISSUE TITLE
How to perform pFBA 10000 times with sampling by optGpSampler?

### ISSUE THREAD

**Issue by zhangzn19** [opencobra/cobrapy#1007]
### Checklist

- [X] I searched the [documentation](https://cobrapy.readthedocs.io).
- [X] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [X] I looked up "How to do ... in cobrapy" on a search engine.

### Question

I do not understand how to perform pFBA 10000 times with sampling by optGpSampler, so could you please give me a simple example code.

**Comment by Midnighter** [comment]
A typical comment that you get on code Q&A sites like https://stackoverflow.com/ is, what have you tried so far? Can you show us a few lines of code of your attempts, please?

**Comment by zhangzn19** [comment]
> A typical comment that you get on code Q&A sites like https://stackoverflow.com/ is, what have you tried so far? Can you show us a few lines of code of your attempts, please?

thank you for fast reply
and below is my code of sampling of a model
```python
import cobra
model = cobra.io.read_sbml_model('../iJO1366.xml')
from cobra.sampling import sample
s = sample(model, 10000, processes=4) # sample the model 10000 times
s.mean(0)  # calculate average flux of each reaction sampled by 10000 times
```

and result was the average flux of each reaction  after 10000 times sample

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gj7w8ywtcfj30cw0a6dh6.jpg)

but I do not understand the methods description underlined by red line below:

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gj7x6om1p6j325i0kme0d.jpg)

and above methods description was from this article [A White-Box Machine Learning Approach for
Revealing Antibiotic Mechanisms of Action](https://www.sciencedirect.com/science/article/pii/S0092867419304027)

so what is the meaning of "perform pFBA 10000 times with sampling by optGpSampler and compute mean flux across all 10,000 samples"

**Comment by Midnighter** [comment]
Thank you for the additional info @zhangzn19. It'll be much easier to help you now. @cdiener is the most experienced dev when it comes to sampling, I think, so maybe you have an idea?

My immediate take would be to add parsimonious constraints to the model before sampling. Something like the following code. But I didn't test it.

```py
import cobra
from cobra.flux_analysis.parsimonious import add_pfba
from cobra.sampling import sample

model = cobra.io.read_sbml_model('../iJO1366.xml')
add_pfba(model)
s = sample(model, 10000, processes=4) # sample the model 10000 times
s.mean(0)  # calculate average flux of each reaction sampled by 10000 times
```

**Comment by gregmedlock** [comment]
In addition to the recommendation made by @Midnighter I suggest you take a look at GapSplit from Paul Jensen's lab: https://academic.oup.com/bioinformatics/article/36/8/2623/5698269

It's been a while since I made the comparison, but I did some sampling with pFBA constraints/objective in the past and remembering GapSplit being substantially faster than the methods currently implemented in cobrapy. I recommend you try it out if you are having performance issues: https://github.com/jensenlab/gapsplit

**Comment by zhangzn19** [comment]
> Thank you for the additional info @zhangzn19. It'll be much easier to help you now. @cdiener is the most experienced dev when it comes to sampling, I think, so maybe you have an idea?
> 
> My immediate take would be to add parsimonious constraints to the model before sampling. Something like the following code. But I didn't test it.
> 
> ```python
> import cobra
> from cobra.flux_analysis.parsimonious import add_pfba
> from cobra.sampling import sample
> 
> model = cobra.io.read_sbml_model('../iJO1366.xml')
> add_pfba(model)
> s = sample(model, 10000, processes=4) # sample the model 10000 times
> s.mean(0)  # calculate average flux of each reaction sampled by 10000 times
> ```

thank you for your kindfuly code and it worked well in my machine

best regards,
zhongnan

**Comment by zhangzn19** [comment]
> In addition to the recommendation made by @Midnighter I suggest you take a look at GapSplit from Paul Jensen's lab: https://academic.oup.com/bioinformatics/article/36/8/2623/5698269
> 
> It's been a while since I made the comparison, but I did some sampling with pFBA constraints/objective in the past and remembering GapSplit being substantially faster than the methods currently implemented in cobrapy. I recommend you try it out if you are having performance issues: https://github.com/jensenlab/gapsplit

thank you for your recommendation, I will try GapSplit sampling methods after.
best regards,
zhongnan

**Comment by Midnighter** [comment]
Great, I'm glad this worked for you. I will close the issue then but feel free to reopen it if you have further questions on this topic.
