### ISSUE TITLE
model.problem.Objective throws an error

### ISSUE THREAD

**Issue by pcuevas-ch** [opencobra/cobrapy#1008]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

**Comment by Midnighter** [comment]
Please provide more context for your problem. I will re-open the issue when you do.
