### ISSUE TITLE
error in model.problem.Objective()

### ISSUE THREAD

**Issue by pcuevas-ch** [opencobra/cobrapy#1009]
Hello everyone! I have an issue with this command. I would like to change the objective function in the model to a linear combination of some fluxes of interest, but when I try to do this with model.problem.Objective() Cobrapy throws the error:

```python 
AttributeError: 'Model' object has no attribute 'problem'
```

Thank you in advance for any light about this.

**Comment by Midnighter** [comment]
Can you please show the code how you created your `model` object?

Also, please provide the output of `python -c "import cobra;print(cobra.show_versions())"`.
