### ISSUE TITLE
Dual optimization (?)

### ISSUE THREAD

**Issue by rcolpo** [opencobra/cobrapy#1015]
Is it possible to find the minimal growth media for the model to grow, such that the model does not grow in a second media?
Is it possible to include such a constrain to the optimization problem?
Thank you.

**Comment by Midnighter** [comment]
I'm not sure what exactly you are trying to achieve. If you find some minimal medium that supports growth of your model, adding more components to that medium will always continue to allow growth. So how exactly do you want to define that second medium?

**Comment by rcolpo** [comment]
Dear Moritz, Thank you for your feedback. I will describe my problem better.
I have one negative control media, without carbon sources, and several other media with carbon sources. Initially, the model does not grow in any media. To make the model capable of growing in at least one media, I have a set of metabolites that can be added to the external media. I'm trying to find out the minimum set of metabolites that are to be included in every media, so that the model does not grow in the negative control, but grows in at least one of the media with carbon sources.
The model does not need to grow in every carbon source.
A different way of formulating the same problem, would be to initially include this set of extra metabolites to every media, and then remove metabolites so that the model does not grow in the negative-control media, but it still grows in at least one of the carbon sources.
Do you have any idea on how to achieve this?
Thank you.

**Comment by Midnighter** [comment]
@cdiener since you wrote the minimal medium code, maybe you have an immediate insight?

**Comment by rcolpo** [comment]
Another approach would be to add the extra set of metabolites to a non-control medium, and delete reactions from this extra set to force the carbon source to be essential - finding a subset of the original extra set of metabolites. Because the difference between the control and no-control medium is just a carbon source, and now the carbon source is essential, the model would not grow in the control medium, and grow in the non-control medium.

**Comment by rcolpo** [comment]
I managed to solve this problem using a modified version of the function minimal_medium. However, I have noticed a scenario when the minimal_medium returns a wrong solution. 

The function works if the exchange reactions are defined as 
A_e <=>
But it returns a wrong result if the exchange reactions are defined as:
 <=> A_e

Is this really de desired behavior?

**Comment by cdiener** [comment]
Sorry for the late reply. There are many ways to address this. One is to modify the the objective so that you penalize the unwanted medium. Another one is to get the essential reactions for the minimal medium and the negative medium and then knocking a reaction that is in the second set but not in the first. Negative media are often under-determined though and can often be achieved with a single knockout so some care has to be taken with biological interpretations. 

I did not completely get your exchange notation in that last comment. If you have a minimal example for that case where it does not work that would be great.

**Comment by rcolpo** [comment]
(I edited my last comment, and hopefully my notation is clear now.)
I was initially getting a wrong result with the function minimal_medium because of my uncommon notation. 
In the conventional notation of a a exchange reaction, the metabolite is on the left side, but I was putting it on the right side. For example, my "wrong" notation causes an error in 

```
for rxn in find_boundary_types(model, "exchange"):
	export = len(rxn.reactants) == 1
	if export:
		coefs[rxn.reverse_variable] = 1
	else:
		coefs[rxn.forward_variable] = 1
```

and because my notation is flipped, "rxn.reverse_variable" and "rxn.forward_variable" should also be flipped. 
Maybe I'm the only person using the strange notation, and it is not necessary to change the function. However, I should definitely change my notation :) 
Thank you for all the support.

**Comment by cdiener** [comment]
The code you pasted is there to support both notations. In your case the else clause should have triggered and it should work. What is the wrong behavior you get?

**Comment by rcolpo** [comment]
Oh! Now I see! So sorry for my mistake and thank you very much for your patience.
