### ISSUE TITLE
OverflowError when sampling

### ISSUE THREAD

**Issue by pbordron** [opencobra/cobrapy#1016]
#### Problem description

I try to generate a huge flux sampling with `optgp` method. Around 1 million samples.
I get the following error during the computation. This error occurs with `python 3.7`, but not with `python 3.8`
However, as I need `cplex` or `gurobi` for next steps of my analysis, I must stick to  `python 3.7` until those solvers support `python 3.8+`

```bash
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(0, array([[6.30115911e-06, 0.00000000e+00, 1.21627395e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.30124544e-06, 0.00000000e+00, 1.30249123e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.32567071e-06, 0.00000000e+00, 1.30247105e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.17100438e-01, 0.00000000e+00, 3.49562681e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.16903736e-01, 0.00000000e+00, 3.48866572e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.15490326e-01, 0.00000000e+00, 3.49157214e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]))]'. Reason: 'OverflowError('cannot serialize a bytes object larger than 4 GiB')'
```
I suspect `python 3.8` doesn't fail because of the following change in pickle:
https://docs.python.org/3/whatsnew/3.8.html#pickle-protocol-5-with-out-of-band-data-buffers

#### Code Sample

Here a minimal example `test_sampling.py` that reproduce the error: 

```python
import cobra.io
from cobra.sampling import sample
model = cobra.io.load_model("iML1515")
s = sample(model, 1000000, thinning=100, processes=10, method = "optgp")
```

### Context

For reproducing the error, following `conda` environment is enough:

```bash
conda create -n test-sampling-3.7 python=3.7 cobra=0.20
conda activate test-sampling-3.7
python test_sampling.py
```

Changing python version allows to succeed the computation:

```bash
conda create -n test-sampling-3.8 python=3.8 cobra=0.20
conda activate test-sampling-3.8
python test_sampling.py
```

**Comment by cdiener** [comment]
Yep it's a limit with the amount of data a single process can send. However you can work around that using batch sampling. Basically instead of sampling 1e8 samples you can sample 1000 batches of 1e5 samples. Those you can collect in a single Python object if you have the RAM or write it to a file. See https://cobrapy.readthedocs.io/en/latest/sampling.html#Batch-sampling. This will still run in parallel and as long as the batches are large (>1000 samples) there will be no overhead.

**Comment by cdiener** [comment]
Closing for now since that seems like a limitation of Python itself and there are simple workarounds...
