### ISSUE TITLE
ModuleNotFoundError: No module named 'plot_helper'

### ISSUE THREAD

**Issue by ryusukemomota** [opencobra/cobrapy#1018]
I'm trying to test the section 8 "Loopless FBA", but I couldn't import plot_helper module.
Any changes have been made for this module?
Thanks in advance.

**Comment by cdiener** [comment]
Yeah, that won't be available in a normal install. It is just used to draw the example loop in the notebook. For now you can just skip this import and everything should work.

**Comment by synchon** [comment]
I am guessing this: [https://pypi.org/project/plot-helper/](https://pypi.org/project/plot-helper/) was used and I could add a comment in the cell to indicate that. Is that okay?

**Comment by synchon** [comment]
Okay I think I was wrong and I believe the module comes from [https://github.com/opencobra/cobrapy/blob/devel/documentation_builder/plot_helper.py](https://github.com/opencobra/cobrapy/blob/devel/documentation_builder/plot_helper.py).

**Comment by cdiener** [comment]
This has been removed from the docs.
