### ISSUE TITLE
installation via anaconda

### ISSUE THREAD

**Issue by elnormo** [opencobra/cobrapy#1020]
#### Problem description

Please explain:
* **what**: installed anaconda, upgraded to latest version. Tried to install cobrapy.
* **how**: followed the instructions in  as described in https://github.com/opencobra/cobrapy/blob/devel/INSTALL.rst.
```
conda install -c bioconda cobra
```
* **why**: Installation failed.
```(base) C:\Users\vinsonn>conda install -c bioconda cobra
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Please note: cobrapy does not appear as a package in the bioconda channel in Anaconda navigator.

See also https://groups.google.com/g/cobra-pie/c/jZUE-Xt2g3M (reported by someone else)

**Comment by cdiener** [comment]
Hmm, works for me. And it is visible on bioconda: https://bioconda.github.io/recipes/cobra/README.html.

**Comment by pluthert** [comment]
Hi
Getting precisely the same error with fresh install of miniconda and creation of environment
conda create --name cobra python=3.8
activate cobra
conda install -c bioconda cobra

I am using Windows 10. Might the OS be the difference between elnormo and cdiener?

Curiously pip install cobra did work even though I couldn't get it to install using pip from a python only set up (ie without miniconda).

New to python and it is all a bit confusing!

**Comment by cdiener** [comment]
Oh yeah that is it. Bioconda does not support windows, only linux and mac. You can still install it on windows with pip using `pip install cobra`.

**Comment by pluthert** [comment]
Thanks!

**Comment by cdiener** [comment]
Cobrapy is now in conda-forge and can be installed on all OSs with `conda install -c conda-forge cobra`.

**Comment by danolson1** [comment]
If conda is a recommend method of installing cobra, can this be added to the documentation?

Right now, the [main documentation](https://github.com/opencobra/cobrapy?tab=readme-ov-file) says to use pip.

The [detailed installation instructions](https://github.com/opencobra/cobrapy/blob/devel/INSTALL.rst) say to use pip for linux and mac, but cobra for windows.

The [anaconda website](https://anaconda.org/conda-forge/cobra) says cobra is a noarch package, and is compatible with linux, mac, and windows.
