### ISSUE TITLE
Exception: GLPK could not successfully create the GLPK file.

### ISSUE THREAD

**Issue by Kevinkaiyan** [opencobra/cobrapy#1021]
Dear contributor:
When I load the test model and run the FBA analysis, it runs successfully like this:
![image](https://user-images.githubusercontent.com/49591512/99015528-2e76fb80-2590-11eb-8521-c13e91a513d2.png)
But when I run FVA analysis, he will get the following error:
![image](https://user-images.githubusercontent.com/49591512/99015592-58302280-2590-11eb-852d-55c473522b58.png)
![image](https://user-images.githubusercontent.com/49591512/99015603-5f573080-2590-11eb-807c-7777973bc2f4.png)
I am eager to know how to solve this problem, many thanks!

**Comment by cdiener** [comment]
Hi, this happens during pickling. It looks like python can't write to the temporary file location. What Windows and Python version are you running? Could you give more info as stated in the issue template, especially the following part:

---

Please run the following code and paste the output between the ``` tickmarks below
inside the details block.

python -c "import cobra;cobra.show_versions()"


<details>

```
```

</details>

---

**Comment by 17321010162** [comment]
Hello, many thanks for your reply, my information are as follows:
![image](https://user-images.githubusercontent.com/49591512/99023090-db587500-259e-11eb-9828-560e4f65edc0.png)


> Hi, this happens during pickling. It looks like python can't write to the temporary file location. What Windows and Python version are you running? Could you give more info as stated in the issue template, especially the following part:
> 
> Please run the following code and paste the output between the ``` tickmarks below
> inside the details block.
> 
> python -c "import cobra;cobra.show_versions()"

**Comment by 17321010162** [comment]
Hello, many thanks for your reply, my information are as follows:
![image](https://user-images.githubusercontent.com/49591512/99023202-0e9b0400-259f-11eb-84e7-3db241122afa.png)


> Hi, this happens during pickling. It looks like python can't write to the temporary file location. What Windows and Python version are you running? Could you give more info as stated in the issue template, especially the following part:
> 
> Please run the following code and paste the output between the ``` tickmarks below
> inside the details block.
> 
> python -c "import cobra;cobra.show_versions()"

**Comment by 17321010162** [comment]
Hello, many thanks for your reply! My information are as follows:
![image](https://user-images.githubusercontent.com/49591512/99023238-1d81b680-259f-11eb-8189-62db6ac46cb0.png)

**Comment by 17321010162** [comment]
Hello, many thanks for your reply! My information are as follows:

System Information
==================
OS         Windows
OS-release      10
Python       3.8.3

Package Versions
================
appdirs (~=1.4)                              not installed
black ; extra == 'development'               not installed
bumpversion ; extra == 'development'         not installed
cobra                                               0.20.0
depinfo                                              1.6.0
diskcache (~=5.0)                            not installed
future                                              0.18.2
httpx (~=0.14)                               not installed
importlib-resources                                  3.3.0
isort                                               4.3.21
numpy (~=1.13)                               not installed
optlang (<1.4.6)                             not installed
pandas (~=1.0)                               not installed
pip                                                 20.1.1
pydantic (~=1.6)                             not installed
python-libsbml-experimental (==5.18.3)       not installed
rich (~=6.0)                                 not installed
ruamel.yaml (~=0.16)                         not installed
scipy                                                1.5.0
setuptools                             49.2.0.post20200714
six                                                 1.15.0
swiglpk                                             4.65.1
tox ; extra == 'development'                 not installed
wheel                                               0.34.2

**Comment by 17321010162** [comment]
Hello, many thanks for your reply! My information are as follows:
![image](https://user-images.githubusercontent.com/49591512/99023465-a3056680-259f-11eb-85cf-72b45bd8a561.png)

**Comment by 17321010162** [comment]
System Information
==================
OS         Windows
OS-release      10
Python       3.8.3

Package Versions
================
appdirs (~=1.4)                              not installed
black ; extra == 'development'               not installed
bumpversion ; extra == 'development'         not installed
cobra                                               0.20.0
depinfo                                              1.6.0
diskcache (~=5.0)                            not installed
future                                              0.18.2
httpx (~=0.14)                               not installed
importlib-resources                                  3.3.0
isort                                               4.3.21
numpy (~=1.13)                               not installed
optlang (<1.4.6)                             not installed
pandas (~=1.0)                               not installed
pip                                                 20.1.1
pydantic (~=1.6)                             not installed
python-libsbml-experimental (==5.18.3)       not installed
rich (~=6.0)                                 not installed
ruamel.yaml (~=0.16)                         not installed
scipy                                                1.5.0
setuptools                             49.2.0.post20200714
six                                                 1.15.0
swiglpk                                             4.65.1
tox ; extra == 'development'                 not installed
wheel                                               0.34.2

**Comment by 17321010162** [comment]
![image](https://user-images.githubusercontent.com/49591512/99023867-76058380-25a0-11eb-8fe6-461ca2bd1fe6.png)

**Comment by 17321010162** [comment]
![微信截图_20201113105905](https://user-images.githubusercontent.com/49591512/99023939-9b928d00-25a0-11eb-950d-ebe095488729.png)

**Comment by 17321010162** [comment]
![20201113105905](https://user-images.githubusercontent.com/49591512/99023998-b95ff200-25a0-11eb-805c-fbb470b52e07.png)

**Comment by 17321010162** [comment]
Hello, many thanks for your reply! My informations are as follows:
System Information
==================
OS                      Windows
OS-release         10
Python               3.8.3

Package Versions
================
appdirs (~=1.4)                                                   not installed
black ; extra == 'development'                           not installed
bumpversion ; extra == 'development'              not installed
cobra                                                                   0.20.0
depinfo                                                                1.6.0
diskcache (~=5.0)                                                not installed
future                                                                   0.18.2
httpx (~=0.14)                                                      not installed
importlib-resources                                              3.3.0
isort                                                                      4.3.21
numpy (~=1.13)                                                   not installed
optlang (<1.4.6)                                                   not installed
pandas (~=1.0)                                                    not installed
pip                                                                       20.1.1
pydantic (~=1.6)                                                  not installed
python-libsbml-experimental (==5.18.3)            not installed
rich (~=6.0)                                                          not installed
ruamel.yaml (~=0.16)                                          not installed
scipy                                                                    1.5.0
setuptools                                                           49.2.0.post20200714
six                                                                        1.15.0
swiglpk                                                                4.65.1
tox ; extra == 'development'                              not installed
wheel                                                                   0.34.2

**Comment by 17321010162** [comment]
System Information
==================
OS                   Windows
OS-release      10
Python            3.8.3

Package Versions
================
appdirs (~=1.4): not installed
black ; extra == 'development': not installed
bumpversion ; extra == 'development'         not installed
cobra                                               0.20.0
depinfo                                              1.6.0
diskcache (~=5.0)                            not installed
future                                              0.18.2
httpx (~=0.14)                               not installed
importlib-resources                                  3.3.0
isort                                               4.3.21
numpy (~=1.13)                               not installed
optlang (<1.4.6)                             not installed
pandas (~=1.0)                               not installed
pip                                                 20.1.1
pydantic (~=1.6)                             not installed
python-libsbml-experimental (==5.18.3)       not installed
rich (~=6.0)                                 not installed
ruamel.yaml (~=0.16)                         not installed
scipy                                                1.5.0
setuptools                             49.2.0.post20200714
six                                                 1.15.0
swiglpk                                             4.65.1
tox ; extra == 'development'                 not installed
wheel                                               0.34.2

**Comment by 17321010162** [comment]
System Information
==================
OS         Windows
OS-release      10
Python       3.8.3

Package Versions
================
appdirs(~=1.4):not installed
black ; extra == 'development'               not installed
bumpversion ; extra == 'development'         not installed
cobra                                               0.20.0
depinfo                                              1.6.0
diskcache (~=5.0)                            not installed
future                                              0.18.2
httpx (~=0.14)                               not installed
importlib-resources                                  3.3.0
isort                                               4.3.21
numpy (~=1.13)                               not installed
optlang (<1.4.6)                             not installed
pandas (~=1.0)                               not installed
pip                                                 20.1.1
pydantic (~=1.6)                             not installed
python-libsbml-experimental (==5.18.3)       not installed
rich (~=6.0)                                 not installed
ruamel.yaml (~=0.16)                         not installed
scipy                                                1.5.0
setuptools                             49.2.0.post20200714
six                                                 1.15.0
swiglpk                                             4.65.1
tox ; extra == 'development'                 not installed
wheel                                               0.34.2

**Comment by 17321010162** [comment]
![image](https://user-images.githubusercontent.com/49591512/99033355-ac99c900-25b5-11eb-921d-b7b74b1a054b.png)

**Comment by Kevinkaiyan** [comment]
Hello, many thanks for your reply! Here is my information:
![image](https://user-images.githubusercontent.com/49591512/99033412-c89d6a80-25b5-11eb-99a7-bf855dfd1bb2.png)

**Comment by cdiener** [comment]
Hmm, that is the same setup as our test runner and it works there. Looks like it might be some problem with the local setup. For now, you can probably work around that by using `flux_variability_analysis(model, model.reactions[:10], processes=1)`.
