### ISSUE TITLE
Something went wrong reading the SBML model

### ISSUE THREAD

**Issue by ibrfakih** [opencobra/cobrapy#1027]
Hello,
While importing a model.sbml 
using model=cobra.io.read_sbml_model("model.sbml") an error message is displayed: 

**Model does not contain SBML fbc package information.
SBML package 'layout' not supported by cobrapy, information is not parsed
SBML package 'render' not supported by cobrapy, information is not parsed**

Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .

NB: I checked the file and the SBML is valid with a lot of warnings. The think ythe problem came from the fbc package info that I don't have any idea how to include it in the model sbml file

**Comment by Midnighter** [comment]
Hi @ibrfakih, can you check whether you can load the model with an older cobrapy version, please? You can try with version 0.13.4, for example, type `pip install cobra==0.13.4` in a console to do so.

**Comment by cdiener** [comment]
Note that those are all just warnings. The actual error should appear somewhere else in the output. Could you post the entire output when reading? Also, the model might still have been read. What does `print(model)` give you after reading?

**Comment by matthiaskoenig** [comment]
@ibrfakih Could you post the model or the actual error message. Like stated above most of these are warnings.
