### ISSUE TITLE
FBA of the example model in the documentation always returns 0

### ISSUE THREAD

**Issue by ixy90** [opencobra/cobrapy#1028]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question

I have an issue with building my own model and doing FBA on it. After it didn't work with my own model I tried to copy and paste everything from chapter 2 in the documentation and it still doesn't work. The solution is always 0.000. Except when I don't run `reaction.add_metabolites`, then the solution is 1000, but I do kind of want the metabolites.

Is there anything I am doing wrong or have I missed something simple? 

Here is the code I'm running:

```
import cobra
from __future__ import print_function
from cobra import Model, Reaction, Metabolite

model3 = Model('example_model')

reaction = Reaction('3OAS140')
reaction.name = '3 oxoacyl acyl carrier protein synthase n C140 ' 
reaction.subsystem = 'Cell Envelope Biosynthesis' 
reaction.lower_bound = 0. # This is the default 
reaction.upper_bound = 1000. # This is the default

ACP_c = Metabolite( 'ACP_c', formula='C11H21N2O7PRS', name='acyl-carrier-protein', compartment='c')
omrsACP_c = Metabolite( '3omrsACP_c', formula='C25H45N2O9PRS', name='3-Oxotetradecanoyl-acyl-carrier-protein', compartment='c')
co2_c = Metabolite('co2_c', formula='CO2', name='CO2', compartment='c') 
malACP_c = Metabolite('malACP_c', formula='C14H22N2O10PRS', name='Malonyl-acyl-carrier-protein',compartment='c')
h_c = Metabolite('h_c', formula='H', name='H', compartment='c') 
ddcaACP_c = Metabolite('ddcaACP_c', formula='C23H43N2O8PRS', name='Dodecanoyl-ACP-n-C120ACP', compartment='c')

reaction.add_metabolites({ malACP_c: -1.0,
h_c: -1.0, ddcaACP_c: -1.0, co2_c: 1.0, ACP_c: 1.0, omrsACP_c: 1.0
})

reaction.gene_reaction_rule = '( STM2378 or STM1197 )' 
reaction.genes

model3.add_reactions([reaction])

model3.objective = '3OAS140'

solution = model3.optimize() 
print(solution)
```

**Comment by A2P2** [comment]
Hi,

You do miss exchange reactions in your model. For an FBA analysis to have a solution >0 you need to have balanced uptake and secretion reactions for certain metabolites.

For your example model with one reaction you would need to have exchange reactions for all metabolites:
```
for metabolite in model3.metabolites:
    
    reaction = Reaction('EX_{}'.format(metabolite.id[:-2]))
    reaction.bounds = (-1000,1000)
    reaction.add_metabolites({metabolite: -1})
    
    model3.add_reactions([reaction])
```

I would advise checking existing test models in cobrapy to understand how they are structured:

```
import cobra.test

model = cobra.test.create_test_model("textbook")
print(model.summary())

print('Exchange reactions')
for reaction in model.exchanges:
    print(reaction)

print('All reactions')
for reaction in model.reactions:
    print(reaction)
```

**Comment by ixy90** [comment]
Thank you so much! That worked :))
