### ISSUE TITLE
Solution fluxes are different from model summary fluxes

### ISSUE THREAD

**Issue by danolson1** [opencobra/cobrapy#1029]
#### Problem description

Please explain:
I am trying to study the FBA output of a model, changing different growth substrates in the media. To do this, I'm mapping the solution fluxes to an Excher map. I noticed that the fluxes on my Escher map didn't match the fluxes from my metabolite summaries. The underlying reason is that the fluxes I get from model.metabolites.XXX.summary() are different than what I get from solution.fluxes.

It's also possible that this is due to a problem in my model, if so, how would I go about figuring out what's going on?

#### Code Sample
```
import pandas as pd
import cobra
import escher
from escher import Builder
import ipywidgets as widgets

model = cobra.io.load_json_model("iCBI655_cellobiose_batch.json")
s1 = model.optimize()
s2 = model.metabolites.atp_c.summary()

# compare flux for a particular reaction. Let's look at ACKr
# these values should be identical, but they're not
print(s1.fluxes['ACKr'])
print(s2.to_frame().loc['ACKr', 'flux'])
```

### Context

[iCBI655_cellobiose_batch.zip](https://github.com/opencobra/cobrapy/files/5846657/iCBI655_cellobiose_batch.zip)

```
System Information
==================
OS         Windows
OS-release      10
Python       3.8.5

Package Versions
================
appdirs (~=1.4)                              not installed
black ; extra == 'development'               not installed
bumpversion ; extra == 'development'         not installed
cobra                                               0.20.0
depinfo                                              1.6.0
diskcache (~=5.0)                            not installed
future                                              0.18.2
httpx (~=0.14)                               not installed
importlib-resources                                  5.0.0
isort ; extra == 'development'               not installed
numpy (~=1.13)                               not installed
optlang (<1.4.6)                             not installed
pandas (~=1.0)                               not installed
pip                                                 20.3.3
pydantic (~=1.6)                             not installed
python-libsbml-experimental (==5.18.3)       not installed
rich (~=6.0)                                 not installed
ruamel.yaml (~=0.16)                         not installed
scipy                                                1.5.2
setuptools                             51.3.3.post20210118
six                                                 1.15.0
swiglpk                                             4.65.1
tox ; extra == 'development'                 not installed
wheel                                               0.36.2
```

</details>

**Comment by cdiener** [comment]
I don't have access to your model but I don't see the same error when using the E. coli model:

```
In [4]: import pandas as pd
   ...: import cobra.test
   ...: 
   ...: model = cobra.test.create_test_model("ecoli")
   ...: s1 = model.optimize()
   ...: s2 = model.metabolites.atp_c.summary()
   ...: 
   ...: # compare flux for a particular reaction. Let's look at ACKr
   ...: # these values should be identical, but they're not
   ...: print(s1.fluxes['ACKr'])
   ...: print(s2.to_frame().loc['ACKr', 'flux'])
0.5723062411712343
-0.572306241171235
```

This is as intended at least and the sign difference is because ACKr consumes ATP...

**Comment by danolson1** [comment]
On the model I was using (see attached zip file), one version gave me 0 and the other gave me 10, so it wasn't just a sign issue. I found the same problem with the iAF1260 E. coli model, although not with some other E. coli models (iML1515 and iJO1366).

I think the problem is that calling the summary function generates a new solution, and this is not guaranteed to be identical to the previous solution. A simple fix would be to change the documentation to suggest that people specifically pass a solution to the summary function (or at least note the potential problem that could arise). A better solution would be to make sure that the default behavior of the summary method is to refer to the prior solution, and not to generate a new solution.

-Dan

**Comment by cdiener** [comment]
> I think the problem is that calling the summary function generates a new solution, and this is not guaranteed to be identical to the previous solution.

Yes, that is correct. You can use the `solution` argument to force it to use the previous solution: `s2 = model.metabolites.atp_c.summary(solution=s1)`.

**Comment by danolson1** [comment]
Yes, that's definitely what's going on.

Since the summary function is used for inspecting a solution, it seems
strange that the default behavior can give different results every time you
look at it. So although this is not technically a "bug," it seems like a
user interface problem that should be addressed, or at the very least,
mentioned in the documentation.

**Comment by cdiener** [comment]
Yes, a lot of that was already discussed in #900. I would also prefer it being static. Maybe @Midnighter can chime in as well.
