### ISSUE TITLE
cobrapy does not seem to work with libsbml 5.19

### ISSUE THREAD

**Issue by tillea** [opencobra/cobrapy#1030]
#### Problem description

I'm trying to update the cobrapy package in Debian to be up to date with the latest version in the next Debian stable release.  Debian has libsbml version 5.19.0 packaged.  When building against this version I get a lot of test suite errors that seem to be caused by incompatibilities with sbml.  For completeness and to let you know what versions are used here is a full build log:

[python-cobra_0.20.0-1_amd64.zip](https://github.com/opencobra/cobrapy/files/5867974/python-cobra_0.20.0-1_amd64.zip)

You can find the error messages at the end of the log.

Please let me know if I can provide any more detailed information.

Kind regards, Andreas.

**Comment by cdiener** [comment]
So it is kind of expected since the only supported version of libSBML is currently libsbml-experimental 5.18.3 (https://github.com/opencobra/cobrapy/blob/devel/setup.cfg#L65). @matthiaskoenig would know more about how feasible it would be to update the dependency.

**Comment by tillea** [comment]
On Tue, Jan 26, 2021 at 02:31:27PM -0800, Christian Diener wrote:
> So it is kind of expected since the only supported version of libSBML is currently libsbml-experimental 5.18.3 (https://github.com/opencobra/cobrapy/blob/devel/setup.cfg#L65).
Sure.  I have read this.  However, at the time of writing this restriction libsbml 5.19 was probably not released yet and thus it was not clear whether there might be any conflicts or not.  Thus I was simply trying.

> @matthiaskoenig would know more about how feasible it would be to update the dependency.
As I said this is simply needed if cobrapy should be delivered with the next Debian release.  I would like to do so but I have no idea how hard the adaption might be.

Kind regards, Andreas.

**Comment by Midnighter** [comment]
What is the deadline for wrapping up the packaging for the Debian release?

**Comment by tillea** [comment]
On Wed, Jan 27, 2021 at 02:20:42AM -0800, Moritz E. Beber wrote:
> What is the deadline for wrapping up the packaging for the Debian release?
According to the [Freeze Timeline](https://release.debian.org/bullseye/freeze_policy.html) its 2021-02-12 - but we probably need some days for the packaging and testing.  So well, to say it bluntly, its "right now". ;-)
Kind regards, Andreas.

**Comment by matthiaskoenig** [comment]
Should be no problem to update. Complete backwards compatibility.
Just write 
```
python-libsbml-experimental>=5.19.0
```
Making a pull request for this in a min.

**Comment by cdiener** [comment]
I think the version in debian is not the one with experimental features though. I guess that is why there were errors?

**Comment by matthiaskoenig** [comment]
It would be perfect if there would be some option for the dependencies to say:
try this package if not try this one, I.e. 
`python-libsbml-experimental >=5.19.0 OR python-libsbml >=5.19.0`

For cobrapy this should not make any difference, but for people working with cobrapy this could be important.
Basically `python-libsbml-experimental` is `python-libsbml` plus additional features and packages. If someone wants to use this additional features the experimental package is required.
Because `distrib` was released and is now in the python-libsbml package (at least for me an colleagues there is no need to have the experimental release any more and we could switch back to the non-experimental branch, i.e. use `python-libsbml>=5.19.0`. As far as I know I am one of the few people working with the experimental packages.

**Comment by cdiener** [comment]
I think the errors are actually related to https://github.com/biosustain/swiglpk/issues/39. The SBML error is only since it is kind of a catch all for exceptions when loading the textbook model which most tests do. Further down you can find the swiglpk errors:

```
...
    from sys import version_info as _swig_python_version_info
    if _swig_python_version_info < (2, 7, 0):
        raise RuntimeError("Python 2.7 or later required")
    
    # Import the low-level C/C++ module
    if __package__ or "." in __name__:
>       from . import _swiglpk
E       ImportError: /usr/lib/python3/dist-packages/swiglpk/_swiglpk.cpython-39-x86_64-linux-gnu.so: undefined symbol: glp_netgen_prob
...
```

Due to that bug cobrapy is currently not compatible with Python 3.9. I submitted a fix in https://github.com/biosustain/swiglpk/pull/42 a while ago but the maintainer has not responded yet.

**Comment by tillea** [comment]
On Wed, Jan 27, 2021 at 03:20:52PM -0800, Moritz E. Beber wrote:
> Closed #1030 via #1031.
Cool.  It would be absolutely great if you could issue a point release (0.20.1) featuring this patch.
Kind regards, Andreas.

**Comment by Midnighter** [comment]
> It would be perfect if there would be some option for the dependencies to say:
> try this package if not try this one, I.e.
> `python-libsbml-experimental >=5.19.0 OR python-libsbml >=5.19.0`
> 
> For cobrapy this should not make any difference, but for people working with cobrapy this could be important.
> Basically `python-libsbml-experimental` is `python-libsbml` plus additional features and packages. If someone wants to use this additional features the experimental package is required.
> Because `distrib` was released and is now in the python-libsbml package (at least for me an colleagues there is no need to have the experimental release any more and we could switch back to the non-experimental branch, i.e. use `python-libsbml>=5.19.0`. As far as I know I am one of the few people working with the experimental packages.

As I am not aware of a way to specify alternative dependencies, I think the best way forward is to go with `python-libsbml`. I'm assuming that if you need experimental features, you are advanced enough to simply uninstall libsbml and install libsbml-experimental in your environment after installing cobrapy.

**Comment by tillea** [comment]
On Sat, Feb 06, 2021 at 02:18:00AM -0800, Moritz E. Beber wrote:
> As I am not aware of a way to specify alternative dependencies, I think the best way forward is to go with `python-libsbml`. I'm assuming that if you need experimental features, you are advanced enough to simply uninstall libsbml and install libsbml-experimental in your environment after installing cobrapy.
If the Debian package should work there should be simply an option to work with python-libsbml.  Otherwise it will not be shipped with the next stable release.  BTW, we need a solution until tomorrow since the package will not meet the freeze deadline any more.
Kind regards, Andreas.

**Comment by Midnighter** [comment]
> BTW, we need a solution until tomorrow

My aim is to make a release tonight.

**Comment by tillea** [comment]
On Sat, Feb 06, 2021 at 05:20:37AM -0800, Moritz E. Beber wrote:
> My aim is to make a release tonight.
Thanks a lot for your great support!  Andreas.

**Comment by Midnighter** [comment]
0.21.0 is released. Hope the packaging is successful 🙂
