### ISSUE TITLE
Is there a non-neglect form of the reaction, if the reaction is something like x -> x?

### ISSUE THREAD

**Issue by forestrywhale** [opencobra/cobrapy#1032]
### Question

Hello, thank you for developing cobrapy! I have a question about it. 

So I have a reaction like x [cytosol] -> x [cytosol], which basically meaning something transporting (K+ for example), like from one membrane to another membrane structure in the cytosol, with the help of an enzyme. When reading this reaction into a cobra model, the reaction becomes () -> (). I understand that this kind of reaction is meaningless for FBA, since the left and right are equal, but it is somehow meaningful for the integrity of the model.

Is there an option that I can keep this info in my model?

Thank you and have a great day!

**Comment by matthiaskoenig** [comment]
@ocean-whale I just looked through the implementation of how metabolites are handled associated to reactions. Unfortunately it looks like that only a single reference to a metabolite is allowed in the internal data model of cobrapy. I.e. there is no concept of reactants and products in an cobrapy model. Consequently you will loose this information in the model.
You can encode this in the SBML, but on the model import this information will be lost.

**Comment by cdiener** [comment]
Yeah the concept is that every metabolite is some kind of unique molecule class. So a reaction that consumes and produces it would be moot. However, I would argue that in your case those are two different molecule types (K+ in the first structure and K+ in the second). So I would add a new metabolite that describes K+ in the other structure.

**Comment by forestrywhale** [comment]
Thank you Matthias and Cdiener! Yes, I think it makes sense to have a unique key for the metabolites. Adding another metabolite to the model seems to be the best answer here, I'll do that :)
