### ISSUE TITLE
Improve the reading of MATLAB models

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#1040]
### Checklist

- [X] There are [no similar issues or pull requests](https://github.com/opencobra/cobrapy/issues) for this yet.

### Description

We support reading MATLAB (`.mat`) models but we only read a very minimal set of info which leads to a loss of information. The full set of available information can be [found here](https://github.com/opencobra/cobratoolbox/blob/master/docs/source/notes/COBRAModelFields.md).

Currently dropped:
1. names for metabolites and reactions
2. all annotations for Models, Metabolites, Reactions and Genes
3. extra variables

Furthermore, we don't sanitize IDs which can lead to introducing invalid IDs that will crash optlang. Since cobrapy is no pretty standard-compliant in writing SBMl due to @matthiaskoenig's contributions it would be nice to allow full conversion of MATLAB to SBML. The inverse would be handy too but has a lower priority for me. 

## Solution

Expand the parser to include 1-3 mentioned above.

## Describe alternatives you considered

You could convert with the cobratoolbox but this solution is only accessible to individuals with a Matlab license and may not support all features supported by cobrapy (for instance SBML groups).

## Additional context

I feel this is necessary since many source models are still only published in MATLAB formats. This applies to Recon3 as well as Harvetta and Harvey. The proposal will make it possible to generate modern and standardized SBML versions of those with cobrapy.

If this is fully supported we might consider dropping the Matlab bridge as this has been shown to be unmaintainable due to infeasibility of testing and lacking maintainers. We would rather argue for using the `.mat` format for communication between cobrapy and the cobratoolbox.

**Comment by akaviaLab** [comment]
Hi @cdiener 
What kind of help are you looking for here?
Just go over the features you linked and make sure everything is imported/exported?

Some clarifying questions - what do you mean that names are dropped?
There's a bit of code in the reading that states
new_metabolite.name = str(m["metNames"][0, 0][i][0][0]) (line 300 or so)
so it seems like that would mostly work, with some exceptions when no name is present.

I guess a big part would be processing the additional annotations like metKEGGID, metPubChemID and so on. Making sure they have the right format for each.

**Comment by cdiener** [comment]
If names are read I'm not sure what I meant by this 🤦‍♂️ 
But yeah reading/writing all the annotations is definitely the most important part. And I think there was an issue if metabolite IDs have spaces in the Matlab model.
Thanks for tackling this!

**Comment by akaviaLab** [comment]
Hi @cdiener 
Is reading matlab models supposed to be slow?
I've been trying Recon3D, which should have many of these fields, and it seems to be taking forever.

**Comment by cdiener** [comment]
Yeah, it is very slow. Not sure where that occurs, I know that reading the raw data structure from the mat file is superfast, so the parsing seems to be the issue. We could try to identify some of the worst bottlenecks and make it faster. I think the stoichiometry setting is inefficient right now. It would be better to collect those in a dict for each reaction, to limit the calls to `set_linear_coefficients`. Though reading Recon3 from SBML is not that fast either.

**Comment by akaviaLab** [comment]
Yeah, it is slow.
set_linear_coefficients is called multiple times for each reaction, so I'm
going to try tackling that.
It seems that
```

num_rows = glp_get_mat_row(self.problem.problem, self._index, ia, va)
variables_and_coefficients = {var.name: coeff for var, coeff in
six.iteritems(coefficients)}

```

is the slow bit, since ._index is slow. I don't understand enough
about optlang to see if we could use the indexes of the matrix from
matlab to skip the lookup.

**Comment by cdiener** [comment]
Most of that is C code and `self._index` is just a Python attribute look-up which you can't really speed up. It is slow because it gets called too often with only a single coefficient. I think one easy workaround is setting the stoichiometry on reactions before adding them to a model and then adding them all. This will trigger some optimizations in `_populate_solver` that will group the coefficients and minimize the calls to optlang.

**Comment by Midnighter** [comment]
I don't know if you use PyCharm (it has a handy plugin for this) but I highly recommend first running a profiler to spot bottleneck function calls and then a line profiler on those functions to identify the offending code. (Unless you have already done so, of course.) Quite often my assumptions of what is slow and the reality have differed widely.

**Comment by akaviaLab** [comment]
Okay.
I did some modifications for accessing S and it sped it up by around 6 or so
Replace the coo_matrix code with

```
csc = scipy_sparse.csc_matrix(m["S"][0, 0])
for i in range(csc.shape[1]):
    stoic_dict = {}
    for j in csc.getcol(i).nonzero()[0]:
        stoic_dict[model.metabolites[j]] = csc[j, i]
    model.reactions[i].add_metabolites(stoic_dict)
```

I'm going to keep trying improvements to make sure everything is
loaded, and possible speed ups.

Christian - do you have examples of models that failed in the past?
Models that required the various try, except blocks? I think one
speedup might involve modifying them, and I want to make sure that
failing code will succeed without them (or have them in a different
format).

**Comment by cdiener** [comment]
The nested for loop probably makes it even slower than it needs to be, but the strategy looks right to me. The try blocks are there because the Matlab format is not really standardized, and most fields are optional. So you don't need a name for a reaction etc. Though, try blocks are surprisingly fast in Python as long as no exception is thrown (even somewhat faster than a substituting them with an if statement).

**Comment by akaviaLab** [comment]
csc.getcol(i).nonzero()[0] gives back a tuple array.
 array([0, 2], dtype=int32)

I can convert it to a list, but I can't access model.metabolites using it
in one action.
I keep getting errors like
Traceback (most recent call last):
  File
"/Users/uridavidakavia/PycharmProjects/venv_cobrapy3_7/lib/python3.7/site-packages/IPython/core/interactiveshell.py",
line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-5efa7a991822>", line 1, in <module>
    model.metabolites.__getitem__(*[csc.getcol(i).nonzero()[0][:]])
  File
"/Users/uridavidakavia/PycharmProjects/cobrapy/src/cobra/core/dictlist.py",
line 465, in __getitem__
    return self.__class__(list.__getitem__(self, i))
TypeError: only integer scalar arrays can be converted to a scalar index

or

Traceback (most recent call last):
  File
"/Users/uridavidakavia/PycharmProjects/venv_cobrapy3_7/lib/python3.7/site-packages/IPython/core/interactiveshell.py",
line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-5611fc49998c>", line 1, in <module>
    model.metabolites.__getitem__(foo)
  File
"/Users/uridavidakavia/PycharmProjects/cobrapy/src/cobra/core/dictlist.py",
line 465, in __getitem__
    return self.__class__(list.__getitem__(self, i))
TypeError: list indices must be integers or slices, not list

What am I missing?

**Comment by cdiener** [comment]
Yeah it is not vectorized. But you could use a dictionary comprehension in the inner loop.
