### ISSUE TITLE
swglkp 5.0.0 is out and cobrapy 3.9 works

### ISSUE THREAD

**Issue by carrascomj** [opencobra/cobrapy#1048]
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/opencobra/cobrapy/issues) for this yet.

### Is your feature related to a problem? Please describe it.
 [swiglpk](https://github.com/biosustain/swiglpk) was delaying cobrapy's compatibility with python3.9 (see https://github.com/opencobra/cobrapy/issues/1030#issuecomment-768610423 and https://github.com/biosustain/swiglpk/issues/39).

## Describe the solution you would like.
Linux wheels have been released for swiglpk 5.0.0 and cobrapy is now working on python3.9.
> **NOTE**: macOSX wheels have not been uploaded yet due to problems with deployment.

**Comment by Midnighter** [comment]
Very cool Jorge. Would it help to move swiglpk to GitHub Actions rather than Travis?

**Comment by carrascomj** [comment]
Definitely, I have a branch here https://github.com/carrascomj/swiglpk/tree/ci-actions but I still have problems with macOSX, where I am apparently not linking the right version of the libraries (these are different from the travis problems, which are related to the OSX image timing out on the brew updates).

**Comment by cdiener** [comment]
Your mac builds on Actions look pretty good by now, looks like you only need to either move glpk.h into the build directory or use the `GLPK_HEADER_PATH` env variable so distutils can find it. I wouldn't worry about the libgmp warning until you see test failures.

**Comment by carrascomj** [comment]
Just to have it documented, the swiglpk wheels are now available for linux, macos and windows.
