### ISSUE TITLE
Change wording of pFBA description in the docs

### ISSUE THREAD

**Issue by hbsmith** [opencobra/cobrapy#1049]
### Checklist

- [x ] There are [no similar issues or pull requests](https://github.com/opencobra/cobrapy/issues) for this yet.

### Is your feature related to a problem? Please describe it.

I want it to be clear what objective value means, and what to expect from the pFBA output by reading this section [https://cobrapy.readthedocs.io/en/latest/simulating.html#Running-pFBA](url).

I think the wording of what to expect from the pFBA output is confusing. Specifically, the phrase "objective value" is used a bit sloppily, because it's used to mean two completely different things: 
1. The value of the internal function's objective (which differ between FBA and pFBA)
2. The value of the objective for standard FBA.

## Describe the solution you would like.

I would recommend to change this sentence "These functions should give approximately the same objective value." to something like:

> "These functions will likely give completely different objective values, because the objective value shown from pFBA is defined as `sum(abs(pfba_solution.fluxes.values))`, while the objective value for standard FBA is defined as the flux through the reactions being optimized for (e.g. `fba_solution.fluxes["Biomass_Ecoli_core"]`).
>
> Both pFBA and FBA should return identical results for the flux being optimized for (e.g. `abs(fba_solution.fluxes["Biomass_Ecoli_core"] - pfba_solution.fluxes["Biomass_Ecoli_core"]`)

## Describe alternatives you considered

Redefining the words used in the standard output from running pFBA or FBA, which seems more complicated than simply clarifying behavior in the docs. 

## Additional context

I'm clearly not alone in being confused by the current wording, and my expected behavior for comparing outputs from these two functions:
https://github.com/opencobra/cobrapy/issues/518
https://github.com/opencobra/cobrapy/issues/635

Both of these issues could have been mitigated with these simple doc wording changes.

**Comment by matthiaskoenig** [comment]
I agree with the update. The second sentence does not make sense yet. You probably meant something like:

Both pFBA and FBA should return identical results within solver tolerances for the objective being optimized. E.g. for a FBA problem which maximizes the reaction `Biomass_Ecoli_core` the following should be true:  `np.isclose(fba_solution.fluxes["Biomass_Ecoli_core"], pfba_solution.fluxes["Biomass_Ecoli_core"]`).

**Comment by hbsmith** [comment]
@matthiaskoenig Yep, that's what I meant! Thanks for the wording suggestion.

**Comment by matthiaskoenig** [comment]
I will incorporate the updates.

**Comment by matthiaskoenig** [comment]
Is updated in pull request. Should be in develop soon after some review. 
Thanks for the contribution.
Best Matthias
