### ISSUE TITLE
Does the cobrapy have a function to test whether each precursor can be produced?

### ISSUE THREAD

**Issue by hongzhonglu** [opencobra/cobrapy#1054]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question
Hi all, could I ask a question? Does the cobrapy have a function to test whether each precursor can be produced? It will be useful to do model quality check like the Cobra toolbox from matlab version.

**Comment by Midnighter** [comment]
This is a test that is implemented in [MEMOTE](https://memote.io). You can also look at the source code for it if you like.

**Comment by hongzhonglu** [comment]
Hi Moritz,
Thanks for your help!  In the cobra matlab, the 'biomassPrecursorCheck' function did very detailed check, for example, it could detect List of metabolites which need an exchange reaction for at least one other biomass component because their production is coupled to it. I have checked the source code of MEMOTE, I think the function in MEMOTE-' test_biomass_precursors_open_production' did not cover the similar function?

https://github.com/opencobra/cobratoolbox/blob/efb2c06be702aaed38349581ba73ed420251992b/src/analysis/exploration/biomassPrecursorCheck.m

**Comment by Midnighter** [comment]
You're completely right. It does not do that. If you would like to try and implement it, feel free to open a pull request on memote. Otherwise, please open an issue there but it will probably take time to address.

**Comment by hongzhonglu** [comment]
Nice! Thanks! I will firstly try to solve it.
