### ISSUE TITLE
Knockout vs. deletion results

### ISSUE THREAD

**Issue by paocorbin** [opencobra/cobrapy#1102]
### Checklist
- [ x]  I searched the [documentation](https://cobrapy.readthedocs.io).
- [ x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ x] I looked up "How to do ... in cobrapy" on a search engine.

### Knockout results are different from deletion results

Hello,
I am simulating knockouts for some genes and reactions and the results I obtain are different if I apply `.knock_out()` or `_gene_deletion()`. I have noticed that it occurs in double deletions.

Example for the cobra test _E. coli_  model with the reaction ACONTa and its two genes (b0118 or b1276):

```py
import cobra
from cobra.flux_analysis import (
    single_gene_deletion, single_reaction_deletion, double_gene_deletion,
    double_reaction_deletion)


cobra_model = cobra.test.create_test_model("ecoli")
```

```py
print('complete model: ', cobra_model.optimize())
with cobra_model:
   cobra_model.reactions.ACONTa.knock_out()
   print('ACONTa knocked out: ', cobra_model.optimize())
```
Result:
##complete model: <Solution 0.982 at 0x1345d6e748>
##ACONTa knocked out: <Solution -0.000 at 0x1345d6e4a8>

```py
print('complete model: ', cobra_model.optimize())
with cobra_model:
   cobra_model.genes.b0118.knock_out()
   print('b0118 knocked out: ', cobra_model.optimize())
   cobra_model.genes.b1276.knock_out()
   print('b1276 knocked out: ', cobra_model.optimize())
```

Result:
##complete model: <Solution 0.982 at 0x134564fbe0>
##b0118 knocked out: <Solution 0.982 at 0x134564f978>
##b1276 knocked out: <Solution 0.000 at 0x134564f470>

```py
genes_list = ['b0118', 'b1276']
dbdeletion_results = double_gene_deletion(cobra_model, genes_list)
dbdeletion_results
````
Result:

| ids | growth | status
-- | -- | --
{b1276} | 0.982372 | optimal
{b1276, b0118} | 0.982372 | optimal
{b0118} | 0.982372 | optimal

Any ideas of what is happening?
Thank you.

**Comment by Midnighter** [comment]
Hi @paocorbin,

Unfortunately, it's not possible to help you because the formatting of your code got lost. Please use

````
```py
```
````

instead of `>` to format your code so that we can tell what is within a context (indented) and what is without.

**Comment by paocorbin** [comment]
Oh, sorry. I edited my comment.

**Comment by Midnighter** [comment]
That indeed looks like a problem. I'll need to dig deeper. Can you please post the output of:

```
python -c "import cobra;print(cobra.show_versions())"
```

**Comment by paocorbin** [comment]
Output of :

```
python -c "import cobra;print(cobra.show_versions())"
```

System Information
==================
OS         Darwin
OS-release 18.7.0
Python      3.7.3

Package Versions
================
appdirs               1.4.4
cobra                0.22.0
depinfo               1.5.1
diskcache             5.2.1
future               0.17.1
httpx                0.18.2
importlib-resources   5.2.0
numpy                1.20.2
optlang               1.5.2
pandas                1.3.0
pip                  19.0.3
pydantic              1.8.2
python-libsbml       5.19.0
rich                 10.5.0
ruamel.yaml         0.17.10
setuptools           40.8.0
swiglpk              4.65.0
wheel                0.33.1
None

**Comment by Midnighter** [comment]
Thanks for the report. There is indeed a bug in one of the internal functions. It has been around since COBRApy version 0.10 so I'm quite surprised you're the first one to discover it! I will create a patch ASAP.

**Comment by paocorbin** [comment]
Great. Thank you.

**Comment by Midnighter** [comment]
If you like, you can try the fix in branch https://github.com/opencobra/cobrapy/tree/fix-gene-deletion already. I will make a new release as soon as #1103 has been reviewed.

**Comment by NantiaL** [comment]
Hello, did you fix this bug also for the `single_reaction_deletion()` function from cobrapy or only for the gene deletion function?. Because I also noticed different results between `single_reaction_deletion()` and the `reaction.knock_out()`.

**Comment by Midnighter** [comment]
It should be fine. Can you open a new issue please showing exactly how you get different results?

**Comment by NantiaL** [comment]
I am sorry. I spotted my mistake and now it works fine.
