### ISSUE TITLE
model = cobra.io.read_sbml_model("model.xml")

### ISSUE THREAD

**Issue by brunorbqi** [opencobra/cobrapy#1109]
The command line model = cobra.io.read_sbml_model("model.xml") is not working properly is giving the following error:
 GurobiError                               Traceback (most recent call last)
/home/brunobqi/anaconda3/lib/python3.7/site-packages/cobra/io/sbml.py in read_sbml_model(filename, number, f_replace, **kwargs)
    254                               f_replace=f_replace,
--> 255                               **kwargs)
    256     except IOError as e:

/home/brunobqi/anaconda3/lib/python3.7/site-packages/cobra/io/sbml.py in _sbml_to_model(doc, number, f_replace, set_missing_bounds, **kwargs)
    359         LOGGER.error("'%s' is not a valid SBML 'SId'." % model_id)
--> 360     cobra_model = Model(model_id)
    361     cobra_model.name = model.getName()

/home/brunobqi/anaconda3/lib/python3.7/site-packages/cobra/core/model.py in __init__(self, id_or_model, name)
    116             interface = configuration.solver
--> 117             self._solver = interface.Model()
    118             self._solver.objective = interface.Objective(Zero)

/home/brunobqi/anaconda3/lib/python3.7/site-packages/optlang/gurobi_interface.py in __init__(self, problem, *args, **kwargs)
    514         if problem is None:
--> 515             self.problem = gurobipy.Model()
    516             self.problem.params.OutputFlag = 0

src/gurobipy/env.pxi in gurobipy.gurobipy.Env.__init__()

src/gurobipy/gurobi.pxi in gurobipy.gurobipy.gurobi._getdefaultenv()

src/gurobipy/env.pxi in gurobipy.gurobipy.Env.__init__()

GurobiError: HostID mismatch (licensed to d5c35cc0, hostid is d3e26228)

The above exception was the direct cause of the following exception:

CobraSBMLError                            Traceback (most recent call last)
<ipython-input-2-a2d6e1107373> in <module>()
----> 1 model = cobra.io.read_sbml_model("iBP1046f.xml")
      2 num_reactions = len(model.reactions)
      3 num_metabolites = len(model.metabolites)
      4 num_genes = len(model.genes)
      5 # Making lesser adjustments

/home/brunobqi/anaconda3/lib/python3.7/site-packages/cobra/io/sbml.py in read_sbml_model(filename, number, f_replace, **kwargs)
    266             "\nIf the model is valid and cannot be read please open an issue "
    267             "at https://github.com/opencobra/cobrapy/issues .")
--> 268         raise_from(cobra_error, original_error)
    269 
    270 

/home/brunobqi/anaconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .

PS: I am using a valid SBML model.

**Comment by Midnighter** [comment]
It's unfortunately, a bit deeper in your stacktrace but you have an issue with your Gurobi license:

```
GurobiError: HostID mismatch (licensed to d5c35cc0, hostid is d3e26228)
```
