### ISSUE TITLE
separated bacteria's biomass in one community model

### ISSUE THREAD

**Issue by oMersa344** [opencobra/cobrapy#1112]
Hi everyone,

I'm using COBRApy to analyze community models made with CarveMe (with cobra.io.read_sbml_model).

I can only see the **entire community biomass**, both with model.summary() that gives comminuty_growth as the objective function and also in the secretion flux as community_biomass.
Is it possible to see the biomass of each bacteria within the model and not only the total biomass of the community?
According to CarveMe documentation, it creates a separated compartment for each bacteria in the community.

I've searched both the documentation and also in the similar issues but didn't find any idea for that.

thanks

**Comment by Midnighter** [comment]
Hi,

COBRApy is not directly aimed at community modeling so you have to carefully manage, for example, identifiers to ensure that they are unique per community member. When that is case, you can look at the fluxes in a solution object corresponding to the biomass reactions of the members. However, there is likely also some scaling necessary. I recommend that you give [MICOM](https://micom-dev.github.io/micom/) a try since it takes care of many of those pitfalls for you.

**Comment by cdiener** [comment]
In CARVEME individual biomass reaction IDs usually start with "Growth_" so if you look through the list of fluxes in the solution you should be able to find them. The flux values of those reactions are the growth rates. 
However, I would be careful with those. For any given community growth rate there are infinitely many solutions of individual growth rates that are valid. So if you would reoptimize you might get completely different individual growth rates. In most cases, those do not correspond to the growth rates the organisms would actually choose in an experimental setting as we have shown in https://doi.org/10.1128/mSystems.00606-19. So you would probably want to introduce additional, data-derived constraints to alleviate this.

**Comment by oMersa344** [comment]
Thanks for your answer and suggestion.
The only relevant IDs I've got in COBRA fluxes are the community_growth and commuity_biomass, with no evidence for a specific organism biomass or growth rate. I'm not sure if I don't know where to search or if it just doesn't calculate by COBRApy.
I've read the documentary for MICOM and think maybe it's a bit overkill for my purpose.
The community model I want to analyze is a simple one, made with 2-3 bacteria strains with a known genome from the NCBI database and constructed by CarveMe (an artificial community that doesn't base on metagenomic analysis of a biological sample).
I want to model the growth rate (or the biomass fluxes) of two specific bacteria strains together (by a community model with CarveMe) and see if it's bigger (/smaller/ equal) than the growth rate of each of them alone (by a one strain model with CarveMe).
Do you think COBRApy is still not suitable for this purpose?

**Comment by cdiener** [comment]
Some more discussion at https://github.com/micom-dev/micom/discussions/55. Seems to be resolved.
