### ISSUE TITLE
 <bound method Model.slim_optimize of <Model FAEPRAA2165 at 0x7f8c6dfbb2d0>>

### ISSUE THREAD

**Issue by wintermute221** [opencobra/cobrapy#1115]
Hi!

I just loaded my model (Bifidobacterium adolescentis L2-32_iBif452.V01.00) on the Spyder and I would like to know its growth rate in the default condition. I used the `model.slim_optimize()`function. Below is my code.

```

import cobra
import cobra.test

from gurobipy import *

from cobra.io import read_sbml_model

model_ba = read_sbml_model('/TwoModelsInSBMLAndExcel/Bifidobacterium adolescentis L2-32_iBif452.V01.00.xml')

In [18]: model_fp.slim_optimize

Out[18]: <bound method Model.slim_optimize of <Model FAEPRAA2165 at 0x7f8c6dfbb2d0>>

```

So I just wonder why the output wasn't a number indicating the growth rate of the model. Appreciate it if anyone could help!

**Comment by Midnighter** [comment]
Hi,

I recommend that you start with a Python tutorial, it will save you a lot of frustration down the line. In this case, you did not call the method which requires the parentheses `model.slim_optimize()` so the output is a representation of the method itself.

**Comment by wintermute221** [comment]
Oh thanks a lot! I will have a look.
