### ISSUE TITLE
Inconsistent packages

### ISSUE THREAD

**Issue by Corleno** [opencobra/cobrapy#1117]
#### Problem description

I have install cobra but when I import cobra, it has issues.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
```
import cobra

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-2-3d1a977f0ea3> in <module>
----> 1 import cobra
      2 import bayflux
      3 import pandas as pd
      4 import numpy as np
      5 

d:\research\cobrapy\src\cobra\__init__.py in <module>
      3 
      4 
----> 5 from cobra.core import (
      6     Configuration,
      7     DictList,

d:\research\cobrapy\src\cobra\core\__init__.py in <module>
----> 1 from cobra.core.configuration import Configuration
      2 from cobra.core.dictlist import DictList
      3 from cobra.core.gene import Gene
      4 from cobra.core.metabolite import Metabolite
      5 from cobra.core.model import Model

d:\research\cobrapy\src\cobra\core\configuration.py in <module>
     14 from cobra.core.singleton import Singleton
     15 from cobra.exceptions import SolverNotFound
---> 16 from cobra.util.solver import interface_to_str
     17 from cobra.util.solver import solvers as SOLVERS
     18 

d:\research\cobrapy\src\cobra\util\__init__.py in <module>
----> 1 from cobra.util.array import *
      2 from cobra.util.context import *
      3 from cobra.util.solver import *
      4 from cobra.util.util import *
      5 from cobra.util.process_pool import *

d:\research\cobrapy\src\cobra\util\array.py in <module>
     20 def create_stoichiometric_matrix(
     21     model: "Model", array_type: str = "dense", dtype: Optional[np.dtype] = None
---> 22 ) -> Union[np.ndarray, dok_matrix, lil_matrix, pd.DataFrame]:
     23     """Return a stoichiometric array representation of the given model.
     24 

AttributeError: module 'pandas' has no attribute 'DataFrame'

```
```

### Context

<details>

```
```

</details>

**Comment by Midnighter** [comment]
Seems to me like your installed pandas package is broken. `pandas.DataFrame` should exist. Can you reinstall pandas, please, and see if that fixes things?

Also, providing the version information that we ask for will be helpful if this doesn't solve your problem.

**Comment by Corleno** [comment]
Thanks. That works！
