### ISSUE TITLE
How to manipulate media in COBRA

### ISSUE THREAD

**Issue by Shakra-A** [opencobra/cobrapy#1122]
I made a metabolic model and now I have to simulate the growth by using defined media from literature. 
I am using following command from COBRA
medium = model.medium
medium["EX_o2_e"] = 0.0
model.medium = medium
model.medium

I give the value of each component according to the literature. There are two problems I am facing.
1. There is MgCl2 and CaCL2 media components. I have calculated the ionic concentrations of Mg , Cl2, Ca and Cl2 separately. problem is now I have two Cl concentrations. Can anyone help me in managing that?
2. The next problem is ammonium citrate. The BiGG data base has ammonia or ammonium and citrate separately but it is difficult to convert to ionic concentrations as I done it in MgCl2 case. how to solve this problem.

Kindly anyone help me. Thank you

**Comment by Midnighter** [comment]
Dear @aini-bio,

 In flux-balance analysis you cannot use medium concentrations directly anyway. If you want to simulate different media, you have to provide uptake rates. Normally, the rates for ionic species as you describe are not very impactful so you can safely set a high uptake rate. Most important is to have good estimates for the carbon source and oxygen uptake rates. And maybe CO2 secretion rate. Those are also more readily measured.

**Comment by cdiener** [comment]
Nitrogen is also important. But I would say the correct way to handle those concentrations is to add them up. If you get 1 mole of ion from one component and another mole of the same Io from another compound you have 2 mole in total.

**Comment by Shakra-A** [comment]
thank you @cdiener you gave me solution to my first problem.
