### ISSUE TITLE
protein production

### ISSUE THREAD

**Issue by ShannyAc** [opencobra/cobrapy#1124]
Hi, 

Is COBRApy also suitable for modeling protein production in cell-free systems? 

I see that I can add metabolites and reactions to the model (which will be created initially with CarveMe based on the genome of the relevant bacteria the cell-free system is made of), so theoretically, I can create a reaction like this (very schematic one) 
21 Met + 45 Asp + ... + 90gtp -> 1 protein 
As for the objective value, I can also set it to be this reaction.

Does it make any sense? Do you have any other suggestions or modifications to add to the model?

Thank you!

**Comment by matthiaskoenig** [comment]
This looks good. We did similar things with Albumin synthesis and other liver proteins to test that an hepatocyte can synthesize key enzymes. There are also extensions to simple FBA such as Resource Balance Allocation (RBA) which track the proteins much more explicitly.

**Comment by cdiener** [comment]
Looks resolved, feel free to open a discussion topic for more.
