### ISSUE TITLE
pip install cobra fails in Python 3.10

### ISSUE THREAD

**Issue by pems21** [opencobra/cobrapy#1142]
Executing 
```bash 
pip install cobra
```
on Arch Linux with the latest Python version (3.10.1) fails. Apparently, `cobra` 0.22.1 depends on `python-libsbml==5.19.0`, which has a bug (see [https://github.com/sbmlteam/libsbml/issues/173](https://github.com/sbmlteam/libsbml/issues/173)) that makes it impossible to install in python 3.10 and that was fixed in `python-libsbml` 5.19.1 or 5.19.2. Anecdotally, forcing the install with a constraints.txt that specifies the 5.19.2 version of that package works with no apparent issues.

Also, installing `cobra` through `pip` kinda works up until `python-libsbml` turn, but importing it gives a 

```python
[...]__init__.py:63: UserWarning: No LP solvers found
  warn("No LP solvers found")
```
error.

**Comment by Midnighter** [comment]
Thank you for the report @pems21. I just tried to set up a quick new release to address this issue but this is blocked by https://github.com/biosustain/swiglpk/issues/51 which is also why you see the warning above about 'No LP solvers found'.

**Comment by cdiener** [comment]
swiglpk has now been updated and there are wheels for Python 3.10 with swiglpk>=5.0.4. Thanks for your patience.
