### ISSUE TITLE
Make libSBML requirement as permissive as possible (e.g., `>= 5.19.0` rather than `== 5.19.2`)

### ISSUE THREAD

**Issue by jonrkarr** [opencobra/cobrapy#1160]
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/opencobra/cobrapy/issues) for this yet.

### Is your feature related to a problem? Please describe it.
It would be useful to be able to use COBRApy together with other modeling tools in the same Python environment, including ones which have alternative version requirements, such as for the experimental version (python-libsmbl-experimental) which supports the draft packages such as spatial.

## Describe the solution you would like.
The libSBML requirement is currently `python-libsbml==5.19.2`. If this specific microversion isn't required, ideally this would be changed to something like `python-libsbml>=5.19.0` (or whatever minimum version is required).

## Describe alternatives you considered
Alternatives include forking COBRApy, editing the requirements, and installing it from the source; using a older version; or some other hacking. It would be best to change this at the source, rather than managing it downstream.

## Additional context

N/A

**Comment by Midnighter** [comment]
I certainly see the issue. The reason that we use a strict pin at the moment, is that when we were less strict, there would be problems with every new release of libSBML because wheels are released significantly later than the source package. So pip would install the latest python-libsbml which at the time is only available as a source package and users would mostly be unable to compile from sources.

That said, cobrapy should work with most libsbml versions. So if you install cobra first and afterwards any other tool or python-libsbml-experimental it will work even though pip complains.

**Comment by jonrkarr** [comment]
It looks like libsbml has released wheels at the same time for at least the last two years. 

If a new version of python is released and the SBML team hasnt updated their build matrix, wheels for that new version might get published later.

**Comment by Midnighter** [comment]
True, latest issues were indeed due to Python 3.10 and new Mac M1 architecture.

**Comment by Midnighter** [comment]
> That said, cobrapy should work with most libsbml versions. So if you install cobra first and afterwards any other tool or python-libsbml-experimental it will work even though pip complains.

Would this work for now, though? We cannot have both python-libsbml and python-libsbml-experimental in the dependencies simultaneously anyway.

**Comment by jonrkarr** [comment]
Relaxing the pinning would help users understanding which version is required, rather than me trying to figure this out.

Please ignore the libsbml-experimental aspect of this issue. This is my motivation for this, but I don't think COBRApy or other tools should aim to deal with libsbml-experimental. The experimental version needs to be installed on top of the regular version, preferably with the same revision as the regular version (which is additionally complicated by limited releases for the experimental version). One way I could see to manage this with pipenv, but probably not pip, would be for libsbml to have an experimental option, rather than experimental being a separate package. This an issue for the libsbml team rather than individual tools.

**Comment by Midnighter** [comment]
Okay, I've added https://github.com/opencobra/cobrapy/pull/1170 to address this. I really hope this will not cause more support requests in future with version issues.

**Comment by jonrkarr** [comment]
Thanks!
