### ISSUE TITLE
how to access this data in a model. mat (Harvey& Harvetta model)

### ISSUE THREAD

**Issue by Ilhem36** [opencobra/cobrapy#1198]
### Checklist

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-67-b9434722a7ea> in <module>
----> 1 find_external_compartment(model_harvey)

/opt/python-3.6.9/lib/python3.6/site-packages/cobra/medium/boundary_types.py in find_external_compartment(model)
     52     """
     53     if model.boundary:
---> 54         counts = pd.Series(tuple(r.compartments)[0] for r in model.boundary)
     55         most = counts.value_counts()
     56         most = most.index[most == most.max()].to_series()

/opt/python-3.6.9/lib/python3.6/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    299                 raise TypeError(f"'{type(data).__name__}' type is unordered")
    300             else:
--> 301                 data = com.maybe_iterable_to_list(data)
    302 
    303             if index is None:

/opt/python-3.6.9/lib/python3.6/site-packages/pandas/core/common.py in maybe_iterable_to_list(obj)
    277     """
    278     if isinstance(obj, abc.Iterable) and not isinstance(obj, abc.Sized):
--> 279         return list(obj)
    280     return obj
    281 

/opt/python-3.6.9/lib/python3.6/site-packages/cobra/medium/boundary_types.py in <genexpr>(.0)
     52     """
     53     if model.boundary:
---> 54         counts = pd.Series(tuple(r.compartments)[0] for r in model.boundary)
     55         most = counts.value_counts()
     56         most = most.index[most == most.max()].to_series()

IndexError: tuple index out of range

### Question

Hello everyone I m trying to manipulate the WBM model ( mat file) for Ines Thiele with cobra py but I can't access to some information ( such us external compartments, exchange , sink and demand reactions) using cobrapy functions. For instance I used : find_external_compartment(model_harvey) but I got errors (you find it above) but  when I use it with .json model , it is working. Do you think that there is another manner to access information in .mat files ? . 
In fact my goal is to merge two models the WBM(.mat file) and the microbiote community (.json file), but I don't know if it is possible with cobrapy ? or not ?

**Comment by akaviaLab** [comment]
Where do you find the model?
If you add a link, I can try to see if it can be loaded or not, and try to fix it.

**Comment by cdiener** [comment]
Looks like the compartments did not get read correctly. But like @akaviaLab said, we will need the model file to check what is going on. For instance, the Harvey/Harvetta models from https://github.com/opencobra/cobrapy/issues/1194 seem to have been fixed.

**Comment by cdiener** [comment]
Okay after a lot of investigation with @akaviaLab the underlying issue is that the Matlab model has not been saved with any compartment information. So even if we fix find_external_compartment it would likely give incorrect information because there is no information about the actual compartments saved in the model. So if you really want to get this working we would recommend you contact the authors and ask them for a version that has the compartments set for the metabolites explicitly.

**Comment by cdiener** [comment]
Should now work in 0.25.0
