### ISSUE TITLE
Parallelization not working?

### ISSUE THREAD

**Issue by febedtu** [opencobra/cobrapy#1201]
Parallelization does not seem to work for me. I am running COBRApy on a Macbook Pro M1 Max

Running a test on [5. Simulating Deletions](https://cobrapy.readthedocs.io/en/latest/deletions.html)

```
start = time()  # start timer()
double_gene_deletion(
    ecoli_model, ecoli_model.genes[:25], processes=4)
t1 = time() - start
print("Double gene deletions for 200 genes completed in "
      "%.2f sec with 4 cores" % t1)

start = time()  # start timer()
double_gene_deletion(
    ecoli_model, ecoli_model.genes[:25], processes=1)
t2 = time() - start
print("Double gene deletions for 200 genes completed in "
      "%.2f sec with 1 core" % t2)

print("Speedup of %.2fx" % (t2 / t1))`
```

`Double gene deletions for 200 genes completed in 6.14 sec with 4 cores
Double gene deletions for 200 genes completed in 1.75 sec with 1 core
Speedup of 0.29x`

Any idea why this might be the case? To my knowledge this has not been reported before.

**Comment by Midnighter** [comment]
I'm not sure right now if there is anything special with the M1 hardware with regard to multiprocessing. However, please note that multiprocessing does introduce some overhead which you can see here in the additional time with 4 processes. So it's only really worth it for large numbers of tasks. A double knock-out of all genes should certainly show a speed up compared to serial processing.

**Comment by febedtu** [comment]
Thank you for the reply. I didn't know that the overhead has such a significance.

> A double knock-out of all genes should certainly show a speed up compared to serial processing.

I don't think I understand this. Could you give an example?

**Comment by Midnighter** [comment]
I simply mean that

```py
double_gene_deletion(ecoli_model, processes=4)
```

should be much faster than

```py
double_gene_deletion(ecoli_model, processes=1)
```

**Comment by cdiener** [comment]
As @Midnighter said, this is due to Mac and Windows not supporting fork to spawn new processes, so you will see the multiprocessing advantage kick in a bit earlier on Linux systems. For 100 genes+ you should start to see the parallel version becoming faster.

**Comment by febedtu** [comment]
Thank you both for the explanation. I tested and confirmed this by running parallelizations of different gene sets. I wasn't aware of the impact of the overhead.

**Comment by cdiener** [comment]
For what it's worth, your M1 is super fast with it even on a single core. When I run this benchmark on an Intel i7 it takes at least twice as long as it did for you.
