### ISSUE TITLE
Error when removing a list of genes

### ISSUE THREAD

**Issue by migp11** [opencobra/cobrapy#1214]
#### Problem description

I was trying to remove genes from a model and I got a `ValueError` exception:

```
cobra/core/dictlist.py", line 358, in index
ValueError: Another object with the identical id (FOLR2) found
```

I then realized that in the model I'm using, some ids are shared between reactions and genes (by the way I'm using a Recon3D from which I first removed isoforms and then rename genes from Entrez IDs to gene symbols for reasons that are irrelevant to explain here). 

I checked a couple of workarounds until I found a fix but on my way, I also found a couple of potential bugs.

The workarounds I tried to solve the error were the following ones:
1- rename conflicting reactions
2- rename conflicting genes
3- read the model and pass `f_replace={}` to avoid ID conflicts from the very beginning.

WA 1 fail with the same error as before. After some debugging, I found the two potential bugs mentioned above; I first realize the error raises inside the remove_gene function when retrieving the groups that have the gene to be removed as a member. To find those groups, the model iterates over the `DictList`of groups and checks which `__contains__` the element id (gene in this case). Then it follows that if a gene and a reaction (or any other type o elements) share the same id this wrong group can potentially be identified as containing the element (because this function just checks the ID as a string). Later, in the `remove_gene` function, the model tries to remove the gene from the group and retrieves an object that matches the gene ID (which in my case was a reaction with the same ID) and since the reaction and the gene are not the same object, the program raises an error.

Then I wondered why my second WA did not work and I found the second potential bug. I found that when the id of a reaction is changed and `model.repair()` is called there's still some part where this change is not updated (reflected). Specifically, within the group objects, there is a `DictList` called members and this class has a private dictionary `self._dict` used to store the indexes of the elements stored. I found that when I tried to rename the conflicting reactions the `self._dict` of the groups in which the reaction is a member are not updated and this is the source of my second error.

Renaming conflicting genes fix my problems because luckily genes are not members of any group and neither the first and the second bug manifest. But this was a lucky shot.

WA 3 solves the issue from the very root because allowing the prefixes in `R_` and `G_` in reactions and genes avoid any id conflict, and then no renaming is needed etc.

#### Code Sample

Below you will find the minimal code to reproduce all the comment points. To get the exception just remove the `try/except` block on the first try. The model I used can be found [here](https://drive.google.com/file/d/11qySXbMptvuj9NNkIlpEUEiF1Oan-0jK/view?usp=sharing).

Code:
```
from cobra.io import read_sbml_model
from cobra.manipulation import remove_genes
 
def rename_element_ids(model, rename_dict, type='reaction'):
    if type == 'reaction':
        element_list = model.reactions
    elif type == 'gene':
        element_list = model.genes
    elif type == 'metabolite':
        element_list = model.metabolites
    else:
        raise Exception(f"Unknown type {type}")
    for id_old, id_new in rename_dict.items():
        if id_old not in element_list:
            continue
        el = element_list.get_by_id(id_old)
        el.id = id_new
    model.repair()
    return model

model = read_sbml_model("Recon3DModel_301_no_isoforms.xml.gz")
print("- Testing remove genes:", end=" ")
try:
    remove_genes(model, ['FOLR2'])
    print("WORKED")
except:
    print("FAIL")

model = read_sbml_model("Recon3DModel_301_no_isoforms.xml.gz")
rxn_rename_dict = {'FOLR2': 'FIXED_FOLR2'}
model = rename_element_ids(model, rxn_rename_dict)
print("- Testing remove genes with renaming reactions:", end=" ")
try:
    remove_genes(model, [gene_id])
    print("WORKED")
except:
    print("FAIL")

model = read_sbml_model("Recon3DModel_301_no_isoforms.xml.gz")
gene_rename_dict = {'FOLR2': 'FIXED_FOLR2'}
model = rename_element_ids(model, rxn_rename_dict, type='gene')
print("- Testing remove genes with renaming genes:", end=" ")
try:
    remove_genes(model, ['FIXED_FOLR2'])
    print("WORKED")
except:
    print("FAIL")

model = read_sbml_model("Recon3DModel_301_no_isoforms.xml.gz",  f_replace={})
print("- Testing remove genes with f_replace={}:", end=" ")
try:
    remove_genes(model, ['G_FOLR2'])
    print("WORKED")
except:
    print("FAIL")
```

As commented above, to obtain the following error just remove the first `try/except` block to let the exception make the program crash.
Traceback:
```
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
/home/mponce/local/research/constraint-based-modeling/cll-metabolism/env/lib/python3.6/site-packages/cobra/core/group.py:148: UserWarning: need to pass in a list
  warn("need to pass in a list")
- Testing remove genes: Traceback (most recent call last):
  File "test.py", line 28, in <module>
    remove_genes(model, [gene_id])
  File "/home/mponce/local/research/constraint-based-modeling/cll-metabolism/env/lib/python3.6/site-packages/cobra/manipulation/delete.py", line 270, in remove_genes
    group.remove_members(gene)
  File "/home/mponce/local/research/constraint-based-modeling/cll-metabolism/env/lib/python3.6/site-packages/cobra/core/group.py", line 152, in remove_members
    self._members.remove(member_to_remove)
  File "/home/mponce/local/research/constraint-based-modeling/cll-metabolism/env/lib/python3.6/site-packages/cobra/core/dictlist.py", line 423, in remove
    self.pop(self.index(x))
  File "/home/mponce/local/research/constraint-based-modeling/cll-metabolism/env/lib/python3.6/site-packages/cobra/core/dictlist.py", line 358, in index
    f"Another object with the identical id ({id.id}) found"
ValueError: Another object with the identical id (FOLR2) found
```

### Context

<details>

```
System Information
==================
OS                               Linux
OS-release 5.3.18-150300.59.63-default
Python                          3.6.15

Package Versions
================
appdirs                                      1.4.4
black ; extra == 'development'       not installed
bumpversion ; extra == 'development' not installed
cobra                                       0.25.0
depinfo                                      1.7.0
diskcache                                    5.4.0
future                                      0.18.2
httpx                                       0.22.0
importlib-resources                          5.4.0
isort ; extra == 'development'       not installed
numpy                                       1.19.5
optlang                                      1.5.2
pandas                                       1.1.5
pip                                         21.3.1
pydantic                                     1.9.0
python-libsbml                              5.19.2
rich                                        12.3.0
ruamel.yaml                                0.17.21
scipy                                        1.5.4
setuptools                                  59.6.0
swiglpk                                      5.0.5
tox ; extra == 'development'         not installed
wheel                                       0.37.1
```

</details>

**Comment by akaviaLab** [comment]
Could we solve the problem with groups by modifying __contains__?
I'm thinking it would make sense to modify __contains__ to have an optional type/class as a second argument. That way, if you care, you can give it, so remove_genes, remove_reactions would give the type. Previous code wouldn't have to change.

**Comment by migp11** [comment]
Indeed, I believe one of the errors can be fixed by reimplementing the `contains` methods as @akaviaLab suggest, but this could come at the cost of losing the speed that DcitList is intended to provide. Also, since this functionality is at the very core of cobra, one has to be very careful when modifying things at that level.

The second error could be fixed by a reindexing of group._dict in the model repair function. I try to fix the second one and add a PR, hopefully, some day this week.

**Comment by akaviaLab** [comment]
I was thinking of overriding __contains__ in group, leaving __contains__ in DictList as is, in order to avoid major changes.
Or it could be explicit in remove_genes/reactions - find members and check type there explicitly. This explicit option seems like it would be more error prone (if some rewrites remove_genes or adds a function to add_genes).

**Comment by migp11** [comment]
Yep, that sounds very reasonable. Indeed, groups are the only cases of DictList in which entities from different classes (e.g. reactions, genes, metabolites) can be mixed. Other DictList used by the model only contains a single class of elements (either reactions or genes, etc) so I don't see the point in reimplementing the to contain a lower level. For the second bug related to the update of the indexes, I started implementing a quick fix at the level o model.repair() but I believe it will require adding some reindex function into the DictList since _dict is a private attribute from the class.

**Comment by cdiener** [comment]
@akaviaLab The group class has no `__contains__` method so not sure what you are getting at. It makes sense to me that `remove_members` should check for the type though. But `add_members` also behaves odd when there are Reactions and Genes with the same ID, so this probably requires some more fixes. 

@migp11 Yeah, model.repair ignores groups right now. If you need to rename large groups of objects it's probably always safer to do that before they get added to a model or to add them to a new model. 

I think we are also considering disabling `f_replace` by default (behaving like in your setting), since those problems creep up quite often.

**Comment by akaviaLab** [comment]
@cdiener I was thinking of making a special __contains__ method for group, to override the method inherited from DictList. 
Upon thinking about it a bit more, I think that might break the code because in uses __contains__.
Maybe it can be something like
def __contains__(self, obj, type: Optional)
and then if type isn't given it will behave like in.

Or the code could be added to add_members, remove_members explicitly, without changing __contains__ or in. I think it makes sense to add it at a relatively low level - to group (contains or add_members/remove_members) instead of modifying the higher level code like in cobra.manipulation (for example).

**Comment by cdiener** [comment]
Yeah, looks like `add_members` and `remove_members` would be the obvious things to change. I don't think we need to change the signature. They can just be changed to infer the type from the object itself and check against that. `add_members` currently collapses duplicate IDs via a union and that probably has to be replaced with something else.

**Comment by akaviaLab** [comment]
I think I have a fix for remove_members, but what should add_members do if there are two entities with the same id?
For example, let's say I want to add Reaction FOLR2 and Gene FOLR2 to the same group. I think currently add_members will be fine with that, but then the dictlist would be confused because there's  two entities with the same id, which would break the dict. Index would stop working correctly, etc.

**Comment by akaviaLab** [comment]
Or add Gene FOLR2 to a group that already contains Reaction FOLR2.
Similar problem, maybe not identical

**Comment by cdiener** [comment]
Yes, agreed. We probably want to revert 81717afd0bf763eeb17b3d5d4a90e7d89e6dbbb7. It looks like the state before that had none of the problems, and a set seems  like the more appropriate type here.

**Comment by cdiener** [comment]
I can't check whether it works with your example since model download link you provided does not work. However, that issue should be fixed now.

**Comment by migp11** [comment]
Ok, thanks! I probably removed the model from google drive by error. I'll check it in the upcoming days.
Just curious, what was the fix you implemented?

**Comment by cdiener** [comment]
Groups were reverted to being sets. That now allows to have a gene and a reaction in a group even if they have the same ID.

**Comment by akaviaLab** [comment]
So, just switch it back to set, which would solve the problem of
identifying by IDs. I can do it and post a PR for that in a few minutes.
