### ISSUE TITLE
ModuleNotFoundError: No module named 'cobra.test'

### ISSUE THREAD

**Issue by jeromeRlon** [opencobra/cobrapy#1224]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question

When I used the command： 

from cobra.test import create_test_model

The jupyter notebook reported:

ModuleNotFoundError: No module named 'cobra.test'

**Comment by francescodc87** [comment]
same problem for me

**Comment by akaviaLab** [comment]
Okay. This is actually a documentation bug, since you should be using 

`import cobra.io
cobra.io.load_model('textbook')`

for example in https://cobrapy.readthedocs.io/en/latest/io.html

I updated the documentation, but the website hasn't been updated. It might be related to #1041 and #970.

**Comment by Midnighter** [comment]
I've built the documentation for the latest version 0.25 now. https://cobrapy.readthedocs.io/en/0.25.0/index.html

As mentioned in the [release notes](https://github.com/opencobra/cobrapy/blob/devel/release-notes/0.25.0.md), we no longer distribute the tests with the package.
