### ISSUE TITLE
load_json_model_model"

### ISSUE THREAD

**Issue by jthom17** [opencobra/cobrapy#1229]
it says 'load_json_model_model' when it should just say 'load_json_model' when importing 

<img width="1512" alt="Screen Shot 2022-06-01 at 3 12 35 PM" src="https://user-images.githubusercontent.com/69604345/171510495-4654d676-9ee0-4c49-80af-9eb320586b46.png">

</details>

**Comment by akaviaLab** [comment]
Not relevant for the most recent version of cobra. What version are you using?

**Comment by cdiener** [comment]
Why is it not relevant? Looks like an error in the docs that could be fixed easily...

**Comment by akaviaLab** [comment]
Sorry. I was wrong about this error not being in the current devel. Now I fixed it.

**Comment by akaviaLab** [comment]
Sorry - looking at tge most recent version of io.ipynb, it doesn't have
this error. The file had different problems that I'm fixing.
