### ISSUE TITLE
Adding metabolites to a reaction using a dictionary

### ISSUE THREAD

**Issue by kristycyw** [opencobra/cobrapy#1230]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question
I have my reaction equation as a dictionary:
reaction= {'glu__L_c': -1.0, 'h2o_c': -1.0, 'nadp_c': -1.0, 'akg_c': 1.0, 'h_c': 1.0, 'nadph_c': 1.0, 'nh4_c': 1.0}
but when I do:
reaction.add_metabolite(reaction)
it gives a blank result and the following error:
TypeError: 'dict' object is not callable
or TypeError: Either add the reaction to a model or use Metabolite objects instead of strings as keys

How do I use metabolite objects as keys? (or rather, how do I convert my keys into objects?)

This is a needlessly terrible issue, since the docs only require a dictionary of metabolites, yet a dictionary doesn't work. Is there a way to solve this by programming, instead of me having to manually input the dictionary in?

**Comment by Midnighter** [comment]
Hi @kristycyw,

Did you have a read through this part of the docs https://cobrapy.readthedocs.io/en/latest/building_model.html ? I believe it answers all your questions.

**Comment by kristycyw** [comment]
Hi, I have, and I've also tried it, if you directly form a dictionary of metabolites, and then do Reaction.add_metabolites(dictionary), it gives you blank reactions, I've even tried calling the key, value pairs. It only works when I physically copy the dictionary and type it in.

**Comment by Midnighter** [comment]
Maybe the confusion is that you expect a return value when there is none? You can only add metabolites to an existing reaction object. Minimal example:

```py
reaction = cobra.Reaction("RXN")

reactant = cobra.Metabolite("reactant")
product = cobra.Metabolite("product")

reaction.add_metabolites({reactant: -1, product: 1})
reaction.build_reaction_string()
```
```
'reactant --> product'
```

**Comment by cdiener** [comment]
seems to be resolved
