### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by dengxiao01** [opencobra/cobrapy#1236]
#### Problem description

![image](https://user-images.githubusercontent.com/103829632/174247489-e3bfd9ea-c1e2-43db-84c3-993cfa76a25c.png)

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
```

```
```

### Context

<details>

ValueError: Object has no .reactions attribute. Cannot load.

</details>

**Comment by cdiener** [comment]
This does not look like it is an actual JSON COBRA model in the file. Where did you get this model from, or can you attach it here?

**Comment by dengxiao01** [comment]
> This does not look like it is an actual JSON COBRA model in the file. Where did you get this model from, or can you attach it here?

this Is derived from the https://modelseed.org/genomes/Plants
The json file in the model seed database cannot be uploaded
thanks

**Comment by cdiener** [comment]
Thanks, that helps. It is a bit confusing but even though you can download JSON files from ModelSEED those are not COBRAPY JSON models but just the ModelSEED data in JSON format. So you waon't be abble to read those files with COBRAPY. The SBML file should be readable but as pointed out by the other issue they have duplicated IDs which is a bug in ModelSEED.
