### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alvxi** [opencobra/cobrapy#1238]
### Checklist

- [x] I searched the [documentation](https://cobrapy.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [x] I looked up "How to do ... in cobrapy" on a search engine.

### Question

Hi, I'm having issues importing a model in COBRApy.

when the script runs `cobra_model = cobra.io.load_matlab_model("input_models/yeast8_thermo_curated.mat")` I get the following error:

```
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, ce, e, er, erm, g, gm, i, lp, m, mm, n, p, v, vm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/cobra/io/mat.py", line 301, in load_matlab_model
    return from_mat_struct(data[possible_name], model_id=possible_name, inf=inf)
  File "/home/user/.local/lib/python3.10/site-packages/cobra/io/mat.py", line 773, in from_mat_struct
    mat_parse_annotations(new_metabolites, m, d_replace=DICT_MET)
  File "/home/user/.local/lib/python3.10/site-packages/cobra/io/mat.py", line 394, in mat_parse_annotations
    obj.annotation = {
  File "/home/user/.local/lib/python3.10/site-packages/cobra/io/mat.py", line 395, in <dictcomp>
    prov: annotations[prov][i] for prov in providers if annotations[prov][i]
IndexError: list index out of range

```

Don't know what could be the problem, already tested in 3 different environments and gives the same error.
The model I'm trying to import belongs to the[ yETFL model](https://github.com/EPFL-LCSB/yetfl) and can be found [here on zenodo](https://zenodo.org/record/4778047#.YKfF8OvRY6U)

Thanks in advance

**Comment by akaviaLab** [comment]
Hi.
I looked at the model, and there is something wrong with it.
There are 2692 metabolites, but most of the fields for metabolites (like metNotes, metKEGGID) have 2691 entries.
So when the code gets to the last metabolite (h_i) it tries to find metKEGGID for it, and fails, since the list for kegg IDs isn't big enough. 
Can you check with the cobratoolbox pepole (https://groups.google.com/forum/#!forum/cobra-toolbox) if this is valid? Can you open this model in MATLAB (if you have it) and see what happens?

**Comment by alvxi** [comment]
> Can you open this model in MATLAB (if you have it) and see what happens?

Hi, I tried to import this model on matlab, and it didn't work. I checked on the verifyModel function and raises this:

```
>> verifyModel(model)
verifyModel: The following problems have been encountered in the model structure
inconsistentFields:
metNotes: mets: Size of metNotes does not match elements in mets
metKEGGID: mets: Size of metKEGGID does not match elements in mets
metChEBIID: mets: Size of metChEBIID does not match elements in mets
metMetaNetXID: mets: Size of metMetaNetXID does not match elements in mets
metSBOTerms: mets: Size of metSBOTerms does not match elements in mets

ans = 

  struct with fields:

    Errors: [1×1 struct]
```
It seems that is what you are saying. How do I solve this? Couldn't I add some blank space where is needed to get the same number of entries? Or it will ignore the spaces in blank when matching the sizes of the vectors?
Thanks

**Comment by akaviaLab** [comment]
Contact the people who made the model? And ask them to fix it?
I could maybe get cobrapy to load it but the model would still be broken.
Also not sure cobrapy can de0al well with thermodynamics.
