### ISSUE TITLE
The file cannot save formula after assigning a model formula

### ISSUE THREAD

**Issue by dengxiao01** [opencobra/cobrapy#1241]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

### Question
model=cobra.io.read_sbml_model('Sitalica-v2.1.sbml')
for met in model.metabolites:
    met.formula=formula[1]
    met.charge=charge[1]
    print(met.formula,met.charge)
formula[] and charge[] is two lists.
The background is that the model doesn't have formula and charge, so add it.
As shown in the code above, the metabolite charge can be added, and the file has been changed; Formula is successfully assigned, but the formula of the original file is not changed.
What is the reason for this? How to change the formula in the file?

**Comment by matthiaskoenig** [comment]
To store the changed model you have to save the model to file again, i.e. use `cobra.io.write_sbml_model`.
You can nicely format your code by using three back ticks, which makes it much more readible.
```python
model=cobra.io.read_sbml_model('Sitalica-v2.1.sbml')
for met in model.metabolites:
    met.formula=formula[1]
    met.charge=charge[1]
    print(met.formula,met.charge)
```
Try to do the following after the changes. You only changed the model object in memory but did not write it back to a file.
```python
cobra.io.write_sbml_model(model, 'Sitalica-v2.1_with_charge_formula.sbml')
```

**Comment by dengxiao01** [comment]
> 要存储更改的模型，您必须再次将模型保存到文件中，即使用。您可以通过使用三个反向刻度来很好地格式化代码，这使其更具可读性。`cobra.io.write_sbml_model`
> 
> ```python
> model=cobra.io.read_sbml_model('Sitalica-v2.1.sbml')
> for met in model.metabolites:
>     met.formula=formula[1]
>     met.charge=charge[1]
>     print(met.formula,met.charge)
> ```
> 
> 更改后，请尝试执行以下操作。您只更改了内存中的模型对象，但未将其写回文件。
> 
> ```python
> cobra.io.write_sbml_model(model, 'Sitalica-v2.1_with_charge_formula.sbml')
> ```

This error is reported when I write using the write_sbml_model method
![image](https://user-images.githubusercontent.com/103829632/176361432-7b175ea1-1182-45b8-9f13-d7f30a93903b.png)

**Comment by cdiener** [comment]
Can you share the model file so we debug what is going on?
