### ISSUE TITLE
ModuleNotFoundError: No module named 'cobra.test'

### ISSUE THREAD

**Issue by sshort325** [opencobra/cobrapy#1243]
### Question
Hello, 
I am new to python and cobra, I keep getting this message on my python and Im not sure how to fix it. For reference I am on a mac big sur. Thank you for any help, or ideas. 
![Screen Shot 2022-06-29 at 11 00 44 AM](https://user-images.githubusercontent.com/107510978/176498752-66127f48-c696-4cac-8b29-f0bd56cdaf94.png)

**Comment by cdiener** [comment]
Hi. `cobra.test` has been deprecated for the newer `load_model`. See https://cobrapy.readthedocs.io/en/latest/getting_started.html.

**Comment by sshort325** [comment]
Thank you so much! I just want to check one thing to make sure that I have everything working right. When I did "import cobra" a little orange warning came up and it said " 'cobra' imported but unused (pyflakes E)" is that normal?

**Comment by cdiener** [comment]
Yep, that is just the linter (like a code style checker showing common problems). You imported COBRAPY but did not actually use any functions from it yet (no code with `cobra.XXX`) so it's telling you that it is unused and could be removed from the code. As soon as you actually use any functions/objects from it, the warning will go away.

**Comment by sshort325** [comment]
Awesome :) thank you so much for your help!

**Comment by cdiener** [comment]
Sure, good luck!
