### ISSUE TITLE
module 'cobra' has no attribute 'test'

### ISSUE THREAD

**Issue by sshort325** [opencobra/cobrapy#1244]
I am not sure what this means, can anybody help? Thank you! 
![Screen Shot 2022-07-01 at 1 27 47 PM](https://user-images.githubusercontent.com/107510978/176957957-13945ea8-57f2-449f-b8c4-ce4d9195a3bf.png)

**Comment by cdiener** [comment]
You asked the same question 2 days ago, so I'll just post the answer from there: https://github.com/opencobra/cobrapy/issues/1243 . Also for questions on COBRAPY usage please use the [Discussion forum](https://github.com/opencobra/cobrapy/discussions), thank you!

EDIT: fixed the link.

**Comment by cdiener** [comment]
Sorry, also in line 15 you are using `cobra.test` again. That is why it complains even though you don't import it anymore.

**Comment by sshort325** [comment]
Do i replace that with the "model = load_model(file name here)?

**Comment by cdiener** [comment]
`load_model("iJO1366")` should do the trick (E. coli model was renamed since there are many models for it available).
