### ISSUE TITLE
 save the model in mat file  error 

### ISSUE THREAD

**Issue by Ilhem36** [opencobra/cobrapy#1249]
#### Problem description

Please explain:
I'm trying to merge the Harvetta model with a .json model using merge function which generates a merged model in json and then convert it to .mat file but it' is crushing and gave me this error: 
MemoryError: Unable to allocate 225. GiB for an array with shape (153774, 196073) and data type float64
Do you have any idea please  to fix this error. 
How can we merge the stoichiomatrix  of two models in cobrapy ? 

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```import cobra 
cobra.Configuration().upper_bound = 100000
model=cobra.io.load_json_model("merged_model.json")
cobra.io.save_matlab_model(model,"Model_humain.mat")
```

```
ile "C:\Users\IRI3\Desktop\stage_ilhem\code_ilhem\model_data\code\one_model\save_Human_model_matlab.py", line 11, in <module>
    cobra.io.save_matlab_model(model,"Model_humain.mat")

  File "C:\Users\IRI3\Anaconda3\lib\site-packages\cobra\io\mat.py", line 116, in save_matlab_model
    mat = create_mat_dict(model)

  File "C:\Users\IRI3\Anaconda3\lib\site-packages\cobra\io\mat.py", line 155, in create_mat_dict
    stoich_mat = create_stoichiometric_matrix(model)

  File "C:\Users\IRI3\Anaconda3\lib\site-packages\cobra\util\array.py", line 72, in create_stoichiometric_matrix
    array = array_constructor[array_type]((n_metabolites, n_reactions), dtype=dtype)

MemoryError: Unable to allocate 225. GiB for an array with shape (153774, 196073) and data type float64
```

### Context

<details>

```
```

</details>

**Comment by matthiaskoenig** [comment]
You are running out of memory creating an extremly large stoichiometric matrix. Because stoichiometric matrices are practically empty you should use a sparse matrix representation instead (much less memory).

Basically by changing
https://github.com/opencobra/cobrapy/blob/178bb089530810785a1a080f443c3e46ba718461/src/cobra/io/mat.py#L686
from 
```python
stoich_mat = create_stoichiometric_matrix(model)
```
to 
```python
stoich_mat = create_stoichiometric_matrix(model, array_type="dok")
```
or
```python
stoich_mat = create_stoichiometric_matrix(model, array_type="lil")
```
should fix the issue.

**Comment by Ilhem36** [comment]
Thank your answer , but  the principal issue is when I want to save the model in .mat format  using this function: 
cobra.io.save_matlab_model(merged_model,"merged.mat")
after merging two models, and I'm getting the same error . Do you know please how can I fix it ?

**Comment by matthiaskoenig** [comment]
This is the cause of your "principal" issue. The stoichiometric matrix created in the process of saving the model is just too large (too much memory), so you have to use sparse matrices during saving.
Please try the fix and let me know if it works. I.e. install the version with the bugfix and see if it solves your issue
```
pip install git+https://github.com/opencobra/cobrapy.git@247716b74f1d151daadff7ea8ed2b33d3fa9fc61
```
It seemed that you used an older version of cobrapy, so you should probably first update to the latest version and see if your issue remains and then try the bugfix install.

Best Matthias

**Comment by Ilhem36** [comment]
Thanks it was fixed but when I'm trying to open the model I'm getting this error

![image](https://user-images.githubusercontent.com/75625865/178938328-265f62c3-7ac5-43c8-b9de-c361e53e1ccf.png)
and this one i'm trying to run my model from the begining to save directly the model in .mat format
![image](https://user-images.githubusercontent.com/75625865/178938449-c393f952-e878-4822-8650-433c0231f7da.png)

**Comment by cdiener** [comment]
If you are using pickled models make sure they are saved and read on the same cobrapy version. A model pickled in one cobrapy version can generally not be unpickled with another version.
