### ISSUE TITLE
can't find the additional constraints after saving the model in .mat format or .json format 

### ISSUE THREAD

**Issue by Ilhem36** [opencobra/cobrapy#1255]
Please explain:
I'm trying to add coupling constraints in a model  and save the modifications in a new model with cobra.save matlab or json 
![image](https://user-images.githubusercontent.com/75625865/180626562-fe244d98-5328-42c2-9c8e-807ce4e86652.png)

the coupling are inserted successfully but when i reload the model I don't find the modification in the model. Do you Have please any idea to how to save the modification in the model? 
#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
```

```
```

### Context

<details>

```
```

</details>

**Comment by cdiener** [comment]
Yep, unfortunately not supported yet. There is current work to bring it to SBML and JSON (see the respective PR). MAT is on the horizon but will probably still take a while

**Comment by Ilhem36** [comment]
Where  can I find please  the respective PR  please ?

**Comment by cdiener** [comment]
The newer discussion is in #1240 and the previous PR is in #996.
