### ISSUE TITLE
Bug in solving a model with  qsqp and pFBA solver 

### ISSUE THREAD

**Issue by Ilhem36** [opencobra/cobrapy#1265]
#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```def FBA_solver(solver, merged_model): 
    merged_model.solver = solver
    solution =cobra.flux_analysis.pfba(merged_model)
    return solution
```

```
![image](https://user-images.githubusercontent.com/75625865/184305996-8cd40099-45ce-492f-81b3-a6a8d3bb5415.png)

```

**Comment by Ilhem36** [comment]
![image](https://user-images.githubusercontent.com/75625865/184305996-8cd40099-45ce-492f-81b3-a6a8d3bb5415.png)

**Comment by cdiener** [comment]
OSQP is not a good solver for linear problems. GLPK - or CPLEX/Gurobi for larger models - will perform better here.

**Comment by cdiener** [comment]
Alternatively, you can try to lower the tolerance, and it might converge by doing:

```
merged_model.solver = "osqp"
merged_model.tolerance = 1e-4
solution =cobra.flux_analysis.pfba(merged_model)
return solution
```
