### ISSUE TITLE
can't read sbml model, the window not respond when using vscode jupyter

### ISSUE THREAD

**Issue by yezhizi** [opencobra/cobrapy#1270]
### Description

<img width="1080" alt="Snipaste_2022-08-26_10-06-52" src="https://user-images.githubusercontent.com/74295100/186803764-48706cea-6d6d-4414-9253-b4639ed8ac63.png">

I tried to read a sbml model file, the window freezed when using vscode jupyter.  But I can load the model in cmd prompt.
```python
import cobra
from cobra import read_sbml_model
model=read_sbml_model("./Creinhardtii-v5.5-copy.xml")
print(model.summary())
```
<img width="828" alt="Snipaste_2022-08-26_10-30-29" src="https://user-images.githubusercontent.com/74295100/186804130-dcf43fc0-8b34-4107-a732-39b71d15c672.png">
the model file is sourced from the MODELSEED website.

**Comment by cdiener** [comment]
When you run it on the command line do you get a lot of warnings when reading the model by any chance? Jupyter often has issues when functions generate huge amounts of warnings or text output. 

If that is the case you could try running something like

```python
import warnings

warnings.simplefilter("ignore")
```

before reading the model.

**Comment by yezhizi** [comment]
> When you run it on the command line do you get a lot of warnings when reading the model by any chance? Jupyter often has issues when functions generate huge amounts of warnings or text output.
> 
> If that is the case you could try running something like
> 
> ```python
> import warnings
> 
> warnings.simplefilter("ignore")
> ```
> 
> before reading the model.

yes, I got a lot of warnings.  I tried but it still not work
<img width="1080" alt="Snipaste_2022-08-26_11-14-08" src="https://user-images.githubusercontent.com/74295100/186810119-54f2bc9c-a9af-4436-b503-2bb014939bd2.png">

**Comment by yezhizi** [comment]
I tried to close the warnings and text output, I don't know something like that didn't work
```python
import warnings

warnings.simplefilter("ignore")
```
but using the magic command may help
```python
%%capture --no-display
 ```
