### ISSUE TITLE
Documentation on https://cobrapy.readthedocs.io/en/latest/ not up to date

### ISSUE THREAD

**Issue by stellaprins** [opencobra/cobrapy#1289]
Was not sure how related this issue is to _Upgrade the documentation #970_. But I noticed that the documentation on https://cobrapy.readthedocs.io/en/latest/ does not match the more up to date documentation on GitHub. e.g. in _» 4. Reading and Writing Models_, it still says _load_json_model_model_ instead of _load_json_model_.

**Comment by cdiener** [comment]
As far as I can see, the docs are building fine. Though, they are only updated on new releases so you are seeing that discrepancy because the docs are still on the 0.25.0 version. We should probably make a new release anyway so hopefully that would fix that.

**Comment by stellaprins** [comment]
Ah that makes sense now. It indeed is the discrepancy of the 0.25.0 version with the ammended documentation on GitHub, thanks!

**Comment by cdiener** [comment]
Hmm, the release did not fix this...
