### ISSUE TITLE
minimal media growth rate

### ISSUE THREAD

**Issue by amarsh26** [opencobra/cobrapy#1307]
Hello,

The documentation for minimal media provides the following example. 

`from cobra.medium import minimal_medium

max_growth = model.slim_optimize()
minimal_medium(model, max_growth)`

When I execute this code on the iML1515 model of _E. coli_, I receive the following results. 

 0.8769972144269745 (growth rate from using the minimal media function)
 0.8769972144269719 (growth rate with the default)

While this is a very slight difference, I was wondering to what level of precision do you expect the growth rate to match between the default configuration and the growth rate using minimal media.

Thanks for your help.

**Comment by cdiener** [comment]
The tolerance of the numerical solver can be inspected with `model.tolerance`. This is the largest relative and absolute deviation that should be expected. I think by default it somewhere between 1e-6 and 1e-9 so the deviation is within that. You can also adjust this tolerance by setting it to something smaller but it will increase computation time.

**Comment by amarsh26** [comment]
Thanks so much for your help!
