### ISSUE TITLE
minimal media question

### ISSUE THREAD

**Issue by amarsh26** [opencobra/cobrapy#1313]
Hello,

When I manually enter the media from minimal_medium(model, max_growth), I receive a different biomass (0.8571429) then using tool to obtain minimal medium for FBA (0.876997). The max_growth used to obtain the minimal was the default. Is this expected behavior?

In addition, if I slightly increase the value for mobd in the manually entered minimal media from (0.000006  to 0.000007) and change no other values, the biomass increase to 0.8761609907. I was also wondering if this is expected. 

The data was obtained using the iML1515 model of _E. coli_.

Thanks!

**Comment by cdiener** [comment]
Sorry for the delayed response. By hand do you mean just typing the first x digits? Than this would be expected because this is not the exact value returned and you would be truncating it...
