### ISSUE TITLE
from cobra.io import load_model  model = load_model("textbook") model.medium

### ISSUE THREAD

**Issue by ChenCongZ** [opencobra/cobrapy#1320]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

### Question

Hi，
from cobra.io import load_model
model = load_model("textbook")
model.medium

 Is it the output file of the model? What is "textbook" in the code file format? for example sbml or json format.

**Comment by ChenCongZ** [comment]
@Midnighter

**Comment by ChenCongZ** [comment]
![QQ浏览器截图20230306135258](https://user-images.githubusercontent.com/98649346/223029747-96b8c81b-5ec8-4c04-8576-911d95b341fa.png)

**Comment by cdiener** [comment]
Hi, `load_model` is used to load models directly from repositories. For loading an SBML model you can use:

```python
from cobra.io import read_sbml_model

model = read_sbml_model("YOUR_MODEL_PATH")
```

Also see https://cobrapy.readthedocs.io/en/latest/io.html .

**Comment by ChenCongZ** [comment]
Hi, @cdiener 
 Thank you for help. I solved the problem I encountered.
