### ISSUE TITLE
How to set the model solver

### ISSUE THREAD

**Issue by brunorbqi** [opencobra/cobrapy#1333]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

### Question

How can I set a solver other than gurobi for cobrapy ? In the cobrapy documentation says that glpk solver is used as default, but always when I load a model in cobrapy, shows that gurobi is being used. Once my license have expired I could not use cobrapy funcions. I tried use the 'model.solver = glpk' but not worked. There is any way other than model.solver to set the solver in cobrapy? Because even when others solvers are available looks like the gurobi overlaps. Best regards.

**Comment by cdiener** [comment]
Your syntax is slightly off. It would be `model.solver = "glpk"`. Alternatively if you uninstall gurobi from your python environment it will use GLPK by default.
