### ISSUE TITLE
ContainerAlreadyContains error with the fastcc()

### ISSUE THREAD

**Issue by Alvis-Jiang** [opencobra/cobrapy#1334]
Hi 

I am currently using cobrapy but came across some errors with the fastcc( ) module, which is "ContainerAlreadyContains: Container '' already contains an object with name 'constraint_r0998'." 

I am using Python 3.8. Could you help me to figure out this issue? Any feedback will be greatly appreciated!
![WeChat Screenshot_20230520151354](https://github.com/opencobra/cobrapy/assets/64271338/267bc376-43ed-47d5-87ea-375e888d7bdf)

**Comment by cdiener** [comment]
Our apologies, the FastCC code is currently a bit buggy and does not work correctly. It is on our radar to fix it though... You can use the `find_blocked_reactions` function in the meantime which should work.

**Comment by cdiener** [comment]
Sorry, just saw similar errors pop up elsewhere. That particular error should be fixed by downgrading sympy to 1.11.1 (`pip install "sympy==1.11.1". After that the function should run, but the results will likely not be correct.

**Comment by Alvis-Jiang** [comment]
Got it, thanks a lot for your help!
