### ISSUE TITLE
createMultipleSpeciesModel function can not find in cobrapy

### ISSUE THREAD

**Issue by wupeng1998** [opencobra/cobrapy#1336]
Hi everyone, I want to simulate the interaction of bacterium like the method 2.7 of the article "https://pubmed.ncbi.nlm.nih.gov/36720400/", but I didn't find it in cobrapy createMultipleSpeciesModel function, how should I implement it in python?

**Comment by cdiener** [comment]
This is a function in the (Matlab-based) cobratoolbox not in cobrapy. You could look into MICOM if you want to run microbial community models on Python.

**Comment by wupeng1998** [comment]
> This is a function in the (Matlab-based) cobratoolbox not in cobrapy. You could look into MICOM if you want to run microbial community models on Python.

Ok, thank you. I know it's a function on matlab, but I'm getting errors when I replicate it to python, so I was wondering if anyone has ever replicated this function from MATLAB to Python,.

**Comment by cdiener** [comment]
The [`Community`](https://micom-dev.github.io/micom/community.html) class in MICOM is somewhat similar, and the community objective is the same. So you could start there.

**Comment by cdiener** [comment]
Closing for now since it's not really a bug in cobrapy. Feel free to open a discussion topic. Best.
