### ISSUE TITLE
SBML file not getting uploaded

### ISSUE THREAD

**Issue by ksingh371** [opencobra/cobrapy#1337]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

### Question

I had prepared my metabolic model on merlin and was trying to run the model for FBA on COBRApy. But on uploading the model the following error is coming up:
1912 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id

1912 is the NCBI taxonomic identifier of the organism used in merlin.  Please suggest ways to overcome this problem

**Comment by cdiener** [comment]
Not sure what you mean by upload here. Can you give a minimal reproducible example and provide the model file? Looks like your model has incorrect annotations. If that file was generated by Merlin maybe also report it there?

**Comment by Midnighter** [comment]
NCBI txids are not recognized in https://registry.identifiers.org/registry. I would encourage you to remove that model annotation. You should be able to give it a RefSeq annotation for the genome used, if that is important to you.

Otherwise, please provide more information as @cdiener asked for.
