### ISSUE TITLE
how to handle mixed-integer programming (MIP) problems with the glpk, cplex or/and gurobi solvers in python/with cobrapy?

### ISSUE THREAD

**Issue by helehera** [opencobra/cobrapy#1342]
in matlab/cobra toolbox, I have use the functions glpk, cplexmilp and gurobi_mex to solve the following problems: 
% Solve problem
        [x, f, stat, extra] = glpk(c, A, b, lb, ub, csense, vartype, osense, solverParams)

            [x, f, exitflag, output] = cplexmilp(c, Aineq, bineq, MILPproblem.A, b, lb, ub, vartype);

        [x,f,stat,output] = gurobi_mex(c,osense,sparse(A),b, ...
            csense,lb,ub,vartype,opts);

How do I solve the problems in python/cobrapy?

**Comment by Midnighter** [comment]
Is your question, [how to change the solver backend](https://cobrapy.readthedocs.io/en/latest/solvers.html#Solvers)?

**Comment by helehera** [comment]
No. How to solve an LP/MILP problem like the one in https://www.mathworks.com/matlabcentral/fileexchange/75318-glpkmex-gnu-linear-programming-kit-glpk-mex-generator. I know it says that Cobrapy have not implemented any algorithms to find solutions to such problems but I do not know how do come about it.

**Comment by Midnighter** [comment]
There are some MILP implemented. But if you are talking about defining your own problem you need to get familiar with [optlang](https://optlang.readthedocs.io/). That is what cobrapy uses underneath.

**Comment by helehera** [comment]
ok @Midnighter. Where can I find more information about the MILP that has already been implemented? I have searched without any luck!

**Comment by Midnighter** [comment]
[Minimizing a medium's components](https://cobrapy.readthedocs.io/en/latest/media.html#Minimal-media) is an MILP, for example.
