### ISSUE TITLE
Flux-Samplig: Cannot escape sampling region, model seems to be numerically unstable. Reporting the model

### ISSUE THREAD

**Issue by brunorbqi** [opencobra/cobrapy#1344]
### Checklist

- [ ] I searched the [documentation](https://cobrapy.readthedocs.io).
- [ ] I looked through [similar issues on GitHub](https://github.com/opencobra/cobrapy/issues).
- [ ] I looked up "How to do ... in cobrapy" on a search engine.

### Question

I gave tried to make a flux samplig for my model as following: 
mfg_bruc = cobra.io.read_sbml_model("iRAW-iBP.xml")

pfba_solution = cobra.flux_analysis.pfba(mfg_bruc)
opt_value = pfba_solution["biomass_BA"]

with mfg_bruc:
    
    mfg_bruc.reactions.get_by_id("biomass_BA").lower_bound = opt_value*.95
   
    %time mfg_bruc_samples = sample(mfg_bruc, 10000, processes=4)
  
At the end, I got the following error : RuntimeError: Cannot escape sampling region, model seems to be numerically unstable. Reporting the model.

How can I fix this error ?! Best regards

**Comment by cdiener** [comment]
Hi thanks for the report. Can you share your model, so we can take a look what is going on?

**Comment by cdiener** [comment]
Closing because no response received.
