### ISSUE TITLE
find_gene_knockout_reactions error

### ISSUE THREAD

**Issue by Laminsecin** [opencobra/cobrapy#1351]
cannot import name 'find_gene_knockout_reactions' from 'cobra.manipulation.delete' (C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\cobra\manipulation\delete.py)

**Comment by cdiener** [comment]
This function has been deprecated since [version 0.25.0](https://github.com/opencobra/cobrapy/releases/tag/0.25.0). Do you get that error in a different package that uses cobrapy internally?
