### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by jotech** [opencobra/cobrapy#136]
Perhaps you could add 
``
python-dev
``
as neccessary packages on debian-like systems in the install instructions ([1](https://github.com/opencobra/cobrapy/blob/master/INSTALL.md))?
Otherwise ``pip install cobra --pre`` does not compile:
``
cobra/solvers/cglpk.c:8:22: fatal error: pyconfig.h: No such file or directory
``

**Comment by aebrahim** [comment]
Thanks for pointing this out.
