### ISSUE TITLE
upgrading dependency to allow pandas>=2.0

### ISSUE THREAD

**Issue by eladnoor** [opencobra/cobrapy#1362]
Now the requirement is `pandas~=1.0` which is already a problem on python 3.12 (there are no wheels for `pandas==1.5.3`).
Changing to `pandas>=1.0`, or `pandas~=2.0` would solve it.

* pandas 2.0 was released on April 3, 2023.

**Comment by Midnighter** [comment]
That's a good point. I don't think the pandas API relevant to cobrapy has changed at all. So hopefully just changing the version modifier should be enough.
