### ISSUE TITLE
cglpk cython compile error 

### ISSUE THREAD

**Issue by afif-elghraoui** [opencobra/cobrapy#138]
Hi,
I tried to install the latest version via pip and I get a compiler error on the cython file. When I run cobra after this installation, only glpk is in `cobra.solvers` (not cglpk).
    Downloading cobra-0.3.0.tar.gz (2.3Mb): 2.3Mb downloaded
    Running setup.py egg_info for package cobra
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # Do not want to print out to terminal. Even when not verbose, output
    # will be redirected through the hook.
    glp_term_out(GLP_OFF)
    
    
    cdef int hook(void *info, const char *s):
                                        ^
    ------------------------------------------------------------
    
    cobra/solvers/cglpk.pyx:92:37: Expected ')', found '*'
    Compiling cobra/solvers/cglpk.pyx because it changed.
    Cythonizing cobra/solvers/cglpk.pyx

Do you also see this problem? I was getting this error before, but I needed QSOpt to work, so I had written my own interface to that solver using the regular glpk bindings.

**Comment by aebrahim** [comment]
Hello?

To help debug this, can you let me know:

1) What OS are you using?
2) What version of Cython?
3) What version of GLPK (and how was it installed)?

**Comment by afif-elghraoui** [comment]
I'm sorry for the lack of information-- I was first just wondering if it was a simple syntax error that might be easily reproducible. I'm using Debian 7, Cython version 0.15.1, and GLPK v.4.45-- both installed through the package manager. I've never had any trouble using glpk with cobra before.

**Comment by aebrahim** [comment]
My suggestion is to update Cython. I use version 0.21.2

**Comment by afif-elghraoui** [comment]
Ok, I just updated to Cython 0.19.1 through Debian stable backports and that solved the problem. Thanks for your prompt help!

**Comment by aebrahim** [comment]
No problem.
