### ISSUE TITLE
Error in find_blocked_reactions() 

### ISSUE THREAD

**Issue by oveoyas** [opencobra/cobrapy#139]
In the latest version of COBRA (0.3.0), `cobra.flux_analysis.variability.find_blocked_reactions()` fails. I get the following error message:
```
  File "/usr/local/lib/python2.7/dist-packages/cobra/flux_analysis/variability.py", line 81, in find_blocked_reactions
    if not the_reactions:
UnboundLocalError: local variable 'the_reactions' referenced before assignment
```
Passing `the_reactions` to the function as a keyword argument does not resolve the problem. It appears that the name of `the_reactions` has been changed to `reaction_list` without fully updating the body of the function.

**Comment by aebrahim** [comment]
Thank you for pointing this out.
