### ISSUE TITLE
[BUG] Unable to load SBML model despite valid online validation

### ISSUE THREAD

**Issue by hazlamshamin** [opencobra/cobrapy#1417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am encountering an issue where COBRApy fails to load multiple SBML models. These models were freshly downloaded from the BiGG Models Database (http://bigg.ucsd.edu/) and validated successfully using the SBML online validator (https://sbml.bioquant.uni-heidelberg.de/validator_servlet/index.jsp).

Despite this, COBRApy reports validation errors (SBML_FATAL, SBML_ERROR, etc.) and refuses to load the models. This behavior persists across different models, including:
	•	iJO1366.xml
	•	e_coli_core.xml

### Code sample

Code run:

```python
from cobra.io.sbml import validate_sbml_model, read_sbml_model

model_path = "/path/to/model.xml"

try:
    # Validate model in COBRApy
    _, errors = validate_sbml_model(model_path)
    if errors:
        print("Validation Errors:")
        for error in errors:
            if hasattr(error, '__dict__'):
                print(error.__dict__)  
            else:
                print(error) 
    else:
        # Attempt to load the model
        model = read_sbml_model(model_path)
        print("Model loaded successfully!")
except Exception as e:
    print(f"Error loading model: {e}")
```

Validation output:

```text
Validation Errors:
SBML_FATAL
SBML_ERROR
SBML_SCHEMA_ERROR
SBML_WARNING
COBRA_FATAL
COBRA_ERROR
COBRA_WARNING
COBRA_CHECK
```

### Environment

<details>
<summary>Environment Details</summary>

Operating System: macOS Sonoma 15.1.1 (Build 24B91)  
Python Version: 3.9.18  
COBRApy Version: 0.29.1  
libsbml Version: 5.20.4  
Active Environment: straindesign_env (conda)  
Solver Versions:  
- Gurobi: 12.0.0  
- GLPK: 5.0  

</details>

**Comment by Midnighter** [comment]
You are printing the possible error and warning types, not actual errors. Not super intuitive but each error has then a list of messages if there are any. So it seems none of these models actually have any errors.
