### ISSUE TITLE
Suggestion: Replacing DictList with Python's official OrderedDict

### ISSUE THREAD

**Issue by afif-elghraoui** [opencobra/cobrapy#142]
Python includes an `OrderedDict` type, which offhand looks like it plays the same role as `cobra.core.DictList`. Would deprecating that in favor of `OrderedDict` be an acceptable substitution? If it is the same, it would appear to be a safer way to go. From PEP 372:

There are many ordered dict implementations in various libraries and applications, most of them subtly incompatible with each other. Furthermore, subclassing dict is a non-trivial task and many implementations don't override all the methods properly which can lead to unexpected results.

Additionally, many ordered dicts are implemented in an inefficient way, making many operations more complex then they have to be.

**Comment by aebrahim** [comment]
DictList inherits from list, not dict. Therefore OrderedDict would not be a
suitable replacement. Are there any list methods in particular you feel are
missing, or inefficiencies/bugs?

DictList acts like a list but has an o(1) lookup time for index (a list has
o(n)), which makes cobrapy a lot faster than if a regular list was used.

Something which inherits from list may be a suitable replacement.

**Comment by afif-elghraoui** [comment]
Oh no, it was just a suggestion that might have resulted in one less Python class to look after if it worked out. I haven't seen any particular inefficiencies or bugs.
Thanks for taking a look

**Comment by aebrahim** [comment]
Thanks for the suggestion. Please keep them coming. I generally agree with the sentiment to replace things with strandardized components, but it would not have provided the necessary features in this case.
