### ISSUE TITLE
read_sbml_model fails with attached model only under python 3

### ISSUE THREAD

**Issue by phantomas1234** [opencobra/cobrapy#154]
Under python 3.4

    read_sbml_model('EcoliCore.xml')

leads to

    cobra/io/sbml.py:269 UserWarning: gene_reaction_rule is not ascii compliant
    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-7-c0f4c8b042ea> in <module>()
    ----> 1 m = read_sbml_model('../cameo/tests/data/EcoliCore.xml')

    /Users/niko/Dev/cobrapy/cobra/io/sbml.py in create_cobra_model_from_sbml_file(sbml_filename, old_sbml, legacy_metabolite, print_time, use_hyphens)
        286 
        287                     if 'ABBREVIATION' in tmp_row_dict:
    --> 288                         gene_id_to_object[tmp_locus_id].name = tmp_row_dict['ABBREVIATION']
        289 
        290         if 'SUBSYSTEM' in reaction_note_dict:

    KeyError: 'b0351'

No problem under python 2.7. python-libsbml-experimental has been installed for libsbml support. The cobra version is '0.3.2.post19+git24f785b'.

The model can be found [here](https://raw.githubusercontent.com/biosustain/cameo/devel/tests/data/EcoliCore.xml).

**Comment by aebrahim** [comment]
I'll take a look. Thanks for the bug report Niko.

On a side note, support for the draft fbc v2 is implemented in #152. Because the format is a lot better, there should be way fewer bugs. It's also a lot faster because it's using pure python instead of python-libsbml-experimental. I recommend converting your models when it's finalized.

**Comment by phantomas1234** [comment]
Yeah, I saw that. That would be great. Works almost. The fbc encoded
objective function doesn't get set yet though, right? At least no objective
was set when I tried loading a fbc model.

**Comment by aebrahim** [comment]
I think there was a bug like that in an earlier implementation - did you
try it with the latest version in the pull request?

Also my pure python implementation only handles sbml l3v1 with fbc v2. It
also doesn't sanitize id's.

**Comment by aebrahim** [comment]
Parsing of this file now works for me as of 0.4.0a1.post4+git013d2ab

You must have fixed the issue in #156.

**Comment by phantomas1234** [comment]
Yes, I think it did, thanks.
