### ISSUE TITLE
Python 3 compatibility issue in cplex_solver.py 

### ISSUE THREAD

**Issue by phantomas1234** [opencobra/cobrapy#155]
https://github.com/opencobra/cobrapy/blob/master/cobra/solvers/cplex_solver.py#L153

No such thing as dict.iteritems in python 3.

**Comment by aebrahim** [comment]
Does cplex work in Python 3 yet? I only have 12.3 which doesn't (and I can't get access to the latest version to test)

**Comment by phantomas1234** [comment]
Yes,

12.6.1 does. I'll share with you in a sec.

Niko
