### ISSUE TITLE
Wrong reversibilities when exporting to MATLAB

### ISSUE THREAD

**Issue by oveoyas** [opencobra/cobrapy#158]
When exporting a model to MATLAB format using the ```save_matlab_model``` function, the reversibility vector of the exported model seems to be incorrect. Take the following code, for example:
```python
import cobra.test
from cobra.io.mat import save_matlab_model
model = cobra.test.create_test_model()
save_matlab_model(model, model.id + ".mat")
```
The reversibility vector of the resulting MATLAB model starts as follows (first ten elements):
true
true
true
false
false
false
false
false
true
false

However, the first ten reversibilities should be:
false
false
false
false
false
false
false
true
true
true

**Comment by oveoyas** [comment]
This can for example be fixed by replacing "True" and "False" with 1 and 0, respectively, in the list of reversibilities in the dict that is passed to the ```savemat``` function. I did this by replacing
```python
mat["rev"] = array(rxns.list_attr("reversibility"))
```
with
```python
 mat["rev"] = array([int(x) for x in rxns.list_attr("reversibility")])
```
in the ```create_mat_dict``` function

**Comment by aebrahim** [comment]
Thanks for the bug report!
