### ISSUE TITLE
Reducing number of optimizations when finding blocked reactions

### ISSUE THREAD

**Issue by oveoyas** [opencobra/cobrapy#159]
In the ```find_blocked_reactions``` function the number of necessary optimizations can be reduced by optimizing once at the beginning and then only looking for blocked reactions among reactions whose flux in the optimal solution is exactly zero. For example, I do the following when finding blocked reactions:
```python
model.optimize(solver='gurobi')
reaction_list = [r.id for r in model.reactions if r.x == 0]
blocked_reaction_ids = find_blocked_reactions(model, reaction_list=reaction_list, solver='gurobi')
```
A quick test with the iAF1260 model showed that the number of optimizations performed was reduced from 4767 to 3914. The total time used on my system was reduced from 33 to 25 seconds. Also, the obtained lists of blocked reactions were confirmed to be identical.

**Comment by aebrahim** [comment]
Done! Thanks for the suggestion.

**Comment by oveoyas** [comment]
Great, thanks a lot!
