### ISSUE TITLE
check_reaction_balance method

### ISSUE THREAD

**Issue by meono** [opencobra/cobrapy#162]
I think there is a problem with this line:
https://github.com/opencobra/cobrapy/blob/master/cobra/core/Reaction.py#L555
```                for k, v in the_metabolite.formula.elements.items():```

It works for salmonella test case but the models I read from xml have `...metabolite.elements`,not `...metabolite.formula.elements`

`                for k, v in the_metabolite.elements.items():` fixes the issue for me.

**Comment by aebrahim** [comment]
You are absolutely 100% correct. Thanks for the bug report! This should now
be fixed in 21af02a.

-Ali
