### ISSUE TITLE
ValueError: id SMILEY_DEMAND_RXN is already present in list

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/cobrapy#163]
Dear Cobrapy-Devs,

I realise that the gapAnalysis module is still in the "oven", yet I tried my hands on getting it functional to find and fill some gaps in a model that I wanted to work with. Eventually I got some error-free results out of the SMILEY function that made it useful as a gap finding tool, yet fixing the gap filling functionality was beyond my capability. Here is what I did and the errors I encountered, perhaps this helps "baking" this module.

-------------------------------

1. Initial attempt

when using the vanilla gapAnalysis.py with this script...

<pre><code>from cobra.io import read_sbml_model
import gapAnalysis
import cobra.test
import os

### Definition of the model that needs gaps to be filled (cobra_model) with reactions from the Universal model.
relative_directory = os.getcwd()
filename = relative_directory + '/BMID000000141026-M1.xml'

cobra_model = read_sbml_model(filename);
Universal = cobra.test.create_test_model('ecoli')

### Minimal growth medium (Methane and Ammonia)
cobra_model.reactions.MNXM99_in.upper_bound = 0
cobra_model.reactions.MNXM105_in.upper_bound = 0
cobra_model.reactions.MNXM13_in.upper_bound = 0
cobra_model.reactions.MNXM15_in.upper_bound = 10
cobra_model.reactions.bigg_ch4_out.lower_bound = -10
cobra_model.reactions.bigg_ch4_out.upper_bound = 10

### Maximize each Biomass component individually to reveal which cannot be produced.
non_producable = []
for metabolite in cobra_model.reactions.BIOMASS_REACTION.metabolites.keys():
    model_copy = cobra_model.copy()
    tmp_exc_rxn = cobra.Reaction('%s_out' % (metabolite))
    tmp_exc_rxn.add_metabolites({metabolite: -1})
    tmp_exc_rxn.objective_coefficient = 1
    tmp_exc_rxn.lower_bound = 0
    tmp_exc_rxn.upper_bound = 1000
    model_copy.add_reaction(tmp_exc_rxn)
    # print tmp_exc_rxn.reaction
    solution = model_copy.optimize(solver='cglpk')
    if solution.f <= 0.1:
        non_producable.append(metabolite)
# print non_producable , len(non_producable)

### Translate the metabolites from non_producable into metabolite IDs to simplify the later comparison with results of SMILEY algorithm
non_producable_ids = []
for item in non_producable:
    x = item.id.replace('_bm','')
    x = x + '_c'
    non_producable_ids.append(x)
print non_producable_ids

### This is important for the gapAnalysis to work at all
for met in Universal.reactions:
    if met in cobra_model.reactions:
        Universal.reactions.remove(met)
        
### Run the GapAnalysis on each individual metabolite that cannot be produced
supplemented_metabolites = []
for metabolite in non_producable_ids:
    used_reactions = gapAnalysis.SMILEY(cobra_model, metabolite, Universal, debug=True, dm_rxns=True, ex_rxns=True , solver='cglpk', iterations=1)
    for item in used_reactions[0]:
        item_clean_name = item.id.replace('DM_','')
        item_clean_name = item_clean_name.replace('_reverse','')
        if (item_clean_name not in non_producable_ids) and (item_clean_name not in supplemented_metabolites):
            supplemented_metabolites.append(item_clean_name)</code></pre>

... and the model linked <a href="http://puu.sh/hDw9E/371e30ae05.xml" title="Title">
here</a>. I would get the following error message: 

<pre><code>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-a0d1d0b0c582> in <module>()
     54 supplemented_metabolites = []
     55 for metabolite in non_producable_ids:
---> 56     used_reactions = gapAnalysis.SMILEY(cobra_model, metabolite, Universal, debug=True, dm_rxns=False, ex_rxns=True , solver='cglpk', iterations=1)
     57     for item in used_reactions[0]:
     58         item_clean_name = item.id.replace('DM_','')

/Users/clie/Desktop/EFPro2/gapAnalysis.pyc in SMILEY(model, metabolite_id, Universal, iterations, debug, dm_rxns, ex_rxns, solver, time_limit, **solver_parameters)
    176     demand_reaction.add_metabolites(
    177         {SUX.metabolites[SUX.metabolites.index(metabolite_id)]: -1})
--> 178     SUX.add_reaction(demand_reaction)
    179     used_reactions = SUX.solve(iterations=iterations, debug=debug,
    180         solver=solver, time_limit=time_limit, **solver_parameters)

/Users/clie/Desktop/EFPro2/gapAnalysis.pyc in _add_reaction(self, reaction)
    112     def _add_reaction(self, reaction):
    113         cobra.Model.add_reaction(self, reaction)
--> 114         self.original_reactions.append(reaction)
    115         self._update_objectives()
    116 

/Users/clie/.virtualenvs/modeling/lib/python2.7/site-packages/cobra/core/DictList.pyc in append(self, object)
    103         """append object to end"""
    104         the_id = object.id
--> 105         self._check(the_id)
    106         self._dict[the_id] = len(self)
    107         list.append(self, object)

/Users/clie/.virtualenvs/modeling/lib/python2.7/site-packages/cobra/core/DictList.pyc in _check(self, id)
     40         """
     41         if id in self._dict:
---> 42             raise ValueError("id %s is already present in list" % str(id))
     43 
     44     def _generate_index(self):

ValueError: id SMILEY_DEMAND_RXN_his_L_c is already present in list
</code></pre>

2. After changing the SMILEY function in gapAnalysis.py ...

... commenting out the lines 174 - 178 like so...
<pre><code>
def SMILEY(model, metabolite_id, Universal, iterations=1, debug=False,
           dm_rxns=False, ex_rxns=False, solver="glpk", time_limit=60, **solver_parameters):
    """
    runs the SMILEY algorithm to determine which gaps should be
    filled in order for the model to create the metabolite with the
    given metabolite_id.

    This function is good for running the algorithm once. For more fine-
    grained control, create a SUXModelMILP object, add a demand reaction
    for the given metabolite_id, and call the solve function on the
    SUXModelMILP object.
    """
    model = model.copy()
    SUX = SUXModelMILP(model, Universal, dm_rxns=dm_rxns, ex_rxns=ex_rxns)
    # change the objective to be the metabolite
    for reaction in SUX.original_reactions:
        reaction.objective_coefficient = 0
    # demand_reaction = cobra.Reaction("SMILEY_DEMAND_RXN_%s" % metabolite_id)
    # demand_reaction.objective_coefficient = 1
    # demand_reaction.add_metabolites(
    #     {SUX.metabolites[SUX.metabolites.index(metabolite_id)]: -1})
    # SUX.add_reaction(demand_reaction)
    used_reactions = SUX.solve(iterations=iterations, debug=debug,
        solver=solver, time_limit=time_limit, **solver_parameters)
    return used_reactions
</code></pre>

... I am no longer getting the error anymore and instead I get a nice enough result of which metabolites need to be added for the model to be able to produce the desired compounds and by extension this way I can find the corresponding gaps in my pathways. However, optimally I don't want to use the demand reactions to fill the gaps, but instead I want reactions from the Universal model. 

3. Hence, I tried running my script again with "dm_rxns=True"...

...and I received the following error message:
<pre><code>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-a0d1d0b0c582> in <module>()
     54 supplemented_metabolites = []
     55 for metabolite in non_producable_ids:
---> 56     used_reactions = gapAnalysis.SMILEY(cobra_model, metabolite, Universal, debug=True, dm_rxns=False, ex_rxns=True , solver='cglpk', iterations=1)
     57     for item in used_reactions[0]:
     58         item_clean_name = item.id.replace('DM_','')

/Users/clie/Desktop/EFPro2/gapAnalysis.pyc in SMILEY(model, metabolite_id, Universal, iterations, debug, dm_rxns, ex_rxns, solver, time_limit, **solver_parameters)
    178     # SUX.add_reaction(demand_reaction)
    179     used_reactions = SUX.solve(iterations=iterations, debug=debug,
--> 180         solver=solver, time_limit=time_limit, **solver_parameters)
    181     return used_reactions
    182 

/Users/clie/Desktop/EFPro2/gapAnalysis.pyc in solve(self, solver, iterations, debug, time_limit, **solver_parameters)
    127         for i in range(iterations):
    128             used_reactions[i] = []
--> 129             self.optimize(objective_sense="minimize", solver=solver, **solver_parameters)
    130             if debug:
    131                 print "Iteration %d: Status is %s" % (i, self.solution.status)

/Users/clie/.virtualenvs/modeling/lib/python2.7/site-packages/cobra/core/Model.pyc in optimize(self, objective_sense, solver, quadratic_component, **kwargs)
    283         the_solution = optimize(self, solver=solver,
    284                                 objective_sense=objective_sense,
--> 285                                 **kwargs)
    286         self.solution = the_solution
    287         return the_solution

/Users/clie/.virtualenvs/modeling/lib/python2.7/site-packages/cobra/solvers/__init__.pyc in optimize(cobra_model, solver, **kwargs)
    119         solver = get_solver_name(qp=qp)
    120 
--> 121     return solver_dict[solver].solve(cobra_model, **kwargs)

cobra/solvers/cglpk.pyx in cobra.solvers.cglpk.GLP.solve (cobra/solvers/cglpk.c:4162)()

cobra/solvers/cglpk.pyx in cobra.solvers.cglpk.GLP.solve_problem (cobra/solvers/cglpk.c:3969)()

cobra/solvers/cglpk.pyx in cobra.solvers.cglpk.check_error (cobra/solvers/cglpk.c:1631)()

RuntimeError: glp_simplex failed with error code GLP_EROOT: root LP optimum not provided
</code></pre>

Thats what I have so far. Perhaps it helps someone! I am personally going to use gapAnalysis as a tool to find gaps which I will then fill manually, which is helpful enough, but perhaps in the future it works as an automatic gap filler too.

Best,

Christian

**Comment by aebrahim** [comment]
Thanks for this detailed bug report. I'm hoping to get SMILEY and growMatch into mainline (not the oven) for the 0.4 release. This bug report helps a lot! Would you be willing to be a beta tester for this module when it's more polished up?

**Comment by ChristianLieven** [comment]
Hey Ali,

Sorry for the delayed response. Sure, count me in and let me know if you have something that I should test!

Best,
Christian

**Comment by SowbhagyaSuresh** [comment]
Funnily I am working with the same model and had the same issue! Thank you!
