### ISSUE TITLE
Disappearing metabolites after reaction removal

### ISSUE THREAD

**Issue by phantomas1234** [opencobra/cobrapy#164]
Fresh cobra 0.3.2 install. Running

    from cobra.io import read_sbml_model
    model = read_sbml_model("iJO1366.xml")
    r = model.reactions.EX_23cgmp_LPAREN_e_RPAREN_
    print(r.reaction)
    model.remove_reactions([r])
    print(r.reaction)

will yield

    23cgmp_e -->
and
      -->

**Comment by aebrahim** [comment]
This is the expected behavior. To keep metabolites in the removed reaction,
they would all need to be copied, which would greatly slow down the
operation.

Is this a necessary use case? If so I think there can be a flag or
something (preserve_reaction) which copies the metabolites.

-Ali

**Comment by phantomas1234** [comment]
You can close this one if you like

**Comment by aebrahim** [comment]
OK thanks
