### ISSUE TITLE
Integrate BiGG reactions with gapfilling

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#169]
We should be able to use the entire reaction matrix in bigg as the universal set of reactions for gapfilling. This would be a great way to leverage the intergrated ID system.

**Comment by vivekiitkgp** [comment]
@aebrahim I would like to know more about this and work if possible.

**Comment by aebrahim** [comment]
Sure!

Basically, the gap filling algorithms take in as an argument a "Universal" set of reactions.

This pull requests proposes using the entirety of the "BIGG" universal reactions to do this.

There are a few things to figure out (can be done incrementally)

1. Will bigg have an API endpoint for a universal reaction model? Alternately, which is the best API to use (@zakandrewking)
sary?
2. What is the best way to cache this universal reactions database?
3. Bigg needs to ensure a universal reactions model is completely mass and charge balanced - SBRG/bigg_models#190 
4. Will we need options to control compartmentalization of reactions, and change them if needed?

**Comment by mmundy42** [comment]
I'm working on a new package called cobrababel that has support for creating a universal model from the BiGG universal database. The create_bigg_universal_model() function downloads the BiGG database via the web API and creates a cobra.Model object with the reactions and metabolites. I think the current direction is for these type of functions to be in separate packages instead of the base cobrapy package.

**Comment by pstjohn** [comment]
Agreed, if anything that should probably get integrated with BIGG itself. I put a ticket there a while back (SBRG/bigg_models#204), but essentially I think the advice was to roll your own universal model.

I have some older jupyter scripts I used to stitch a universal model together, as well as a universal.json file I use pretty regularly: I'm happy to send either / both if that helps your effort.

**Comment by hredestig** [comment]
Dropping this as modelseed has it's new fancy mackinac package and gapfilling is broken in cobrapy
