### ISSUE TITLE
Expand unit tests

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#178]
Missing coverage for these functions. Unit tests should get written for functions still in use; other functions should get marked deprecated.
- [ ] reporter metabolites
- [x] overloaded operators on Reaction
- [ ] Metabolite.remove_from_model
- [ ] asses_medium_component_essentiality

**Comment by cdiener** [comment]
Could you indicate which parts are going to be deprecated? So we don't write tests for functions that are on their last breath :)

**Comment by aebrahim** [comment]
Whatever doesn't get tests will get deprecated.

**Comment by cdiener** [comment]
I started working on asses_medium_component_essentiality but have some questions regarding the code (what happens if EX reactions are not formulated in the import direction). What is the right forum to discuss that?

**Comment by aebrahim** [comment]
Right here in the issue tracker sounds good to me

**Comment by cdiener** [comment]
So right now the medium composition requires that exchange reactions for medium components are specified in the import reaction. Whether this is actually true is never checked in the code. I am not aware of a standard that enforces that, and have seen many models that rather specify those the other way around (to not have an empty left-hand side I suppose). So I think there at least be an error if the exchange reaction does not comply. For the long run it would be more user friendly if one only has to specify the metabolites and cobra automatically searches for the corresponding exchange reactions. However, that could be difficult if you have active transporters (atp -> glucose + adp)...

**Comment by hredestig** [comment]
gone stale
