### ISSUE TITLE
Hit UserWarning: cobra.io.sbml requires libsbml on import cobra package

### ISSUE THREAD

**Issue by csyangning** [opencobra/cobrapy#180]
Hey,

I am following the instructions here: 
https://github.com/opencobra/cobrapy/blob/master/INSTALL.md

for Mac OS (10.10.2 ):
- sudo pip install cobra
- sudo pip install python-libsbml-experimental

But I am getting the following errors on import cobra package:
cobra/io/__init__.py:17 UserWarning: cobra.io.sbml requires libsbml

I tried import libsbml, it returns following error:
>import libsbml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/libsbml/__init__.py", line 28, in <module>
    _libsbml = swig_import_helper()
  File "//anaconda/lib/python2.7/site-packages/libsbml/__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libsbml', fp, pathname, description)
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/libsbml/_libsbml.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: //anaconda/lib/python2.7/site-packages/libsbml/_libsbml.so
  Reason: Incompatible library version: _libsbml.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

Anyone can help me here? THX

**Comment by aebrahim** [comment]
This appears to be an issue with libsbml, not cobrapy, so I'm closing the issue.

It looks like libsbml failed to install properly because it's linking against the wrong version of libxml2.

**Comment by aebrahim** [comment]
Also the latest versions of cobrapy can read SBML level 3 with fbc2 without libsbml at all.... although I guess this only helps you if the models you are loading are already available in this format.

**Comment by aebrahim** [comment]
I've made a pre-compiled binary wheel of python-libsbml for MacOSX. Maybe the libsbml maintainers will also be willing to upload binary wheels to pypi.

For now, you can get this wheel by doing the following:

```pip install -f https://pypi.drosophi.la --no-index python-libsbml```

**Comment by csyangning** [comment]
thanks for the response. I get this error msg instead:
could not find a version that satisfies the requirement python-libsbml

**Comment by aebrahim** [comment]
Please attach output of th e following

```python --version```
```pip --version```
