### ISSUE TITLE
The notes section of reactions is not imported from legacy SBML - Fixed

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/cobrapy#192]
Hey @aebrahim,

I am working with Cameo, but what I say should also be true for Cobrapy, because Cameo uses the same functions.
I noticed that when reading in an SBML level 2 version 4 file with the following function `create_cobra_model_from_sbml_file()`, the resulting Cameo model did not include any of the annotations from the notes section of the SBML file. So the first fix here was simply to include the following line of code:
`        reaction.notes = reaction_note_dict` (line 294)

Once I had that in place, I realized that the legacy_sbml export (`write_cobra_model_to_sbml_file`) only includes two items from the notes section: Gene Association and Subsystem. So on the basis of the updated import I fixed that up with this block of code:

```    
        note_str = str(the_reaction.notes.viewitems())
        note_start_tag, note_end_tag, note_delimiter = '<p>', '</p>', ':'
        note_str = note_str.replace('dict_items([','<html xmlns="http://www.w3.org/1999/xhtml">')
        note_str = note_str.replace('(\'',note_start_tag)
        note_str = note_str.replace('),',note_end_tag)
        note_str = note_str.replace('\',',note_delimiter)
        note_str = note_str.replace('\']','')
        note_str = note_str.replace('[\'','')
        note_str = note_str.replace(')])',note_end_tag+'</html>')
        sbml_reaction.setNotes(note_str)
``` 
(starting line 479)

I hope this helps!

It sure did help me, because it made mapping the MNX IDs in my model to BiGG IDs much easier, as some of them could now simply be taken straight from the notes section.

Best,
Christian

**Comment by aebrahim** [comment]
Thanks. If it's not too much trouble, would you mind making a pull request?

**Comment by ChristianLieven** [comment]
Will do! I am testing it  currently so I don't break anything when I issue the pull request.

**Comment by aebrahim** [comment]
Please test #205 to see if it works for you.

**Comment by aebrahim** [comment]
#205 has been merged, so I'm marking this closed.
