### ISSUE TITLE
Support conda on Windows

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#195]
It seems like a lot of users, especially on windows, use enthought's python disribution and/or conda instead of the version from python.org and pip. There should also be a package hosted on conda to make this easier to support.

**Comment by phantomas1234** [comment]
Let me know how that goes, I'd love to do the same for cameo

**Comment by aebrahim** [comment]
I have it working, at least on my machine (still need to figure out distribution). I also got glpk added to the conda-recipies conda/conda-recipes#481

**Comment by vivekiitkgp** [comment]
Hi, I am writing a conda recipe for cobrapy right now.  I was wondering if optional dependencies should also be installed like a full installation or just the basic one?

**Comment by aebrahim** [comment]
I think with optional dependencies would be better.

Thanks so much for tackling this.

**Comment by vivekiitkgp** [comment]
@aebrahim Currently, facing a bit glitch in adding `libsbml` dependency. Apparently, the `python-libsbml` package hard codes the library include paths making it a bit non trivial to work write conda recipe. Working on resolving it though.

**Comment by aebrahim** [comment]
I think that can be left out if it's too difficult to get working

**Comment by vivekiitkgp** [comment]
@aebrahim I have resolved the dependencies. Just on the final step of adding cobra to conda. Would you mind making a release with the recent bug fix?

**Comment by cdiener** [comment]
Thanks for all the work. This will be awesome for testing and teaching. There is a small typo in the conda recipe in the requirements: gplk instead of glpk. I guess that's why the ci is failing. Cheers

**Comment by aebrahim** [comment]
Sure, I will create a new release soon.

I'd never heard of bioconda, and it seems awesome! Do you happen to know if
bioconda has any plans to also build windows packages using appveyor?

**Comment by vivekiitkgp** [comment]
> In principle, I have no objections against windows packages. Our team initially decided that we won't dedicate resources for that, but if somebody volunteers to port our build system to e.g. AppVeyor, I would be fine with that. In principle, adding an appveyor.yml to the repository with a similar setup as the travis.yml should be enough. We would welcome any initiative in this direction.

By the main contributor of Bioconda.

**Comment by vivekiitkgp** [comment]
https://github.com/bioconda/bioconda-recipes/pull/761
@aebrahim Fixed.

**Comment by aebrahim** [comment]
Thank you so much. I am going to update the bug title to only refer to conda on windows now.

**Comment by vivekiitkgp** [comment]
@aebrahim The added recipe will also build for Windows (an included `build.bat` file). Just that it is not tested.

**Comment by aebrahim** [comment]
Only linux is listed here: https://anaconda.org/bioconda/cobra

I just created a pull request to add mac as well bioconda/bioconda-recipes#798

**Comment by vivekiitkgp** [comment]
That is because the bioconda channel itself doesn't support Windows builds yet. We could submit this to main conda channel if you wish.

**Comment by aebrahim** [comment]
How do you submit a package to the main conda channel? As far as I know the
https://github.com/conda/conda-recipes repository is not used to create the
main conda channel.

You said bioconda would be willing to build packages with appveyor. Would
that be a solution?

**Comment by vivekiitkgp** [comment]
Yes. You can probably submit a PR with appveyor setup that allows for automated building of recipes.

**Comment by cdiener** [comment]
I think this can be closed. As discussed Windows will be supported via pip. The appveyor configs have been updated as well and produce working wheels.
