### ISSUE TITLE
FAIL: test_loopless (cobra.test.flux_analysis.TestCobraFluxAnalysis)

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#200]
I just tried to run the tests with 
```
from cobra.test import test_all
test_all()
```
One of the tests fails due to a wrong string comparison.
```
======================================================================
FAIL: test_loopless (cobra.test.flux_analysis.TestCobraFluxAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cobra/test/flux_analysis.py", line 314, in test_loopless
    self.assertEqual(infeasible_sol.status, "infeasible")
AssertionError: 'integer infeasible' != 'infeasible'
----------------------------------------------------------------------
```
It looks like the assertiong checks for the wrong string, i.e. the string changed in newer version of libglpk-dev or CPLEX.

I am using 
* Ubuntu 14.04 LTS x86_64
* libglpk-dev Version: 4.52.1-2build1
* IBM(R) ILOG(R) CPLEX(R) Interactive Optimizer 12.6.1.0

**Comment by matthiaskoenig** [comment]
And I just build from the latest source (commit 48bd7cf4003b67).

**Comment by matthiaskoenig** [comment]
Closed. Thanks.

**Comment by aebrahim** [comment]
Thanks for reporting the bug
