### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#206]
Not high profile but teaching some CobraPy I noticed that a lot of the documentation is outdated. For instance it still uses `single_deletion` which is deprecated, does not mention parsimonous FBA etc.

Might be good to schedule some updates there...

**Comment by aebrahim** [comment]
Thanks for the bug report.

I think you're probably looking at the stable version of the documentation. The [latest](http://cobrapy.readthedocs.org/en/latest/) version for the 0.4 beta updates the ```single_deletion``` function.

I think you are right that pFBA docs should probably be included, maybe in the simulating with FBA section.

If you want to add any docs, I would accept pull requests. The documentation is all done as IPython notebooks in https://github.com/opencobra/cobrapy/tree/master/documentation_builder.

**Comment by cdiener** [comment]
Ok, that's true. We build our containers from the master branch but direct to the stable docs and that's not right. 

Okay, I will probably make a pull for the pFBA stuff in the future (might be a bit). Should we reference it from the loopless part as well? As I understand ist pFBA solutions should not have loops...

**Comment by aebrahim** [comment]
pFBA solutions are not guaranteed to be free of loops. They will just
minimize loops as much as possible. For example, if all reactions in a loop
have a lower bound of 1, then there would still be flux through the loop in
the pFBA solution, but loopless FBA would say that problem is infeasible.

**Comment by cdiener** [comment]
okay so we better don't reference it in the loopless part then. 

So would pFBA create loopless solutions if all lower bounds are 0?

**Comment by aebrahim** [comment]
No, it shouldn't

**Comment by aebrahim** [comment]
Oops, that was phrased ambiguously.

A pFBA solution on a model with all lower bounds set to 0 and upper bounds > 0 shouldn't have any loops.

**Comment by aebrahim** [comment]
Also, I added in a very quick pFBA demo, so I closed this issue. If you want to change any of the other docs, modify the notebooks (or add new ones), and send a PR.

**Comment by cdiener** [comment]
Okay that's what I thought. Thanks for the changes!
