### ISSUE TITLE
Creating a stoichiometry matrix

### ISSUE THREAD

**Issue by vivekiitkgp** [opencobra/cobrapy#210]
Hi,

I was trying to create a stoichiometry matrix from model files (or reaction objects) but couldn't find any relevant function in cobrapy. Does cobrapy implement this functionality?

**Comment by pstjohn** [comment]
It does, check out the cobra.core.ArrayBasedModel class.

Specifically, you could create an Array model from your existing cobra model

>>> array_model = cobra.ArrayBasedModel(cobra_model)

and then use the "S" property, which returns a sparse matrix. Use the
'toarray' method to get a numpy array.

>>> my_matrix = array_model.S.toarray()

**Comment by vivekiitkgp** [comment]
Thanks! I hadn't looked into the submodules documentation. Closing.

On a side note, I was wondering if already pending issues are up for grabs. I would like to fix/contribute to them. @pstjohn

**Comment by aebrahim** [comment]
Issues #177 #178 and #211 are good places to start.

If you want to try to tackle #195 you can start from the already existing glpk recipe (https://github.com/conda/conda-recipes/tree/master/glpk)
