### ISSUE TITLE
Rewrite docstrings to conform to google style guide

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#211]
Docstrings should be written as done here: http://google.github.io/styleguide/pyguide.html?showone=Comments#Comments

This will allow use of sphinx-napoleon to autogenerate documentation.

Currently the documentation uses a mix of numpydoc, rst, and no formatting.

**Comment by vivekiitkgp** [comment]
Perhaps it'd be nice to conform to Python style (PEP8 etc.,) in general as well?

**Comment by hredestig** [comment]
could we use numpy docstring style instead of google? The reason I'm asking is because cameo uses numpy style and it would facilitate maintenance if these packages used the same style.. any strong opinions? I volunteer to do conversion and clean-up action.

**Comment by mmundy42** [comment]
Just to be clear, you are proposing using the style described at https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard? I'm fine with that style and it is good to have a consistent style for docstrings.

**Comment by hredestig** [comment]
yes exactly, that's the one

**Comment by pstjohn** [comment]
is there a linter we can run to verify this for new PRs?

**Comment by hredestig** [comment]
That is a good point and pydocstyle supports numpy style in their master branch, I'll add this to #388

**Comment by Midnighter** [comment]
I think it'd be good to upgrade the cobrapy infrastructure a little anyway. Like make a flake8 and pydocstyle check in tox and upgrade travis accordingly. I also would vote for using bumpversion rather than versioneer.py.

**Comment by hredestig** [comment]
I take that back, linting functionality will have to go in a different PR to not block progress towards 0.6
