### ISSUE TITLE
Changing metabolite ID doesn't update get_by_id

### ISSUE THREAD

**Issue by wbryant** [opencobra/cobrapy#212]
If a metabolite ID is directly changed, model.metabolites.get_by_id still uses the old ID and throws a key error on the new ID.

However, writing the model to SBML and reimporting retains the metabolite attributes, while using the new ID.

**Comment by mendessoares** [comment]
Came across the same thing with reaction ids. If you use model.repair it will update without the need to export the model.



H


-------- Original message --------

**Comment by wbryant** [comment]
Thanks H.

**Comment by aebrahim** [comment]
If you are using the latest beta, there is also the [cobra.manipulation.modify.escape_ID](https://cobrapy.readthedocs.org/en/latest/cobra.manipulation.html#cobra.manipulation.modify.escape_ID) function which should fix all the ID's for you.
