### ISSUE TITLE
Under consideration: should Reaction.metabolites have string keys?

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#219]
This would mean that you could do

that would mean that you would be able to do

```
>>> model.reactions.PGI.metabolties["f6p_c"]
1
```

This would break compatibility but be a much more convenient API. Any thoughts?

**Comment by pstjohn** [comment]
I'd vote against, it might allow you to get stoichiometry easier but makes iterating over the metabolites more difficult:

```
[met.formula for met in model.reactions.PGI.metabolites.iterkeys()]
```

In general, none of the containers use string ids, this would break consistency. (i.e., `Metabolite.reactions` returns a set of cobra reaction objects)

You could subclass `dict` and allow it to handle either cobra objects or string ids, that might be the best of both worlds. A simpler solution might be to just allow `Reaction.add_metabolites()` to accept dictionaries with string keys. That would allow you to avoid the currently awkward: 

```
nad_reduction = cobra.Reaction('NAD_REDUCTION')
nad_reduction.add_metabolites({
        model.metabolites.nad_c : -1,
        model.metabolites.h_c   : -1,
        model.metabolites.nadh_c : 1,
    })
```

with a more reasonable:
```
nad_reduction = cobra.Reaction('NAD_REDUCTION')
nad_reduction.add_metabolites({
       'nad_c' : -1,
       'h_c'   : -1,
       'nadh_c' : 1,
    })
```

**Comment by aebrahim** [comment]
So the Reaction.add_metabolites string key feature was just added! See 3c1d68c.

But still, to access the stoichiometry, the API is a bit awkward.

Perhaps instead of changing the behavior a new attribute should be used? Like Reaction.metabolite_ids or something?

**Comment by pstjohn** [comment]
Either way, just sharing my thoughts. A second attribute is probably awkward to keep synced.

what about something like
```python

class id_dict(dict):
    def __getitem__(self, key):
        try:
            return dict.__getitem__(self, key)
        except KeyError:
            for ikey in iterkeys(self):
                if ikey.id == key:
                    return dict.__getitem__(self, ikey)
            else:
                raise KeyError(key)
                
    def __setitem__(self, key, val):
        
        if hasattr(key, 'id'):
            dict.__setitem__(self, key, val)
        else:      
            # Need to get the model now
            model = next(iterkeys(self)).model
            dict.__setitem__(self, model.metabolites.get_by_id(key), val)
```

you could even generalize it to reactions, genes, etc by overriding `__init__` to take a model attribute

**Comment by aebrahim** [comment]
Ah I was unclear it would be a property, no reason to keep it synced.

And yes, it could eventually morph into something like what you described
using abstract base classes for dictionaries.

**Comment by pstjohn** [comment]
It might take some work to make it a property: how would you handle 
```python
model.reactions.PGI.metabolite_ids["f6p_c"] = 2
```

**Comment by hredestig** [comment]
stale, lacking interest
