### ISSUE TITLE
Analyzing model solutions with summary methods

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#223]
As a general question for cobrapy users/developers, how do you actually analyze a model once its been solved? In general, the current API for answering questions like "what reactions are producing or consuming a given metabolite?" seems fairly sparse.

Specifically, being able to do things like this:
```python
In [4]: model.summary()
IN FLUXES                     OUT FLUXES                    OBJECTIVES          
o2_e       -21.80             h2o_e    29.18                Biomass_Ecoli_core    0.874
glc__D_e   -10.00             co2_e    22.81                                    
nh4_e       -4.77             h_e      17.53                                    
pi_e        -3.21         
```

Or, with FVA:
```python
In [5]: model.summary(fva=0.95)
IN FLUXES                     OUT FLUXES                    OBJECTIVES          
o2_e        -21.80 ± 1.91     h2o_e       27.86 ± 2.86      Biomass_Ecoli_core    0.874
glc__D_e     -9.76 ± 0.24     co2_e       21.81 ± 2.86                          
nh4_e        -4.84 ± 0.32     h_e         19.51 ± 2.86                          
pi_e         -3.13 ± 0.08     for_e        2.86 ± 2.86                          
                              ac_e         0.95 ± 0.95                          
                              acald_e      0.64 ± 0.64                          
                              pyr_e        0.64 ± 0.64                          
                              etoh_e       0.55 ± 0.55                          
                              lac__D_e     0.54 ± 0.54                          
                              succ_e       0.42 ± 0.42                          
                              akg_e        0.36 ± 0.36                          
                              glu__L_e     0.32 ± 0.32         
```

Or for a given metabolite:
```
In [6]: model.metabolites.q8_c.summary()
PRODUCING REACTIONS -- Ubiquinone-8
-----------------------------------
  %      FLUX   RXN ID                        REACTION                       
100.0%     44    CYTBD 2.0 h_c + 0.5 o2_c + q8h2_c --> h2o_c + 2.0 h_e + q8_c

CONSUMING REACTIONS -- Ubiquinone-8
-----------------------------------
  %      FLUX   RXN ID                        REACTION                       
 88.4%    -39   NADH16   4.0 h_c + nadh_c + q8_c --> 3.0 h_e + nad_c + q8h2_c
 11.6%   -5.1    SUCDi                       q8_c + succ_c --> fum_c + q8h2_c
```

These are actually taken from some summary methods in my fork, but I wanted to ask whether or not this would be a useful feature for the main repo before spending the time to make the pull request.

Also, a non-negligible concern is that I use the pandas library for a lot of the underlying legwork. Where is cobrapy trying to fall on the features vs. dependencies front?

**Comment by aebrahim** [comment]
I personally think this looks awesome. I'd be very :+1: assuming the appropriate unit tests :)

We also have to be very careful with avoiding circular dependencies by doing this. Also will every summary call trigger fva, or should the result stored as a part of the model? Should we instead have a ```summary(object, fva_result)``` function?

Previously, cobrapy has had the philosophy of "additional dependencies only to enable extra non-core features" side of things. pandas is already used optionally right now for some things, and I think this is very much along the same lines (calling summary without pandas installed can simply raise an error).

**Comment by pstjohn** [comment]
Agreed on circular dependencies, I just imported on runtime in my implementation.
There are probably [better](http://stackoverflow.com/questions/22187279/python-circular-importing) ways to do it though.

Sounds great, I'll start putting together a pull request.

**Comment by aebrahim** [comment]
Added in #226
