### ISSUE TITLE
Uppercase in GPRs causes warnings and errors

### ISSUE THREAD

**Issue by oveoyas** [opencobra/cobrapy#225]
Models that encode GPRs with uppercase AND/OR cause "malformed gene reaction rule" warnings when reading from SBML and errors when using cobra.manipulation.delete.delete_model_genes(). In my experience, simply replacing uppercase AND/OR with lowercase and/or usually resolves the problem. It would be nice if the GPR parsing took this into account by default.

**Comment by aebrahim** [comment]
Thank you for reporting this.
