### ISSUE TITLE
optimize_minimal_flux should allow passing a measured objective value

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#233]
One of the nice features of pFBA is that it is capable of assigning the most economic fluxes to a predefined objective value. For now this objective value is always the computed maximal solution value of the model. However, in some applications we may have measured growth rates (easy to obtain for bacteria and there some for human cell lines as well). It would be great if one could pass such a value to optimize_minimal_flux, skipping the first optimization.

**Comment by aebrahim** [comment]
That sounds like a useful feature.

I would accept a pull request implementing this.

**Comment by aebrahim** [comment]
Pinging @pstjohn who wanted a similar feature (only a fraction of maximum instead of the value directly)

**Comment by cdiener** [comment]
Cool. The let's see what @pstjohn says. Either way I will start playing around with it since I need it now.

**Comment by aebrahim** [comment]
Good plan!

**Comment by pstjohn** [comment]
I'm happy to take a stab at this along with #228, keep an eye on PR #227.

**Comment by cdiener** [comment]
Ok great. Thanks!

**Comment by aebrahim** [comment]
Fixed in #277

**Comment by cdiener** [comment]
Thanks!
