### ISSUE TITLE
Python Crash while testing if cobra installation worked

### ISSUE THREAD

**Issue by vaastav** [opencobra/cobrapy#234]
So I downloaded cobra and tried to check if the installation had worked by trying the following on a python shell:
```

> from cobra.test import test_all
> test_all()
```
The shell crashes while executing the test test_read ( cobra.test.io_tests.TestCobraIOmat )
I am working with Python 2.7 currently.
I haven't tried debugging it yet but I feel it might be a segmentation fault or something

**Comment by aebrahim** [comment]
What operating system and python version

**Comment by vaastav** [comment]
Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
Windows 10 OS

**Comment by aebrahim** [comment]
Try not anaconda. Not yet supported

**Comment by vaastav** [comment]
Oh Ok! Thats sad. 
Are there any plans of supporting anaconda? Because installing numpy and scipy without anaconda is a big hassle and I know those 2 libraries are dependencies for cobra

**Comment by aebrahim** [comment]
My personal opinion is that anaconda is a lot more trouble than its worth. It's a huge pain to get stuff working, especially on Windows. You can get numpy and scipy with regular python from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/

There is an open bug for this (#195) already, but it's unclear how exactly to fix it.

If you don't mind, I'm going to close this as a duplicate. If you still encounter crashes with regular python, please file a new bug.

**Comment by vaastav** [comment]
I know this is closed but I managed to get a workaround for this for anyone who comes across this.
I created an environment in conda with Python=3.4 and then installed libsbml and cobra and then ran the tests. The specific test that was causing the crash gave me this output: 

```
test_read (cobra.test.io_tests.TestCobraIOmat) ... cobra\io\mat.py:145 FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
ok
```

The commands I used to get everything working were as follows:

```
> conda create -n py34 python=3.4 anaconda # Creates a new conda environment named py34with python3.4 
> activate py34 # Activates the py34 environment
> pip install python-libsbml # Installs libsbml which is a good lib to have but no necessarily a ependency
> pip install cobra # Installs cobra

**Comment by aebrahim** [comment]
Glad you were able to get it working! Thank you for putting your advice
here for other users.

**Comment by apanda4** [comment]
Thanks so much! This worked for me.
