### ISSUE TITLE
Summary methods docstrings still not on readthedocs

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#236]
The summary methods added in a recent pull request still don't appear on the readthedocs site, I'm guessing I forgot to regenerate the simulating.rst file. Should I put in a PR?

**Comment by aebrahim** [comment]
It's not necessary.

I'm working on removing the ipynb to rst step with nbsphinx
https://github.com/spatialaudio/nbsphinx

**Comment by aebrahim** [comment]
Fixed in afb5192
