### ISSUE TITLE
Conda recipe will lead to an installation with no solvers

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#237]
Hi,

I'll report that here and not in bioconda for now. When installing cobrapy with the new (bio)conda recipe you will get the infamous no solvers error:

```python
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cobra
cobra/solvers/__init__.py:62 UserWarning: No LP solvers found
```

Steps to reproduce:
1. Install Anaconda or conda locally
2. Add bioconda channel `conda config --add channel bioconda`
3. install cobra with `conda install cobra`
4. import cobrapy `import cobra`

glpsol is installed into the bin directory of Anaconda but it seems that cobrapy does not find it.

**Comment by aebrahim** [comment]
pinging @vivekiitkgp

**Comment by aebrahim** [comment]
When doing a conda install, the package should not be getting compiled on your system. It should be just downloading a pre-compiled package.

Could you please paste the output of ```import cobra.solvers.cglpk```

**Comment by cdiener** [comment]
Exactly. It seems that in that process (the bioconda build) cglpk never gets built:

```python
In [2]: import cobra.solvers.cglpk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-465ef8852430> in <module>()
----> 1 import cobra.solvers.cglpk

ImportError: No module named 'cobra.solvers.cglpk'
```

**Comment by cdiener** [comment]
Already found the fix. The problem was that cython was not in the build requirements. Adding it leads to a successful build:

```bash
building 'cobra.solvers.cglpk' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/cobra
creating build/temp.linux-x86_64-3.5/cobra/solvers
gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cdiener/software/anaconda3/envs/_build/include -I/home/cdiener/software/anaconda3/envs/_build/include/python3.5m -c cobra/solvers/cglpk.c -o build/temp.linux-x86_64-3.5/cobra/solvers/cglpk.o
gcc -pthread -shared -L/home/cdiener/software/anaconda3/envs/_build/lib -Wl,-rpath=/home/cdiener/software/anaconda3/envs/_build/lib,--no-as-needed build/temp.linux-x86_64-3.5/cobra/solvers/cglpk.o -L/home/cdiener/software/anaconda3/envs/_build/lib -L/home/cdiener/software/anaconda3/envs/_build/lib -lglpk -lpython3
.5m -o build/lib.linux-x86_64-3.5/cobra/solvers/cglpk.cpython-35m-x86_64-linux-gnu.so
```

**Comment by vivekiitkgp** [comment]
@aebrahim I think it just depends the way recipe is written. In most cases, what the recipe does is to download pre-compiled binaries for the appropriate platform and install it on the user system. This works out of the box. In other cases, however, the recipe contains instructions to build the package from source and that's where getting the `build` and `runtime` dependencies right comes into the picture.

@cdiener Thanks for reporting. I will make the edit.

**Comment by vivekiitkgp** [comment]
@cdiener On a second note, it might be best for you to take it up! Let me know if there are any issues.

**Comment by cdiener** [comment]
@vivekiitkgp Ok, made a pull request https://github.com/bioconda/bioconda-recipes/pull/996. It would be cool if cobra could have its own test script (`run_tests.py` or something) so we could integrate it into the conda build so a (semi-) full suite of tests is run instead of just checking whether the imports work...

**Comment by cdiener** [comment]
Fix has been merged into bioconda.

**Comment by vivekiitkgp** [comment]
@cdiener You can add a command like following into the `meta.yaml` file to automatically run the tests.

`python -c 'import cobra.test; cobra.test.test_all()'`

**Comment by cdiener** [comment]
@vivekiitkgp ok sounds good. I think this is something we can leave until we bump the version in bioconda again.
