### ISSUE TITLE
Silent error when loading SBML Level 3 files with no stoichiometry

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#250]
Loading a SBML Level 3 model (not FBC) that has missing stoichiometry values (as in the example below) does not raise an error, but metabolite stoichiometries are `nan`.

```
      <reaction id="R_EX_for_e" name="for exchange" reversible="false">
        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <p>GENE_ASSOCIATION: </p>
            <p>SUBSYSTEM: Exchange</p>
            <p>EC Number: </p>
            <p>Confidence Level: </p>
            <p>AUTHORS: </p>
            <p/>
          </body>
        </notes>
        <listOfReactants>
          <speciesReference species="M_for_e" constant="false"/>
        </listOfReactants>
        <kineticLaw/>
      </reaction>
```

Just an error or warning would be enough to fix this.

**Comment by aebrahim** [comment]
Could you please attach the file?

**Comment by zakandrewking** [comment]
It's unpublished, so I'll share it privately. 
Zak






On Wed, Apr 6, 2016 at 12:01 PM -0700, "Ali Ebrahim" <notifications@github.com> wrote:












Could you please attach the file?

**Comment by aebrahim** [comment]
Thanks, that'll make it easier to test

**Comment by aebrahim** [comment]
Only fbc v2 models are really supported. The fact that they are SBML level 3 doesn't make a difference; they are being parsed just like SBML2 models would be, with the legacy libsbml-based nonvalidating parser.

Should I put in a warning for all non-fbc 2 models?

**Comment by zakandrewking** [comment]
Yeah, that wouldn't be a bad idea. Especially since COBRA toolbox is spitting these out.

**Comment by aebrahim** [comment]
That sounds like a bug on the cobra toolbox's end. Why on earth are they
making SBML level 3 without FBC v2?

I don't want annoying warnings to be raised with every legacy model though.
Maybe I'll try to detect SBML level 3 without FBC v2 and make that an error.

-Ali

**Comment by zakandrewking** [comment]
well, you could get the same silent error in SBML level 2, right? Maybe just a warning that things will fail silently?

I've had some trouble in the past with this. When I try to save JSON models with odd values somewhere in the model structure (nan, decimal, inf, etc), it's actually pretty difficult to track them down.

**Comment by aebrahim** [comment]
OK, I should probably patch this in the SBML 2 code
