### ISSUE TITLE
Support writing SBML Level 3 (with FBC)

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#251]
In think in the long haul it would be nice if COBRApy could write SBML L3 models with FBC. This would also help to promote the format a bit (if I understand correctly it's the preferred SBML format for FBA models) and allow for the conversion of SBML L2 to L3. A lot of the stuff is very similar to the writer for L2. The major challenges I see are:

- [ ] writing the gene-reaction rules 
- [ ] getting the annotations right
- [ ] defining the global parameters for the bounds

Maybe it's not really a top priority but something to keep on the radar.

**Comment by aebrahim** [comment]
Check out ```cobra/io/sbml3.py``` This already is the default.

**Comment by cdiener** [comment]
Just saw it, sorry. I should also try to be less verbose :)

**Comment by aebrahim** [comment]
No worries. Input appreciated.

**Comment by aebrahim** [comment]
And actually, AFAIk cobrapy was actually the first software tool to support
fbcv2 (before even libsbml and JSBML)

**Comment by cdiener** [comment]
Yes, you converted me when we first discussed on the mailing list. One of the things where Matlab is starting to stay behind...
