### ISSUE TITLE
Awkward formatting in docs

### ISSUE THREAD

**Issue by shlicshlac** [opencobra/cobrapy#258]
On page 49 of cobrapy.pdf, starting with the bullet point for objective_sense, it looks like the text formatting is a bit garbled; for example some descriptions are bolded when it should only be the parameter names that are bolded, and some fragments of descriptions are their own bullet points.

**Comment by cdiener** [comment]
You are referring to the doc of the `dual_problem` function, correct? Can confirm that this has a broken docstring which is garbled by sphinx. Also affects the online docs at https://cobrapy.readthedocs.io/en/stable/cobra.design.html#module-cobra.design.design_algorithms.
