### ISSUE TITLE
mistake in docs/comments for model.summary()

### ISSUE THREAD

**Issue by shlicshlac** [opencobra/cobrapy#266]
In the docs/comments for cobra.core.model.py, the argument for specifying decimal precision is listed as "round", but in cobra.flux_analysis.summary.py, method model_summary() instead takes "digits" as the parameter to do this. 

For example, using model.summary(round=4) will still give 2 digits after the decimal, whereas using model.summary(digits=4) will give 4.

Line 370 in cobra.core.model.py should be changed from `round: int` to `digits: int` so that the docs generated will be correct.

**Comment by pstjohn** [comment]
Can we close this now?
