### ISSUE TITLE
list index error in model summary

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#267]
Using for example the model at https://github.com/cdiener/corda/blob/master/corda/data/cemet.xml calling

```python
model.optimize()
model.summary()
```

gives 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/core/Model.py", line 376, in summary
    return model_summary(self, **kwargs)
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/flux_analysis/summary.py", line 132, in model_summary
    out_fluxes = pd.Series({r.reactants[0]: r.x for r in out_rxns})
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/flux_analysis/summary.py", line 132, in <dictcomp>
    out_fluxes = pd.Series({r.reactants[0]: r.x for r in out_rxns})
IndexError: list index out of range
```

The error occurs since it is assumed that all reactions always have reactants. However, that does not have to be the case, particularly if not using boundary metabolites. I could set up a fix but do not understand the logic of using only the first reactant for the summary, could you give me a hint what this is supposed to do @pstjohn? 

Cheers

**Comment by pstjohn** [comment]
The motivation was that for almost all bigg models, boundary reactions are specified as
`reactant <-- `, rather than `--> product`. This is definitely an oversight though.
I'll send in a PR soon

**Comment by mmundy42** [comment]
Just to confirm, the preferred format for boundary reactions is `reactant <--` ?
