### ISSUE TITLE
Reaction.check_mass_balance() gets AttributeError when Metabolite.elements returns None

### ISSUE THREAD

**Issue by mmundy42** [opencobra/cobrapy#273]
I'm running check_mass_balance() for all of the reactions in a model that I imported. Some of the metabolites have errors which causes Metabolite.elements to return None instead of an empty dictionary (lines 57 and 75 in cobra.core.Metabolite.py). The None return value then causes this AttributeError:

```
File "/Users/m097749/Source/cobrapy/cobra/core/Reaction.py", line 570, in check_mass_balance
for element, amount in iteritems(metabolite.elements):
File "/Library/Python/2.7/site-packages/six.py", line 599, in iteritems
return d.iteritems(**kw)
AttributeError: 'NoneType' object has no attribute 'iteritems'
```

Should Metabolite.elements return an empty dictionary for error conditions or should Reaction.check_mass_balance() check for the None return value?

**Comment by pstjohn** [comment]
Thanks for reporting this. we should check for `None` values in `Reaction.check_mass_balance()` and raise an exception (ValueError?)

I'll submit a PR soon
