### ISSUE TITLE
add functionality for flux sampling

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#295]
Ongoing progress can be seen in https://github.com/cdiener/cobrapy mostly in `flux_analysis/sampling.py`. 

For now the provided algorithms will be Artificial Centering Hit-and-Run and [optGPSampler](http://dx.doi.org/10.1371/journal.pone.0086587).

As soon as I have some benchmarks they will appear here. 

Any features you consider important? Let me know.

**Comment by cdiener** [comment]
Docs and tests (98%) are now pushed.

**Comment by HAHerrmann** [comment]
Hi, I was hoping to use the cobra.flux_analysis.sampling functionality you described above but can't seem to find it anywhere. Could you please let me know where I can find the flux_analysis/sampling.py file?

**Comment by cdiener** [comment]
Hi @HAHerrmann, flux sampling is currently still in development, that is why is has not been merged into cobrapy yet. The branch that contains is can be found [here](https://github.com/cdiener/cobrapy/tree/sampling). To set up a local test environment where you can use it, use the follwoing steps:

1. `git clone` the branch to a local directory
```bash
git clone -b sampling https://github.com/cdiener/cobrapy
cd cobrapy
```

2. Install locally with `pip` (I dont your setup, should be `pip` or `pip3` for you). This will require `cython` in order to generate the glpk bindings. If you have cplex, gurobi or mosek this step can be skipped entirely.

```bash
pip install --editable .
```

3. Staying in the same directory you can now use flux sampling (if you leave the directory your "normal" cobrapy install will be used).

```python
from cobra.flux_analysis import sample
```

For usage instructions [see the docs in the sampling branch](https://github.com/cdiener/cobrapy/blob/sampling/documentation_builder/sampling.ipynb).

**Comment by HAHerrmann** [comment]
@cdiener , that worked fine. Thanks for your quick and thorough reply!

**Comment by cdiener** [comment]
Glad it worked. If you find any bugs please post them here :)

**Comment by phantomas1234** [comment]
Would this be ready now for the devel-2 branch in cobrapy?

**Comment by cdiener** [comment]
Yeah definitely will open a pull request. This will also help me to see what is needed to make it work on Windows.

**Comment by cdiener** [comment]
Flux sampling has now been merged into `devel-2`. Any new bugs, feature requests and comments are better addressed in individual issues. Thanks!

**Comment by HAHerrmann** [comment]
I have been using the ACHR sampler using cobra both in Matlab and Python. In Python when plotting the flux distributions it is obvious that the sampler gets stuck in a certain value which appears much more frequently than the others. This is not the case in Matlab. Do we know why this is? 

Also, I really like the CHRR algorithm in Matlab and was hoping to use it using cobrapy. Will this algorithm ever be available in cobrapy also? 

Thank you!
