### ISSUE TITLE
Make the parser for SBML V2 read annotations

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#300]
Currently the parser for SBML V2 ignores the `<annotation>` tag. Since it is an (optional) part of the standard it might be worthwhile to implement it.

Also see the mailing list discussion at https://groups.google.com/forum/#!topic/cobra-pie/w0BUb1ZzMoU.

**Comment by matthiaskoenig** [comment]
This works now in develop with new libsbml parser. If problems persists reopen this issue with an example.
