### ISSUE TITLE
Deprecate ArrayBasedModel

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#330]
This was brought up on the gitter and I just wanted to make sure it gets its own issue.

I'm in favor of dropping this class in favor of a `model.S` property to generate a stoichiometric matrix. The proposed changes of 0.6 would probably break a lot of the ArrayBasedModel's functionality, and I'm not sure the speed improvements offered are worth the development effort.

Definitely chime in if you think its worth keeping? The plan I'm guessing would be to raise some deprecation warnings in a future version (0.6?) and remove it some time later. 

Would finally close #160

**Comment by hredestig** [comment]
Fixed with #343
