### ISSUE TITLE
Report a potential bug in 'prune_unused_metabolites()'

### ISSUE THREAD

**Issue by ehukim** [opencobra/cobrapy#332]
Running 'prune_unused_metabolites()' caused an error in my system, which I think to be a bug.

Here are some details to reproduce the bug:

- OS: Ubuntu 14.04.5 LTS
- cobra 0.5.8 was installed via `pip install "cobra[all]"` in virtual environment (`virtualenv`)
- Simply `prune_unused_metabolites(cobra_model)` was implemented with a standard cobra sbml file.

My quick solution was to remove the argument `cobra_model` for `the_metabolite.remove_from_model(cobra_model)` (line 21) in `delete.py` file.

Thanks.

**Comment by hredestig** [comment]
cheers for reporting, should be fixed now

**Comment by ehukim** [comment]
Thanks!
