### ISSUE TITLE
Report a potential bug in `write_cobra_model_to_sbml_file()`

### ISSUE THREAD

**Issue by ehukim** [opencobra/cobrapy#333]
Here's another potential bug I found from cobra 0.5.8.

Symptom: A note `<GENE_ASSOCIATION>` and ORFs are redundantly inserted into sbml output file.
For example,
```
     <reaction id="R_R00618" name="Thiamin-triphosphate phosphohydrolase" reversible="true" fast="false">
        <notes>
          <html xmlns="http://www.w3.org/1999/xhtml">
            <p>SUBSYSTEM: rn00730 Thiamine metabolism</p>
            <p>GENE_ASSOCIATION: ( B446_RS13775 )</p>
            <p>GENE ASSOCIATION: ( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 ): &apos;( B446_RS13775 )</p>
          </html>
        </notes>
```

Details:
- OS: Ubuntu 14.04.5 LTS
- cobra 0.5.8 was installed via `pip install "cobra[all]"` in virtual environment (`virtualenv`)
- This error seems to happen only when inserting new reactions to a model loaded from existing sbml file. Such error was not found in the process of building a new model (e.g., building_model.ipynb)

My quick solution:
1. Remove `note_dict = the_reaction.notes.copy()` (line 509) in `sbml.py`
2. Instead declare `note_dict = {}` at the same position.

Thanks.

**Comment by hredestig** [comment]
Thanks for reporting! I can't easily reproduce this so to facilitate fixing, could you please share the sbml file and the code you use that leads to this result?

**Comment by ehukim** [comment]
Hi, attached please find the sbml file and the code here:
[cobrapy_sbml_bug.zip](https://github.com/opencobra/cobrapy/files/701927/cobrapy_sbml_bug.zip)

I did a bit of test myself:
- As you can see in the code, you can test 3 different models (`iMK1208.xml` and two test models from `cobra.test`).
- Only the `iMK1208.xml` generated the bug (repeated insertion of `<GENE_ASSOCIATION>`s for the existing reactions), while the other two test models worked fine. This would mean that the bug might also be caused by the model itself.
- I expect that I would see a greater number of repeated `<GENE_ASSOCIATION>`s for a reaction if I attempt to insert a greater number of new reactions (e.g., like the above example one).
- I didn't see this sort of bug with any models in cobrapy 0.2.1.

Please let me know if you need additional info to reproduce the bug.
Thanks!
