### ISSUE TITLE
"CHARGE" note not read in sbml

### ISSUE THREAD

**Issue by mauriceccy** [opencobra/cobrapy#348]
The "CHARGE" in notes of metabolites is not read to give the charge attribute of metabolites. 

You may consider adding "tmp_metabolite.charge = note_charge" somewhere around lines 142-160 in cobra/io/sbml.py

**Comment by cdiener** [comment]
Thanks for the bug report :) 

After reviewing I agree that it's missing a statement setting the charge. I'm on it.

**Comment by cdiener** [comment]
Ok. Has been fixed with #352. Might take a little until the changes propagate to stable branch.

Feel free to reopen if you consider the fix insufficient.
