### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#358]
I had some trouble installing with Python 3.6, because it looks like there is not a wheel yet for 3.6 (I am on macOS)

Thanks for all your hard work maintaining the many COBRApy binaries!

**Comment by hredestig** [comment]
Good point, will enable py36 in the build plans.

**Comment by hredestig** [comment]
cobra 0.5.11 with binaries for py36 on pypi now
