### ISSUE TITLE
Tests take forever with additional installed solvers and benchmarks

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#366]
Having installed other solver than glpk the new pytest tests take forever to run particularly in `test_flux_analysis.py`. Maybe we should choose smaller examples...

**Comment by pstjohn** [comment]
is this when you run it without `--benchmark-skip`?

**Comment by cdiener** [comment]
Yeah, it's mostly due to the benachmarks. But I dont think that those should take half an hour either...

**Comment by cdiener** [comment]
If #367 is pulled *as is* it would resolve that issue.
