### ISSUE TITLE
type errors in setting metabolites with numpy int's

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#376]
I'm not sure where on the cobrapy / optlang / swiglpk stack this should go, but here's an error:

```python
import cobra.test
import numpy as np

model = cobra.test.create_test_model('textbook')
model.reactions[0].add_metabolites({
    model.metabolites[0]: np.int64(1),
    })
```

```python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model.metabolites[0]: np.int64(1),
  File "/Users/pstjohn/Packages/cobra_upstream/cobra/core/Reaction.py", line 730, in add_metabolites
    self.reverse_variable: -coefficient
  File "/Users/pstjohn/anaconda3/envs/cobra_test/lib/python3.5/site-packages/optlang/glpk_interface.py", line 263, in set_linear_coefficients
    va[i + 1] = coeff
  File "/Users/pstjohn/anaconda3/envs/cobra_test/lib/python3.5/site-packages/swiglpk.py", line 156, in __setitem__
    return _swiglpk.doubleArray___setitem__(self, index, value)
```

This comes up in using a pandas series with integer values, for instance.

**Comment by cdiener** [comment]
That's because swiglpk maps basic Python floats and ints to its underlying C types. And glpk would not accept 64 bit ints anyways, so there must be a cast before. I would say that should be handled either in optlang or we should clarify that the coefficients must be default python types.

**Comment by KristianJensen** [comment]
Hi there.

This is an oversight in optlang. All optlang methods (should) accept all numeric types including numpy and sympy numbers, so feel free to report it if you find other cases where it doesn't work :)

**Comment by cdiener** [comment]
That was fixed in https://github.com/biosustain/optlang/commit/fdb5aba16ec059bf0f33ee84d4daa4c458204f51 and will probably trickle down to master soon.
