### ISSUE TITLE
Improve LazySolution behavior/interface

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#380]
* Let LazySolution record requested values and make those available even after being invalidated.
* Add `__getitem__` that works just like `get_primar_by_id`.

**Comment by Midnighter** [comment]
# `cobra.core.solution` Interfaces

## Proposal/Questions:

* Should `.f` also be deprecated just like `.x`, `.y`, `x_dict`, and `y_dict`?
* Give `SolutionBase` the `.data_frame` and `_repr_html` methods?
* Rename `.data_frame`? `numpy` and `scipy` use `asdataframe`-like syntax
  whereas `pandas` uses `.to_dataframe`. Either form seems more explicit. At
  least have a method like that and deprecate the old one.
* The solution interface could be further improved by implementing [vectorized getting of values](https://github.com/biosustain/optlang/issues/69).

## `SolutionBase`

```python
.f
.x
.x_dict
.y
.y_dict
.get_primal_by_id
.objective_value
.model
.__repr__
```

## `Solution`

Extends `SolutionBase` with the following attributes/methods:

```python
.fluxes
.reduced_costs
.shadow_prices
.status
.__dir__
```

## `LazySolution`

Extends `SolutionBase` with the following attributes/methods:

```python
.fluxes
.reduced_costs
.shadow_prices
.status
.data_frame
._repr_html
```

## `LegacySolution`

Does not directly inherit from `BaseSolution` but from `object`. Although,
BaseSolution `__new__` may construct a `LegacySolution` class.

```python
.solver
.f
.x
.x_dict
.y
.y_dict
.status
```

**Comment by pstjohn** [comment]
> * Give SolutionBase the .data_frame and _repr_html methods?
> * Rename .data_frame? numpy and scipy use asdataframe-like syntax

Even as a fan of both pandas and jupyter, I'd probably vote for omitting these methods at first. If we do choose to put `_repr_html_` methods in cobrapy, we should make that a separate proposal/PR, just so we can talk about how everything could be consistent. For the dataframes, I think we should similarly talk separately about how and where we want to use them.


On `Solution` vs. `LazySolution`, is there any place we'd prefer to use the former? Would constructing a `Solution` take less time than constructing a `LazySolution` and then accessing all the values? why? I guess I would prefer to have a single `Solution` object, and if evaluating the properties lazily gives us the best performance, then that object should be the current `LazySolution` -- just to try to keep things as simple as possible.

**Comment by KristianJensen** [comment]
- Let LazySolution record requested values and make those available even after being invalidated.

I think this one is a good idea. Maybe LazySolution could also have a method that retrieves everything, so that it behaves as an ordinary Solution. That way both behaviours could be contained in the same class. It could either be up to the user to call this method, e.g. `sol = model.optimize().full()` or there could be a `lazy` argument to the optimize method and/or a `lazy` switch attribute on the model.

**Comment by hredestig** [comment]
I second the idea of having only one class, two is quite confusing, when to use which and how they differ. The dataframe topic is indeed perhaps best discuss in a different pr, before 0.6 cobrapy didn't have this functionality so should make a decision that we can then use as model for all objects that can be represented as data frame. Agree on the `to_dataframe`being more explicit. As far as I'm concerned, good to deprecate `f` but I suspect many people are very used to it so that might be excessively annoying(?)

**Comment by pstjohn** [comment]
I'm happy with the more explicit names. Just be sure to do a `git grep '.f'` or similar so we know where things are used internally before we deprecate them?

i.e., `flux_analysis.summary` will need some updating with the newer methods once this settles.

**Comment by cdiener** [comment]
> Let LazySolution record requested values and make those available even after being invalidated.
Hi sorry did not understand that one well. In

```Python
model.optimize()
sol = model.solution  # Assume it's a LazySolution
print(sol["Biomass_Ecoli_core"]
model.reactions.ATPM.bounds = (0, 0)
model.optimize()
x = sol["Biomass_Ecoli_core"]
```

What would be the value of x (currently throws an error)? Would it be the old value of Biomass_Ecoli_core (1st optimize) or the new value (2nd optimize)?

**Comment by Midnighter** [comment]
My idea was to save those values accessed in `sol` so that they are available at any time without raising an exception. In your example it would return the value from the first optimization. Values that had not previously been accessed would still raise an error. In my mind every time you optimize you should ask for a new solution instance which can then be stored in separate variable (if you care for that).

**Comment by Midnighter** [comment]
So far it seems like we like:
1. More explicit names.
2. A single (lazy) solution class.
3. Possibly deprecate `f` if not too annoying for users.

On the question of `_repr_html` and `data_frame`, I only mentioned those since they are part of the `LazySolution` class and have been part of the code since Niko's merge of cameo code in September. Wouldn't be a problem to take that out, though, and add it with a better or more general concept later.

**Comment by cdiener** [comment]
Okay, thanks for the clarification.

**Comment by phantomas1234** [comment]
Is it a big issue to have pandas as a hard dependency in the future? Installing pandas is straightforward nowadays and for me pandas is on the same level as numpy in terms of "how can anyone survive without it?". I always found it extremely cumbersome to deal with the basic python data structures that cobrapy provides for results (especially the ones using cryptic one character variables which is basically a relict of the matlab toolbox). In cameo, we made the decision very early on to always provide a DataFrame for every type of result so users can quickly filter, sort, drop etc. (I at least never use any of the cobrapy data structures, not sure about the others). Also basic plotting of cobra results becomes much more straightforward.

Regarding the `_repr_html_` methods, I think it would be very desirable to have them (very useful for teaching ...) but I don't think the ones implemented in cameo should necessarily be the basis for them. I also would favor pull requests to find a consensus of how all data types should be represented.

**Comment by mmundy42** [comment]
I agree with Niko here. I don't think a dependency on pandas is a big deal and I've switched MMinte to return results in a DataFrame for the same reasons.

**Comment by pstjohn** [comment]
Also agreed. One thing to remember is that the pandas API does change with some regularity. We'll just have to stay up on it.

**Comment by cdiener** [comment]
:+1: from me. I think all deps are fine as long as the deps itself and all packages they depend on have prebuilt wheels for all major platforms. Pandas and numpy fall in that category and scipy, for instance, does not.

**Comment by Midnighter** [comment]
I certainly prefer working with pandas but I also agree that it should be a general configuration for cobrapy. I would either expect structures to always be DataFrames where it makes sense or always something else. Having a mix of data structures depending on the individual functions would be terribly confusing.

Should I add pandas to #387 then?

**Comment by Midnighter** [comment]
I certainly prefer working with pandas but I also agree that it should be a general configuration for cobrapy. I would either expect structures to always be DataFrames where it makes sense or always something else. Having a mix of data structures depending on the individual functions would be terribly confusing.

Should I add pandas to #387 then?
