### ISSUE TITLE
refactor phenotype phase plane

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#382]

**Comment by pstjohn** [comment]
This was another feature I'm not sure gets a lot of use. I'd rather make the base methods so easy to use (and fast enough by default) that writing your own visualization code is rather trivial.

At the end of the day its just a couple nested `for` loops. All the other code in there is either for parallelization (which I don't think we really want to get into?) or visualization (which I also don't think we want to be in..) 

The original `mayavi` looks like it was last updated in 2005...

**Comment by hredestig** [comment]
do you mean by visualisation code just the plotting or the entire ppp calculation? I agree that it would be nice to get rid of the plotting (perhaps for a cobraplots package) but the ppp calculation fits well in cobrapy or? We could add a function to just get the ppp results and return that as dict (or better data frame if we decide to have that as a standard data return format).

**Comment by pstjohn** [comment]
are we doing anything more special than
```python
for i, rxn1_flux in rxn1_flux_range:
    for j, rxn2_flux in rxn2_flux_range:
        model.medium = {rxn1: rxn1_flux, rxn2: rxn2_flux, ...}
        growth_rate[i,j] = model.optimize().objective_value
```

If that's pretty much it, I'd say leave it to the user to implement 😄 . 
If there's some solver-level optimization, or if we want to deal with parallelizing / etc, then perhaps its worth keeping around.

But ultimately, my opinion would be that it would be great if this type of code snippet was *already* fairly optimized through the cobrapy internals (re-using solution bases, etc.)..

**Comment by hredestig** [comment]
simple multiprocessing like there now seems an obvious thing to have as well. And return yield as well as flux perhaps. But you're right, it's not a big one. Then again, saving people to write a bit can be helpful on its own but can also help those that wouldn't know exactly how to write those couple of lines.. I agree of course, with a good code base, this should be fast and easy.

**Comment by cdiener** [comment]
Multiprocessing is complicated in those cases since recycling the basis is usually even faster and that only works in the same process. Maybe refactor to the code you posted and return as numpy array instead of plotting the solution (to not have to maintain matplotlib calls)?

**Comment by pstjohn** [comment]
Another approach would be to incorporate this in #339 where we show an example of how to use cobrapy to calculate the phenotype phase plane and then use matplotlib to plot it. It would be great to have more examples of ways to use cobrapy, and this could definitely be one.

**Comment by hredestig** [comment]
Since this functionality is available in cameo, but generally fits better in cobrapy it was added #422 
It's a simple feature but then also shouldn't hurt much being there.
