### ISSUE TITLE
remove reporter metabolites

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#384]

**Comment by cdiener** [comment]
I would take that one if nobody else has started already. I would like that to be similar to MOMA so you can do something like:

```python
with model:
  loopless(model)
  model.optimize()
  single_reaction_deletion(model)
```

So you can plug-and-play it with other methods.

**Comment by pstjohn** [comment]
I don't even know what cobra.topology is doing 😄 . A lot of that code is ~6 years old at this point. Thumbs up if you want to take a stab at it!

**Comment by cdiener** [comment]
Ah sorry wrong issue :(

**Comment by hredestig** [comment]
Also seems like something better fitting in a different package, shall we instead just drop this one?
