### ISSUE TITLE
**solver_kwargs in the time of optlang

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#386]
### After old solver interface deprecation

Many of the cobrapy functions still take the `**solver_kwargs` optional arguments. However, optlang models carry their own config around which is accessible via `model.solver.configuration` and I think that should become the new standard to configure a solver. 

### Now

optlang solver currently ignore `**solver_kwargs` should be mentioned explicitly in docs.

**Comment by Midnighter** [comment]
via #636
