### ISSUE TITLE
LazySolution gives in incorrect current solutions

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#402]
I think we forgot to test some edge cases with LazySolution. I think this potentially breaks a lot of code I wrote since I often use the optlang interface directly for performance reasons.

```Python
In [4]: mod = create_test_model("textbook")

In [5]: mod.optimize()
Out[5]: <Solution 0.874 at 0x7fa6058175c0>

In [6]: mod.reactions.Biomass_Ecoli_core.flux
Out[6]: 0.8739215069684307

In [7]: mod.reactions.Biomass_Ecoli_core.upper_bound = 0.8

In [8]: mod.solver.optimize()
Out[8]: 'optimal'

In [9]: mod.solution._is_current() is None
Out[9]: True

In [10]: mod.reactions.Biomass_Ecoli_core.flux
Out[10]: 0.8739215069684307

In [11]: mod.solver.variables.Biomass_Ecoli_core.primal
Out[11]: 0.8
```

It should either have declared the solution as "not current" (_is_current() throws an error) or give a correct flux and not the infeasible one.

**Comment by Midnighter** [comment]
Closing this for now since #431 at least catches the most obvious errors.
