### ISSUE TITLE
Many tests failing after LazySolution changes

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#403]
In the current devel-2 I get large amounts of test failures. Mostly related to the cglpk solver which seems to be broken now.

[test_errors.txt](https://github.com/opencobra/cobrapy/files/783944/test_errors.txt)

**Comment by cdiener** [comment]
My bad. Don't forget to recompile the cython deps :sweat_smile:

**Comment by pstjohn** [comment]
hehe, I just got that too 😄

**Comment by cdiener** [comment]
Hope it didn't take you as long to realize it :D
