### ISSUE TITLE
Refactor the solution class (part 2)

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#411]
**Suggestion:**

* Let solution not be lazy but its contained values are determined by a parameter to `model.optimize` which returns the solution.
* The attribute `model.solution` will be ~~deprecated.~~ removed
* ~~`Reaction.flux` and similar will continue to use the solution attribute but also be deprecated.~~

EDIT (hredestig): don't deprecate reaction.flux (see below), and completely remove `model.solution`

**Comment by hredestig** [comment]
To continue the discussion from gitter and elsewhere I'd like to update the proposal to:

### Recommend `model.optimize` as the interactive use method and no lazy solution
`model.optimize` returns a Solution which is not lazy but contains values always contain all fluxes, reduced_costs etc.

The argument for this is that `model.optimize` is something the user does interactively to get a bunch of fluxes and here the few ms it takes to fetch the values has no practical issue.

Point to `model.solver.optimize` in the docs for non-interactive use.
### Recommend `model.solver.optimize` for non-interactive use
`model.solver.optimize` is fast and non-interactively it is easy to fetch fluxes etc with e.g. `reaction.flux`

### remove `model.solution`
This property was undocumented and only sparsely used in 0.5 series. Removing it solves the issue of having a model which has changed but lugs around an outdated solution.

Further suggestions? Concerns?

**Comment by hredestig** [comment]
Also, add utils to get all fluxes, reduced_costs etc (which the Solution class then uses) to get all fluxes as an OrderedDict if only one component is needed.

**Comment by Midnighter** [comment]
`OrderedDict` or `pandas.DataFrame`?

**Comment by cdiener** [comment]
I think we should not recommend reaction.flux if it will be deprecated anyways. Maybe just point to Cobra.util.solver in general.

**Comment by hredestig** [comment]
After discussion here, and from what I gathered on gitter, reaction.flux is appreciated and should remain?

**Comment by cdiener** [comment]
Ah wow. I completely misunderstood the gitter posts. I understood the exact opposite :grimacing:

**Comment by Midnighter** [comment]
That's my understanding, too. We just need to figure out its proper function. Some people use `Reaction.flux` because it's easy to interactively say `model.reactions.XYZ.flux` with tab-completion and others use it for the speed of accessing the solver attributes directly.

**Comment by Midnighter** [comment]
I did argue for its deprecation before but was convinced otherwise.

**Comment by pstjohn** [comment]
I like the interactivity of reaction.flux, but honestly I use the tab-completion on the summary methods more frequently. (`model.metabolites.pyr_c.summary()`) is probably easier than `cobra.flux_analysis.metabolite_summary(model, 'pyr_c')` or similar

So we could certainly refactor those methods to not use `Reaction.flux`, as long as they still were associated with a model (a full #394 will take more thought)

what does an 'interactive' use method mean? If I call `model.optimize()`, can I then start exploring the solution with summary calls, reduced costs, etc? And `model.solver.optimize()` would be for more internal, performance-oriented code like FVA, pFBA, etc?

**Comment by hredestig** [comment]
The additional point that came up here (but didn't make it to gitter) is also that a substantial amount of code, notebooks etc liberally use reaction.flux so deprecating that adds a significant amount of work to the backlog; the value must warrant the impact. 

With interactive, I meant when I in a notebook load a model and start exploring it, checking fluxes, making changes, checking flux again etc. With non-interactive I mean indeed performance oriented code, fva, pfba as you say.

**Comment by Midnighter** [comment]
> I like the interactivity of reaction.flux, but honestly I use the tab-completion on the summary methods more frequently. (model.metabolites.pyr_c.summary()) is probably easier than cobra.flux_analysis.metabolite_summary(model, 'pyr_c') or similar

Totally agree. As far as I could see in the code `Reaction.summary` already calls itself on `cobra.flux_analysis.metabolite_summary` so that's fine IMO.

> what does an 'interactive' use method mean? If I call model.optimize(), can I then start exploring the solution with summary calls, reduced costs, etc? And model.solver.optimize() would be for more internal, performance-oriented code like FVA, pFBA, etc?

That's pretty much the idea. Still need to work on the details. For starters I would like solution to also be tab-completable, i.e., `solution.pyr_c.flux`.

**Comment by cdiener** [comment]
:+1: with all of it. Better docstring for reaction.flux is important since it can lead to some surprises. I think using cplex if you call `model.solver.optimize()` followed by changing bounds you get a cryptic cplex error for instance. `model.objective.value` has the same surprises by the way.
