### ISSUE TITLE
Make analysis functions return data frames

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#412]
Since there was some agreement on making pandas a hard requirement, shall we make FVA return a data frame? Other methods as well, where applicable?

**Comment by cdiener** [comment]
If that were to happen should FVA also gain a version where it returns all fluxes for each optimization instead of only the target flux? 

Can be useful to get a set of very different flux distributions given a target objective and is also needed to get initial search directions for sampling.

**Comment by cdiener** [comment]
Also this breaks backwards compatibility.

**Comment by hredestig** [comment]
On the first point, I don't have a clear opinion there but sounds useful. Perhaps raise another issue for that topic.

On the second, yes it does :/ Could gain another argument like `return_frame` in the double gene deletion? Or live with the compatibility break? I am fine with either but would like to move further on the point of having a more useful default return type than dicts, to facilitate implementation of a future plotting package and for refactoring cameo (where data frames are used quite a lot).

**Comment by cdiener** [comment]
Yeah I agree. I think by that point we already introduced a lot of backwards incompatible changed like Model.objective and removing modules. We just need to keep track of those things and collect them in a detailed release document.
