### ISSUE TITLE
Errors with nested contexts and objectives

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#416]
Currently on devel-2:

```python
import cobra.test
model = cobra.test.create_test_model('textbook')

print('Before:\t{}'.format(model.objective.expression))
with model:
    with model:
        model.objective = model.reactions.ATPM
        print('Inner context:\t{}'.format(model.objective.expression))
    print('Outer context:\t{}'.format(model.objective.expression))
print('After:\t{}'.format(model.objective.expression))
```

```
Before:	-1.0*Biomass_Ecoli_core_reverse_2cdba + 1.0*Biomass_Ecoli_core
Inner context:	-1.0*ATPM_reverse_5b752 + 1.0*ATPM
Outer context:	-1.0*Biomass_Ecoli_core_reverse_2cdba + 1.0*Biomass_Ecoli_core
After:	0
```

**Comment by cdiener** [comment]
Is this the same thing I described in #391?

> Model.objective still had the @resettable decorator. That together with the new set_objective caused some bugs filling up the contexts. Taking @resettable off Model.objective uncovered some bugs with set_objective where it would first zero the objective and than read the reset value (which is surprisingly zero in this case :) ).

Will check whether the bug is gone in #391...

**Comment by pstjohn** [comment]
Oh, perfect! Yeah, sorry for the duplicate bug then. Messed up some of my code running on devel-2 but didn't really have too much time to dig in 😄 .

**Comment by cdiener** [comment]
No, that was my mistake for not separating the issue from my PR. That one gave me a lot of headaches with loopless FVA.
