### ISSUE TITLE
Some inconsistencies

### ISSUE THREAD

**Issue by joaocardoso** [opencobra/cobrapy#423]
Hi all!

So, from our gitter discussion here are some points I would like to bring to the development:

### 1. `model.solution`
This atribute doesn't make sense. If I solve the model, it will store a solution in an atribute inside the model. After that, the model can be manipulated, like changing bounds, adding reactions, changing the stoichiometry of reactions, etc. However, if I change the model state, the `model.solution` is no longer valid. My suggestion is that `model.solution` should be removed and it should be used as follows:
```
solution1 = model.optimize()
# do whatever modifications
# ...
solution2 = model.optimize()
# solution1 and solution2 are different and there is no confusion about what is inside the model.
```
### 2. What is a Reaction
When we look at Reaction, there is a `model` atribute. Also, the Model has a `reactions` atribute which is a DictList with reactions. In the `add_reactions` method, we change the `Reaction.model` atribute. So if I take a reaction from _model1_ and I add the same reaction to _model2_, the reaction is no longer in model1. 

So, what is Reaction? 

a) Is reaction a representation of any metabolic conversion? Or b) is the reaction a representation of a metabolic conversion in a specific model? 

If a) reaction cannot have a model attribute. If b) we cannot add a reaction from a model and we need to build the reaction with a model. This raises implementation issues such as: if a) and the reaction can be in any model, then how do we represent the GPR. In the a) scenario, it should not be in the reaction.

## Optimized ideas
We discussed the problem of how slow it is to get primals and duals from the solver. I think the implementation of `optimize` and/or `solve` should as simple as possible to start with. As we identify advance stuff, we can add protected methods, keyword arguments, etc. So, for `optimize `, my suggestion is: 

(with @cdiener contribution)
`optimize(..., reactions=self.reactions)` returns all fluxes as default. When `reactions=[]` returns no fluxes and when `reactions=[r1, r2, ...]` returns only the subset of fluxes.

I have a bit of mixed feeling here, so I'll share my ideas.

1.Other advanced keyword arguments like `shadow_prices=True`, `reduced_cots=True`, ` irreducibly_inconsistent_constraints=False` can be set on the method. The default values would be to return the most complete solution for a regular user.

2. Advanced implementations can interact with the solver directly to retrieve duals and primals and other information. Here my main concern is concurrent multithread implementations. We would need to be able to lock the model.

3. This is the most disruptive idea: get rid of `model.solve`. Then if the user want a flux distribution he has to explicitly use a method to retrieve it: `fba(model)`, `pfba(model)`, `moma(model)` or `my_brilliant_method(model)`. The implementation and access to the solver would be done through less exposed methods.

I hope that we can use this discussion forum give more stability and coherence to cobrapy implementation.

Cheers,

Joao

**Comment by Midnighter** [comment]
As mentioned in gitter, can you copy this over to #394, please?
