### ISSUE TITLE
weed out the packaged solvers

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#428]
I would like to propose to clean up the `cobra.solvers`. So far in the tests I've only seen the legacy "cglpk" and "esolver" show up. There are a couple of other solver interfaces there, though. Are any other ones functional and could be configured to be run by the tests, too? I don't know if there's a good way for us to poll which ones are in use out there. It would be good to remove unnecessary ones, though.

**Comment by cdiener** [comment]
cplex, gurobi and mosek will be used by the tests if installed. See for instance the benchmarks where you will see `[cplex]` and also `[optlang-cplex]`. But I think this will be easier in 0.7 where we will delete the entire folder anyways...

**Comment by Midnighter** [comment]
Another thing about solvers that has been bothering me and is not correctly handled everywhere is the `solver` argument to analysis functions. I vote for removing that argument when we completely rely on optlang and don't support the legacy solvers any longer. I think setting `model.solver` (or whatever we name it) should be the one obvious way to do it and is totally sufficient.

**Comment by cdiener** [comment]
`Model.optimize`, `single_*_deletions` and FVA handle the solver argument correctly and use `Model.solver` when set to None. I agree that this should be removed along with the **solver_kwargs as mentioned in #386.
