### ISSUE TITLE
fix optimize_minimal_flux to return solution

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#429]
`optimize_minimal_flux` should be the (roughly) same as `model.optimize()` so should return a solution and not dataframe.

Which make me think, why not have a `method=['pfba', 'fba']` argument to `model.optimize` to make this connection more obvious?

**Comment by pstjohn** [comment]
Ali was against it, see #227 😄 . Not a reason to keep it out, just a historical context.

**Comment by hredestig** [comment]
Thinking about it a bit more I think I change my view on that as well, `model.optimize` doesn't do any particular algorithm, it just does what the current model defines. If it all is fba then pfba is a subset of fba so the choice is not either. So, the new way of doing it is then
```
with model:
    add_pfba(model)
    model.optimize()
```
or using the `optimize_minimal_flux`, also avoids risk of having a method argument that would get more options as we go along

**Comment by cdiener** [comment]
On a side note I find "optimize_minimal_flux" confusing. What is "minimal flux"? Since it is more commonly known as parsimonious FBA in the literature I think we should maybe use a variation of this like pfba, parsimonious_fba, etc.

**Comment by pstjohn** [comment]
One concern I have with adding constraints to the model (with add_pfba, add_moma, etc) is what what happens what I accidentally add pfba, loopless, and / or moma constraints to the same model?

What happens when I save/load the model (json, sbml, etc), do they come back?

I do think this is a neat way to go, I just think these kinds of behavior should be made more explicit. Maybe PfbaModel subclasses Model? (But then contexts might be hard).. Maybe there could be a property that lists active flux constraints?

**Comment by cdiener** [comment]
I agree. There are still the optimize_minimal_flux and single_*_deletion methods that take care of removing the added constraints. I think the add_* functions are for more advanced use. Writing models modified with add_* to SBML would create a weird hybrid that does not include the new constraints and variables but does include the new objective...

**Comment by pstjohn** [comment]
Depending on how those are implemented, maybe we just warn when a user calls `add_*` without an active context?

**Comment by hredestig** [comment]
we can also make sure to name the objective to be able to check that we don't add it twice. And for saving, doesn't strike me so strange that not everything in the object gets written, in the short term documentation appears sufficient to me..
