### ISSUE TITLE
Probable bug in the cobrapy SBML parser

### ISSUE THREAD

**Issue by arturomarin** [opencobra/cobrapy#432]
Hello everyone,

I am working with the model "iJR904.xml" from http://bigg.ucsd.edu/models/iJR904

Using COBRApy is easy to do a single deletion of all reaction, but I try do this manually for learning purpose.

From the single deletion of reaction did by COBRApy I can see that the deletion of reaction "A5PISO" cause a 0 flux. Well, when I try block the reaction manualy in the .xml file I can not. The reaction is:

```
    <reaction fast="false" fbc:lowerFluxBound="cobra_0_bound" fbc:upperFluxBound="cobra_default_ub" id="R_A5PISO" metaid="R_A5PISO" name="Arabinose-5-phosphate isomerase" reversible="true"
      sboTerm="SBO:0000375">
        <annotation>
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#R_A5PISO">
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/bigg.reaction/A5PISO" />
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>
        <listOfReactants>
          <speciesReference constant="true" sboTerm="SBO:0000010" species="M_ru5p__D_c" stoichiometry="1" />
        </listOfReactants>
        <listOfProducts>
          <speciesReference constant="true" sboTerm="SBO:0000011" species="M_ara5p_c" stoichiometry="1" />
        </listOfProducts>
      </reaction>
```

When I change "lowerFluxBound" and "upperFluxBound" to 0

`      <reaction fast="false" fbc:lowerFluxBound="0" fbc:upperFluxBound="0" id="R_A5PISO" metaid="R_A5PISO" name="Arabinose-5-phosphate isomerase" reversible="true"`

the flux give by COBRApy is not 0. I think there is a problem with cobrapy SBML parser.
How can I avoid this error?

Thanks in advance,

Arturo Marin

**Comment by cdiener** [comment]
Hi this is not a bug but an error in your SBML. SBML with strict FBC does not allow you to add values into lowerFluxBound directly with just a value. It has to be the name of a parameter as in the example you posted. What does work is setting both bounds in the SBML to "cobra_0_bound". This should lead to a zero flux in that reaction. 

Actually I'm surprised you did not see an error when reading your SBML. I will check that.

**Comment by arturomarin** [comment]
Hi, the solution of setting both bounds to "cobra_0_bound" is suggested to me by Mathias Köning

https://groups.google.com/forum/#!topic/sbml-discuss/MYp6JI5MaYM

but does not work. The flux of the A5PISO reaction is the same that without change the bounds, 42... so, probably is a bug of cobrapy.

**Comment by cdiener** [comment]
I can not reproduce that. 

The model you appended in your Email on the mailing list still has the bound set incorrectly to "0.0000" and *not* in the way it was suggested by Matthias and me. Changing both bounds to "cobra_0_bound" in the model you sent I obtain the following:

```Python
In [1]: import cobra

In [2]: ecoli = cobra.io.read_sbml_model("iJR904_NoA5PISO.xml")
cobra/io/sbml3.py:256 UserWarning: loading SBML model without fbc:strict="true"

In [3]: ecoli.optimize()
Out[3]: <Solution 0 at 0x7f2b700174e0>

In [4]: ecoli.reactions.A5PISO.flux
Out[4]: 0.0
```

In general, I don't recommend editing SBML by hand since you have to follow a strict specification of a few hundred pages of documentation. In any case it's always a good idea to check your SBML file with the official validator at http://sbml.org/Facilities/Validator/. For instance the model you sent in your Email states "This document is not valid SBML".

**Comment by arturomarin** [comment]
Ok, thank you very much for your time. I had understood that Matthias want the file with my original change. Well, now I use your code posted here and it is work for me to. I think that the problem is that I loaded the model in a different way:

```
from cobra.io.sbml import create_cobra_model_from_sbml_file
cobra_model = create_cobra_model_from_sbml_file('iJR904_NoA5PISO.xml')

```
And this load the model, but not in a right way. I will follow your advice to check my SBML files. For me the issue is close if you are agree.

**Comment by cdiener** [comment]
Ah ok. The thing is that you forced a SBML 2 parser to read a SBML3 model with FBC. So it ignored all fbc:lowerFluxBound terms. Better use `io.read_sbml_model` as described [in the docs](http://cobrapy.readthedocs.io/en/latest/io.html#SBML). This one will figure out which SBML version you used itself.
