### ISSUE TITLE
Documentation for 0.6.0 missing on readthedocs

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#450]
I can't find the documentation for 0.6.0. 
I wanted to lookup how the HistoryManager works and how to access the solution in 0.6.0
But 
http://cobrapy.readthedocs.io/en/latest/getting_started.html
does not seem to be for 0.6.0.

The release notes link this
https://github.com/opencobra/cobrapy/blob/devel/release-notes/0.6.0.md
but cannot find the 0.6.0 documentation anywhere.

**Comment by matthiaskoenig** [comment]
Also other notebooks missing mentioned in the release notes
http://cobrapy.readthedocs.io/en/latest/sampling.html

**Comment by cdiener** [comment]
As mentioned on gitter those are still building :smile:

**Comment by hredestig** [comment]
Just got access to rtd account from Ali, fixing some bugs there

**Comment by hredestig** [comment]
[Fixed](http://cobrapy.readthedocs.io/en/0.6.0a2/)

**Comment by matthiaskoenig** [comment]
Thanks for this. The sampling link is working also.
Opened another missing link in separate issue #454
