### ISSUE TITLE
Broken link release notes

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#454]
The following link is broken in
https://github.com/opencobra/cobrapy/blob/devel/release-notes/0.6.0.md

Objectives can now easily be made quite advanced by simply crafting the right expression and assigning this as usual to model.objective, see the --> contraints and objectives notebook <--. 
http://cobrapy.readthedocs.io/en/latest/constraints_objective.html

**Comment by hredestig** [comment]
Fixed

**Comment by matthiaskoenig** [comment]
Great. Thanks a lot.
