### ISSUE TITLE
Documentation of context manager

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#462]
Hi all,

I saw a lot of discussion/mentioning of the new model context manager in 0.6. Unfortunately, I could not find and documentation about it. It would be great if there could be a notebook added to the readthedocs documentation which shortly explains what it is, how to use it, why it is useful.
- I understood mainly that it allows to make small changes to model without the need of creating a complete copy of the model. But could be completely about that. 
Sounds like a great feature.

The best
Matthias

**Comment by hredestig** [comment]
Is [this](http://cobrapy.readthedocs.io/en/latest/getting_started.html#Making-changes-reversibly-using-models-as-contexts) sufficient?

**Comment by matthiaskoenig** [comment]
perfect. thanks
