### ISSUE TITLE
Matlab file import truncated model ID

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#486]
I noticed that the model IDs for Matlab models get truncated to the first letter. This is easy to replicate with models from BiGG:

```shell
wget http://bigg.ucsd.edu/static/models/iCHOv1.mat
python -c "import cobra; m = cobra.io.load_matlab_model('iCHOv1.mat'); print(cobra.__version__, m.id)"
# Prints ('0.5.11', u'i')
```

It looks like this popped up in https://github.com/opencobra/cobrapy/commit/9a5a789ebfb53fd951a6ec0f296d189f5038df23.

**Comment by cdiener** [comment]
Yeah my bad. This was supposed to only use the first ID in case there are several. It's missing a check for the type. Will make a PR for a fix...

**Comment by zakandrewking** [comment]
thanks!!
