### ISSUE TITLE
cobrapy 0.5.11 not available for installation in QIIME 1 virtualbox

### ISSUE THREAD

**Issue by mmundy42** [opencobra/cobrapy#492]
Over the mminte repo we received an [issue](https://github.com/mendessoares/MMinte/issues/7) because pip returned an error installing cobrapy. The error message is "No distributions matching the version for cobrapy=0.5.11".

It looks like the user is trying to install mminte in a QIIME virtual box. Are there specific combinations of operating systems and Python versions where the latest versions of cobrapy are not supported?

**Comment by cdiener** [comment]
Could be related to the required pandas versions (cobra wants >=0.17, qiime <=0.16.2). Maybe that causes the conflict. Unfortunately, Qiime 1 is pretty much abandoned in favour of the still unreleased Qiime 2, thus the outdated requirements...

**Comment by hredestig** [comment]
Anything more to do here @mmundy42 ? Seems to be an issue for QIIME folks to address..

**Comment by mmundy42** [comment]
Sorry for the delayed response, I was out of the office for a few days. I think the base problem was that the latest 0.5.x version of cobrapy on Linux for Python 2.7 was 0.5.4. Now that cobrapy 0.6.x is out I'm updating mminte to work with 0.6.x and will be releasing a new mminte version soon.

**Comment by cdiener** [comment]
For the Qiime users you could tell them to install Qiime in a virtual environment. I also made a Qiime docker image a while ago which is surprisingly popular (https://hub.docker.com/r/cdiener/qiime-docker). Either way those problem will go away with Qiime 2.
