### ISSUE TITLE
consistent behavior between `add_metabolites` and `add_reactions`

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#511]
Currently, `model.add_reactions` will throw a `ValueError` if any of the reaction IDs are already in the model, while `model.add_metabolites` will just not add them.

Is there any motivation to this? If we were to standardize them, which would we prefer?

**Comment by cdiener** [comment]
Good one. Considering the `+` operators for models it might be easier to implement if it would just not add them. This way adding reactions and metabolites from one model to another only adds new ones. In this case we could add warnings to the logger so it isn't done completely silent...

**Comment by hredestig** [comment]
I'd like the behavior to not just add them, what the user is requesting is then already achieved so no reason to error. There is very little logging going  on in cobrapy currently but would be nice to add that a bit all over the package..
