### ISSUE TITLE
Summary method after pfba

### ISSUE THREAD

**Issue by ma-blaetke** [opencobra/cobrapy#520]
There is a problem with the summary method called on a model after doing pfba(). I get the following error message:

_OptimizationError: Likely no solution exists. Original solver message: Unable to retrieve attribute 'X'._
(Below, complete output)

Nevertheless, if I call e.g. the x_dict on the result of pfba(), there clearly is an optimal solution. What I also get from the x_dict, that now reversible reactions are splitted, instead of summed up as before. Is this on purpose?

```
---------------------------------------------------------------------------
OptimizationError                         Traceback (most recent call last)
<ipython-input-121-8a0c3b7fef90> in <module>()
      1 result_fba = cobra.flux_analysis.parsimonious.optimize_minimal_flux(cobra_model, solver="gurobi")
----> 2 cobra_model.summary()

//anaconda/lib/python2.7/site-packages/cobra/core/model.pyc in summary(self, threshold, fva, floatfmt, **kwargs)
    926         from cobra.flux_analysis.summary import model_summary
    927         return model_summary(self, threshold=threshold, fva=fva,
--> 928                              floatfmt=floatfmt, **kwargs)
    929 
    930     def __enter__(self):

//anaconda/lib/python2.7/site-packages/cobra/flux_analysis/summary.pyc in model_summary(model, threshold, fva, floatfmt, **solver_args)
    144             metabolite_fluxes[met] = {
    145                 'id': format_long_string(met.id, 15),
--> 146                 'flux': stoich * rxn.x}
    147 
    148     # Calculate FVA results if requested

//anaconda/lib/python2.7/site-packages/cobra/core/reaction.pyc in x(self)
    476         """
    477         warn("Please use reaction.flux instead.", DeprecationWarning)
--> 478         return self.flux
    479 
    480     @property

//anaconda/lib/python2.7/site-packages/cobra/core/reaction.pyc in flux(self)
    317             raise_from(OptimizationError(
    318                 "Likely no solution exists. Original solver message: {}."
--> 319                 "".format(str(err))), err)
    320 
    321     @property

//anaconda/lib/python2.7/site-packages/future/utils/__init__.pyc in raise_from(exc, cause)
    452             raise TypeError("exception causes must derive from BaseException")
    453         e.__context__ = sys.exc_info()[1]
--> 454         raise e
    455 
    456     exec('''

OptimizationError: Likely no solution exists. Original solver message: Unable to retrieve attribute 'X'.
```

**Comment by pstjohn** [comment]
Could you post an example of the model that's causing those issues?
And perhaps which version of cobra you're using?

**Comment by ma-blaetke** [comment]
It's cobra 0.6.1.
By preparing an example, I encountered that it must be related to the "gurobi" solver I am using, it is not happing with glpk. Hope this helps.

```
import cobra.test
model = cobra.test.create_test_model("textbook")
model.solver = "gurobi"
sol_fba = model.optimize()
model.summary()
```

IN FLUXES        OUT FLUXES    OBJECTIVES
---------------  ------------  ----------------------
o2_e      21.8   h2o_e  29.2   Biomass_Ecol...  0.874
glc__D_e  10     co2_e  22.8
nh4_e      4.77  h_e    17.5
pi_e       3.21

```
sol_pfba = cobra.flux_analysis.parsimonious.pfba(model)
model.summary()
```

```
---------------------------------------------------------------------------
OptimizationError                         Traceback (most recent call last)
<ipython-input-18-3e32a54b8daa> in <module>()
      1 sol_pfba = cobra.flux_analysis.parsimonious.pfba(model)
----> 2 model.summary()

//anaconda/lib/python2.7/site-packages/cobra/core/model.pyc in summary(self, threshold, fva, floatfmt, **kwargs)
    926         from cobra.flux_analysis.summary import model_summary
    927         return model_summary(self, threshold=threshold, fva=fva,
--> 928                              floatfmt=floatfmt, **kwargs)
    929 
    930     def __enter__(self):

//anaconda/lib/python2.7/site-packages/cobra/flux_analysis/summary.pyc in model_summary(model, threshold, fva, floatfmt, **solver_args)
    131     objective_reactions = linear_reaction_coefficients(model)
    132     obj_fluxes = pd.DataFrame({key: key.flux * value for key, value in
--> 133                                iteritems(objective_reactions)},
    134                               index=['flux']).T
    135     obj_fluxes['id'] = obj_fluxes.apply(

//anaconda/lib/python2.7/site-packages/cobra/flux_analysis/summary.pyc in <dictcomp>((key, value))
    130     # Create a dataframe of objective fluxes
    131     objective_reactions = linear_reaction_coefficients(model)
--> 132     obj_fluxes = pd.DataFrame({key: key.flux * value for key, value in
    133                                iteritems(objective_reactions)},
    134                               index=['flux']).T

//anaconda/lib/python2.7/site-packages/cobra/core/reaction.pyc in flux(self)
    317             raise_from(OptimizationError(
    318                 "Likely no solution exists. Original solver message: {}."
--> 319                 "".format(str(err))), err)
    320 
    321     @property

//anaconda/lib/python2.7/site-packages/future/utils/__init__.pyc in raise_from(exc, cause)
    452             raise TypeError("exception causes must derive from BaseException")
    453         e.__context__ = sys.exc_info()[1]
--> 454         raise e
    455 
    456     exec('''

OptimizationError: Likely no solution exists. Original solver message: Unable to retrieve attribute 'X'.

```

**Comment by gregmedlock** [comment]
I can't test this at the moment, but it doesn't look like the gurobi interface has been updated for gurobi version >7.0. You may have better luck trying gurobi 6.5 (although gurobi 7.0 has some neat features!)

**Comment by cdiener** [comment]
Hmm, I tested some examples with optlang and gurobi 7.02 and it worked. @ma-blaetke could you also give us your version of optlang?

**Comment by ma-blaetke** [comment]
Its optlang 1.2.0.

**Comment by cdiener** [comment]
Hi @ma-blaetke, thanks for your help I can now reproduce your error with the following minimal example:

```Python
import cobra.test
from cobra.flux_analysis import pfba

model = cobra.test.create_test_model("textbook")
model.solver = "gurobi"
sol = pfba(model)
model.summary()
```

The error is caused by `summary()` using `reaction.flux` which is not safe after a context manager reset like the one caused by `pfba`. Rather summary should generate its own solution *de novo* and obtain fluxes via `solution.fluxes`. So it's definitely a bug :cry:

**Comment by pstjohn** [comment]
but summary has only started using reaction.flux as of a few days ago...
I'm sure we talked previously about having summary generate it's own solution, but I tend to think of the summary methods mainly being there to 'summarize' a previous solution :).

And in this case, if `summary` had to give its own *de novo* solution, then you're still stuck in using `summary` after `pfba`. You'd have to use the `pfba` context.

Should we instead be thinking about `solution.summary()`? That also was brought up before, by @Midnighter I believe. The issue there is that then solutions would have to carry around their own models...

Maybe we should just let flux hang around after exiting a context? Does that bite us elsewhere?

**Comment by pstjohn** [comment]
Also, this is what I get on `devel`:

```python
import cobra
import cobra.test

model = cobra.test.create_test_model('textbook')
cobra.flux_analysis.pfba(model)
model.summary()
```

```
IN FLUXES        OUT FLUXES    OBJECTIVES
---------------  ------------  ----------------------
o2_e      21.8   h2o_e  29.2   Biomass_Ecol...  0.874
glc__D_e  10     co2_e  22.8
nh4_e      4.77  h_e    17.5
pi_e       3.21
```

```python
>>> import optlang; print(optlang.__version__)
1.2.1
```

**Comment by cdiener** [comment]
> Maybe we should just let flux hang around after exiting a context? Does that bite us elsewhere?

I think that's not possible since `reaction.flux` requests its value from `solver.variable.primal` which is handled by optlang which in turn gets the value from the lower level interfaces.  

> And in this case, if summary had to give its own de novo solution, then you're still stuck in using summary after pfba. You'd have to use the pfba context.

Nope. Solution is a snapshot and does not receive any values on demand, for instance

```Python
sol = pfba(model)
sol.fluxes # will work even though solver in invalidated
model.biomass_reaction.flux # error
```

**Comment by cdiener** [comment]
You forgot to change the solver to gurobi in your example. Gurobi checks whether the model has been modified and invalidates the primals. GLPK is not very good with that...

**Comment by pstjohn** [comment]
Ah.. right. oops. I don't have access to gurobi sadly, so not sure that's something I can test. 

But my point in generating a de novo solution is that model.summary() would have to know to use pfba. 

```python
sol = pfba(model)  #solves via pfba
model.summary()  # solves without pfba
```

unless we carry the solution object around with us:
```python
sol = pfba(model)
model.summary(sol=sol)
```

which seems like an API burden.

**Comment by cdiener** [comment]
Wasn't there an arg (`pfba=True`) in model.summary before? 

Same thing happens with cplex btw. I fear the only save way with the new API is either to generate a new solution within summary or take a solution as an argument.

**Comment by pstjohn** [comment]
Oh wow, so is a solution just a thin veil around the model anyways? I must have missed this :).
You can remove reactions from a model within a solution:

```python
sol.reactions.ACALD.remove_from_model()
```

But that would mean that `sol.reactions.PYK.flux` would point to the new basis, while `sol.fluxes['PYK']` would stay put? Confusing..

So would we just re-write the summary methods to use self.fluxes (like the old self.solution.x_dict) and only apply to solution objects?

Then you could do `model.optimize().summary()`, which is nice.

**Comment by hredestig** [comment]
I also didn't consider that, `sol.reactions.ACALD.remove_from_model()` feels very awkward, as a user I would prefer if the solution was decoupled from the model I think.. I like the suggested `solution.summary()` being more explicit about what it actually does, and `model.summary` a wrapper for that perhaps

**Comment by Midnighter** [comment]
`solution.reactions.xyz` is a reference to the reaction instance. Thus you can call any method on it. I have no problem with removing `Solution.reactions` and `Solution.metabolites`.

With the current way that summaries are displayed I would strongly argue for a function:
```python
def summary(model, solution, reaction=None, metabolite=None):
```
or similar signature. I don't think the solution instance carries enough information to generate the summary without access to the model instance and I would certainly not want to add more information to the `Solution` class.

**Comment by pstjohn** [comment]
I'd thought about it before but I'm not sure what a `reaction.summary` would display. So not sure we need that functionality.

I do like the tab-complete ability of exploring a model's fluxes through `metabolite.summary`, which we would loose by making it a general function. I use the model-level summaries to make sure the optimization is doing what I think its doing, and the metabolite summaries as a way of tracking down how flux is moving inside the model.

If we *could* attach them to the solution object (we'd need to figure out how to deal with the model information), that makes intuitive sense to me. A solution arises from a specific model and isn't valid for any other ones, so from an API standpoint it seems odd to make a user remember which solution goes with which model.

Not that it's the most intuitive interface, but [statsmodels](http://www.statsmodels.org/stable/index.html) uses the paradigm
```python
result = model.fit()
result.summary()
```

So maybe, if we can figure out the model encapsulation, we aim for something like
```python
result = model.optimize()
result.summary()
result.metabolites.PYK.summary()  # or just result.PYK.summary() ?
```

**Comment by Midnighter** [comment]
Let's start from a different point of view. What is the information we want to or expect to see when we call each of:

1. `Model.summary()`
2. `Reaction.summary()`
3. `Metabolite.summary()`

I think when we know what we want to see, it's much easier to debate the technicalities of how to implement that.

**Comment by mmundy42** [comment]
For me, what you want to expect to see from the 3 methods is different depending on whether you have produced a solution or not. So I'm leaning towards an interface like what @Midnighter proposed above where the solution needs to be a parameter to a summary method or function.

**Comment by pstjohn** [comment]
So I may be biased, but I think the current outputs are fairly intuitive:
1. Model: show the input and output reactions of the model, together with the objective.
2. Reaction: ?? `reaction.reaction` and `reaction.flux` gives you about as much as you need.
3. Metabolite: Show how flux enters and leaves the metabolite. FVA and percentages are nice here.

What do you think they should show without a solution?


My main preference away from requiring the solution argument is that it seems cumbersome. Separating the solution from the model might allow you in theory to do stuff like 
```python
model.metabolites.summary(solution1)
model.metabolites.summary(solution2)
```
but now we have to be careful about making sure the model is *similar enough* between when solution1 was generated vs. solution2.

Larger question I suppose: whats the point of the `solution` class? (i.e., vs. `reaction.flux` which grabs its information directly from the solver).
* Should a solution be interpretable without a corresponding model? I.e.,
```python
solution1 = model.optimize()
change_stuff(model)
solution2 = model.optimize()
```

`solution1` at this point seems to have outlived its usefulness: we can't be sure the model hasn't had reactions / metabolites removed, objectives changed, etc., so summary methods are off the table unless solution1 contains a deep copy of the model (which it shouldn't). It's really just a list of the fluxes, maybe a status message and an objective value.

**Comment by pstjohn** [comment]
A couple of options I talked about with @cdiener on the gitter:

1. `summary()` puts in a call to `model.optimize()`, perhaps with kwargs to support common methods.
2. `solution` can sit on the context stack, and `*_summary()` can check to make sure a `solution` is sitting on the top of the stack, grabbing its flux values from there.
3. `solution` copies the relevant details from the model when it is created, like ` {met.id: {"consumed": [r.ids]. "produced": [r.ids]}}`
4. `solution` is a Singleton, and always reflects the most recent solve for a given model.

Thoughts:
1. Inefficient, but straightforward. Still lets you keep the `fva` kwarg. My main concern is that with repeated optimizations in `model.metabolite.summary()`, you couldn't be guaranteed the fluxes you were exploring were coming from the same solution.

2. Would require model.summary() to operate from within a context, which destroys some of its interactive charm. But we'd be sure that the solution was fresh.

3. Possibly slow, but more importantly wouldn't allow the 'fva' kwarg. But then we could follow the `statsmodels` paradigm

4. This is essentially the way it works now with GLPK, which is sloppy about invalidating the primal values. Would just cache results from the last run, and therefore would likely display the wrong objective in the pfba example, solution isn't guaranteed to have come from the same model.

**Comment by Midnighter** [comment]
Some thoughts:
* The relationship between model and solution is definitely 1:n. I may want to compare FBA with pFBA or some other method. I may want to change bounds (granted, that makes it not the exact same model but very close) and compare the flux distribution, etc. Due to these reasons the solution as a singleton is also not an option to me.
* I actually kinda like your above `model.metabolites.PYK.summary(solution_1)`, I still think this should be deprecated in favour of `summary(model.metabolites.PYK, solution_1)` eventually but I don't mind it for now. I would argue that it's up to the user to do the right thing here and ensure that model state should correspond to the solution. Do you see a big problem with that?
* I would like to move away from code that uses `Reaction.flux` etc. and not strengthen that relation in the codebase. I really, really hope that `Solution.fluxes.xyz` can replace this behaviour so that we can do away with all the complex relationships between classes in future.
* I also prefer providing the summary function/a corresponding method with the solution object because I don't think that resolving the model is an option. It's just too surprising and a terrible side effect from something as harmless sounding as summary. I sort of understand the `fva=` argument but even then I could say, generate an FVA solution first and use that to display a summary.

**Comment by hredestig** [comment]
Moving my comment from gitter here as well, I agree with @Midnighter, I see the solution as a snapshot of what state the model was in at a given moment, thus would even intuitively favour
`summary(solution, metabolite=None)`
as don't really see why summary would need the model as argument, in addition to what's already in the solution, the summary methods only need

- reactions taking part in objective (can be captured in solution)
-  exchanges

and these could easily also be recorded in the solution.. FVA results could be summarized the same way. It would be quite a break, but change could happen gradually if we would decide to go that way.

**Comment by cdiener** [comment]
I prefer options 1 or 3 from @pstjohn's list.

**Comment by pstjohn** [comment]
@hredestig, the metabolite summaries would require you to know to know the full model stoichiometry. you look at all the flux coming into and going out of any given node

**Comment by pstjohn** [comment]
> It's just too surprising and a terrible side effect from something as harmless sounding as summary. 
that's a good point, I'm leaning away from (1). 

> I would argue that it's up to the user to do the right thing here and ensure that model state should correspond to the solution.
I think that's part of the issue that started this thread -- after pfba exits the context the model objective is changed, and (if you used glpk), the model would summarize the wrong objective. Whatever we work towards should let you do
```
pfba(model)
summary(??)
```

**Comment by hredestig** [comment]
after `pfba` the objective is back to what it was before.. `summary(pfba(model))` seems the natural  choice to me.

**Comment by pstjohn** [comment]
so that would mean the solution objects would need to keep a record of the model objective?
As well as pointer to the model for reaction / metabolite relationships? (which are vulnerable to changing before the solution is printed)

**Comment by hredestig** [comment]
..or if we could summarise everything you need know about the model at the state of `model.optimize` and capture that in the solution object? Not sure how intense that is but also don't think `model.optimize` has to be very performant as meant to be used interactively. Could even add a switch to `model.optimize` to not create avoid filling out the attributes that take longer to compute.. I think it would be great if we could decouple the solution from the model completely as we already started doing that by removing `model.solution`

**Comment by Midnighter** [comment]
Completely agree on keeping solution and model decoupled. A flag might be the way to go as it could also be useful to not always instantiate the complete solution object when an optimization strategy like pFBA or ROOM is called as part of higher order functions (such as double knock-outs etc.).

**Comment by cdiener** [comment]
I think `model.optimize` is still one of the most used functions in cobrapy and from the code snippets I have seen in the Google group it is used in loops quite a lot (only way to get all fluxes). So I think I would prefer if it doesn't get another performance hit. Also computing what is essentially the stoichiometric matrix on every optimize might be a bit redundant (probably changes only very little between calls).

I agree with decoupling solution and model of course. Whether the extra info really makes model instantiation slower is still something we would have to check. The alternative would be to take model as an argument to summary and make some validation whether it's still close enough to what the solution describes (model still includes the same reactions for instance).

**Comment by hredestig** [comment]
Indeed a bit non-backwards compatible but what to do.. The idea of `summary(model, solution)` sounds inherently fragile and cumbersome to me. Clear documentation, announcement can perhaps be sufficient? Anyway good if the distinction between `model.solver.optimize` and future `full_solution=True` is stressed in the docs.

**Comment by pstjohn** [comment]
I don't think it would be outrageous to try to put the model information in the `solution` object. A first pass option looks to be around 2x as slow:

```python
>>> model = cobra.test.create_test_model('ecoli')
>>> model.optimize()
>>> %timeit cobra.core.solution.get_solution(model)
10 loops, best of 3: 21.8 ms per loop
```

```python
%%timeit

G = nx.Graph()
var_primals = model.solver.primal_values

def iter_edge(model):
    for rxn in model.reactions:
        flux = var_primals[rxn.id] - var_primals[rxn.reverse_id]
        for met, stoich in rxn.metabolites.items():
            yield (rxn.id, met.id, {'flux': flux * stoich})
            
G.add_edges_from(iter_edge(model))
```
```
10 loops, best of 3: 41.3 ms per loop
```

These kinds of loops could be sped up a lot if we could move to some sort of compiled library... But I'm not sure how we'd want to do that. optlang's interfaces are all at the python level. @Midnighter, I know you have some experience with networkx, anything we could do to speed these up?

**Comment by Midnighter** [comment]
Some musings:
* The number of edges will increase sharply with larger models so I doubt that the 2x factor will hold.
* In the current code you hardly use networkx at all (`iter_edge` is completely independent) so that's where I would look into optimizations. If we're always interested in summarizing the whole model then a (sparse) stoichiometric matrix representation might be faster but I'm not sure. On the other hand, `model.summary` only shows a handful of values so maybe that decision can be made beforehand?
* I'm seriously starting to reconsider my earlier statement that `summary` shouldn't create a new solution. Since a user might be interested in minimal/maximal flux anyway (thus requiring an FVA), we might consider calling it `model.compute_summary` and otherwise be very clear in the docs that this will compute new values.

**Comment by cdiener** [comment]
I think the benchmark is not super fair since `get_solution` does much more than just getting the fluxes. It also gets the dual values, objective value etc. So the truth is probably 3x slower. Taking up earlier discussions it would also be a surprising side effect that `get_solution` spends the majority of computation time creating additional objects that are not really required for the solution but only for the summary method... I don't really have a better idea though :disappointed:

**Comment by pstjohn** [comment]
> On the other hand, `model.summary` only shows a handful of values
We'll still need the whole stoichiometry for `model.metabolite.xyz.summary()`,

**Comment by pstjohn** [comment]
`model.compute_summary` would have to take arguments for pfba, fva, etc., as well as perhaps the individual metabolite you wanted to summarize. So its usefulness for exploring a particular solution would be more limited.

getting back to the original point of this issue, `solution = pfba(model)` essentially guarantees that `solution` will no longer correspond to `model`. One option could be to have `pfba` and other context short-cuts have the kwarg `summary=False` to print a summary while still inside the context. But then metabolite summaries might not work after the fact.

I do think we should stop having `reaction.flux` point to the underlying solver object. We should decide whether these methods can access the most recent solution and add that in accordingly. 
What are the problems with having a `model.last_solution` object?

**Comment by cdiener** [comment]
`model.last_solution` might be wrong. The example that was discussed before was solving a model then deleting a reaction. The reaction would still have a flux in the last solution, however it is gone (flux=0?).

I think based on the discussion here I prefer either having `model.summary` explicitly call `optimize` or the `summary(model, solution, metabolite=model.metabolites)` API.

**Comment by pstjohn** [comment]
* with `summary(model, solution, metabolite=model.metabolites)`, (not computing a new solution), you wont be able to inspect the solution from pfba, moma, etc., since the objective will have changed after the `pfba(model)` function exits:
```python
solution = pfba(model)  # solution corresponds to a model inside the pfba context
summary(model, solution)  # model and solution no longer match
```
* A `model.calculate_summary()` could get around that with kwargs, but then you're not able to compare/contrast metabolite summaries for a *single* solution to track mass balances through the model.
```python
calculate_summary(model, metabolite='pep_c')  # could be an entirely different solution basis than
calculate_summary(model, metabolite='pyr_c')  # and would make analysis difficult.
```

Or we could just trust users to not call `model.summary` with a radically different model object: that's essentially how it works now for glpk.

**Comment by cdiener** [comment]
Good points. Maybe the first one could be avoided by embedding the linear coefficients for the objective in the solution object (quadratic components are ignored by summary anyways, correct?). This is less heavy than saving the entire model structure.

**Comment by hredestig** [comment]
@pstjohn What was wrong with  your suggestion 3 far above, capture what is needed from model (e.g. just copy the metabolites and reactions lists/compute a summary of them) and then have `solution.summary()`? The lack of fva? Couldnt' that then be included in the `fva_result.summary()` instead?

**Comment by matthiaskoenig** [comment]
Please don't make solution slower. I use pfba in a DFBA context which will
suffer from a 2x speed decrease in every timepoint.

**Comment by pstjohn** [comment]
@hredestig, that's partly what I was testing in the graph benchmarks above. You essentially add the cost of creating a stoichiometric matrix to the solution creation.
To @cdiener's point, we could just remember the objective, but then it seems like we're being choosy on what model attributes to preserve in Solution. But anything like this:
```python
solution1 = model.optimize()
solution2 = pfba(model)
with model:
    model.reactions.my_reaction.knockout()
    solution3 = model.optimize()

summary(model, solution1)
summary(model, solution2)
summary(model.metabolites.pyr_c, solution3)
```

would be OK, and wouldn't really add to the `optimize` overhead.

**Comment by pstjohn** [comment]
To @matthiaskoenig's point, I think dfba is a great example of where to not call `model.optimize` for performance reasons. We may want to have a doc page somewhere of how to use the lower-level interface?

**Comment by hredestig** [comment]
Right, I was just thinking that you don't actually have to make that matrix, just capture the pieces that are needed to make it, i.e. the metabolites and reactions lists, or a summarized form of them, which perhasp would be fast enough. Having the situation when the two objects can go out of sync and produce erroneous output seems a bit broken no? Also, I couldn't pickle the solution and go back to it at a later stage..

As a user I'd in that case probably favour `summary(model, optimization_fun)` which included a `solution = optimization_fun(model)` call. 

Overall speed hits could be avoided by including flag to indicate which type of solution to return, minimal or full.. That could perhaps even make it faster than currently as a really very minimal solution would e.g. only fetch fluxes.
