### ISSUE TITLE
Minimized Biomass flux

### ISSUE THREAD

**Issue by alvipat** [opencobra/cobrapy#522]
Hello everyone,

I'm looking for ways to minimize biomass without reaching 0 flux (dies), and maximizing another flux.
I read about pfba, but I'm not sure how to apply it in this case. Because I have tried with pfba and I get a flow of my desired substrate, but the biomass reaches 0.

```
cobra.flux_analysis.parsimonious.pfba(model, 
                                    already_irreversible=False, 
                                    fraction_of_optimum=1.0,
                                    solver=None,
                                    objective=model._MYREACTION_
                                    reactions=model.reactions)
print model.reactions.Ec_biomass.flux
print model.reactions._MYREACTION_.flux
```
0.0
10.0

with Moma, maybe?? 

I would appreciate any advice.
Thank you very much.

**Comment by pstjohn** [comment]
I just replied on the google group, but fva is probably your best bet. Otherwise, just a set a lower bound for the biomass reaction that's greater than 0 prior to running pfba.

```python
model.reactions.Ec_biomass.lower_bound = 0.1
model.objective = model.raections._MYREACTION_
model.optimize()
model.summary()
```

**Comment by hredestig** [comment]
Answered/confirmed on google group
