### ISSUE TITLE
Change bounds of a set of reactions

### ISSUE THREAD

**Issue by Andr3aCbb** [opencobra/cobrapy#527]
Hello, 

I am trying to iteratively change the bounds of the exchange reactions of my model, to match a profile that simulates the nutrient intake of a particular diet:

Here's an example:
```
for r in ex_r2:   # list of exchange reactions 
    R2.reactions.get_by_id[r] .upper_bound   
    ...........


Traceback (most recent call last):

  File "<ipython-input-52-727d79319a81>", line 2, in <module>
    print(R2.reactions.get_by_id[r])

TypeError: 'method' object is not subscriptable

```
is there any other method/function to do it? maybe I am missing something 

Ideally I was looking for something similar to the function ["changeRxnBounds"](https://opencobra.github.io/cobratoolbox/deprecated/docs/cobra/changeRxnBounds.html) included in COBRAtoolbox, which allows to input a list of reaction ID and respective bounds.

 
I am using RECON2.2 and COBRApy 0.6.1

**Comment by pstjohn** [comment]
`get_by_id` is a function, so you have to invoke it with `R2.reactions.get_by_id(r).upper_bound`. `R2.reactions[r].upper_bound` should also do what you want.

**Comment by hredestig** [comment]
..for the function corresponding to that matlab function you can use
`R2.reactions.get_by_id(r).bounds = lower, upper`

**Comment by Andr3aCbb** [comment]
I was mixing up the two notations...
Anyway that's right what I needed.

Thanks both of you!

Andrea
