### ISSUE TITLE
Remove unused functions from manipulation module

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#530]
This will be applicable when we delete the old solver interface.

Functions like `delete_model_genes` and `undelete_model_genes` are pretty much superseded by the context managers and only used by the old versions of gene deletion routines.

**Comment by stairs** [comment]
@cdiener @Midnighter I have noticed that we have Model methods for reactions and metabolites removal which are reversible but not for gene removal. Does the ticket imply that we need to implement them first?
I'm willing to work on the issue. Could you please help to define the list of such functions?

**Comment by synchon** [comment]
Any updates for this issue? Since it is added to the COBRApy version 1.0 milestone, would be nice to resolve this ASAP.

**Comment by cdiener** [comment]
@stairs is right that we are still missing Gene removal. In general the Gene module needs some love. For now I would juts remove the obvious things like `make_irreversible` etc.

**Comment by synchon** [comment]
@cdiener Do you suggest that we work on `cobra.core.Gene` and then take up this one?
@stairs Would you still like to work on this issue?

**Comment by stairs** [comment]
@cdiener Thanks for the clarification!
@synchon Yes, I'm willing to work on it, thanks!

**Comment by stairs** [comment]
@cdiener Sorry to bother you again. But it looks like all the other deprecated functions in the module were deleted by @Midnighter in https://github.com/opencobra/cobrapy/commit/34040067f28566d904f90eb97ee7de5665a9747d. Please, correct me if I'm wrong.

**Comment by Midnighter** [comment]
I wasn't sure any longer how much deprecated code we removed. If you cannot find anything then it's only the gene removal feature I suppose.

**Comment by akaviaLab** [comment]
I thought this would have been closed when #1208 was merged.
Requesting that this be closed.
