### ISSUE TITLE
Which functions of MATLAB Cobra toolbox are available or not on cobrapy?

### ISSUE THREAD

**Issue by pcm32** [opencobra/cobrapy#533]
Hi there! Thanks for all the excellent work on cobrapy! 

Is there any reference/wiki page/comparison table that shows which functionality/methods on the Matlab version are available (or not) on the python version of cobra? This might open topics for external contributions and help general users to understand whether using the python version is sufficient or not for what the want to solve.

**Comment by cdiener** [comment]
Currently there is not but it is a good idea :smile: We could put a "features" section on the [webpage](https://opencobra.github.io/cobrapy). Currently we only have a list of additional packages that you can use and that are built on top of cobrapy in the [packages section](https://opencobra.github.io/cobrapy/packages). However, we are happy to help you out on the gitter chat or the mailing list if you are looking for a particular algorithm/problem solution.

**Comment by pcm32** [comment]
Thanks @cdiener! I don't have an immediate need, I don't use COBRA often. The idea crossed my mind as I was at a workshop on MetaboTools from Maike Aurich, and I wondered whether her sampling functionalities would be available in the python port as well.

**Comment by hredestig** [comment]
It would definitely be nice to have and there even was the idea that we could tag methods based on some some simple ontology and then generate an automated overview, and make this content of the opencobra website.

**Comment by pstjohn** [comment]
If we do make an ontology we should make sure it's mirrored in cobrapy's code organization. Could be a good way to go about some housekeeping.

Something like:
```
cobra > flux analysis > pfba
... > ... > flux variability analysis

cobra > modify > knock out
cobra > stoichiometry > create stoichiometric matrix
```

**Comment by cdiener** [comment]
Closing as stale. Feel free to open a new thread in the Discussions.
