### ISSUE TITLE
Duplicated gene associations in a reaction (Previous issue #333)

### ISSUE THREAD

**Issue by ehukim** [opencobra/cobrapy#547]
Hi cobrapy team,

I found that your previous fix for the Issue #333 broke in recent releases of cobrapy: at least in 0.7.0 and 0.6.2. This problem was easy to identify as my work often involves repeated writing/reading of sbml files.

Thank you so much for your great work/support!
Hyun Uk

**Comment by Midnighter** [comment]
Thanks for reporting this again. In future we might move this from the notes field to annotations (see the somewhat long and derailed discussion in #534) with the help of some XML schema additions. Until then we'll try to fix the notes, of course. Did you discover this bug with the same model that you linked in the original issue #333?

**Comment by ehukim** [comment]
Thanks for the info. I used the same base model with a few additional set of reactions.
Thanks!
