### ISSUE TITLE
Adding constraint to model does not update constraint.problem

### ISSUE THREAD

**Issue by gregmedlock** [opencobra/cobrapy#561]
#### Problem description

Hello, I noticed some odd behavior for the constraint/variable.problem attribute after being added to a model. When a constraint or variable is retrieved from a model, .problem points to the correct model. However, if a new constraint/variable is created, then added to the model, .problem is not updated in the original variable, which seems unexpected to me.

The problem itself isn't causing issues for me, but it's a bit annoying to create a new constraint, add it to the model, then have to retrieve it from the model to make changes to it rather than just using the original variable.

#### Code Sample

```python
import cobra
import cobra.test
model = cobra.test.create_test_model("textbook")
same_flux = model.problem.Constraint(
    model.reactions.FBA.flux_expression - model.reactions.NH4t.flux_expression,
    lb=0,
    ub=0, name='same_flux')
model.add_cons_vars(same_flux)
print(same_flux.problem)
print(model.constraints.same_flux.problem)

## example of something I'd like to be able to do, which raises an error 
## because the constraint isn't in the model
same_flux.set_linear_coefficients({model.reactions.FBA.flux_expression: 2})
## how it currently needs to be done
model.constraints.same_flux.set_linear_coefficients({model.reactions.FBA.flux_expression: 2})
```

#### Actual Output
None
<optlang.glpk_interface.Model at '#memory location#'>

#### Expected Output
<optlang.glpk_interface.Model at '#memory location#'>
<optlang.glpk_interface.Model at '#memory location#'>
#### Output of `cobra.show_versions()`

<details>
System Information
==================
OS                        Linux
OS-release     4.4.0-70-generic
Python                    3.5.2

Package Versions
================
pip                       9.0.1
setuptools               34.3.0
cobra                     0.8.1
future                   0.16.0
swiglpk                   1.4.3
optlang                   1.2.1
ruamel.yaml             0.14.12
pandas                   0.20.3
numpy                    1.13.1
tabulate                  0.7.7
python-libsbml           5.13.0
lxml                      3.7.1
scipy                    0.18.1
matplotlib                2.0.0
palettable                2.1.1
pymatbridge               0.5.2

</details>

**Comment by cdiener** [comment]
This is because adding stuff in optlang is lazy. Variables and constraints are not actually added to the model until you trigger some kind of calculation. This is handled by the optlang `update` function which is called for instance before solving, getting variables or associated values etc. For instance the following gives the expected output:

```Python
In [3]: import cobra
   ...: import cobra.test
   ...: model = cobra.test.create_test_model("textbook")
   ...: same_flux = model.problem.Constraint(
   ...:     model.reactions.FBA.flux_expression - model.reactions.NH4t.flux_expression,
   ...:     lb=0,
   ...:     ub=0, name='same_flux')
   ...: model.add_cons_vars(same_flux)
   ...: model.solver.update()
   ...: same_flux.problem
   ...:     
Out[3]: <optlang.glpk_interface.Model at 0x7f8697627be0>
```

**Comment by gregmedlock** [comment]
Ahh I see. So if I do: " print(model.constraints.same_flux) " then there is some lazy loading voodoo that allows it to return the constraint before updating the model?

**Comment by cdiener** [comment]
Yes exactly, when requesting `model.constraints` optlang first checks whether there were any additions that have not been processed yet by calling `model.solver.update`. If you access the Constraint directly this does not happen. Bit weird, but that was a decision that was made in optlang...

**Comment by gregmedlock** [comment]
Interesting. Thanks for the help!
