### ISSUE TITLE
fix optlang solver search order

### ISSUE THREAD

**Issue by hredestig** [opencobra/cobrapy#562]
Currently we have search order `lp_order = ["glpk", "cplex", "gurobi"]` is there a reason for not prioritizing cplex or gurobi? If not, let's change it.

**Comment by cdiener** [comment]
For small (up to 5000 reactions) glpk is the fastest solver. Also basis recycling and modifying models is faster for glpk than cplex or gurobi. For models with 50,000+ reactions cplex and gurobi are much faster. However, there cplex memory leaks can become a problem and gurobi still has some bugs in optlang (see the issues there)...

**Comment by cdiener** [comment]
So by those data gurobi should be used if we  can fix the recursion error in optlang...

**Comment by hredestig** [comment]
Thanks for the insight! Contemplating ways to get sensible default when loading a large model, but then think this should probably be part of `cobra.io` functions instead.. Perhaps we could introduce a new function that can read any format and then also come with setting sensible default solver depending on the size of the model.

**Comment by matthiaskoenig** [comment]
Please don't change solvers depending on size of the model. All models in
one session should use the same solver if non is specified explicitely.
Otherwise this could tesult in strange effects if one works with models of
different sizes at the same time in one session.

**Comment by cdiener** [comment]
Might make sense to add a solver keyword arg to the `read_` functions... Having the same problems right now but fighting more with memory issues...

**Comment by hredestig** [comment]
Yes indeed that would be confusing, sensible defaults here is probably too complicated to be worth it. Let's indeed consider a keyword for the read functions (or for a new unified `read_model` function). Closing this, re-open if more to add.
