### ISSUE TITLE
Sampling tends towards lower end of bounds

### ISSUE THREAD

**Issue by bkamino1** [opencobra/cobrapy#570]
I am seeing a recurring issue when I try to sample my model using the built-in sampling. I am looking at several exchange reactions, and I am setting their bounds as, for instance lb = 0, ub=-.7. Consistently I am seeing the sampling results clustered around the very upper bound. I have also been able to reproduce this issue with an E. Coli model from the [UCSD BiGG database ](http://bigg.ucsd.edu/models/iJO1366). Has anyone encountered this issue before? Is it an intended effect of the sampling process? Could it be a model artifact?

Thank you for any help you can offer.

#### Code Sample
```python
import cobra
import pandas

from cobra.flux_analysis.sampling import sample

model = cobra.io.load_matlab_model("iJO1366.mat") #Load e coli model

rxn = model.reactions.get_by_id('EX_glc__D_e') #Set glucose exchange reaction bounds to test
rxn.lower_bound = -100
rxn.upper_bound = -10


sModel = sample(model, 1500, thinning=1500, processes=10)  #Sample fluxes for model with 1500 returned points and 1500 samples for each returned point. Uses 10 processes

sModel.to_excel('sample.xlsx')

```
This is a scatter plot that was generated from the above code:
![glc_flux](https://user-images.githubusercontent.com/30415057/29093546-2569e834-7c58-11e7-9dc4-ca0514990291.png)

#### Output of `cobra.show_versions()`

<details>
System Information

==================
OS                               Linux
OS-release  2.6.32-573.22.1.el6.x86_64
Python                          2.7.10

Package Versions
================
pip                              9.0.1
setuptools                      28.8.0
cobra                            0.8.0
future                          0.16.0
swiglpk                          1.4.3
optlang                          1.2.1
ruamel.yaml                    0.14.12
pandas                          0.19.2
numpy                           1.12.1
tabulate                         0.7.7
scipy                           0.19.0
matplotlib                       1.5.3

</details>

**Comment by cdiener** [comment]
Yes that is kind of expected given that your other flux bounds are much bigger. Glucose usage is anabolic so you need lots of glucose to create flux in other reactions. As such in mean you will need a lot of glucose just to activate the other fluxes mildly. Using a Ecoli model which is shipped with cobrapy I get a center for the flux space which has a flux of -99.5 for Glucose import with your bounds. The sampling algorithms are designed to give you uniform samples across all dimensions not just one.

So to realize the mean of all fluxes you need a lot of glucose import.  If I check the distribution of fluxes overall I get something like that:

``` 
count    2583.000000
mean        5.343403
std        73.417788
min      -845.331152
25%         0.000000
50%         0.023828
75%         1.837190
max       851.125888
dtype: float64
``` 

So globally most fluxes are sampled pretty well between -1000, 1000 (see min, max). So it is more a consequence of your bounds. If you set you glucose import bounds to -10000, 0 for instance you already get a much wider distribution.

```
count    1002.000000
mean     -863.707096
std        67.429368
min     -1378.836109
25%      -884.982982
50%      -856.967544
75%      -819.566432
max      -767.919080
Name: EX_glc_e, dtype: float64
```

**Comment by cdiener** [comment]
Hi @bkamino1, did that help you? I also recommend to update to 0.8.1 since it fixes some issues with sampling :)

**Comment by bkamino1** [comment]
Hi, thanks so much for the response! I updated cobra and I'm still seeing similar results, but I'm going to do some more investigating into my model.

**Comment by cdiener** [comment]
Hi, I will close that for now. Feel free to reopen if you disagree.
