### ISSUE TITLE
Source distribution contains old core module names

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#571]
#### Problem description

The new tarball that we [distribute on PyPi](https://pypi.python.org/pypi/cobra#downloads) somehow ended up with the old capitalized core modules. I really have no idea how that happened but you can easily confirm this by inspecting the archive.

Maybe it is a mix of very old cached files and updated newer ones? I can try to investigate tomorrow.

**Comment by hredestig** [comment]
Found the issue and deleted that source file, will be fixed by making new release

**Comment by hredestig** [comment]
Fixed in 0.8.2
