### ISSUE TITLE
Model.compartments doesn't reflect additions of reactions with novel compartments

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/cobrapy#574]
#### Problem description
* **what** I tried to achieve:
Adding new compartments to a model by just adding reactions with metabolites in those new compartments.

* **why** the current behaviour is a problem:
When using cobrapy for model reconstruction I'd expect the attributes of the model object to always be up-to-date with changes and reflect the contents of the model accurately.

`model.get_metabolite_compartments()` works as a workaround, but having to manually update the `model.compartments` attribute seems to contradict the behaviour of cobrapy, especially since `model.reactions.SOME_REACTION.compartments` updates when accessed:

```python
    def compartments(self):
        """lists compartments the metabolites are in"""
        if self._compartments is None:
            self._compartments = {met.compartment for met in self._metabolites
                                  if met.compartment is not None}
        return self._compartments
```

#### Code Sample
```python
from cobra import Reaction, Metabolite, Model
model = Model("test","test")
met_a = Metabolite("a_c", compartment="c")
met_b = Metabolite("a_p", compartment="p")
met_c = Metabolite("a_e", compartment="e")
rxn_a_b = Reaction("AB")
rxn_a_b.add_metabolites({met_a: 1,
                         met_b: -1})
rxn_b_c = Reaction("BC")
rxn_b_c.add_metabolites({met_b: 1,
                         met_c: -1})
model.add_reactions([rxn_b_c, rxn_a_b])
print (model.compartments)
```

#### Actual Output
{}
#### Expected Output
{'c': 'cytosol', 'e': 'extracellular space', 'p': 'periplasm'}
#### Output of `cobra.show_versions()`

<details>

System Information
==================
OS              Darwin
OS-release      16.7.0
Python          2.7.10

Package Versions
================
pip              9.0.1
setuptools      34.3.2
cobra            0.8.1
future          0.16.0
swiglpk          1.4.3
optlang          1.2.1
ruamel.yaml    0.14.11
pandas          0.20.1
numpy           1.12.1
tabulate         0.7.7
python-libsbml  5.13.0
scipy           0.18.1
palettable       2.1.1

</details>

**Comment by cdiener** [comment]
I agree that this is a bug. Looking at the code I suspect that also extends to reactions. If you add a metabolite to an already existing reaction it looks like it's not updated either. I would suggest that that all `compartment` attributes should just generate the list of compartments from the respective metabolites on request. For huge models this might be slow but I don't think that is too much of an issue.
