### ISSUE TITLE
use pandas context manager to set maximum display rows on repr_html

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#577]
For even small models, the solution `repr_html` takes up a ton of screen real estate. I would vote that we use something like [this](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.option_context.html) to truncate the display without messing with the user's global options state.

https://github.com/opencobra/cobrapy/blob/7629980105bfd554f1f048a370c1ce383b1ee189/cobra/core/solution.py#L90-L98

Thoughts? Maximum number of lines to display? I was thinking ~10

**Comment by hredestig** [comment]
didn't know about that one, good idea!
