### ISSUE TITLE
Reaction sorting to/from JSON is unintuitive

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#579]
How do we feel about this behavior? I for one wasn't expecting it, but I'm not sure what the best approach to fixing it would be. Do we always keep the DictLists sorted? Or do we respect order when saving the JSON files?

```
model = cobra.test.create_test_model('ecoli')
N1 = cobra.util.create_stoichiometric_matrix(model)
model.reactions[:5]

[<Reaction DM_4CRSOL at 0x12670b198>,
 <Reaction DM_5DRIB at 0x12670b1d0>,
 <Reaction DM_AACALD at 0x12670b208>,
 <Reaction DM_AMOB at 0x12670b278>,
 <Reaction DM_MTHTHF at 0x12670b2b0>]
```

The original model reactions are not sorted, but when we save/load from a JSON they are shuffled to be alphabetical.

```
cobra.io.save_json_model(model, 'test.json')

model2 = cobra.io.load_json_model('test.json')
N2 = cobra.util.create_stoichiometric_matrix(model2)
model2.reactions[:5]

[<Reaction 12DGR120tipp at 0x111ab7e10>,
 <Reaction 12DGR140tipp at 0x111ab7e48>,
 <Reaction 12DGR141tipp at 0x111ab7e80>,
 <Reaction 12DGR160tipp at 0x111ab7eb8>,
 <Reaction 12DGR161tipp at 0x111ab7ef0>]
```

It might matter in other places, but for me specifically I was burned when trying to do operations with the stoichiometric matrices.

```
import numpy as np
np.allclose(N1, N2)

False
```

<details>

System Information
==================
OS                          Darwin
OS-release                  15.6.0
Python                       3.6.1

Package Versions
================
pip                          9.0.1
setuptools     33.1.1.post20170320
cobra                        0.8.2
future                      0.16.0
swiglpk                      1.4.3
optlang                      1.2.1
ruamel.yaml                0.14.11
pandas                      0.20.2
numpy                       1.12.1
tabulate                     0.7.7
python-libsbml              5.15.0
scipy                       0.19.0
matplotlib                   2.0.0
</details>

**Comment by Midnighter** [comment]
So I'm not sure what your expected behavior is. Both the YAML and JSON outputs currently depend on the same ordered dictionary structure which is sorted. I needed that in [memote]() because I needed the order to be deterministic. Of course, when you read in the same XML file you can expect the same order but round tripping XML is actually not guaranteed to have the same order.

So can you sort the `DictList` in your application (which seems much more safe to me anyway) or should we sort on model construction? What's your suggestion?

**Comment by pstjohn** [comment]
I suppose its a general question of whether or not the reactions (and metabolites) in a cobra model have a defined order. That's a larger question to which I don't necessarily have the answer. But it should be yes or no.

If yes:
* json / xml / yaml outputs should respect the order of the reactions, which should still be deterministic. Are you implying that writing xml can shuffle the reactions? Is that a limitation that could be worked around?

If no:
* we should abandon (or change) the dictlist structure to explicitly indicate that these are unordered objects. Maybe inherit from `set` instead of `list`. 
* when a reaction order is needed, we sort alphabetically. So for the use case above, the metabolites and reactions would be sorted when we call `cobra.util.create_stoichiometric_matrix`. For `json` and or `yaml` outputs, they'd also get sorted alphabetically.

**Comment by Midnighter** [comment]
> Are you implying that writing xml can shuffle the reactions?

Reading a model and then writing it again to xml can definitely shuffle the order.

> Is that a limitation that could be worked around?

Possibly, I would have to look at the SBML IO which @cdiener encourages me to do  anyway :stuck_out_tongue: 

> dictlist structure to explicitly indicate that these are unordered objects

I obviously don't have numbers on it but that sounds like a change that would cause unexpected behavior with a lot of existing code.

> So for the use case above, the metabolites and reactions would be sorted

That's the current behavior for JSON and YAML (or really the underlying dictionary structure ). To me it makes sense to also sort the stoichiometric matrix that way.

From `model_to_dict`:

```python
    obj = OrderedDict()
    obj["reactions"] = sorted(
        (reaction_to_dict(reaction) for reaction in model.reactions),
        key=itemgetter("id"))
    obj["metabolites"] = sorted(
        (metabolite_to_dict(metabolite) for metabolite in model.metabolites),
        key=itemgetter("id"))
    obj["genes"] = sorted(
        (gene_to_dict(gene) for gene in model.genes), key=itemgetter("id"))
```

**Comment by pstjohn** [comment]
I could certainly sort them in `create_stoichiometric_matrix`, but I do think we should either support reaction/metabolite ordering or make them explicitly unordered objects.

In terms of unexpected behavior w/ existing code, I'll look into it. But I partly think that if code is *assuming* an ordered object, then its likely we'll see inconsistencies after saving / loading the model.

**Comment by pstjohn** [comment]
A quick look at the places we use `reactions[` in cobrapy seems to indicate that it happens most in the test methods, or when we iterate over the reactions. Those places we iterate over reactions could certainly be replaced with a different method if we choose to have a `dictlist` behave more like a `dict` than a `list`. 

But we could certainly also have the json/yaml outputs respect the order from the cobra model. I just think that might require some extra saved arguments (i.e., index), since I don't think yaml/json explicitly respect the ordering of key-value pairs.

(The way I've always handled version-control of cobrapy jsons was using `jq`, which pretty-prints and sorts all the fields):
```bash
#!/bin/bash

for file in "$@"
do
        jq . -S <"$file" >"$file"_t
        mv "$file"_t "$file"
done
```

<details>

```
cobra/core/arraybasedmodel.py:        """convert from model.reactions = v to model.reactions[:] = v"""
cobra/core/arraybasedmodel.py:            reaction = self._model.reactions[index[1]]
cobra/core/arraybasedmodel.py:            reactions = [self._model.reactions[index[1]]]
cobra/core/arraybasedmodel.py:            reactions = self._model.reactions[index[1]]
cobra/core/model.py:                reaction = self.reactions[self.reactions.index(reaction)]
cobra/flux_analysis/deletion_worker.py:        reaction = model.reactions[i]
cobra/flux_analysis/double_deletion.py:    row_ids = [cobra_model.reactions[i].id for i in reaction_indexes1]
cobra/flux_analysis/double_deletion.py:    column_ids = [cobra_model.reactions[i].id for i in reaction_indexes2]
cobra/flux_analysis/loopless.py:        rxn = model.reactions[i]
cobra/flux_analysis/loopless.py:                 "delta_g_" + model.reactions[ridx].id]: row[i]
cobra/flux_analysis/loopless.py:    for reaction in model.reactions[:]:
cobra/flux_analysis/moma.py:        mutant_reaction = moma_model.reactions[i]
cobra/flux_analysis/moma.py:        mutant_reaction = moma_model.reactions[i]
cobra/flux_analysis/moma.py:        wt_reaction = moma_model.reactions[n + i]
cobra/flux_analysis/phenotype_phase_plane.py:    reaction1 = model.reactions[index1]
cobra/flux_analysis/phenotype_phase_plane.py:    reaction2 = model.reactions[index2]
cobra/flux_analysis/phenotype_phase_plane.py:    metabolite1_name = list(model.reactions[index1]._metabolites)[0].id
cobra/flux_analysis/phenotype_phase_plane.py:    metabolite2_name = list(model.reactions[index2]._metabolites)[0].id
cobra/flux_analysis/phenotype_phase_plane.py:        carbon_io = c_input, objective_reactions[0]
cobra/flux_analysis/reaction.py:            demand_reactions[demand] = (component, coeff)
cobra/io/mat.py:        model.reactions[j].add_metabolites({model.metabolites[i]: v})
cobra/manipulation/delete.py:    cobra_model.reactions[:].gene_reaction_rule
cobra/manipulation/delete.py:        cobra_model._trimmed_reactions[the_reaction] = (old_lower_bound,
cobra/test/test_flux_analysis.py:                  reaction_list=large_model.reactions[1::3])
cobra/test/test_flux_analysis.py:                  solver=solver, reaction_list=model.reactions[1::3])
cobra/test/test_flux_analysis.py:                reaction_list=model.reactions[1::3])
cobra/test/test_flux_analysis.py:        result = find_blocked_reactions(model, model.reactions[40:46])
cobra/test/test_flux_analysis.py:        result = find_blocked_reactions(model, model.reactions[40:46],
cobra/test/test_flux_analysis.py:        result = find_blocked_reactions(model, model.reactions[42:48],
cobra/test/test_flux_analysis.py:        result = find_blocked_reactions(model, model.reactions[30:50],
cobra/test/test_io.py:            assert getattr(model1.reactions[0], attr) == getattr(
cobra/test/test_io.py:                model2.reactions[0], attr)
cobra/test/test_io.py:            assert getattr(model1.reactions[5], attr) == getattr(
cobra/test/test_io.py:                model2.reactions[5], attr)
cobra/test/test_io.py:            assert getattr(model1.reactions[-1], attr) == getattr(
cobra/test/test_io.py:                model2.reactions[-1], attr)
cobra/test/test_io.py:        assert len(model1.reactions[0].metabolites) == len(
cobra/test/test_io.py:            model2.reactions[0].metabolites)
cobra/test/test_io.py:        assert len(model1.reactions[8].metabolites) == len(
cobra/test/test_io.py:            model2.reactions[8].metabolites)
cobra/test/test_io.py:        assert len(model1.reactions[-1].metabolites) == len(
cobra/test/test_io.py:            model2.reactions[-1].metabolites)
cobra/test/test_io.py:        assert model2.reactions[0]._model is model2
cobra/test/test_io.py:        assert model1.reactions[4].annotation == model2.reactions[4].annotation
cobra/test/test_model.py:        assert '<table>' in model.reactions[0]._repr_html_()
cobra/test/test_model.py:            model.remove_reactions(model.reactions[:1])
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.remove_reactions(model.reactions[:1],
cobra/test/test_model.py:            model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        removed_reaction = model.reactions[0]
cobra/test/test_model.py:        model.reactions[0].remove_from_model(remove_orphans=False)
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[0].remove_from_model(remove_orphans=True)
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[1].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[0].remove_from_model(remove_orphans=False)
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:            model.reactions[0].delete(remove_orphans=False)
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[0].delete(remove_orphans=True)
cobra/test/test_model.py:        model.reactions[0].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[1].add_metabolites({tmp_metabolite: 1})
cobra/test/test_model.py:        model.reactions[0].delete(remove_orphans=False)
cobra/test/test_model.py:        model_copy.remove_reactions(model_copy.reactions[0:5])
cobra/test/test_model.py:        bounds0 = model.reactions[0].bounds
cobra/test/test_model.py:            model.reactions[0].bounds = bounds1
cobra/test/test_model.py:                model.reactions[0].bounds = bounds2
cobra/test/test_model.py:                assert model.reactions[0].bounds == bounds2
cobra/test/test_model.py:            assert model.reactions[0].bounds == bounds1
cobra/test/test_model.py:        assert model.reactions[0].bounds == bounds0
cobra/test/test_model.py:            assert array_model.reactions[0]._metabolites[
cobra/test/test_model.py:            assert array_model.lower_bounds[0] == array_model.reactions[
cobra/test/test_model.py:            assert array_model.lower_bounds[5] == array_model.reactions[
cobra/test/test_model.py:            assert array_model.upper_bounds[0] == array_model.reactions[
cobra/test/test_model.py:            assert array_model.upper_bounds[5] == array_model.reactions[
cobra/test/test_model.py:            assert array_model.reactions[6].lower_bound == 2
cobra/test/test_model.py:            assert array_model.reactions[2].lower_bound == -1
cobra/test/test_model.py:            assert array_model.reactions[2].objective_coefficient == 1
cobra/test/test_model.py:            array_model.remove_reactions([array_model.reactions[2]],
cobra/test/test_solver_model.py:        assert model.reactions[0].__str__().startswith('ACALD')
cobra/test/test_solver_model.py:        assert model.reactions[-2] == r1
cobra/test/test_solver_model.py:        assert model.reactions[-1] == r2
cobra/test/test_solver_model.py:        assert isinstance(model.reactions[-2].reverse_variable,
cobra/test/test_solver_model.py:        reactions_to_remove = model.reactions[10:30]
documentation_builder/constraints_objectives.ipynb:    "for reaction in model.reactions[:5]:\n",
documentation_builder/deletions.ipynb:    "single_reaction_deletion(cobra_model, cobra_model.reactions[:20])"
documentation_builder/deletions.ipynb:    "    cobra_model, cobra_model.reactions[2:7], return_frame=True).round(4)"
documentation_builder/getting_started.ipynb:    "model.reactions[29]"
documentation_builder/getting_started.ipynb:    "for reaction in model.reactions[:5]:\n",
documentation_builder/getting_started.ipynb:    "[reaction.bounds for reaction in model.reactions[:5]]"
documentation_builder/simulating.ipynb:    "flux_variability_analysis(model, model.reactions[:10])"
documentation_builder/simulating.ipynb:    "    model, model.reactions[:10], fraction_of_optimum=0.9)"
```

</details>

**Comment by Midnighter** [comment]
I'd like to push this issue a bit and I've made a test module which you can find in [this PR]() which should eventually contain all the necessary changes.

As you will see from the test run (`pytest cobra/tests/test_io_order.py -v --tb=no`):
* for 'minimized_core' (unordered) and the sorted model 'minimized_sorted' all `io` functions correctly round trip metabolites and reactions
* for 'minimized_reversed' JSON and YAML fail since they do their own sorting
* legacy SBML and Matlab fail to round trip genes completely
* JSON and YAML fail with the unordered or reversed genes

I honestly don't care much about the legacy SBML io but I would like to find out why the Matlab io fails. My suggestion is thus: Do not sort JSON and YAML order of metabolites, reactions, and genes but **do** sort alphabetically the order of their attributes such that proper diffs can be created. What do you think @pstjohn?

**Comment by pstjohn** [comment]
So another concern is that we're abusing the JSON spec a bit by requiring the ordering to be consistent: "An object is an unordered set of name/value pairs". So we might just be getting lucky that our json parsers preserve the order of the attributes.

Also, how is io working for both the unordered and sorted io functions? Is the unordered one sorted by default?

And do we definitely feel that reactions need an inherent order? I'm feeling less and less that we do, especially since we already forbid duplicate IDs.

**Comment by Midnighter** [comment]
> So another concern is that we're abusing the JSON spec a bit by requiring the ordering to be consistent: "An object is an unordered set of name/value pairs". So we might just be getting lucky that our json parsers preserve the order of the attributes.

The model is an object whereas metabolites, reactions, and genes are arrays of objects. So their ordering is deterministic.

> Also, how is io working for both the unordered and sorted io functions? Is the unordered one sorted by default?

The honest answer is, I don't know :stuck_out_tongue: something to look into for me.

> And do we definitely feel that reactions need an inherent order? I'm feeling less and less that we do, especially since we already forbid duplicate IDs.

I'm probably biased since I have that need in memote where I want to be able to output the model with as few changes as possible such that diffs are minimal. I know you mentioned `jq` but I think that it should be possible from within cobrapy. I don't mind that being a keyword argument.

I also think it's a nice property to read in a file, write it again, and end up with the same file exactly.

**Comment by pstjohn** [comment]
Oh ok, cool. If JSON supports it then I'm fine keeping reaction ordering.

If we did want an unordered model, for memote (or `create_stoichiometric_matrix`, or anything else that requires an ordering), I would have sorted the reactions by id's on the spot to make sure things are deterministic.

Come to think of it, why do we have a `DictList` when `OrderedDict` is in `collections`? 🤔 

On the test model, it looks like everything is sorted *except* `'EX_h_e', 'EX_h2o_e'` are flipped. So as long as you don't grab both of those reactions, you should pass :).

**Comment by Midnighter** [comment]
> Come to think of it, why do we have a DictList when OrderedDict is in collections?

It has some other niceties like `get_by_id`, `get_by_any`, or `query` and checks membership both by `id` attribute as well as object. It could very well inherit from `OrderedDict`, though.

I would have though that `random.sample` selects random elements in any order. If that's not the case then I'll shuffle it.

**Comment by Midnighter** [comment]
Ah, the selection is random but then I only remove the other reactions from the model, of course...

**Comment by Midnighter** [comment]
Alright, I'm excluding boundary reactions now and I'm adding the randomly selected reactions  to a new model. So unless you're really unlucky, the tests show the expected pass/fail pattern. In a next step I will alter the dict, JSON, and YAML io so that the tests pass.
