### ISSUE TITLE
Allow multiple carbon sources in production envelope?

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#583]
I have not deeply inspected the code but is there anything speaking against also computing yields from multiple carbon sources?

**Comment by hredestig** [comment]
I don't see why not, seems like a straight-forward adjustment

**Comment by joaocardoso** [comment]
@Midnighter: we should do that. Media with multiple carbon sources and pathway feeding are examples of when all carbon sources should be accounted for.

**Comment by hredestig** [comment]
closed with https://github.com/opencobra/cobrapy/pull/587
