### ISSUE TITLE
I want to set the solver without using the model context or providing my own context

### ISSUE THREAD

**Issue by joaocardoso** [opencobra/cobrapy#584]
#### Problem description
Hi. 

Please have a look at the following line:
https://github.com/opencobra/cobrapy/blob/devel/cobra/util/solver.py#L96

Please explain:
* **what** you tried to achieve:
I want to use my own context manager even when setting the model objective without having to implement the conversation in the `set_objective`.

I can do `model.solver.add` for variables and constraints.
I cannot do `model.objective = new_objective` without bypassing the context manager without workarounds.

* **how** you went about it (referring to the code sample), and
The solution would be to add a `context` to the `set_objective` like this:
`def set_objective(model, value, additive=False, context=None):`

and then in https://github.com/opencobra/cobrapy/blob/devel/cobra/util/solver.py#L156

`context = context | get_context(model)`

* **why** the current behaviour is a problem and what output
  you expected instead.

Because if I am using a custom context manager will be in conflict with model context manager.

**Comment by pstjohn** [comment]
Can you give an example of what you're trying to do with a custom context manager?

Did you inherit from `cobra.model` and redefine the `__enter__` and `__exit__` methods? `get_context` shouldn't necessarily interfere with your own methods, its just checking the `model._contexts` stack. But maybe `get_context` should be a class method or property of `cobra.model`: That way you could inherit from `cobra.model` and redefine the complete context management chain. A use case would definitely make these more obvious.

My concern with your suggestion is that you'd really want all these different operations to have a similar interface. So we'd have a context kwarg for all the solver util methods, maybe also setting reaction bounds, adding/removing metabolites, etc.

Part of the motivation for context managers over the `cameo`-inspired `TimeMachine` class was that a user wouldn't have to carry around their own history and pass it to the desired methods. Everything should get handled under the hood.

**Comment by cdiener** [comment]
If you set the objective in optlang doing `model.solver.objective = ...` the cobrapy context manager will not see that and you can manage it by yourself.

**Comment by Midnighter** [comment]
Closing for now. Please re-open if this is something we should pursue.
