### ISSUE TITLE
calculate_phenotype_phase_plane cannot handle positive exchange bounds

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#585]
#### Problem description

I tried to play with the ecYeast7 model that has manually split reactions into their forward and reverse components. When I try to `calculate_phenotype_phase_plane` I get wrong results since the upper bound of the reverse exchange reaction should be adjusted and not the lower bound.

Adjusting the lower bound of the forward exchange would break the model logic I'm afraid.

**Comment by hredestig** [comment]
Actually `calculate_phenotype_phase_plane` is deprecated, use `production_envelope` instead, which takes that into account.
