### ISSUE TITLE
Create a Summary class

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#586]
I suggest creating a `Summary` class that is instantiated and returned by `Model.summary`, `Reaction.summary`, and `Metabolite.summary`.

Primary benefits:
* A class instance can have multiple representation methods, e.g., `__repr__` and `_repr_html_`.
* The information of the summary is not merely displayed but can be made accessible via a `to_frame` method, for example.

I don't see any downside other than having to fiddle with preferably the same class being returned by all three summary methods. If that doesn't work out they should be subclasses.

**Comment by pstjohn** [comment]
certainly not a bad idea. a lot of the code in that summary class is pretty hacked together as well, so I'm sure it could get cleaned up in the process. 

I will say that not *everything* needs to be an html table in __repr_html__ :). but if they make the summary methods clearer that's fine. I think `tabulate` even supports converting to an html table as well.

**Comment by joaocardoso** [comment]
It is a great idea. A few suggestions:
1 - make references to the metabolites being imported (so one can filter, for ex., substrates with carbon)
2 - one should be able to get in_fluxes, out_fluxes, growth_rate (which might not be the objective_value) and objective_value

One more question: should the summary be attached to a Solution or to the Model?

Cheers

**Comment by synchon** [comment]
Any new thoughts on this? I can take up this issue if no one is working on it currently. :)

**Comment by matthiaskoenig** [comment]
I like the idea. Not much else to say. Please go for it.
