### ISSUE TITLE
write_sbml_model() stores metabolite charges as floats instead of ints

### ISSUE THREAD

**Issue by mmundy42** [opencobra/cobrapy#591]
#### Problem description

Please explain:
* **what** I wrote a model to a SBML format file and then read the SBML file back (round trip). When the metabolites in the model have charges that are floats, the SBML file has the charge as a float and an exception is raised when reading the SBML file. Note that cobra.core.Metabolite defines the charge attribute as a float.
* **why** I expected cobra.io.write_sbml_model() to generate a SBML file that can be read by cobra.io.read_sbml_model().

One possible fix is to change line 486 of cobra.io.sbml3 to:

```python
set_attrib(species, "fbc:charge", int(met.charge))
```

but I'm not sure how that would impact the changes discussed in #534.

#### Code Sample

```python
import cobra
from cobra.test import create_test_model
model1 = create_test_model('textbook')
model1.metabolites[0].charge = -4.0
cobra.io.write_sbml_model(model1, 'textbook.sbml')
model2 = cobra.io.read_sbml_model('textbook.sbml')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cobra/io/sbml3.py", line 586, in read_sbml_model
    "Something went wrong reading the model. You can get a detailed "
CobraSBMLError: Something went wrong reading the model. You can get a detailed report using the `cobra.io.sbml3.validate_sbml_model` function or using the online validator at http://sbml.org/validator
cobra.io.sbml3.validate_sbml_model('textbook.sbml')
(None, {'validator': [], 'other': ["invalid literal for int() with base 10: '-4.0'"], 'SBML errors': [], 'warnings': []})
```

#### Actual Output

read_sbml_model() raises a CobraSBMLError exception.

#### Expected Output

read_sbml_model() returns success when reading a SBML file created by write_sbml_model().

#### Output of `cobra.show_versions()`

<details>
System Information
==================
OS              Darwin
OS-release      16.7.0
Python          2.7.13
Package Versions
================
pip              9.0.1
setuptools      36.2.6
cobra            0.8.2
future          0.16.0
swiglpk          1.4.4
optlang          1.2.2
ruamel.yaml    0.14.12
pandas          0.20.3
numpy           1.13.1
tabulate         0.7.7
python-libsbml  5.13.0
lxml             3.8.0
scipy           0.19.1
matplotlib       2.0.2
</details>

**Comment by cdiener** [comment]
Since SBML with FBC only allows int charges the suggested fix makes sense to me. Should also create an entry in the logger.

**Comment by matthiaskoenig** [comment]
With the planned fbc v3 the charges are probably relaxed to floats. Personally I don't see a problem with floats for charges in cobrapy. Only point where it matters is in calculating charge balance, where one needs a correct double comparison between values. And for the SBML export, i.e. when writing either fbc-v2 (casting to int) or fbc-v3 to come (casting to double).

**Comment by matthiaskoenig** [comment]
This is fixed in the new libsbml parser. Please reopen this issue with example if problems persist.
