### ISSUE TITLE
Implement model reduction

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#592]
I think this would be an awesome addition to the cobrapy package. Specifically if we ever get to #293 we'll probably want something to reversibly compress / expand cobra models.

@jlerman44, hopefully you don't mind me sharing your [gist](https://gist.github.com/jlerman44/f795cb6de8872edab7c07b5be4e761e6) from the gitter.

**Comment by cdiener** [comment]
Yes definitely. I would be particularly interested in reductions that:

- maintain all original imports/exports
- maintain the objective

so basically all internal reactions can be lumped as long as those requirements are kept.

**Comment by Midnighter** [comment]
In a far future we should get redGEM and lumpGEM from Hatzimanikati's lab in Python but this is a good start indeed!

**Comment by pstjohn** [comment]
So I think there's probably two applications here. If you look at what they do in [EFMtool](http://intra.csb.ethz.ch/javadoc/metabolic/), they compress the model's stoichiometric matrix so that you can calculate EFMs on the reduced model, and then easily rescale them back to the full model:

> The `compress(ReadableBigIntegerRationalMatrix, boolean[], String[], String[], Set)` method uses mainly the stoichiometric matrix and reaction reversibilities as input, and returns 3 matrices pre, post and cmp, such that `pre * stoich * post == cmp`. Fba and flux analysis methods can be performed on the compressed matrix. Resulting flux vectors such as elementary modes can easily be mapped back to the original network.

Then they uncompress with 
```
       pre * stoich * post * efmc = 0
             stoich * efm         = 0
                              efm = post * efmc
```

If we can do FBA/FVA on the compressed model too, I wonder how much of our existing algorithms we could speed up with a pre/post processing compression step. 

But yeah, `redGEM` and `lumpGEM` certainly seem interesting as well. but that seems more like a modeling technique and less of a numerical method, which might indicate it would live better outside the core `cobrapy` package?

**Comment by sulheim** [comment]
If anyone else comes across this issue - it seems like both redGEM and lumpGEM are implemented in the pyTFA pacakge: https://github.com/EPFL-LCSB/pytfa (see e.g. tutorials)
