### ISSUE TITLE
model.summary()  returns error after optimizing an exchange(or sink) reaction

### ISSUE THREAD

**Issue by Andr3aCbb** [opencobra/cobrapy#593]
Hi all, 

After setting an exchange reaction as objective, I call model.optimize(). 
But when I call model.summary() , it returns this error, instead of the usual summary() output:
```python

# my code
model.objective = 'an exchange reaction' 
model.optimize()
model.summary()

Traceback (most recent call last):

  File "<ipython-input-394-9a7881f870d4>", line 1, in <module>
    model.summary()

  File "/usr/local/lib/python3.5/dist-packages/cobra/core/model.py", line 970, in summary
    fva=fva, floatfmt=floatfmt)

  File "/usr/local/lib/python3.5/dist-packages/cobra/flux_analysis/summary.py", line 157, in model_summary
    index=['flux']).T

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 275, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 411, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 5501, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 5800, in _homogenize
    v = v.reindex(index, copy=False)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/series.py", line 2426, in reindex
    return super(Series, self).reindex(index=index, **kwargs)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2515, in reindex
    fill_value, copy).__finalize__(self)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2533, in _reindex_axes
    copy=copy, allow_dups=False)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 2627, in _reindex_with_indexers
    copy=copy)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)

  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 2836, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")

ValueError: cannot reindex from a duplicate axis
```
I am using Recon 2.2. 

<details>

System Information
==================
OS                        Linux
OS-release 4.8.7-040807-generic
Python                    3.5.2

Package Versions
================
alabaster==0.7.10
altair==1.2.0
appdirs==1.4.3
apturl==0.5.2
asn1crypto==0.22.0
astroid==1.5.3
Babel==2.5.0
beautifulsoup4==4.6.0
biomart==0.9.2
biopython==1.70
bioservices==1.4.17
bleach==2.0.0
blinker==1.4
Brlapi==0.6.4
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
checkbox-support==0.34.0
chrome-gnome-shell==0.0.0
cobra==0.8.2
cobrababel==0.1.3
colorama==0.3.9
command-not-found==0.3
corda==0.3.4
cryptography==2.0.3
csscompressor==0.9.4
cycler==0.10.0
d3flux==0.1.4
decorator==4.1.2
defer==1.0.6
docutils==0.14
easydev==0.9.35
entrypoints==0.2.3
feedparser==5.2.1
framed==0.3.5
future==0.16.0
fuzzywuzzy==0.15.1
GEOparse==1.0.1
gevent==1.2.2
greenlet==0.4.12
grequests==0.3.0
guacamole==0.9.2
html5lib==0.999999999
httplib2==0.10.3
idna==2.6
imagesize==0.7.1
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==7.0.0
isort==4.2.15
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
language-selector==0.1
lazy-object-proxy==1.3.1
louis==2.6.4
lxml==3.8.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.0.2
matplotlib-venn==0.11.5
mccabe==0.6.1
meneco==1.5.2
mistune==0.7.4
mpmath==0.19
nbconvert==5.3.1
nbformat==4.4.0
networkx==1.11
notebook==5.0.0
numpy==1.13.1
numpydoc==0.7.0
oauthlib==2.0.3
olefile==0.44
onboard==1.2.0
optlang==1.2.2
padme==1.1.1
pandas==0.20.3
pandocfilters==1.4.2
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
plainbox==0.35.0
prompt-toolkit==1.0.15
psamm==0.31
psutil==5.3.1
ptyprocess==0.5.2
pyasn1==0.3.4
pyasp==1.4.3
pybiomart==0.2.0
pycodestyle==2.3.1
pycparser==2.18
pycups==1.9.73
pycurl==7.43.0
pyflakes==1.6.0
Pygments==2.2.0
pygobject==3.20.0
PyJWT==1.5.3
pylint==1.7.2
PyOpenGL==3.1.0
pyparsing==2.2.0
PyQt5==5.9
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.30
python-igraph==0.7.1.post6
python-Levenshtein==0.12.0
python-libsbml==5.15.0
python-libsbml-experimental==5.15.2
python-systemd==231
pytz==2017.2
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
reportlab==3.4.0
requests==2.18.4
requests-cache==0.4.13
rope==0.10.7
rope-py3k==0.9.4.post1
ruamel.yaml==0.15.33
scikit-learn==0.19.0
scipy==0.19.1
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
simplegeneric==0.8.1
sip==4.19.3
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
ssh-import-id==5.6
sshuttle==0.78.3
suds-jurko==0.6
swiglpk==1.4.4
sympy==1.1.1
system-service==0.3
tabulate==0.7.7
terminado==0.6
testpath==0.3.1
thonny==2.1.11
tornado==4.5.2
traitlets==4.3.2
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
uniprot==1.3
uniprot-tools==0.4.1
urllib3==1.22
usb-creator==0.3.0
vega==0.5.0
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
wgetter==0.7
widgetsnbextension==3.0.2
wrapt==1.10.11
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.9.9
xmltodict==0.11.0
</details>

**Comment by pstjohn** [comment]
Thanks for reporting this! A fix should be incoming.
