### ISSUE TITLE
objective_value not set properly in Solution produced with pfba()

### ISSUE THREAD

**Issue by mvacher** [opencobra/cobrapy#597]
#### Problem description

Hi,
I just noticed that the Solution.objective_value and Solution.fluxes[objective_id] differ in pfba.
See snippet below that replicate the problem.

#### Code Sample

```
import cobra
import cobra.test
model = cobra.test.create_test_model("textbook")
objective_id = 'Biomass_Ecoli_core'
model.objective = objective_id

fba_solution = model.optimize()
pfba_solution = cobra.flux_analysis.pfba(model)

print(fba_solution.objective_value)
print(fba_solution.objective_value == fba_solution[objective_id])

print(pfba_solution.objective_value)
print(pfba_solution.objective_value == pfba_solution.fluxes[objective_id])
print(pfba_solution.fluxes[objective_id])

#ps:  not sure exactly why, but it seems the pfba_solution.objective_value returned corresponds to the sum of the absolute flux values.
print(pfba_solution.fluxes.abs().sum())
```

#### Output of `cobra.show_versions()`

<details>
System Information
==================
OS              Darwin
OS-release      13.4.0
Python           3.5.2

Package Versions
================
pip              9.0.1
setuptools      27.2.0
cobra            0.8.2
future          0.16.0
swiglpk          1.4.4
optlang          1.2.3
ruamel.yaml    0.14.12
pandas          0.20.3
numpy           1.13.1
tabulate         0.7.7
python-libsbml  5.13.0
lxml             3.7.2
scipy           0.18.1
matplotlib       1.5.1
</details>

Thanks!

**Comment by hredestig** [comment]
Hi, this is actually expected as the objective for pfba is to minimize the total sum of fluxes while constraining the original objective, e.g. biomass production, at some lower bound. So what you are getting in the objective is that lower sum of all fluxes, not the flux of your original objective. Hope that answers your question, see also https://github.com/opencobra/cobrapy/issues/518 for further details.

**Comment by mvacher** [comment]
Hi, 
sorry I completely missed #518, everything is working fine then.
Thank you very much for pointing to the right direction.
