### ISSUE TITLE
Failure to open Recon1

### ISSUE THREAD

**Issue by WuyangFF95** [opencobra/cobrapy#602]
#### Problem description

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

I tried to open Recon1.xml model on my machine. My CobraPy is installed on an Anaconda Platform. But the opening attempt failed.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
import cobra

import cobra.test

from os.path import join

model = cobra.io.read_sbml_model(join(data_dir,"recon\\Recon1_fromSuhas.xml"))

```

#### Actual Output
Traceback (most recent call last):
"""
  File "<ipython-input-4-ab9102c202e6>", line 1, in <module>
    model = cobra.io.read_sbml_model(join(data_dir,"recon\\Recon1_fromSuhas.xml"))

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\io\sbml3.py", line 581, in read_sbml_model
    return read_sbml2(filename, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\io\sbml.py", line 329, in create_cobra_model_from_sbml_file
    k, v = the_item.split(':')

ValueError: too many values to unpack (expected 2)
"""
#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.
System Information
==================
OS                         Windows
OS-release                       7
Python                       3.6.2

Package Versions
================
pip                          9.0.1
setuptools     36.5.0.post20170921
cobra                        0.8.2
future                      0.16.0
swiglpk                      1.4.4
optlang                      1.2.3
ruamel.yaml                0.14.12
pandas                      0.20.3
numpy                       1.13.1
tabulate                     0.8.1
python-libsbml              5.15.0
lxml                         3.8.0
scipy                       0.19.1
matplotlib                   2.0.2
palettable                   3.1.0
pymatbridge                  0.5.2
</details>

**Comment by cdiener** [comment]
Hi, thanks for the report. Unfortunately there are many versions of Recon1 out there and I am not sure which one you are using. We usually recommend [the one from BIGG](http://bigg.ucsd.edu/models/RECON1) which does work:

```Python
In [6]: from cobra.io import read_sbml_model

In [7]: mod = read_sbml_model("/home/cdiener/Downloads/RECON1.xml.gz")

In [8]: mod
Out[8]: <Model RECON1 at 0x7fa4401f5438>
```

Hope that helps :smile:

**Comment by WuyangFF95** [comment]
Thanks! But what about Recon2?

**Comment by cdiener** [comment]
I use Recon 2.2 from https://github.com/u003f/recon2/tree/master/models regularly and it works just fine :)

**Comment by WuyangFF95** [comment]
Many Thanks! I'll close the issue. :100: :+1:
