### ISSUE TITLE
Unable to process reaction with colon(":") in its name

### ISSUE THREAD

**Issue by WuyangFF95** [opencobra/cobrapy#605]
#### Problem description
I imported a Matlab model. All of the functions work fine, except the attributes of the reactions. When I entered the attribute for any reaction (e.g. mc_model.reactions.A:3DSPHR.upper_bound), it always shows "invalid syntax".
After that, I figured out that there was a colon in every one of the reaction name, and I guess that's the reason python get confused. Therefore I have to try another more time-consuming way that is:
mc_model.reactions.get_by_id("A:3DSPHR").upper_bound.
Can you help me to fix it so that I can use the upper method? Another question is that how can I change the id for each reaction so that I can prevent this problem?

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
mc_model.reactions.A:3DSPHR.upper_bound
 
```

#### Actual Output
 File "<ipython-input-5-667a43546b0b>", line 1
    mc_model.reactions.A:3DSPHR.upper_bound
                              ^
SyntaxError: invalid syntax
#### Expected Output
1000.0
#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.
System Information
==================
OS                         Windows
OS-release                       7
Python                       3.6.2

Package Versions
================
pip                          9.0.1
setuptools     36.5.0.post20170921
cobra                        0.8.2
future                      0.16.0
swiglpk                      1.4.4
optlang                      1.2.3
ruamel.yaml                0.14.12
pandas                      0.20.3
numpy                       1.13.3
tabulate                     0.8.1
python-libsbml              5.15.0
lxml                         3.8.0
scipy                       0.19.1
matplotlib                   2.0.2
palettable                   3.1.0
pymatbridge                  0.5.2
</details>

**Comment by WuyangFF95** [comment]
Another probelm is that, if there are brackets ("[","]") in a metabolite name, the CobraPy won't recogize it correctly either.

In [25]: dn_model.metabolites.dcdccoa_m_COMMA[x]
Traceback (most recent call last):

  File "<ipython-input-25-d0605b51e91f>", line 1, in <module>
    dn_model.metabolites.dcdccoa_m_COMMA[x]

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\core\dictlist.py", line 451, in __getattr__
    attr)

AttributeError: DictList has no attribute or entry dcdccoa_m_COMMA

**Comment by Midnighter** [comment]
Both cases suffer from the same problem: They are not valid Python variable names. You can find the official rules [here](https://docs.python.org/2/reference/lexical_analysis.html#identifiers). Variables must:

* start with a letter or underscore
* contain only letters, underscores, or numbers

I would recommend changing the identifiers, you might have to change the examples below depending on whether the patterns hold for all identifiers.
```
for rxn in model.reactions:
    rxn.id = rxn.id[2:]  # trim the first two letters thus getting rid of 'A:'

import re
pattern = re.compile(r"\[(?P<compartment>[a-z])\]$")
for met in model.metabolites:
    met.id = pattern.sub(r"_\g<compartment>", met.id)
```
(The regex is untested but should do the trick.)

**Comment by WuyangFF95** [comment]
Thanks! I'll close this issue now.

**Comment by Midnighter** [comment]
@WuyangFF95 a simpler version for the metabolites is:

```python
for met in model.metabolites:
    met.id = "{}_{}".format(met.id[:-3], met.id[-2])
```

**Comment by pstjohn** [comment]
So its also worth mentioning that you're more than able to work with reactions / metabolites that arn't valid python variable names. Even the `textbook` example does that:

```python
from cobra.test import create_test_model
model = create_test_model('textbook')
model.metabolites.6pgc_c
```

```
  File "<ipython-input-90-7fbc8811b949>", line 1
    model.metabolites.6pgc_c
                      ^
SyntaxError: invalid syntax
```

The best solution is often to just index that particular metabolite / reaction with a string key:
`model.metabolites.get_by_id('6pgc_c')`
