### ISSUE TITLE
Error reading SBML model (ids too long for optlang)

### ISSUE THREAD

**Issue by alvipal** [opencobra/cobrapy#609]
Hi everyone, 

I'm trying to reconstruct a first draft of a model with Pathway Tools, using the annotation file Genbank and the genome FASTA curate of NCBI. Then, I export it as SBML format to use it in CobraPy.

If I read the model in this way, I get no errors:
`from libsbml import *`
`reader= SBMLReader()`
`model= reader.readSBML(filename)`
`print model.getNumErrors()`
`print model.printErrors()`

However, If I use read_sbml_model function, the kernel die and I obtain this error. I think it's related with the solver GLPK, but I'm only reading the model. 

`glp_set_col_name: j = 1877; column name too long`
`Error detected in file api/prob1.c at line 506`
`Aborted (`core' generated)`

In addition, I validated the SBML file in http://sbml.org/Facilities/Validator/ and it's OK. 
I took a look at the XML file and all the reactions have the bounds defined, although they aren't curated yet.

How can I read the model?

Any help will be welcome.
Thanks in advance.

**Comment by cdiener** [comment]
Hi,
Yes there is a small problem because you have variables whose IDs are very long (close to 256 characters) which is not supported by GLPK. Honestly, that is the first time we see something like that :sweat_smile: I don't really know right now how we would deal with something like that. We can not simply chop of the names since there might be important info being lost that way. For instance if your variable names are something like `very_long_prefix_and_rest`...

**Comment by pstjohn** [comment]
oh, weird, I'm surprised we pass the cobra id's all the way down the stack. Best bet is to either 
1. warn the user the metabolite id is too long
2. if the metabolite ID is longer than 256, use something like `hashlib` to knock it down to a shorter length. 
```python
import hashlib
met = cobra.Metabolite('my_really_long_id_'*20)
hashlib.sha1(met.id.encode()).hexdigest()
```

But for (2), we'd probably want that to happen at as low a level as possible so the user's ID doesn't get changed. Maybe even in optlang

**Comment by phantomas1234** [comment]
I agree that this should be fixed in optlang. Not sure how to best handle this though. I opened an issue in any case. https://github.com/biosustain/optlang/issues/138

**Comment by matthiaskoenig** [comment]
This is not an SBML issue, but an optlang issue, nothing to do from the SBML side on this one.

**Comment by cdiener** [comment]
Fixed in optlang (raises error) explicitly.
