### ISSUE TITLE
Unable to sample the flux after changing bounds

### ISSUE THREAD

**Issue by WuyangFF95** [opencobra/cobrapy#620]
#### Problem description
I have a model, dn_dia.mat, which works well when doing flux-sampling. And I want to shut down certain reactions by forcing their fluxes to zero. But after doing this, I cannot generate my flux sample because it always comes out a same problem.

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.

ox_shut = dn_dia.copy()

for rxn in ox_shut.reactions:
    if "FADCOX" in rxn.id:
        rxn.bounds = (-0.0,0.0)
        

wos_samp = cobra.flux_analysis.sample(ox_shut,10000)
```

#### Actual Output
cobra\flux_analysis\sampling.py:684 RuntimeWarning: Mean of empty slice.
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:73 RuntimeWarning: invalid value encountered in true_divide
Traceback (most recent call last):

  File "<ipython-input-19-bf5ed307af0c>", line 1, in <module>
    wos_samp = cobra.flux_analysis.sample(ox_shut,10000)

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\flux_analysis\sampling.py", line 826, in sample
    data=sampler.sample(n))

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\flux_analysis\sampling.py", line 733, in sample
    chains = _sample_chain((n, 0))

  File "C:\ProgramData\Anaconda3\lib\site-packages\cobra\flux_analysis\sampling.py", line 576, in _sample_chain
    pi = np.random.randint(sampler.n_warmup)

  File "mtrand.pyx", line 988, in mtrand.RandomState.randint

ValueError: low >= high

#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.

System Information
==================
OS                         Windows
OS-release                       7
Python                       3.6.3

Package Versions
================
pip                          9.0.1
setuptools     36.5.0.post20170921
cobra                        0.9.1
future                      0.16.0
swiglpk                      1.4.4
optlang                      1.2.5
ruamel.yaml                0.14.12
pandas                      0.21.0
numpy                       1.13.3
tabulate                     0.8.1
python-libsbml              5.15.0
lxml                         4.1.0
scipy                       0.19.1
matplotlib                   2.1.0
palettable                   3.1.0
pymatbridge                  0.5.2
</details>

**Comment by cdiener** [comment]
Looks like your problem becomes infeasible when setting that bound. Meaning you have another flux constraint which requires a non-zero flux but can't comply with that particular flux being zero. Unfortunately, I won't be able to debug more without having access to your model...

**Comment by WuyangFF95** [comment]
Thanks!

**Comment by cdiener** [comment]
Hi, could you resolve your issue? Otherwise, what does `ox_shut.optimize()` say after you knocked out the reaction?

**Comment by cdiener** [comment]
Closing for now, feel free to reopen if the problem persists.

**Comment by mjenior** [comment]
This is very similar to a recent problem I have been having after setting weighted linear coefficients to a total sum fluxes constraint on my model. None of the constraints explicit close any reactions, just penalize the flux value based on previous pFBA results.

After I generate the sampling object with:

`sampling_object = ACHRSampler(constrained_model) `

and the try to generate samples with:

`flux_samples = sampling_object.sample(100)`

I get the consistent error message:

>  ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-42-0e4809f15f00> in <module>()
>       1 
> ----> 2 s1 = glucose_min_media_fluxes.sample(100)
>       3 glucose_min_media_fluxes.validate(s1)
> 
> /home/mjenior/anaconda2/lib/python2.7/site-packages/cobra/flux_analysis/sampling.pyc in sample(self, n, fluxes)
>     625         samples = np.zeros((n, self.warmup.shape[1]))
>     626         for i in range(1, self.thinning * n + 1):
> --> 627             self.__single_iteration()
>     628             if i % self.thinning == 0:
>     629                 samples[i//self.thinning - 1, ] = self.prev
> 
> /home/mjenior/anaconda2/lib/python2.7/site-packages/cobra/flux_analysis/sampling.pyc in __single_iteration(self)
>     586 
>     587     def __single_iteration(self):
> --> 588         pi = np.random.randint(self.n_warmup)
>     589         # mix in the original warmup points to not get stuck
>     590         delta = self.warmup[pi, ] - self.center
> 
> mtrand.pyx in mtrand.RandomState.randint()
> 
> ValueError: low >= high
> 

I tried trouble shooting with validate by:

`bad = numpy.random.uniform(-1000, 1000, size=len(iJO1366.reactions))
glucose_min_media_fluxes.validate(numpy.atleast_2d(bad))`

with the output:

> array(['lue'], dtype='|S3')

I'm not sure what next steps to take to correct the issue, and any help would be greatly appreciated. Let me know if it would also be helpful to send the constrained model itself.

**Comment by Midnighter** [comment]
@mjenior can you please open a new issue for this? Even though it's related.

**Comment by mjenior** [comment]
No problem, posting now. Thanks!
