### ISSUE TITLE
reaction.variable_kind

### ISSUE THREAD

**Issue by yseif** [opencobra/cobrapy#625]
#### Problem description

Is reaction.variable_kind obsolete? Is the functionality for .variable_kind still included in the updated cobrapy?

I am trying to add a constraint so that the flux going through a reaction is either 0 or 1.
running reaction.variable_kind = 'integer' does not raise an error, nor does reaction.variable_kind = "random_string"

#### Code Sample

```python
CSfi = Reaction('CSfi')
model.add_reaction(CSfi)
CSfi.reaction = '1000 CSf_plus -> 1000 CSf_minus' 
CSfi.upper_bound = 1
CSfi.lower_bound = 0
CSfi.variable_kind = 'integer' # this is not working!!
solution = model.optimize()
dict(solution.fluxes)['CSfi']

#### Actual Output
0.0060072495753503569

#### Expected Output
1

#### Output of `cobra.show_versions()`

System Information
==================
OS                        Linux
OS-release     4.4.0-93-generic
Python                   2.7.12

Package Versions
================
pip                       9.0.1
setuptools               28.0.0
cobra                     0.8.2
future                   0.16.0
swiglpk                   1.4.3
optlang                   1.2.1
ruamel.yaml             0.14.12
pandas                   0.18.1
numpy                    1.11.2
tabulate                  0.7.7
python-libsbml           5.15.0
lxml                      3.5.0
scipy                    0.18.1
matplotlib                1.5.3
palettable                3.0.0
pymatbridge               0.5.2
<details>

# Paste the output of `import cobra;cobra.show_versions()` here.

System Information
==================
OS                        Linux
OS-release     4.4.0-93-generic
Python                   2.7.12

Package Versions
================
pip                       9.0.1
setuptools               28.0.0
cobra                     0.8.2
future                   0.16.0
swiglpk                   1.4.3
optlang                   1.2.1
ruamel.yaml             0.14.12
pandas                   0.18.1
numpy                    1.11.2
tabulate                  0.7.7
python-libsbml           5.15.0
lxml                      3.5.0
scipy                    0.18.1
matplotlib                1.5.3
palettable                3.0.0
pymatbridge               0.5.2
</details>

**Comment by Midnighter** [comment]
Hi @yseif,

By default cobrapy now uses the newer optlang solver interfaces. The old ones are deprecated and will be removed in future.

From your code I think that directly adding a variable/constraint seems to be more explicit. [This part](http://cobrapy.readthedocs.io/en/latest/constraints_objectives.html) of the documentation shows you how to do that. And here [in the optlang docs](http://optlang.readthedocs.io/en/latest/#example) you can see how to create a binary variable.

Btw, you can directly index into a solution without transforming it to a dict. So either `solution['CSfi']` or `solution.fluxes['CSfi']` work fine.

**Comment by yseif** [comment]
So there are no functionalities to set the type of constraint to binary/integer?

**Comment by Midnighter** [comment]
Yes there is, `Variable(..., type='integer')` or `Variable(..., type='binary')`.

**Comment by Midnighter** [comment]
@yseif did that resolve the issue for you?

**Comment by yseif** [comment]
Yes it did. Thank you for your time and advice.
