### ISSUE TITLE
"How to cite" information missing from webpage/documentation

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#626]
#### Problem description
I want to cite cobrapy, unclear which reference to use. The citation to use should be listed in the README.md and somewhere on readthedocs

I assume it is
```
@article{ebrahim2013cobrapy,
  title={COBRApy: COnstraints-based reconstruction and analysis for python},
  author={Ebrahim, Ali and Lerman, Joshua A and Palsson, Bernhard O and Hyduke, Daniel R},
  journal={BMC systems biology},
  volume={7},
  number={1},
  pages={74},
  year={2013},
  publisher={BioMed Central}
}
```
If there is any newer document (preprint?) or some Zenodo DOI for releases?
Best M

**Comment by cdiener** [comment]
It is listed in the Readme (see last paragraph of "What is cobrapy?"), the website and on Readthedocs (section 13.2)...

And yes. It is the one you mentioned. There is no newer version at the moment.

**Comment by matthiaskoenig** [comment]
Thanks. solved
