### ISSUE TITLE
Fixes for the new double deletion functions

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#630]
Some observations by @cdiener on what's still going wrong with double deletion. @sgalkina and I just discussed those points and you'll find our opinions on the matter.

1. > MOMA gives wrong results for infeasible solutions. For instance setting a lower bound of 0.1 on the biomass reaction and running single reaction deletions with moma you get biomass values like 0.9 or -0.4 which are not possible in the textbook model

   Can you share your sample code, please? We hope this might partially be solved by 6.

2. > single deletions return None for infeasible reactions, however it should return NA for backwards compatibility

   Yes, we'll use `nan` everywhere.

3. > deletion functions should return pandas DataFrames but return dicts

   Agreed, we can go with a `DataFrame`. However, we need a better structure if we also want to allow triple deletions and so on. A possibility is a three column layout with the first column being the `frozenset`s, second the objective flux, and the third the status. Another option is to use a multi-level index instead but that would introduce an order.

4. > growth rates are set to zero when smaller `zero_cutoff`, however that may give wrong results. Should return the same value as returned by optlang.

   Agreed.

5. > many of the arguments in the docstrings don't coincide with the real function arguments

   Will fix.

6. > MOMA can get the biomass value directly from the primal value of the `moma_old_objective` variable, no need to write to notes. Also getting the coefficients dict from an expression does work differently in symengine and sympy, so better avoid that.

   Good idea!

7. > `_model` should not be set as global (may delete user set variables) but rather as module variable for multiprocessing (see sampling code for example)

   We're a bit confused here. The code in sampling seems to make use of the exact same method?

8. > `chunk_size = len(args) // num_cpu` may lead to a chunk size of zero

   Good catch :)

**Comment by cdiener** [comment]
Yeah, point 7 was nonsense from my part. `global` in a module will set a module level variable not a real global. Seems I learned that at some point and forgot it again :/

For point 3 could we split the frozenset into individual columns? All sets have the same number of elements, no?

For the chunksize bug I think the best way is assure that num_cpus is at most len(args). This way you don't spawn processes that do nothing. 

Maybe it might make sense to also call join in the Pool after close after seeing https://stackoverflow.com/questions/38271547/when-should-we-call-multiprocessing-pool-join .

**Comment by Midnighter** [comment]
> For point 3 could we split the frozenset into individual columns? All sets have the same number of elements, no?

My problem with this solution (same as the multi-index) is that it imposes an order when inherently there is none. If we don't use `frozenset`, I favor the using an index so that the shape of the data frame doesn't change with single, double, triple etc. deletions.

**Comment by cdiener** [comment]
Okay, in this case I favour the frozenset as it is used now.
