### ISSUE TITLE
Error in pFBA solution

### ISSUE THREAD

**Issue by JuBra** [opencobra/cobrapy#633]
#### Problem description

Hi everyone,
it seems there is a bug in the setting of the solver for running pFBA.
When 'cglpk' is passed as solver to pFBA a solution is returned where the steady-state assumption does not hold. This is not the case if no solver is passed, nor for loopless or normal FBA.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
import cobra
import cobra.test

cobra.show_versions()


def check_solution(model, solution):
    errors = []
    for metabolite in model.metabolites:

        sum_rates_prod = 0
        sum_rates_cons = 0
        for r in metabolite.reactions:
            rate = r.metabolites[metabolite] * solution.x_dict[r.id]
            if rate < 0.:
                sum_rates_cons += abs(rate)
            else:
                sum_rates_prod += rate

        if round(sum_rates_prod, 9) != round(sum_rates_cons, 9):
            errors.append("{0!s} Producing: {1!s} Consuming: {2!s}".format(metabolite,
                                                                           sum_rates_prod,
                                                                           sum_rates_cons))

    for e in errors:
        print(e)
    if not errors:
        print("No errors found.")


model = cobra.test.create_test_model("ecoli")

print("\nRunning without setting solver:")
solution = cobra.flux_analysis.pfba(model)
check_solution(model, solution)

print("\nRunning with setting solver:")
solution1 = cobra.flux_analysis.pfba(model, solver="cglpk")
check_solution(model, solution1)

```

#### Actual Output
Running without setting solver:
No errors found.

Running with setting solver:
13dpg_c Producing: 16.27477463458948 Consuming: 0
23dhmb_c Producing: 0 Consuming: 0.8588572223410069
2pg_c Producing: 0 Consuming: 14.586890401186844
34hpp_c Producing: 0.1356842124020382 Consuming: 0
3c2hmp_c Producing: 0 Consuming: 0.44258895515970054
3c3hmp_c Producing: 0.44258895515970054 Consuming: 0
3mob_c Producing: 0.8588572223410069 Consuming: 0.4431548013238312
3mop_c Producing: 0.2854075003797577 Consuming: 0
3pg_c Producing: 0 Consuming: 1.6878842334026367
4pasp_c Producing: 1.0502301280629123 Consuming: 0
5aizc_c Producing: 0 Consuming: 0.44011730767886903
5caiz_c Producing: 0.44011730767886903 Consuming: 0
ac_c Producing: 0.5774194864564788 Consuming: 0.5723062411713964
accoa_c Producing: 8.076024737976208 Consuming: 8.648330979147598
acg5p_c Producing: 0.29057772323013975 Consuming: 0
acorn_c Producing: 0 Consuming: 0.2905777232301398
actp_c Producing: 0.5723062411713964 Consuming: 0
ade_c Producing: 0.0006611362299652479 Consuming: 0
adn_c Producing: 0 Consuming: 0.0006611362299652479
adp_c Producing: 78.81777878956954 Consuming: 55.81524739984259
akg_c Producing: 7.081536842497097 Consuming: 3.801538330156842
ala__L_c Producing: 0.0017731811219722044 Consuming: 0.5728809286816803
alac__S_c Producing: 0.8588572223410069 Consuming: 0
asp__L_c Producing: 0 Consuming: 2.876069326312715
aspsa_c Producing: 0 Consuming: 0.3644098415592617
atp_c Producing: 55.81524739984259 Consuming: 78.81777878956956
b2coa_c Producing: 0.3496064807132788 Consuming: 0
btcoa_c Producing: 0 Consuming: 0.3496064807132788
ca2_c Producing: 0 Consuming: 0.005113245285243948
cbasp_c Producing: 0.32496368379102236 Consuming: 0
co2_c Producing: 23.714531196259692 Consuming: 4.039308560596309
coa_c Producing: 9.164504494939614 Consuming: 11.878128914297182
dc2coa_c Producing: 0.3496064807132788 Consuming: 0
dcacoa_c Producing: 0 Consuming: 0.3496064807132788
dd2coa_c Producing: 0.3496064807132788 Consuming: 0
ddcacoa_c Producing: 0 Consuming: 0.3496064807132788
dhap_c Producing: 7.784185977729064 Consuming: 7.647608789349257
dhor__S_c Producing: 0 Consuming: 0.32496368379102236
fad_c Producing: 0.001010860595296067 Consuming: 2.147575790636024
fadh2_c Producing: 2.1473567217217857 Consuming: 0.0007917916810579483
fprica_c Producing: 0.533185248472998 Consuming: 0
gam1p_c Producing: 0 Consuming: 0.0928223478409472
gam6p_c Producing: 0.0928223478409472 Consuming: 0
glu__D_c Producing: 0 Consuming: 0.027298147932057412
glu__L_c Producing: 1.5201761734634132 Consuming: 4.77287653787161
glyc3p_c Producing: 0 Consuming: 0.13657718837980704
h_c Producing: 287.6459647369284 Consuming: 275.8928688606489
h2o_c Producing: 117.45413504310966 Consuming: 81.14965096497522
hdcoa_c Producing: 0 Consuming: 0.14777622704489463
hdd2coa_c Producing: 0.27315437675961407 Consuming: 0
hom__L_c Producing: 0 Consuming: 0.6858202865036506
hx2coa_c Producing: 0.3496064807132788 Consuming: 0
hxcoa_c Producing: 0 Consuming: 0.3496064807132788
ile__L_c Producing: 0 Consuming: 0.2854075003797577
imp_c Producing: 0 Consuming: 0.533185248472998
indole_c Producing: 0.05584096095083991 Consuming: 0
meoh_c Producing: 1.9647436254539666e-06 Consuming: 0
na1_c Producing: 0.005113245285243948 Consuming: 0
nadp_c Producing: 2.570397460180044 Consuming: 13.993416407383462
nadph_c Producing: 13.992977287183173 Consuming: 2.5699583399797428
nh4_c Producing: 11.102862991063889 Consuming: 2.6460656314271316
oaa_c Producing: 7.7338459705391065 Consuming: 4.857776644226393
oc2coa_c Producing: 0.3496064807132788 Consuming: 0
occoa_c Producing: 0 Consuming: 0.3496064807132788
orot_c Producing: 0.32496368379102236 Consuming: 0
orot5p_c Producing: 0 Consuming: 0.32496368379102236
phe__L_c Producing: 0 Consuming: 0.18199911388486456
phpyr_c Producing: 0.18199911388486456 Consuming: 0
pi_c Producing: 70.02035137165808 Consuming: 72.09002203443207
pmtcoa_c Producing: 0 Consuming: 0.12537814971471942
ppi_c Producing: 3.1168624108175105 Consuming: 6.832921653228198e-30
prpp_c Producing: 0.916446805118503 Consuming: 0.5914831213274807
pyr_c Producing: 11.073290257196865 Consuming: 10.446341548686323
r5p_c Producing: 0 Consuming: 2.0832282105662405
ru5p__D_c Producing: 4.081934853516529 Consuming: 1.998045506720326
sl26da_c Producing: 0 Consuming: 0.3644098415592617
sl2a6o_c Producing: 0.3644098415592617 Consuming: 0
succ_c Producing: 0.5162648763705994 Consuming: 3.802195536899557
succoa_c Producing: 3.801538330156842 Consuming: 0.5156076696278851
td2coa_c Producing: 0.27315437675961407 Consuming: 0
tdcoa_c Producing: 6.832921653228198e-31 Consuming: 0.27315437675961407
trp__L_c Producing: 0 Consuming: 0.05584096095083991
tyr__L_c Producing: 0 Consuming: 0.1356842124020382
val__L_c Producing: 0 Consuming: 0.4157024210171757
ca2_e Producing: 0 Consuming: 0.005113245285243948
cl_e Producing: 0 Consuming: 0.005113245285243948
co2_e Producing: 0 Consuming: 19.67522263566338
cobalt2_e Producing: 0 Consuming: 2.4559295318174584e-05
cu2_e Producing: 0 Consuming: 0.0006965016152234311
fe2_e Producing: 0 Consuming: 0.01577787368420809
glc__D_e Producing: 0 Consuming: 10.0
h_e Producing: 0 Consuming: 9.026260125596009
h2o_e Producing: 0 Consuming: 45.619430370035154
k_e Producing: 0 Consuming: 0.19175210124161812
meoh_e Producing: 0 Consuming: 1.9647436254539666e-06
mg2_e Producing: 0 Consuming: 0.008522075475406581
mn2_e Producing: 0 Consuming: 0.0006788189225943454
mobd_e Producing: 0 Consuming: 0.00012672596384178083
nh4_e Producing: 0 Consuming: 10.61042505182508
ni2_e Producing: 0 Consuming: 0.00031730609551081557
o2_e Producing: 0 Consuming: 17.57893353025437
pi_e Producing: 0 Consuming: 0.947626304082619
so4_e Producing: 0 Consuming: 0.24776399488787232
zn2_e Producing: 0 Consuming: 0.0003349887881399013
ac_p Producing: 0 Consuming: 0.005113245285243948
ca2_p Producing: 0.005113245285243948 Consuming: 0
h_p Producing: 233.68292795385938 Consuming: 224.66178107354847
na1_p Producing: 0 Consuming: 0.005113245285243948

#### Output of `cobra.show_versions()`

<details>
System Information
==================
OS                      Linux
OS-release  3.19.0-32-generic
Python                  3.5.3

Package Versions
================
pip                     9.0.1
setuptools             38.2.3
cobra                   0.9.1
future                 0.16.0
swiglpk                 1.4.4
optlang                 1.3.0
ruamel.yaml           0.14.12
pandas                 0.21.0
numpy                  1.13.3
tabulate                0.8.2
lxml                    4.1.1
</details>

**Comment by pstjohn** [comment]
So 'cglpk' is one of the legacy solvers, and doesn't really interact with cobrapy as well as it should. Its slated to deletion in an upcoming release, so I'd avoid writing too much code that depends on it.

As a result, the pfba functions are actually different between the two different calls. In the earlier version we converted the model to an irreversible model before running PFBA. So that `solution1` object contains a bunch of reactions (`blahblah_reverse`) that arnt in the actual model.

```python
>>> len(solution1.x_dict)
3219
>>> len(model.reactions)
2583
```

You can verify that the pFBA is working correctly though if you change your code as follows:

```python
model = cobra.test.create_test_model("ecoli")

print("\nRunning without setting solver:")
solution = cobra.flux_analysis.pfba(model)
check_solution(model, solution)

from cobra.manipulation.modify import convert_to_irreversible
convert_to_irreversible(model)

print("\nRunning with setting solver:")
solution1 = cobra.flux_analysis.pfba(model, solver="cglpk")
check_solution(model, solution1)
```
Gives the output
```
Running without setting solver:
No errors found.

Running with setting solver:
No errors found.
```

**Comment by Midnighter** [comment]
In fact, I'm starting work to remove the old solvers right now. Feel free to re-open this issue if your problems persist.

**Comment by Midnighter** [comment]
cobrapy depends on optlang which in turn comes with swiglpk by default. So the default solver is still GLPK just that it's now the optlang version by default rather than cglpk.

**Comment by JuBra** [comment]
@Midnighter Ah, my bad. I missed the diference between the cglpk and swiglpk. Thanks for clarifying!
