### ISSUE TITLE
Crash of python.exe when loading a model with CPLEX installed

### ISSUE THREAD

**Issue by jwsch** [opencobra/cobrapy#645]
Hey everyone,

as the title says when I try to load a model in COBRApy it crashes the python.exe when CPLEX is installed. I tried to reinstall everything and still the same problem appear (Everything should be up to date). CPLEX works fine with example codes based on optlang and cplex itself. Also, tried GUROBI with COBRApy which works fine.
Tried it on Windows 10 and 7 with the same crash. 

Is this a bug on my side? Does anyone know how to fix this problem? 

Thanks!

**Comment by Midnighter** [comment]
When you say 'crash' do you mean a segmentation fault or is there some sort of traceback we can look at? Without any more information on this error it will be really hard to help you.

**Comment by jwsch** [comment]
There is no traceback other than the attached crash message that python.exe does not work any more.
![error](https://user-images.githubusercontent.com/27813522/34212036-40eeb13c-e59b-11e7-9555-05e5195afd7f.png)

I run those few lines till the message:
```
import cobra
%time m = cobra.io.read_sbml_model("test_model.xml")
```

If this information is necessary i installed CPLEX through Anaconda by running this:
`conda install -c ibmdecisionoptimization cplex`

I would like to provide more information if you could tell me which one you need. 

Thanks!

**Comment by cdiener** [comment]
Hi, in your example the problem seems to be rather with libsbml. Does the following work for you?

```Python
from cobra.test import create_test_model

mod = create_test_model("textbook")
mod.optimize()
```

**Comment by jwsch** [comment]
Hi,
I tried your code and I got the same crash when you load the model. It never reaches the optimization step.

Now I tried to load the model with CPLEX uninstalled. It worked so I installed CPLEX again and changed the solver to CPLEX without restarting the kernel. It also crashes the same way when you change the solver to CPLEX.

I am really confused what is causing this issue.

**Comment by cdiener** [comment]
Okay that is really odd since loading the model does not really use cplex at all. Actually all models are created with the glpk interface by default and you would need to change the solver to cplex. Unfortunately, the error occurs in the compiled libraries so there is no way to see what coe actually causes the error.

If you just import cobra does this crash Python as well?

**Comment by jwsch** [comment]
Importing cobra does not crash Python with CPLEX installed and without.

Good to know, thanks! Do you think this could be the reason for the crash?
