### ISSUE TITLE
Changing metabolites through cobra.Reaction._metabolites is no longer supported?

### ISSUE THREAD

**Issue by jlerman44** [opencobra/cobrapy#649]
Hi all,

Changing metabolite stoichiometry in a reaction through cobra.Reaction._metabolites is no longer supported in cobra, huh?  

I've been porting some code over from cobra==0.5.8 to the latest version (>=0.10.0) and discovered this. It's a big dangerous to use cobra.Reaction._metabolites because there is no warning and the reaction when printed appears to have a 0 coefficient.

Best,
Josh

```python
import cobra

# OLD SYNTAX - DOES NOT WORK ANYMORE
iMM904 = cobra.io.load_json_model('iMM904.json')
cobra.manipulation.delete_model_genes(iMM904, ['YHR046C'])
# Note: After KO, 0 biomass expected since the cell cannot produce ptd1ino_SC_c
# To resolve, remove from biomass equation (not this is just for debugging as it is no longer balanced to 1g of content)
iMM904.reactions.BIOMASS_SC5_notrace._metabolites[ \
    iMM904.metabolites.get_by_id('ptd1ino_SC_c')] = 0.0
print('After setting ptd1ino_SC_c to 0 using old way')
print(iMM904.optimize())

######################

# NEW WAY - DOES WORK
iMM904 = cobra.io.load_json_model('iMM904.json')
cobra.manipulation.delete_model_genes(iMM904, ['YHR046C'])
original_coefficient = iMM904.reactions.BIOMASS_SC5_notrace._metabolites[ \
    iMM904.metabolites.get_by_id('ptd1ino_SC_c')]
iMM904.reactions.BIOMASS_SC5_notrace.subtract_metabolites({iMM904.metabolites.ptd1ino_SC_c: original_coefficient})
print('After setting ptd1ino_SC_c to 0 using the new way')
print(iMM904.optimize())
```

**Comment by jlerman44** [comment]
I guess it does say "# read-only"

https://github.com/opencobra/cobrapy/blob/8ceee36f262754dd6aee4944f79191d362fbd6fc/cobra/core/reaction.py#L361

Josh

**Comment by jlerman44** [comment]
Then again, cobra uses this.. so im still confused..

https://github.com/opencobra/cobrapy/blob/8ceee36f262754dd6aee4944f79191d362fbd6fc/cobra/core/reaction.py#L734

**Comment by jlerman44** [comment]
This must be where the magic comes in https://github.com/opencobra/cobrapy/blob/8ceee36f262754dd6aee4944f79191d362fbd6fc/cobra/core/reaction.py#L785

**Comment by pstjohn** [comment]
In general, class attributes and methods that are prefixed with an underscore are meant to only be used internally within that class. Python doesn't otherwise have strict public / private access control.

In this case specifically, if you look at all the code in `reaction.add_metabolites`, you can see why you can't just set the dictionary item to the value you want. There's some code to make sure the metabolite and reaction objects are linked, that the solver method gets updated, and some stuff for the context management.

**Comment by jlerman44** [comment]
Makes total sense. Issue can be closed. People with old code using this should be warned!
