### ISSUE TITLE
Importing libSBML

### ISSUE THREAD

**Issue by IvanPogrebnyakov** [opencobra/cobrapy#651]
Hi everyone,

I imported libSBML and tried to read a model with it, but it returns an error

![image](https://user-images.githubusercontent.com/35377036/34884907-800211b8-f7be-11e7-9d0d-b9c5bc34f78c.png)

**Comment by cdiener** [comment]
That is weird. How did you install libSBML? Did you restart your notebook afterwards?

**Comment by matthiaskoenig** [comment]
You should check if this works for you in a clean virtual environment:
```
mkvirtualenv test-libsbml
(test-libsbml) pip install python-libsbml cobra
(test-libsbml) python
```
And than run the code. 
If this works it is probably an issue with your libsbml installation on your system.

**Comment by Midnighter** [comment]
Well, he's using conda. Quite mysterious indeed! A fresh conda environment might be helpful, though.

**Comment by Midnighter** [comment]
Seems to be fixed (by other means of communication).
