### ISSUE TITLE
Alternative solutions for an optimization

### ISSUE THREAD

**Issue by yseif** [opencobra/cobrapy#654]
I've tweaked the optimization problem as such: give a minimal number of open exchanges such that growth is achieved.

I simply used the commands "model.add_cons_vars" and "model.optimize()" with indicators set for the upper and lower bound of the exchange fluxes.

I was wondering whether there was a way to automatically obtain alternative solutions rather than running the code snippet multiple times.

**Comment by cdiener** [comment]
There is no general way without re-optimizing, however you can make it more or less efficient. I think what you are trying to do is implemented in https://github.com/opencobra/cobrapy/pull/589 . Maybe you find some solutions there. Particularly the following snippet from the discussion:

```Python
In [1]: from cobra.media import *

In [2]: from cobra.test import create_test_model

In [3]: mod = create_test_model("textbook")

In [4]: minimal_medium(mod, 0.8, minimize_components=5, open_exchanges=True)
Out[4]:
                      0           1           2           3           4
EX_fru_e       0.000000  523.104557    0.000000    0.000000    0.000000
EX_glc__D_e    0.000000    0.000000  523.104557  521.357767  519.750758
EX_gln__L_e    0.000000    0.000000    0.000000   40.698058    0.000000
EX_glu__L_e  348.101944   83.995843   83.995843    0.000000    0.000000
EX_nh4_e       0.000000    0.000000    0.000000    0.000000   81.026921
EX_o2_e      500.000000    0.000000    0.000000    0.000000    0.000000
EX_pi_e       66.431529   56.667310   56.667310   54.913419   54.664344
```

**Comment by yseif** [comment]
Oh I wasn't aware that there was a built in function for that. Either way, I'd rather use my code snippet because I can tweak it more easily. 

I was thinking along the lines of GrowMatch, where you can get just pass a spec for how many iterations you want the algorithm to run. I guess it was just a for loop then.

Thanks for your quick reply!
