### ISSUE TITLE
Reactions with no bounds

### ISSUE THREAD

**Issue by yseif** [opencobra/cobrapy#670]
Is there a way to create a reaction with no upper or lower bound?
Mathematically this could translate to vi>= 0 and -vi>=0. 
In other words is there a way to remove the +/-1000 flux value bounds on a reaction?

**Comment by Midnighter** [comment]
Hello @yseif, you have multiple options. If you have CPLEX you can simply use `numpy.inf`, for example, `model.reactions.PFK.bounds = -numpy.inf, numpy.inf`. This seems to crash with GLPK, though. Your other options is to manipulate the variable bounds directly, e.g.,
```python
model.reactions.PFK.forward_variable.ub = None
model.reactions.PFK.reverse_variable.ub = None
```
Please also see the attached notebook.
[notebook.zip](https://github.com/opencobra/cobrapy/files/1755306/notebook.zip)

**Comment by yseif** [comment]
Thanks!

**Comment by Midnighter** [comment]
Closing this issue then. Feel free to re-open in case you have more questions related to unbounded variables.
