### ISSUE TITLE
Cobrapy allows non-valid SBML export

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/cobrapy#674]
#### Problem description
I work with the JSON file format internally and only export a model to SBML when making a release. Making such a release today I noticed that COBRApy doesn't seem to issue a warning/ error message when exporting a non-valid SBML. I played around with a toy model to explore the extent of this.

I believe an internal check may be more elegant than exporting/ re-importing or checking the model with the SBML validator at every export. In my opinion, a check like the SBML import sanity check should run before ultimately exporting the model.

##### Imports for all subsequent examples:

```python
from cobra.io import read_sbml_model, write_sbml_model
from cobra import Reaction, Metabolite, Model
from os import getcwd
```

#### No Flux Objective
```python
base = Model('Test')
met1 = Metabolite('met1', compartment='a')
met2 = Metabolite('met2', compartment='a')
met3 = Metabolite('met3', compartment='b')
met4 = Metabolite('met4', compartment='b')
rxn1 = Reaction('rxn1')
rxn1.add_metabolites({met1: -1, met2: 1})
rxn2 = Reaction('rxn2')
rxn2.add_metabolites({met3: -1, met4: 1})
base.add_reactions([rxn1, rxn2])
base.compartments = {"a": "compartment a", "b": "compartment b"}

relative_directory = getcwd()
base = write_sbml_model(base, relative_directory + '/toy1.xml')
```
#### Output of the online SBML Validator
```
This document is not valid SBML!

Error Line 14 Column 37: (SBML Validation Rule #10103) An SBML XML document must conform to the XML Schema for the corresponding SBML Level, Version and Release. The XML Schema for SBML defines the basic SBML object structure, the data types used by those objects, and the order in which the objects may appear in an SBML document. listOfFluxObjectives cannot be empty.
```

#### Undefined Compartment
```python
base = Model('Test')
met1 = Metabolite('met1', compartment='a')
met2 = Metabolite('met2', compartment='a')
met3 = Metabolite('met3', compartment='b')
met4 = Metabolite('met4', compartment='b')
rxn1 = Reaction('rxn1')
rxn1.add_metabolites({met1: -1, met2: 1})
rxn2 = Reaction('rxn2')
rxn2.add_metabolites({met3: -1, met4: 1})
base.add_reactions([rxn1, rxn2])
base.compartments = {"a": "compartment a"}
base.objective = base.reactions.rxn1

relative_directory = getcwd()
base = write_sbml_model(base, relative_directory + '/toy2.xml')
```

#### Output of the online SBML Validator
```
This document is not valid SBML!

Error Line 31 Column 79: (SBML Validation Rule #20601) The value of 'compartment' in a <species> definition must be the identifier of an existing <compartment> defined in the model. Reference: L3V1 Section 4.6.3 The <species> with id 'M_met3' refers to the compartment 'b' which is not defined.

<species boundaryCondition="false" compartment="b" constant="false" hasOnlySubstanceUnits="false" id="M_met3" />

Error Line 32 Column 79: (SBML Validation Rule #20601) The value of 'compartment' in a <species> definition must be the identifier of an existing <compartment> defined in the model. Reference: L3V1 Section 4.6.3 The <species> with id 'M_met4' refers to the compartment 'b' which is not defined.

<species boundaryCondition="false" compartment="b" constant="false" hasOnlySubstanceUnits="false" id="M_met4" />
```

**Comment by cdiener** [comment]
I agree with the first one. We should either write a zero objective if SBML allows that or throw an error.

The second is more a bug of cobrapy itself. `model.compartments` should always return all compartments and not only the ones that have annotations.

Unfortunately the SBML module has a lot of issues queued up and we are lacking a bit of help in that department :cry:

**Comment by matthiaskoenig** [comment]
I could help with some of the SBML issues. But I would only be willing to write code based on libsbml python binding for import and export (in my opinion the underlying issue of the SBML cobrapy issues is that a custom parser for import/export was written instead of using a well tested library). I.e. not willing to monkey-patch SBML parser which is not using python-libsbml.

**Comment by cdiener** [comment]
@matthiaskoenig I have no objections to that. Might be more work though since you would have to rewrite the V3 parser. But libsbml has precompiled packages now so the initial reasons to not use libsbml are not valid anymore.

**Comment by Midnighter** [comment]
I fully support dropping the home-grown parser and only using libSBML as well.

**Comment by matthiaskoenig** [comment]
Perfect. This sounds great. Rewriting the v3 parser is no problem. I basically would write a replacement module for the `cobra.io.sbml3`. This looks pretty simple (basically did this already a few times for other projects). But will take a bit of time. Basically have to find a free spot without meetings.

Are there any test cases for the sbml import already? I.e. test cases which load example SBML files and check that the cobra internal data structure contains the correct content?
Also which branch should I develop agains?

Best M

**Comment by Midnighter** [comment]
Thank you for taking this on @matthiaskoenig! I think it's quite a big job so please reach out to me for assistance.

Resources:
1. `cobra/test/test_io.py` contains some test cases for SBML.
2. It'd be great to let libSBML handle every SBML document, of course.
3. There are [plenty of issues](https://github.com/opencobra/cobrapy/issues?q=is%3Aissue+is%3Aopen+label%3Asbml) regarding SBML, please have them in mind when crafting a new parser.

**Comment by matthiaskoenig** [comment]
Most of the SBML issues are from me anyway. No big difference between SBML2 and SBML3 parsing, also easy to deal with fbc-v1 and fbc-v2 very easily. So yes, one parser which handles all SBML.

Currently, there is a lot of arbitrary id replacements in the SBML parsing all over the place which creates lots of problems (basically to fix legacy ids and so on, M_ prefixes and more). I would support these replacements via options on the parser (reader/writer), but the default behavior would be to read the SBML as it is. One could than just set the replacements one wants.

Also only fully reading valid SBML models (trying to be as robust as possible on models with errors). I.e. all issues will be fixed which affect valid models, if models are invalid no guarantee.

**Comment by matthiaskoenig** [comment]
Solved with new libsbml parser.
