### ISSUE TITLE
CommentedMap?

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#675]
Has anyone else noticed that `notes` are now being parsed as a `CommentedMap` object when loading from json? (Maybe yaml too).

```python
>>> model.metabolites.xyl__D_c.notes
CommentedMap([('BioCyc',
               [CommentedMap([('id', 'META:D-Xylopyranose'),
                              ('link',
                               'http://identifiers.org/biocyc/META:D-Xylopyranose')])]),
              ('CHEBI',
               [CommentedMap([('id', 'CHEBI:53455'),
                              ('link',
                               'http://identifiers.org/chebi/CHEBI:53455')]),
                CommentedMap([('id', 'CHEBI:65327'),
                              ('link',
                               'http://identifiers.org/chebi/CHEBI:65327')])]),
```

It's not necessarily an error, it probably comes from the `ruamel` package

**Comment by Midnighter** [comment]
`ruamel` is only for YAML I/O so if you don't store as YAML that shouldn't be the case. Also `ruamel.yaml` is pinned to an older version so it shouldn't suddenly change behavior. It does seem to be a class specific to `ruamel`, though, so I don't know :smile:

**Comment by pstjohn** [comment]
I think I found the issue. I was using `load_yaml_model` to load a json file. So it is yaml-specific. (it appears even if you load a correct yaml file.)

I'm not sure its a sudden change, its more that I just started noticing it.
