### ISSUE TITLE
import sbml model, no genes and no GPR

### ISSUE THREAD

**Issue by XiangZhangSC** [opencobra/cobrapy#676]
#### Problem description
When I import iAdipocytes1809 model (SBML downloaded from human metabolic atlas), no genes, no GPR. 
Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
# load packages
import cobra

# import model
model = cobra.io.read_sbml_model('iAdipocytes1809.xml')

print(len(model.reactions))
print(len(model.metabolites))
print(len(model.genes))

```

#### Actual Output
6100
6170
0
#### Expected Output
6100
6170
1809

#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.
System Information
==================
OS              Darwin
OS-release      17.4.0
Python           3.6.4

Package Versions
================
pip              9.0.1
setuptools      38.5.1
cobra           0.11.3
future          0.16.0
swiglpk          1.4.4
optlang          1.3.0
ruamel.yaml    0.14.12
pandas          0.22.0
numpy           1.14.2
tabulate         0.8.2
python-libsbml  5.16.0
</details>

**Comment by ChristianLieven** [comment]
Could you supply a link to the model file, please?

**Comment by matthiaskoenig** [comment]
The model is the first one on
http://metabolicatlas.com/downloads/curate
http://metabolicatlas.com/assets/curated/iAdipocytes1809.xml-ea2fa20615a73d37571ab86eaffd2889.zip

The model does not encode the GPRs and does not contain any fbc package information. The reason why there are no GPRs is that they are not encoded in the SBML. From where did you get the expected numbers of 1809 genes?

Best Matthias

**Comment by XiangZhangSC** [comment]
Hi Matthias,
Thanks for the information. I found there are Ensembl gene ids inside the SBML file but I don't understand why there is 0 genes in the imported model. The original paper tells me there are 1809 genes and it is also in the name of the model. 

Best Xiang

**Comment by matthiaskoenig** [comment]
Hi Xiang,
you are right. They just choose to use a very uncommon (non-standard way to write down the genes).
They basically encoded them as `species` (annotated with ensemble ids) which they than used as modifiers on the reaction (so you see them in the listOfModifiers in the respective reaction).

But as far as I can tell they don't have the actual GPR rules any where, i.e. the logical `and` and `or` for genes to the reactions. Also the bounds are on the paramers of reactions.
You probably will have to convert the SBML into a standard SBML with encoding the FBC information in the fbc package. But you are still missing the GPR rules as far as I can tell. 
In my opinion this is a problem of the model encoding, i.e. the way the information is stored in the SBML, not of cobrapy.

Best M

**Comment by XiangZhangSC** [comment]
Thanks Marthias, 
I see your point. I will also try to contact the model developers.
