### ISSUE TITLE
Rewrite SBML parser using libsbml

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#683]
Currently, cobrapy uses a custom parser to read and write SBML. This creates many issues, mainly related to the correct implementation of the SBML specification, corner cases, ...
The initial reasoning for a custom parser was that it is difficult to install libsbml on the target system.
With the availability of `python-libsbml` packages this is no longer the case.

This issue handles discussion about the rewriting of the SBML parser.
See also initial discussion in
https://github.com/opencobra/cobrapy/issues/674

Currently there exist many issues related to SBML
https://github.com/opencobra/cobrapy/issues?q=is%3Aissue+is%3Aopen+label%3Asbml

An initial version of this will implement the current feature set of the parser, i.e. everything which works in the legacy parser will work in the new parser. Subsequently additional features will be implemented.

**Comment by matthiaskoenig** [comment]
@Midnighter  @cdiener Could you give me commit access to the repository? I would like to assign myself to the issue, add labels and commit my code directly without forking. I would do everything via feature branches and pull requests.

**Comment by phantomas1234** [comment]
@matthiaskoenig welcome (I add you to the team)! I would like to add though that speed was unfortunately also a reason for developing the non-libsbml-based parser. Does everyone agree that sacrificing speed for lower maintenance cost makes sense?

**Comment by cdiener** [comment]
I didn't know that libsmbl is slower than the custom parser (wouldn't have thought that since it is written in C++ and uses libxml)? What is the factor we are talking about? For the optlang transition we made up the "not more than 20% slower" rule and it has served us pretty well...

**Comment by matthiaskoenig** [comment]
I also don't think libsbml is slower than the custom parser. But I will benchmark this on RECON3D and other large models. This could have been the case when cobra only read the core information and ignored annotations (therefore saving all the parsing). 
But preliminary tests with RECON3D show that the current parser needs around 10 seconds, the libsbml based on ~5-7 seconds (but not all information written in the cobra model yet). 
I think the libsbml based implementation will be probably faster around 10-30%, but can only check when finished.

**Comment by phantomas1234** [comment]
The speed difference was mainly due to the custom parser ignoring anything that is not relevant (I don't think it was ignoring annotations though) if I remember correctly. It was quite noticeable for larger models like the human models. But what you describe sounds like there is really no point in keeping the custom parser anymore.

**Comment by matthiaskoenig** [comment]
This is merged in develop.
