### ISSUE TITLE
OptimizationError when solver stopped by time_limit parameter

### ISSUE THREAD

**Issue by ValentijnBroeken** [opencobra/cobrapy#688]
#### Problem description

I am using the `time_limit` parameter for Gurobi to limit the maximal solving time for a MILP in cobrapy. However, when the solving time exceeds this time_limit, cobra raises an OptimizationError: solver status is 'time_limit'. It thus crashes the program instead of allowing me to retrieve the best solution the solver found in this limited time interval.

This is because the solver returns status TIME_LIMIT in this case, which is not explicitly handled in the check_solver_status() function like the OPTIMAL and INFEASIBLE status are. It would be good to add this, so the solution found after exceeding the time limit can actually be used.

#### OptimizationError traceback
A traceback of the error I get:
```python
OptimizationError                         Traceback (most recent call last)
<ipython-input-78-1d0d70e7cdad> in <module>()
----> 1 milp.optimize()

C:\Anaconda3\lib\site-packages\cobra\core\model.py in optimize(self, objective_sense, raise_error)
    845                 objective_sense, original_direction)
    846         self.slim_optimize()
--> 847         solution = get_solution(self, raise_error=raise_error)
    848         self.objective.direction = original_direction
    849         return solution

C:\Anaconda3\lib\site-packages\cobra\core\solution.py in get_solution(model, reactions, metabolites, raise_error)
    286     legacy solvers.
    287     """
--> 288     check_solver_status(model.solver.status, raise_error=raise_error)
    289     if reactions is None:
    290         reactions = model.reactions

C:\Anaconda3\lib\site-packages\cobra\util\solver.py in check_solver_status(status, raise_error)
    406     elif status is None:
    407         raise RuntimeError(
--> 408             "model was not optimized yet or solver context switched")
    409     else:
    410         raise OptimizationError("solver status is '{}'".format(status))

OptimizationError: solver status is 'time_limit'

```

#### Possible fix
For me, it worked to add the following two lines to the check_solver_status() function in cobra.util.solver:
```python
elif status == optlang.interface.TIME_LIMIT and not raise_error:
        warn("solver status is '{}'".format(status), UserWarning)
```
In this case, it gives the warning that the solution found wasn't optimal, but the program still continues and the solution so far can be retrieved.

**Comment by Midnighter** [comment]
Definitely, thank you for reporting this.

**Comment by cdiener** [comment]
There is actually a whole list of solver states that still permit you to get the solution but are blocked by cobrapy. For instance `[NUMERIC, FEASIBLE, SUBOPTIMAL, ITERATION_LIMIT]`. Interior point methods often do not converge completely so having non-optimal states is quite common there...

**Comment by Midnighter** [comment]
Same as #691. I have some time before in early October where I could look into this. What do you think @cdiener?

**Comment by cdiener** [comment]
Would be great to get that fixed. Had to rewrite large parts of the Solution object in `micom` to get around that (https://github.com/resendislab/micom/blob/master/micom/solution.py). Since it affects me as well I could look into it...
