### ISSUE TITLE
Appveyor builds?

### ISSUE THREAD

**Issue by pstjohn** [opencobra/cobrapy#692]
Anyone know why the appveyor builds are failing? #689 for instance, but it looks like all of them are having the same issue

**Comment by cdiener** [comment]
Ah sure. Conda is outdated. Had similar problems with other packages and just had to clear the cache.

**Comment by Midnighter** [comment]
I just tried to delete the caches via their REST API. Let's see if it helps.

**Comment by Midnighter** [comment]
Just fixed by #697.
