### ISSUE TITLE
Installing cobra through anaconda

### ISSUE THREAD

**Issue by caonetto** [opencobra/cobrapy#693]
Is this installation feasible? Ive been trying to get a working cobra but there always seems to be solver problems, they don't get recognised even if I install them. Any ideas?

Cheers.

**Comment by Midnighter** [comment]
Hey, that's not a lot of information to go on. If you install cobrapy in a conda environment it comes with swiglpk so you should always have GLPK available to you. What other solvers did you try to install? If you have a GUROBI license you can directly install it with pip or maybe even from conda channels.

**Comment by caonetto** [comment]
Hi Midnighter thanks for your reply.
I had problems with swiglpk in the conda installation so I ended up installing cobrapy through pip. I could not figure out what was the issue associated to the conda installation.

Thanks for your help.

**Comment by pstjohn** [comment]
There was a somewhat recent update: bioconda/bioconda-recipes#7340 ?
But I'd agree that issues related to a conda-installed cobrapy might be better addressed to that repository

**Comment by cdiener** [comment]
We already were at that point once and basically decided no since there were some problems with the C extensions (which still seem to exist). I think since pip now has binary wheels for all major platforms there is no real need...

**Comment by phantomas1234** [comment]
I am closing this one as I don't see this happening anytime in the future (at least not from our side).
