### ISSUE TITLE
JSON export version attribute doesn't match JSON-Schema

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/cobrapy#720]
#### Problem description

Our team (credit @dbourdeveloper) noticed that the JSON output has a version attribute as a string, but the JSON-Schema specifies that it should be a number:

https://github.com/opencobra/cobrapy/blob/1ca1bf34508e7380e386935e1664ceab21359603/cobra/io/json.py#L13
https://github.com/opencobra/cobrapy/blob/1ca1bf34508e7380e386935e1664ceab21359603/cobra/io/json.py#L148

Since I'm here, a small suggestion: It would be great to pull the JSON-Schema document out into an independent file, so it can be more easily incorporated into non-Python projects.

Thanks!!

**Comment by Midnighter** [comment]
> It would be great to pull the JSON-Schema document out into an independent file, so it can be more easily incorporated into non-Python projects.

Sure thing. I would change the type to string, I think so that we can use a semantic version in future.

Do you have any other thoughts regarding the schema? Is it still serving your purposes?

**Comment by zakandrewking** [comment]
It's been great for us. Semantic versioning is cool, but you'll have to
think about what constitutes a "non-breaking change". Some previous
discussion:

https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/

We have one now for ME-models too. In fact, I think we should JSON-Schema
everything.

**Comment by zakandrewking** [comment]
@Midnighter I can submit a PR for this if the solution is to just switch the type in the JSON Schema to "string".

I can also pull the schema out into a separate file if you want, or just leave it as is.

**Comment by Midnighter** [comment]
My rationale for waiting on this was that we will soon have compartment classes and thus need a version `"2"` as well. If this is very urgent for you then feel free to make a PR, please. Type string and a separate file would be nice. If you can load that file using https://importlib-resources.readthedocs.io/en/latest/ I would much appreciate. Otherwise as announced earlier, we will do a lot of work on cobrapy in August and cover this as well.

**Comment by zakandrewking** [comment]
Ok. I'm not in a rush. Let's leave this open to wait for version "2".

**Comment by Hemant27031999** [comment]
Are there any updates on this? Though the solution of this issue is quite simple and has already been discussed, json_schema still shows the version type to be an integer instead of string.
Thanks.

**Comment by Midnighter** [comment]
The basic problem was addressed by #956.
