### ISSUE TITLE
No warning raised for adding reactions existing in the model

### ISSUE THREAD

**Issue by hvdinh16** [opencobra/cobrapy#723]
Hi all,

I used the following code to add 'RXNID' to the model and this ID is already used by a reaction in the model.
rxn = cobra.Reaction('RXNID')
model.add_reactions([rxn])

There is no warning raised when I execute the code. When I check the reaction 'RXNID' with the below script, the 'RXNID' is not replaced and information is intact.
model.reactions.RXNID

I use cobra version 0.10.1, commit 8ceee36f262754dd6aee4944f79191d362fbd6fc

**Comment by cdiener** [comment]
At least in version 0.13.0 that does not seem to happen:

```Python
In [1]: from cobra.test import create_test_model

In [2]: mod = create_test_model("ecoli")

In [3]: r = mod.reactions.ATPM.copy()

In [4]: r
Out[4]: <Reaction ATPM at 0x7ff8a5397518>

In [5]: mod.add_reaction(r)
Ignoring reaction 'ATPM' since it already exists.
```

Could you update your cobrapy and check whether the problem persists?

**Comment by hvdinh16** [comment]
I have updated to 0.13.0. The problem still persists for me but a warning "No handlers could be found for logger "cobra.core.model"" popped up. I added the reaction in a different manner from your script. Here is my script.

```
In [1]: import cobra

In [2]: from cobra.test import create_test_model

In [3]: mod = create_test_model('ecoli')

In [4]: r = cobra.Reaction('ATPM')

In [5]: r
Out[5]: <Reaction ATPM at 0x7f3650c66d10>

In [6]: mod.add_reactions([r])
No handlers could be found for logger "cobra.core.model"

In [7]: mod.add_reaction(r)

In [8]: mod.reactions.ATPM
Out[8]: <Reaction ATPM at 0x7f36511d9750>

In [9]: r
Out[9]: <Reaction ATPM at 0x7f3650c66d10>
```

**Comment by cdiener** [comment]
Hi thanks. So it seems something is off with the logger in your case, since it seems to be called but has no handler attached.
