### ISSUE TITLE
Boundary and exchange reactions are defined inconsistently. 

### ISSUE THREAD

**Issue by JanetMatsen** [opencobra/cobrapy#727]
#### Problem description

I noticed that you can add an "exchange" reaction as one of three supported boundary types in `model.add_boundary`.  It is thus confusing that all boundary reactions are considered `exchange` reactions by `model.exchanges`.  

* [model.py](https://github.com/opencobra/cobrapy/blob/master/cobra/core/model.py)
* [reaction.py](https://github.com/opencobra/cobrapy/blob/master/cobra/core/reaction.py)

Proposals: 
(1) It would be much more clear if the `exchanges` attribute of `model` were changed to `boundary_reactions`.
(2) Another possible change could be to have `model.exchanges` return only the type of boundary reactions that are exchanges.  

Looks like @hredestig and @Midnighter added this `exchange` property.  (Thanks!  And sorry if I'm confused.).

I'm happy to submit a PR if you like proposal (1).

**Comment by cdiener** [comment]
Hi, I think https://github.com/opencobra/cobrapy/pull/719 might have already changed a lot of that behavior (deployed in version 0.13.0). Right now you can get different boundary reactions by type as described [here](https://cobrapy.readthedocs.io/en/stable/media.html#Boundary-reactions).

**Comment by JanetMatsen** [comment]
Wow, hot off the press!  Thanks.  I'll upgrade right now.   

A related question I had is about the definition of a "sink" reaction.  I find it surprising that a "sink" boundary reaction, as added by `model.add_boundary` has bounds (-ub, ub).  This could make carbon or energy appear for free.

**Comment by cdiener** [comment]
So we use the definitions taken from [this publication](http://doi.org/10.1038/nprot.2009.203). Honestly, before I wrote the code I also believed that a sink should be irreversible and only consume a metabolite but @Midnighter pointed out that this is not the strict definition of "sink" :sweat_smile:

**Comment by cdiener** [comment]
Important to mention that we always welcome contributions so please don't hesitate to do so if you see anything that could be improved/changed. Thanks!

**Comment by gregmedlock** [comment]
FWIW, this convention question comes up for every new member in our group. We have only ever used "demand" to refer to boundary reactions with an intracellular metabolite which are either constrained to force flux through the demand reaction or are set as the objective for debugging/testing maximal production (i.e. one way or another, you are actually "demanding" flux through the reaction). We only use "sink" to refer to irreversible boundary reactions with an intracellular metabolite allowed to leave the system (it's a sink, not a faucet). The convention of sink reactions being reversible in the protocol paper/COBRA toolbox is just confusing, and I think there are more people confused by the convention than there would be COBRA toolbox users converting to cobrapy that get upset by breaking the convention.

**Comment by cdiener** [comment]
@gregmedlock do you have a reference that includes a definition as it is used in your group?

**Comment by Midnighter** [comment]
Please also take a look at https://github.com/biosustain/cameo/issues/185#issuecomment-329412220. Since the current implementation doesn't **prevent** the expected behavior, I'm a bit hesitant to make changes. It's counter-intuitive nature might lead to a sink being used as a source but that would immediately show up in a `Model.summary`.

Basically, the authors say that sinks should only be used in the construction process as a temporary tool. If you are building your own model, I kind of expect you to know the mechanics rather well.

**Comment by JanetMatsen** [comment]
Thanks for all your thoughts!  I'm ok with closing this.

**Comment by mjenior** [comment]
Along similar lines, it appears that add_boundary, while adding the desired reaction, does not update model.exchanges or model.boundary. If you add a boundary with type='exchange' and lb=-1000. and ub=1000., the reaction is added and returns correctly is you use get_by_id. However, if you are doing a membership check against .boundary or .exchanges, it seems to always return False.

**Comment by mjenior** [comment]
Hi @Midnighter,

Absolutely, opening new issue now. Also, I am currently using version 0.13.0.

**Comment by sumanasri** [comment]
Is there an equivalent of addDemandReaction in cobrapy? Or should  I add a demand reaction as a new reaction? Suppose I want to maximize nadph[c], should I add the following reaction or is there an automatic one call function that does this? Thanks.
DM_nadph[c]	nadph[c] ->
