### ISSUE TITLE
'Model' object has no attribute 'add_boundary'

### ISSUE THREAD

**Issue by silviamorins** [opencobra/cobrapy#731]
Hi,
I'm trying to execute the command
```
model.add_boundary(model.metabolites.get_by_id(metaid), type = "exchange")

```
, where meta id is the id of my metabolite.
in Jupyter notebook on a MacOC Sierra 10.12.6, after importing my SBML model, which is valid according to the SBML online validator, and is read in fine in the notebook. However, I get the error:
```
AttributeError: 'Model' object has no attribute 'add_boundary'

```
even though "add_boundary" is a cobra.core.model.Model method. Do you know why this might be happening?

<details>

System Information
==================
OS              Darwin
OS-release      16.7.0
Python           3.6.4

Package Versions
================
pip              9.0.1
setuptools      38.5.1
cobra           0.11.2
future          0.16.0
swiglpk          1.4.4
optlang          1.3.0
ruamel.yaml    0.14.12
pandas          0.22.0
numpy           1.14.0
tabulate         0.8.2
python-libsbml  5.16.0
lxml             4.1.1
</details>

**Comment by Midnighter** [comment]
That's a little curious :smiley: `add_boundary` is definitely available in cobra version 0.11.2 which you are running. Are you creating a subclass of `cobra.Model`? Did you modify the specific instance of `cobra.Model` by accident?

Can you run below code and confirm that it works for you, please?

```python
from cobra.test import create_test_model


if __name__ == "__main__":
    model = create_test_model("textbook")
    model.add_boundary(model.metabolites.get_by_id("glu__L_c"), type="sink")
    print(model.slim_optimize())
```

Otherwise maybe the environment where you are running your notebook is different from where you ran the version information?

**Comment by silviamorins** [comment]
To my knowledge I am not creating a subclass of cobra.Model, no.

your code:
```
from cobra.test import create_test_model


if __name__ == "__main__":
    model = create_test_model("textbook")
    model.add_boundary(model.metabolites.get_by_id("glu__L_c"), type="sink")
    print(model.slim_optimize())
```

does not work for me. I get again:
```
AttributeError: 'Model' object has no attribute 'add_boundary'
```

you were right about the environment: I ran the check on the terminal, and not in the notebook. in the notebook I get:
```
from cobra import show_versions
show_versions()

ImportError: cannot import name 'show_versions'
```
even tough I had imported cobra.

**Comment by Midnighter** [comment]
The function `show_versions` was introduced in cobra version 0.7.0 so your notebook environment must have a much older version. I don't know if you use Anaconda or some other environment. The easiest might be to run the following command inside of your notebook:
`!pip install --upgrade cobra`.

**Comment by silviamorins** [comment]
I no have that ```!pip install --upgrade cobra```prints ```Requirement already up-to-date: cobra in pathway_to_file/site-packages (0.13.0)```.

The output of show_versions has not changed, though. I might be doing something wrong, but I am not aware of what..

**Comment by Midnighter** [comment]
Can you write to me directly on `gitter.im`, please? You can simply log in with your GitHub account.

**Comment by pstjohn** [comment]
you probably have multiple versions of and / or python installed. `which python` and `which jupyter` might give you some clues, as would `import cobra; cobra.__version__` from both places

**Comment by Midnighter** [comment]
We seem to have resolved the issue for now.

I'm tempted to create an Anaconda version of cobrapy since it seems to happen more and more that we have Anaconda users who unknowingly install the extremely old cobra conda package. :unamused:

**Comment by pstjohn** [comment]
I've got some experience with conda-forge, and its fairly straightforward to repackage a pip package.
