### ISSUE TITLE
Confusing optimisation results

### ISSUE THREAD

**Issue by silviamorins** [opencobra/cobrapy#737]
#### Problem description

I've tried to optimise a very single pathways, just to see if it worked, and it gave me strange results; so I've built the minimal example I explain here, but I still don't understand where it's the problem. I've built a very simple model, one reaction, and added all the exchange reactions necessary to allow fluxes (I've attached the SBML file).
[onereaction_example_withpseudoreactions.xml.zip](https://github.com/opencobra/cobrapy/files/2200831/onereaction_example_withpseudoreactions.xml.zip)

I'm running this model with CobryPy in Jupyter Notebook.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

With the following code:
```python
import cobra
model = cobra.io.read_sbml_model("path/onereaction_example_withpseudoreactions.xml")
model.objective = "HEX1"
solution = model.optimize()
print('solution: {}'.format(solution.f))

from pprint import pprint
print('Summary of fluxes: ')
pprint(model.solution.x_dict)
```
I get the output:
```python
solution: 0.0
Summary of optimization: 
{'DM_g6p_c': 0.0,
 'EX_adp_c': 0.0,
 'EX_atp_c': 0.0,
 'EX_glc__D_c': 0.0,
 'HEX1': 0.0}
```

I don't understand why I get 0 as result, even though I am allowing fluxes. If I apply contraints to the model:

```python
model.reactions.EX_glc__D_c.bounds = (-10,-10)
solution = model.optimize()
print(solution)
```
The output is:
```python
<Solution 'infeasible' at 0x11953e5f8>
```
Any idea of why this is happening?

<details>

System Information
==================
OS              Darwin
OS-release      16.7.0
Python           3.6.4

Package Versions
================
pip              9.0.1
setuptools      38.5.1
cobra           0.11.2
future          0.16.0
swiglpk          1.4.4
optlang          1.3.0
ruamel.yaml    0.14.12
pandas          0.22.0
numpy           1.14.0
tabulate         0.8.2
python-libsbml  5.16.0
lxml             4.1.1
</details>

**Comment by Midnighter** [comment]
Hi @silviamorins,
Basically, (at least in the model that you attached) the exchange for protons was missing. Thus when you force a flux through the glucose exchange the problem becomes infeasible.

[Please take a look at this notebook.](https://github.com/opencobra/cobrapy/files/2201105/simulate_one_reaction.ipynb.gz)

Also, your code uses the old solution attributes which are deprecated and will be removed soon.

**Comment by silviamorins** [comment]
I'm sorry, my bad: my script parsed the exchange reaction somehow wrong and I din't realise the one for h_c got lost. Thank youQ, also for pointing out about the old solution attributes.
