### ISSUE TITLE
different loopless FVA results after upgrading from 0.9.0 to 0.13.3

### ISSUE THREAD

**Issue by JanetMatsen** [opencobra/cobrapy#738]
#### Problem description

I've noticed that the FVA results between 0.9.0 and 0.13.3 are different when loopless=True.  In particular, it seems like version 0.13.0 can produce higher maximum FVA values.

The FVA values are consistent between 0.9.0 and 0.13.3 when `loopless=False`, so this is a loopless-specific issue.   

The reproducible example below only shows differences of only a few fold change.  However, for other (larger) models, I've seen the max FVA value get close to the upper_bound (1000) in version 0.13.3 but not 0.9.0.    

#### Code Sample

This script generates a dataframe summarizing FVA values for glutamate production.  The column names of the resulting dataframe and the filename contain the Cobra version as part of the string.  

I made two different virtual environments via `pip install cobra==0.9.0` and `pip install cobra==0.13.3` and ran this script, then merged and investigated the results.  

```
# coding: utf-8
# In[1]:
import cobra

# In[2]:
version = cobra.__version__
print(version)

# In[3]:
from cobra.test import create_test_model

# In[4]:
model = create_test_model("textbook")

# In[5]:
objective_id = 'glutamate_disappearance'

disappearance = cobra.io.dict.reaction_from_dict({
    'id': objective_id,
    'lower_bound': 0,
    'upper_bound': 1000,
    'metabolites': {'glu__L_c': -1}
}, model)

model.add_reactions([disappearance])

# In[6]:
model.reactions.glutamate_disappearance

# In[7]:
model.objective = objective_id

# In[8]:
from cobra.flux_analysis.variability import flux_variability_analysis

df = flux_variability_analysis(model, loopless=True)
df.reset_index(inplace=True)

new_colnames = {
    'index':'reaction id',
    'maximum': f'maximum {version}',
    'minimum': f'minimum {version}',
}

df.rename(columns=new_colnames, inplace=True)
df.head()

# In[9]:
fname = f'180726_FVA_glutamate_version_{version}.csv'
print(fname)

df.to_csv(fname, index=False)
```

#### Output Difference

![screen shot 2018-07-26 at 8 30 03 am](https://user-images.githubusercontent.com/406350/43272154-23896722-90ae-11e8-95ed-29a33a8ef8d5.png)

![screen shot 2018-07-26 at 8 30 09 am](https://user-images.githubusercontent.com/406350/43272163-28ae166c-90ae-11e8-9ab0-b5900bf78773.png)

#### Dependency Information

Version 0.9.0:
<details>
System Information
==================
OS           Darwin
OS-release   16.7.0
Python        3.6.2

Package Versions
================
pip           9.0.1
setuptools   36.4.0
cobra         0.9.0
future       0.16.0
swiglpk       1.4.4
optlang       1.4.2
ruamel.yaml 0.14.12
pandas       0.23.3
numpy        1.15.0
tabulate      0.8.2
</details>

Version 0.13.3:
<details>
System Information
==================
OS         Darwin
OS-release 16.7.0
Python      3.6.2

Package Versions
================
cobra        0.13.3
depinfo       1.4.0
future       0.16.0
numpy        1.15.0
optlang       1.4.2
pandas       0.23.3
pip           9.0.1
ruamel.yaml 0.14.12
setuptools   36.4.0
six          1.11.0
swiglpk       1.4.4
tabulate      0.8.2
wheel        0.29.0
</details>

Zipped analyses files, so you can run `run.sh` yourself: 
[scripted.zip](https://github.com/opencobra/cobrapy/files/2232894/scripted.zip)

**Comment by cdiener** [comment]
Probably related to #698. There were definitely changes in the look less code between those versions...

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
