### ISSUE TITLE
Checking model.exchanges membership

### ISSUE THREAD

**Issue by mjenior** [opencobra/cobrapy#747]
I am currently trying to check the membership of model.exchanges to make sure all of the metabolites I have added exchanges for are taken care of properly. When I check for previously existing exchanges as a test I get the correct result of True, but when I check for those I added via add_boundary I always get False returned. This is using cobrapy version 0.13.0

I am adding reactions like this:
```python
cpd00141_e = cobra.Metabolite(
    'cpd00141_e',
    formula='C3H5O2',
    name='Propionate',
    compartment='Extracellular')

model.add_boundary(cpd00141_e, type='exchange', reaction_id='EX_cpd00141_e', lb=-1000.0, ub=1000.0)
```

And checking membership this way, which always returns False:
```python
model.reactions.get_by_id('EX_cpd00141_e') in model.exchanges
```

But the reaction is definitely in place when 
```python
model.reactions.get_by_id('EX_cpd00141_e')
```

This metabolite (cpd00141_e) is already included in a transport reaction I added prior to this check.

**Comment by Midnighter** [comment]
It used to work fine in 0.12.0 but doesn't any longer in 0.13.0. I think it's a silent problem with the compartment so in your example above if you change the metabolite's compartment to `'e'` it should work.

Of course, there needs to be a warning at least or maybe even an exception.

**Comment by Midnighter** [comment]
I suspect the same might happen for sinks and demands if the compartment is not intracellular. Any ideas @ChristianLieven and @cdiener?

**Comment by cdiener** [comment]
I agree it is inconvenient. The thing is that there is no sure way to identify the actual "external" compartment in a model. What `model.exchanges` does is use a heuristic where it considers the compartment with the most boundary reactions the external compartment (this usually works). Are you sure that in your model the external compartment is indeed "External" and not "e"? Checking some other exchange reactions might help with that...

**Comment by mjenior** [comment]
The base model I am working with was a automatically generated with the ModelSEED pipeline, and the original compartments are indeed labeled 'c' and 'e'. I went through the model and changed it to 'Cytosol' and 'Extracellular for a little more clarity, and when I go back and check there aren't any remaining instances of the previous labels. I think @Midnighter was correct because model.exchanges seemed to work as expected in an earlier version of cobrapy.

**Comment by pstjohn** [comment]
@cdiener, it might be useful to have a model attribute to explicitly specify the external compartment if its ambiguous. I got into trouble recently when I had a bunch of cytoplasmic sinks and the model wanted to flag the cytoplasm as the external compartment.

**Comment by pstjohn** [comment]
Yeah that could work, but some option to specify I think it important. I was surprised recently since I added those sinks slowly to the cytoplasm, and suddenly model.medium changed its behavior when the external compartment was no longer clear.

**Comment by cdiener** [comment]
Hmm, yes that is not good behavior. Or convert model.exchanges to be a function that requires explicit definition of the of the external compartment (and enforce the same requirement for model.medium).

**Comment by pstjohn** [comment]
I'd be 👎 on that idea, (specifically for medium) since part of the benefit was being able to set the medium to give specific boundary conditions. Although I suppose you could also do model.set_medium, but that seems like a feature regression.

**Comment by cdiener** [comment]
That would leave only the direct attribute. But how do we ensure that it is always set?

**Comment by ChristianLieven** [comment]
Now with model.Compartments being objects soon I'd see either of these options viable:

> Either with an SBO annotation or an attribute...

But we still need to infer which compartment is indeed the extracellular compartment for all the models that don't explicitly set it. So adding a warning to the function that is responsible for that showing the user which compartment was inferred is crucial too in my opinion to allow the user to be aware of issues.

**Comment by cdiener** [comment]
All additional heuristics would help. A warning also seems like a good idea to me.

**Comment by cdiener** [comment]
Will take that on since it seems slightly serious. Will probably add a temporary fix to get the external compartment by name rather than by the heuristic and throw an explicit warning if the heuristic is used.
