### ISSUE TITLE
issue with metabolites starting with a digit

### ISSUE THREAD

**Issue by phibern** [opencobra/cobrapy#751]
Hi,

I am using cobrapy with biggs models in spyder/python 3.6. 
I run into an issue, when defining reactions which start with a digit as first letter, for other reactions no problem. Any suggestion on that issue, how to handle it. here is an example:

# just an example which doesnt make sense but works
new_reaction.add_metabolites({ model.metabolites.g3p_c : -1, model.metabolites.h_c: 1 })
# just an example which doesnt make sense and doesnt work
new_reaction.add_metabolites({ model.metabolites.g3p_c : -1, model.metabolites.13dpg_c: 1 })

Here python gives an error:
    new_reaction.add_metabolites({ model.metabolites.g3p_c : -1, model.metabolites.13dpg_c: 1 })
                                                                                                                               ^
SyntaxError: invalid syntax

**Comment by Midnighter** [comment]
This is a limitation imposed by Python. You can only use metabolites, reactions, and genes in this way if they have a valid Python identifier. That means they have to start with a letter. However, you can still access these in the following way:

```python
metabolite = model.metabolites.get_by_id("13dpg_c")
```

Same with `model.reactions` and `model.genes`.
