### ISSUE TITLE
PFBA strange output

### ISSUE THREAD

**Issue by paxelito** [opencobra/cobrapy#753]
#### Problem description

Hi, If I perform both an FBA and PFBA analysis, I obtain two very different results. I thought it was my model, nevertheless also following the documentation and reproducing the same code, the difference remains, see below.

```python
import cobra.test
model = cobra.test.create_test_model("textbook")
fba_solution = model.optimize()
pfba_solution = cobra.flux_analysis.pfba(model)

fba_solution 
Optimal solution with objective value 0.874

pfba_solution
Optimal solution with objective value 518.422
```
Nevertheless If i run the same test as in the documentation, I got the same result

#### Code Sample
```python
abs(fba_solution.fluxes["Biomass_Ecoli_core"] - pfba_solution.fluxes["Biomass_Ecoli_core"])
```
1.1102230246251565e-16

#### Dependency Information

System Information
==================
OS         Darwin
OS-release 17.7.0
Python      3.6.5

Package Versions
================
cobra        0.13.3
depinfo       1.4.0
future       0.16.0
numpy        1.15.1
optlang       1.4.3
pandas       0.23.4
pip            18.0
ruamel.yaml 0.14.12
setuptools   39.1.0
six          1.11.0
swiglpk       1.5.1
tabulate      0.8.2

</details>

Any ideas?

**Comment by gregmedlock** [comment]
Hi Alessandro,

in pFBA, the objective is the sum of flux through all reactions, which is
the value you see returned in pfba_solution.

if you look at flux through the previous objective in the model (presumably
biomass production), you will find that it is constrained to 0.874 in the
pFBA model, and that this flux through biomass is achieved when minimizing
the sum of fluxes in the model.

Greg

**Comment by paxelito** [comment]
Ok, that' clear. I wrongly thought that the result was always the growth rate, and the flux minimisation was part of the algorithm. That's ok, thanks you very much for the explanation
