### ISSUE TITLE
gapfill using parallel computing

### ISSUE THREAD

**Issue by rcolpo** [opencobra/cobrapy#755]
Is there any perspective for the gapfill algorithm to be able to use parallel computing?

Thanks.
Rodrigo.

**Comment by gregmedlock** [comment]
Hi Rodrigo,

I haven't seen this discussed anywhere--do you have an application in mind
that would demand it?

In the past when I wanted to perform gapfilling many times using an MILP
formulation, I used a high performance computing cluster and just created
many serial jobs and wrote a bash script to submit them. If you have access
to an HPC cluster that uses a SLURM scheduler I'm happy to share some
example scripts. However, there is probably an alternative way to solve
your issue that would not be so computationally demanding.

There is already some parallelization going on under the hood for most
commercial solvers, although I am unsure to what extent optlang takes
advantage of this. I personally don't see much benefit to parallelization
beyond the solver level.

Greg

**Comment by Midnighter** [comment]
At least CPLEX will take advantage of the full number of cores available on your machine so parallelization does happen at the most appropriate level in my opinion. If the solver that you're using doesn't support parallel processing, please [open an issue on optlang for it](https://github.com/biosustain/optlang/issues/new). Please re-open if there is more to be discussed.
