### ISSUE TITLE
getting a list of reactions either producing or consuming a metabolite

### ISSUE THREAD

**Issue by sumanasri** [opencobra/cobrapy#771]
#### Problem description

Please explain:
I need a list of reactions either producing or consuming a metabolite
I tried getting a frozenset of reactions
model.metabolites.get_by_id("atp_c").reactions
but I am unable to get only those where atp_c is produced?

Can you please help me?

**Comment by sumanasri** [comment]
Ii need to compute the sum of production fluxes for a given metabolite. I would like to do it within the python script. Parsing summary output would be a tedious way to do this. A simple interface would help.

**Comment by sumanasri** [comment]
I need to coompute total ATP, NADH and NADPH synthesized. What is the best way to compute these within the script? Thanks.

**Comment by Midnighter** [comment]
Hi @sumanasri, please be aware that you cannot compute accumulation of compounds with the FBA framework. What you can do is look at the formation fluxes in the steady state. You can use the following code to compute fluxes per metabolite:

```python
def metabolite_flux_balance(metabolite, solution):
    """
    Return a vector of reaction fluxes scaled by the stoichiometric coefficient.

    Parameters
    ----------
    metabolite : cobra.Metabolite
        The metabolite whose fluxes are to be investigated.
    solution : cobra.Solution
        Solution with flux values.

    Returns
    -------
    pandas.Series
        A vector with fluxes of reactions that consume or produce the given
        metabolite scaled by the corresponding stoichiometric coefficients. The
        reaction identifiers are given by the index.
    """
    rxn_ids = list()
    adj_flux = list()
    for rxn in metabolite.reactions:
        coef = rxn.get_coefficient(metabolite)
        rxn_ids.append(rxn.id)
        adj_flux.append(coef * solution.fluxes[rxn.id])
    return Series(data=adj_flux, index=rxn_ids, dtype=float, name="reaction")
```

You can then use it to sum up formation fluxes:

```python
atp_flux = metabolite_flux_balance(model.metabolites.atp_c, solution)
influx = atp_flux[atp_flux > 0.0].sum()
```

**Comment by sumanasri** [comment]
Thanks. Will try it out.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be an issue for you.

**Comment by sumanasri** [comment]
Thanks. I have used the function successfully.

**Comment by rmekuli** [comment]
Hello, 
Using the model.metabolites.get_by_id("atp_c").summary() does not seem to show all the reactions it is involved in.
To be more specific, I tried: 

model.metabolites.get_by_id("2fe2s_c").summary()

It shows some reactions but it fails to show its involvement in biotin synthesis reaction for example. Am I missing something?
