### ISSUE TITLE
ImportError: cannot import name 'get_installed_distributions' from 'pip'

### ISSUE THREAD

**Issue by Karrenbelt** [opencobra/cobrapy#772]
#### Problem description

Upgrading to pip==18.1.0 yields an error when trying to import cobra after

#### Code Sample

```python
ImportError: cannot import name 'get_installed_distributions' from 'pip'

```

downgrading back to 18.0.0 for now

**Comment by cdiener** [comment]
I just tried to reproduce that in a docker image with pip 18.1 and could not reproduce it. Could you try updating you dependencies as well? Especially `depinfo`... 

```bash
pip install -U depinfo
```

Thanks!

**Comment by Midnighter** [comment]
This was a problem with `pipdeptree` but there has been a release since. Please, `pip install -U pipdeptree` and all should be fine with the latest pip version.
