### ISSUE TITLE
update contact in contributing guidelines

### ISSUE THREAD

**Issue by BenjaSanchez** [opencobra/cobrapy#778]
#### Problem description

The contributing guidelines need to be updated. Step 4 of ["Pull Request Guidelines"](https://github.com/opencobra/cobrapy/blob/devel/.github/CONTRIBUTING.rst#pull-request-guidelines) states:

> Assign a reviewer to your pull request. If in doubt, assign Henning Redestig.

**Comment by Midnighter** [comment]
Thanks, yes. Our entire documentation needs some love urgently :cry:
