### ISSUE TITLE
Additional functions for Reaction object

### ISSUE THREAD

**Issue by jlerman44** [opencobra/cobrapy#78]
It would be nice to have functions to rename reaction ids and names. 

Currently, if the user changes the reaction name by doing reaction.id = new_id, the old_id stays in the dictlist. 

The user has to know this and manually update the index with:
cobra_model.reactions._generate_index() . One alternative to adding functions is to improve documentation on the Reaction object. 

I can do a pull request if people think either is a good idea.

Josh

**Comment by phantomas1234** [comment]
Wouldn't it be better to make `id` a property in `Object` and then (for example for a reaction) do something along the lines of

    @id.setter
    def id(self, value):
        self._id = value
        if self._model is not None:
            self._model.reactions._generate_index()

?

**Comment by aebrahim** [comment]
Josh does this work?
http://cobrapy.readthedocs.org/en/latest/faq.html#how-do-i-rename-reactions-or-metabolites

Niko that is a good idea but it will break pickle compatibility which is
annoying. I really wish we could ditch pickles. I could probably patch
setstate to get around this.

**Comment by aebrahim** [comment]
In trying this out, I found an issue: the Object doesn't know which list it belongs to, so every type would need its own setter. That makes this even more work.

Generally I like the idea, but I may have to postpone working on implementing it for the time being.

**Comment by phantomas1234** [comment]
I don't get why this breaks pickling but you're right about the additional boilerplate code introduced by properties. I think it's worth it though. Maybe I'll try to get to an acceptable pull request myself if I find the time.
