### ISSUE TITLE
model.add_boundary ignores optional argument reaction_id

### ISSUE THREAD

**Issue by migp11** [opencobra/cobrapy#783]
#### Problem description

When adding a boundary reaction to the model passing a custom id for the new boundary reactions (see code) the model rises an exception.

After inspecting cobra.core.model I've found:
    503        if type in types:
    504             prefix, lb, ub = types[type]
    505             reaction_id = "{}_{}".format(prefix, metabolite.id)
    506         if reaction_id in self.reactions:
--> 507             raise ValueError('boundary %s already exists' % reaction_id)
    508         name = "{} {}".format(metabolite.name, type)
    509         rxn = Reaction(id=reaction_id, name=name, lower_bound=lb,

The expected behavior would be that if reaction_id is not None, the variable name should not be overwritten.

Hope its helps!

Please explain:
* **what** adding a demand variable and set a custom reaction_id
* **how** using the model function add_boundary
* **why** Because it ignores the reaction_id argument
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
model.add_boundary(model.metabolites.trp_L_c, type='demand', reaction_id='MY_DEMAND')
```

#### Actual Output
ValueError: boundary DM_trp_L_c already exists
#### Expected Output
the new reaction variable with the passed id
#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

[Paste output here.]

</details>

**Comment by migp11** [comment]
Ok, got it!

I've tried without setting the type, but it generate an EX_ prefixed reaction. I did not read the documentation carefully, my mistake.

Actually, I do not intend to have duplicate reactions, but sometimes models already has some demand (DM prefixed) reactions and I was trying to avoid errors, when adding my auxiliary variables, by using an alternative prefix. My current fix is to check for the demand reaction presence in the model, before trying to add it. 

Thank you for your answer!

**Comment by cdiener** [comment]
Yeah, for now setting the type to something custom will work around that. I guess your added demand is part of the new objective or has a non-zero extreme bound, so everything should still work.

**Comment by migp11** [comment]
Yes, it does work. Indeed you are right, this variables are part of the new objective I'm using.
In any case, I still found the behaviour of model.add_boundary(metabolite, reaction_id='custom_id') a bit unnatural... but it is just my opinion ;-)
Thanks for your feedback!

**Comment by cdiener** [comment]
I agree. Either the behavior should be changed or the docstring improved.

**Comment by tpfau** [comment]
As a suggestion:
Could you raise an error or a warning, when a user tries to add a type reaction and provides an ID?
Essentially, `reaction_id` and `type` seem to be mutually exclusive. If a valid type (i.e. one of the known types) is provided the id is ignored, so supplying an ID and a 'valid' type is kind of invalid use of the function.

**Comment by migp11** [comment]
In my opinion if a reaction_id is passed as an argument it should be set as the new reaction id, independently of what type of boundary reaction is being instantiated. As far as I see it, reaction type is related to the stoichiometry and bounds, whereas the reaction_id is more a user or modeller decision. Having said that, I recognize that standardizing the name of boundary reactions is a good practice, but the final decision should be left upon the user himself... Again, it is just my opinion

**Comment by Midnighter** [comment]
Good ideas, I will make a PR along those lines.

**Comment by Midnighter** [comment]
My only doubt is that we're checking the annotations for `"SBO"` but the official MIRIAM namespace is lowercase https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000024.

**Comment by Midnighter** [comment]
Please take a look at #788 and let me know what you think.

**Comment by cdiener** [comment]
> My only doubt is that we're checking the annotations for "SBO" but the official MIRIAM namespace is lowercase https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000024.

But the identifier pattern is upper case.

**Comment by Midnighter** [comment]
Yes, so I think it should be something like:

```python
reaction.annotation["sbo"] = "SBO:0000631"
```
rather than

```python
reaction.annotation["SBO"] = "SBO:0000631"
```

**Comment by cdiener** [comment]
Oh, okay. Yeah that makes sense. If you want go ahead and change that in the medium module.
