### ISSUE TITLE
Flux sampling on model with constrained sum of fluxes

### ISSUE THREAD

**Issue by mjenior** [opencobra/cobrapy#786]
#### Problem:
I have been having a problem with flux sampling after setting weighted linear coefficients for all reactions that contribute to a to a total sum of fluxes constraint on my model. None of the constraints explicitly close any reactions, just penalize the flux value based on previous pFBA results.

After I generate the sampling object with:

`sampling_object = ACHRSampler(constrained_model) `

and the try to generate samples with:

`flux_samples = sampling_object.sample(100)`

I get the consistent error message:

>  ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-42-0e4809f15f00> in <module>()
>       1 
> ----> 2 s1 = glucose_min_media_fluxes.sample(100)
>       3 glucose_min_media_fluxes.validate(s1)
> 
> /home/mjenior/anaconda2/lib/python2.7/site-packages/cobra/flux_analysis/sampling.pyc in sample(self, n, fluxes)
>     625         samples = np.zeros((n, self.warmup.shape[1]))
>     626         for i in range(1, self.thinning * n + 1):
> --> 627             self.__single_iteration()
>     628             if i % self.thinning == 0:
>     629                 samples[i//self.thinning - 1, ] = self.prev
> 
> /home/mjenior/anaconda2/lib/python2.7/site-packages/cobra/flux_analysis/sampling.pyc in __single_iteration(self)
>     586 
>     587     def __single_iteration(self):
> --> 588         pi = np.random.randint(self.n_warmup)
>     589         # mix in the original warmup points to not get stuck
>     590         delta = self.warmup[pi, ] - self.center
> 
> mtrand.pyx in mtrand.RandomState.randint()
> 
> ValueError: low >= high
> 

I tried trouble shooting with validate by:

`bad = numpy.random.uniform(-1000, 1000, size=len(constrained_model.reactions))
sampling_object.validate(numpy.atleast_2d(bad))`

with the output:

> array(['lue'], dtype='|S3')

I'm not sure what next steps to take to correct the issue, and any help would be greatly appreciated. Let me know if it would also be helpful to send the constrained model itself.

Version info:

> System Information
> ==================
> OS                     Linux
> OS-release 4.15.0-39-generic
> Python                2.7.14
> 
> Package Versions
> ================
> cobra        0.13.4
> depinfo       1.3.0
> future       0.16.0
> numpy        1.14.3
> optlang       1.4.2
> pandas       0.23.0
> pip            18.0
> ruamel.yaml 0.15.73
> setuptools   39.2.0
> six          1.11.0
> swiglpk       1.4.4
> tabulate      0.8.2
> wheel        0.29.0

**Comment by cdiener** [comment]
Thanks for the report. I can see one problem with a change in the numpy API that is causing the error here. Do you constrain a sum over the variables (irreversible fluxes) or the (reversible) fluxes? 

I will fix the obvious thing and maybe ping you to test it with your model.

**Comment by cdiener** [comment]
Can you also give me the output of `sampling_object.warmup.shape`, please?

**Comment by mjenior** [comment]
Thanks for the quick response! The output of `sampling_object.warmup.shape` is:

> (0, 5166)

I try to constrain only the irreversible fluxes with:

```
    constrained = copy.deepcopy(model)
    solver.fix_objective_as_constraint(constrained, fraction=optimum_fraction)
    constrained.objective = constrained.problem.Objective(Zero, direction='min', sloppy=True, name='_pfba')
    constrained.solver.update()
        
    var_coefficients = {}
    for rxn in constrained.reactions:            
        try: 
            coefficient = coefficient_dict[rxn.id]
        except KeyError:
            coefficient = 1.0
        var_coefficients[rxn.forward_variable] = coefficient
        var_coefficients[rxn.reverse_variable] = coefficient
      
    flux_sum_constraint = constrained.problem.Constraint(0, lb=0, ub=pfba_flux_sum)
    constrained.add_cons_vars([flux_sum_constraint])
    constrained.solver.update()
    flux_sum_constraint.set_linear_coefficients(coefficients=var_coefficients)

    sampling_object = ACHRSampler(constrained) 

```
I have a dictionary of linear coefficients associated with all reactions based on a weighting.

As a test I also tried to optimize the constrained model and did receive an infeasible solution. I was following the guide on cobrapy constraints [here](https://cobrapy.readthedocs.io/en/latest/constraints_objectives.html), but definitely could have done something incorrectly. I have been trying to set the coefficients to < -1 and > 1 to promote flux through different parts of the network, but I'm not 100% sure that's a reasonable thing to do. 

As a side note, I was also wondering if setting the previous objective to 'minimize' was sufficient to tell the flux sampler that my goal involves minimum flux through the model. If so, that might also mean it would be better to set the lower bound of the sum of fluxes constraint instead of the upper bound?

**Comment by Midnighter** [comment]
There is one issue with your problem formulation: By default the forward- and reverse-variables have bounds 0, 1000. In pFBA, for example, we just minimize the sum of all of those variables with uniform weights. If some of your factors in that sum are suddenly negative then the most optimal strategy is to have both forward- and reverse-variables take maximal values, e.g., 1000, in order to decrease the sum. However, the flux through such a reaction will then be zero (forward - reverse primal value). So maybe those are not the results you are expecting.

Also, you need to set the kind of linear coefficients on the objective itself. I don't see you doing that in the sample code above. The current objective is just to minimize zero. So you need both a constraint, in order to bound the flux sum but also set the same linear coefficients on the objective in order to minimize the sum.

**Comment by cdiener** [comment]
Hm. FVA returned no solutions so it does look like your model is indeed infeasible. Still the sampler should have caught that. Will investigate further...

**Comment by mjenior** [comment]
@Midnighter Interesting, I thought is was necessary to only add the constraints to the flux sum constraint because the objective is reset during flux sampling and would lose that information. I just retried it with adding the coefficients to both the objective and flux sum constraint and got the same ValueError. I will try to implement your other suggestion to see if that helps.

**Comment by Midnighter** [comment]
So what happens if you run that minimization before the sampling? Is that feasible?

**Comment by mjenior** [comment]
It is 40346.1697696, so that would put it above the upper bound of 12110.9040826.

**Comment by Midnighter** [comment]
And the line where you fix the previous objective as a constraint, what objective is that? Some kind of growth maximization or something else?

> It is 40346.1697696, so that would put it above the upper bound of 12110.9040826.

So if you set as the upper bound of the flux sum constraint, the sum of the pFBA solution fluxes times the coefficients from your dictionary you should be good. I'm not making any judgement about how meaningful those coefficients are, of course.

**Comment by mjenior** [comment]
Sorry, my objective is growth maximization (Biomass). I didn't think to look at that, the large difference in those values makes me ask does solution.fluxes actually incorporate solution.objective_value or are they kept separate? The coefficients are kind of arbitrary right now, I'm just working through the process of weighting some portions of the network over others based on pathways. When you say I should multiply the sum by the coefficients, do you mean the sum of those coefficients or each of them individually? Thanks again for the help!

**Comment by mjenior** [comment]
I just checked and the objective value is indeed included in the fluxes list, so I must have introduced something strange to problem during the process.

**Comment by Midnighter** [comment]
`solution.objective_value` and `solution.fluxes` are separate attributes so I'm not sure how this could have happened. Only when your objective was maximizing biomass, does the fluxes vector have an entry for the biomass reaction that is equal to the objective value, of course.

**Comment by Midnighter** [comment]
To try and explain what I meant above a bit better, I'm posting some untested Python code because I don't think there's math notation on GitHub.

```python
solution = pfba(model)
assert solution.objective_value == 12110.9040826

flux_sum = 0.0
for rxn in model.reactions:
    coefficient = coefficient_dict.get(rxn.id, 1.0)
    flux_sum += coefficient * rxn.forward_variable.primal
    flux_sum += coefficient * rxn.reverse_variable.primal

assert flux_sum == 40346.1697696
```

**Comment by cdiener** [comment]
I agree with @Midnighter that the hickup here has more to do with new constraint you introduce. If any of your coefficients in `coefficient_dict` are larger than one the problem might become infeasible. If you want to constrain on that new objective you would have to recalculate a new sum of fluxes first and use that in the objective (and not the previous pFBA result). For instance:

```Python3
ex = Zero
solver.fix_objective_as_constraint(model, 1.0)
for rxn in model.reactions:
    coef = coefficient_dict.get(rxn, 1.0)
    ex += coef * rxn.forward_variable + coef * rxn.reverse_variable 
model.objective = ex
model.objective_direction = "min"
min_val = model.slim_optimize()
const = model.problem.Constraint(ex, lb=min_val, ub=1.1 * min_val)  # allow 10% deviation
model.add_cons_vars([const]) 
```

You should be able to sample from that one.

As far as flux sampling goes there is also the limitation that we sample uniformly from the *irreversible* reactions. So even if the flux for a reaction is fixed (let's say `v=1`) you will get many samples like `v_fwd = 1000, v_rev = 999` or `v_fwd = 2, v_rev = 1`. So you get a lot of samples with `v=1` and that might not be a uniform distribution anymore. This can be avoided by fixing the flux direction as well.

**Comment by mjenior** [comment]
Fantastic! Both of you have been extremely helpful. @cdiener I thought by considering the forward and reverse variables separately, instead of just as a single reaction, it automatically integrated as though they were a linked pair of irreversible reactions. This thinking was modeling after my interpretation of the pFBA source code, so again I could be mistaken.

**Comment by Midnighter** [comment]
Please note that assembling an expression by adding to it in a loop is very slow because sympy does a lot of evaluation of the new expression in the background. Setting the linear coefficients as you showed at the beginning is much faster.

**Comment by mjenior** [comment]
@cdiener Two questions based on what you said. Why would setting a coefficient to be >1 make a given problem infeasible if you are still accounting for it during the sum of fluxes calculation? Also, how would mixed integers side step the limitation of the minimization and sampling incompatibility?

**Comment by cdiener** [comment]
@mjenior Yeah sorry, that was a lot of hand-waving. So let's use a simple example system where upper case letters denote metabolites and `v_*` the fluxes:

```
 ->  A  <->  B  ->
v_A    v_AB    v_B

0 <= v_A <= 1
-5 <= v_AB <= 5
0 <= v_B <= Inf
```

The objective is `v_B` and has a maximum of 1. If you fix it at one and solve the pFBA objective

`minimize v_A + v_AB_f + v_AB_r + v_b`

you get a unique optimum with `v_A = 1, v_AB = 1, v_B = 1`. So the pFBA objective is 3 and it corresponds to what you would get if you would sum the absolute values of the *reversible* fluxes as well. If you reweight the pFBA objective for instance as

`obj_2 = 2* v_A + v_AB_f + v_AB_r + v_b`

then `obj_2` must be 4 in order to maintain `v_B == 1`. However, if you give that new sum the old pFBA objective (3) as upper bound you can never fulfill that (since 4 > 3).

Mixed integer only works if you want to maximize the sum of absolute values. In our example if you want to drop the constraint on `v_B` and instead want to maximize the absolute sum of fluxes to get a solution that uses as many fluxes as possible (anti-parsimonious so-to-say), you would get:

`maximize v_A + v_AB_f + v_AB_r + v_b`

which has several optimal solutions, for instance:

```
v_A = 1, v_AB_f = 5, v_AB_r = 4, v_B = 1    sum = 11
v_A = 1, v_AB_f = 5, v_AB_r = 5, v_B = 0    sum = 11
```

The second one is obviously not very good. More importantly, none of those sums corresponds to the maximum sum of absolute values of the *reversible* fluxes which would be 3. You can use mixed integer indicator variables to only allow one direction in a flux (have either the forward or reverse be zero but never both active). That way `v_AB_f = 1` and `v_AB_r = 0` and you now get the same sum.

For sampling you can also get those weird cycles of `v_AB_f` and `v_AB_r` even if you constrain `v_AB = 1`. To avoid those you would have to set `v_AB_r` to zero by hand.

**Comment by mjenior** [comment]
@cdiener I see now, thank you for the explanation! That really helps with understanding of the method.  Also, that kind of leads to my last question on this issue for now, which is that means 0.0 should be excluded as a possible a priori coefficient to both sides of a reaction since it would essentially close it correct? Coefficients you are adding to a system should generally be >0 and <=1.0 to maintain feasible solution space?

**Comment by cdiener** [comment]
It might still be feasible even if you remove a reaction (for example if it is not necessary to produce biomass). But yes, using zero coefs for forward and reverse will remove that reaction. 

If you want to fall in the previous pFBA space you assertion is correct. You can still use coefs > 1 if you reoptimize and use the new optimum as a constraint, like in the sample code I posted above.
