### ISSUE TITLE
Suggestion to re-organize the repository

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#787]
Hey @opencobra/cobrapy-core 

I'm proposing two changes to the organization of the repository structure:

1. Move the `cobra` package into a `src/` directory.
2. Move the test suite out of the package itself into its own `tests` directory.

The second point would go hand in hand with moving the `load_model` logic from cameo into cobrapy so we have an alternative to the common strategy of using `from cobra.test import create_test_model`.

I'm using this structure on a number of other packages with great success. For a bit more background, please take a look at this blog post http://andrewsforge.com/article/python-new-package-landscape/

Please let me know if you agree or disagree with these changes. If you're not feeling motivated to argue a thumbs up or down is enough.

**Comment by synchon** [comment]
Sounds good to me.
