### ISSUE TITLE
gafill function is not defined

### ISSUE THREAD

**Issue by wh960823** [opencobra/cobrapy#796]
Hi: we want to use gapfill to gapfill the model, using the following codes:
import cobra 
from cobra.flux_analysis import gapfill
solution = gapfill(model, target, demand_reactions=True)
for reaction in solution[0]:
    print(reaction.id)

But, the terminal threw a Error:
NameError: name 'gapfill' is not defined

Why this error happen ? How can I solve that ?
Thanks,
William

**Comment by taylo5jm** [comment]
William,

What version of cobrapy and Python are you using? I would try to run your code, but `target` is not defined in your code. Are you running this code in the same order as you have listed above? 

I used some code from the documentation to see if I could get the same error. The code below works for me and I am using the latest version of cobrapy. Try to run it and let me know if you still get the same error. 

Best,
Justin

```
 import cobra
 import cobra.test
 model = cobra.test.create_test_model("salmonella")
 universal = cobra.Model("universal_reactions")
 for i in [i.id for i in model.metabolites.f6p_c.reactions]:
     reaction = model.reactions.get_by_id(i)
     universal.add_reaction(reaction.copy())
     model.remove_reactions([reaction])

model.slim_optimize()
soln = gapfill(model, universal, demand_reactions=False)
soln = gapfill(model, universal, demand_reactions=True)
```

![screen shot 2018-12-09 at 10 56 24 am](https://user-images.githubusercontent.com/6889169/49699601-242c7580-fba1-11e8-80c0-606608fd765c.png)

**Comment by Midnighter** [comment]
Please re-open this issue if you continue to have problems.
