### ISSUE TITLE
Could not load Recon 2.2

### ISSUE THREAD

**Issue by aliabenkahla** [opencobra/cobrapy#799]
#### Problem description
Dear All,
I am new with cobrapy.
I am trying to load Recon2.2 (downloaded from here: https://github.com/u003f/recon2/tree/master/models) and cannot make it work.

I did:
from cobra.io import read_sbml_model
mod = read_sbml_model("/home/benkahla/systembio/recom_2.2.xml.gz")

I had as response:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/anaconda/lib/python2.7/site-packages/cobra/io/sbml3.py", line 572, in read_sbml_model
    xmlfile = parse_stream(filename)
  File "/Applications/anaconda/lib/python2.7/site-packages/cobra/io/sbml3.py", line 158, in parse_stream
    raise CobraSBMLError("Malformed XML file: " + str(e))
cobra.io.sbml3.CobraSBMLError: Malformed XML file: Specification mandate value for attribute data-pjax-transient, line 44, column 94 (line 44)

What can I do?

Many thaks,
Best,
Alia.

Please explain:
* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.

```

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

[Paste output here.]

</details>

**Comment by gregmedlock** [comment]
Hi Alia, it looks like your model is still gzipped as it was in the download source. Try unzipping (via command line, or just use your operating systems graphical archive manager) and try again with the unzipped file.

**Comment by aliabenkahla** [comment]
Hi Greg,
I tried both, gzipped and unzipped. It didn't work.
Then I downloaded recon2.2 xml from a different source and it didn't work.
Best,
ALia.

**Comment by Midnighter** [comment]
Hi,
I downloaded https://github.com/u003f/recon2/blob/master/models/recon_2.2.xml then ran pretty much the same code:

```python
from cobra.io import read_sbml_model
model = read_sbml_model("recon_2.2.xml.gz")
```

there are some warnings but it loads fine for me. As asked for in the issue template, can you please paste the output of `python -c "from cobra import show_versions; show_versions()"`?

**Comment by Midnighter** [comment]
Could you `pip install python-libsbml` and then try again, please?

**Comment by matthiaskoenig** [comment]
I am closing this. 
@aliabenkahla Two people could load the model without problem. Please reopen this issue if the problem persists.
