### ISSUE TITLE
SBML output can contain specific bounds parameters for each reaction

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#800]
I have some example cases where models coming from KBase have thousands of parameters defined. Now that we have a configuration object, A strategy for writing SBML could be to define default bounds using the values set in the configuration plus 0, With those three default parameters defined we should be able to cover most reactions. We should only create additional parameters for reactions that deviate from those values.

**Comment by matthiaskoenig** [comment]
@Midnighter Could you provide an example for this?

**Comment by Midnighter** [comment]
Hmm, on second look I'm not entirely correct on the issue. What happens is that they define the default bounds as well as specific bounds for each exchange reaction, for example,

```xml
    <listOfParameters>
      <parameter constant="true" id="cobra_default_lb" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="-1000000"/>
      <parameter constant="true" id="cobra_default_ub" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="1000000"/>
      <parameter constant="true" id="cobra_0_bound" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="0"/>
      <parameter constant="true" id="R_bio1_biomass_upper_bound" sboTerm="SBO:0000625" units="mmol_per_gDW_per_hr" value="1000"/>
      <parameter constant="true" id="R_EX_cpd00154_e0_upper_bound" sboTerm="SBO:0000625" units="mmol_per_gDW_per_hr" value="1000"/>
      <parameter constant="true" id="R_DM_cpd02701_c0_upper_bound" sboTerm="SBO:0000625" units="mmol_per_gDW_per_hr" value="1000"/>
      <parameter constant="true" id="R_EX_cpd00280_e0_upper_bound" sboTerm="SBO:0000625" units="mmol_per_gDW_per_hr" value="1000"/>
      <parameter constant="true" id="R_EX_cpd00098_e0_upper_bound" sboTerm="SBO:0000625" units="mmol_per_gDW_per_hr" value="1000"/>
```
and so on. An exchange reaction could then look like

```xml
<reaction fast="false" id="R_EX_cpd10515_e0" reversible="true" name="Exchange for Fe2+_e0" metaid="R_EX_cpd10515_e0" fbc:upperFluxBound="R_EX_cpd10515_e0_upper_bound" fbc:lowerFluxBound="R_EX_cpd10515_e0_lower_bound">
```

So while the value 1000 appears quite often it's actually a reasonable representation. Unless you disagree this issue can be closed.

**Comment by matthiaskoenig** [comment]
This is a good point. There exists an underlying issue when writing SBML.
Basically there must be a check if bounds are identical on export (to check if the bounds for a reaction are the default bounds or not). If the bounds are not the default bounds, then some reaction specific bounds must be created in the export. This is a double comparison which requires to define tolerances for when to assume bounds as identical, i.e. something along the line of
```
def isclose(a, b, rel_tol=1e-09, abs_tol=0.0):
    return abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)
```
The question is what are the assumed absolute and relative tolerances in cobrapy for bounds to be assumed as equal?

**Comment by matthiaskoenig** [comment]
This is not a cobrapy issue (but an issue of how Kbase creates their SBML which is introducing some redundancy). This is not creating any issues with cobrapy. Models can be read and simulated. I am closing this for now, please reopen if something should be done with a concrete SBML example
