### ISSUE TITLE
FastCC implementation lacks parts

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#806]
#### Problem description

The FastCC method implemented right now is missing some parts. It only implements LP-7 from the paper but does not perform the flipping and the additional iterations to include further reactions. The test passes because it uses a toy model from the paper that resolves in one iteration. But as stated in the publication this is not generally true (for instance with branched pathways). Maybe a more stringent test would be to compare with the output of FVA which can be used for the same purpose. 

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
from cobra.test import create_test_model
from cobra.flux_analysis import flux_variability_analysis, fastcc

mod = create_test_model("ecoli")
fva = flux_variability_analysis(mod, fraction_of_optimum=0.0)
nonblocked = fva.index[(fva.minimum.abs() > 1e-9) | (fva.maximum.abs() > 1e-9)]

fastcc_mod = fastcc(mod)

len(nonblocked) - len(fastcc_mod.reactions)
```

#### Actual Output

965

#### Expected Output

0

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>
System Information
==================
OS         Darwin
OS-release 17.7.0
Python      3.6.7

Package Versions
================
cobra        0.14.2
depinfo       1.4.0
future       0.17.1
numpy        1.16.1
optlang       1.4.3
pandas       0.24.1
pip          19.0.2
ruamel.yaml 0.15.88
setuptools   40.8.0
six          1.12.0
swiglpk       1.5.1
tabulate      0.8.3
wheel        0.33.1

</details>

**Comment by synchon** [comment]
Thanks for raising the issue! I'll try to fix this ASAP.

**Comment by synchon** [comment]
@cdiener The first run of consecutive runs for FASTCC (using GLPK) with same parameters, is giving me a different value for the reactions. Is it the same case for you?

**Comment by cdiener** [comment]
You mean running the first `fastcc` iteration several times? That is at least not impossible. Flux solutions are usually not unique so there may be many solutions giving the same maximum. If you go through all iterations that should not be a problem though since you should eventually catch all reactions that can carry flux. 

Also for the flipping (minimization) it should be enough to only change the sign of the coefficients of the constraint for v_forward and v_reverse (you don't have to remove or add constraints/variables). Happy to chat on gitter as well or reviewing the PR if that helps :smile:

**Comment by Midnighter** [comment]
I thought the flipping wouldn't be necessary since we have separate variables for both directions and they're in the constraints. However, maybe I overlooked something.

**Comment by cdiener** [comment]
Still need to flip since the optimization is run on the entire flux and still maximizes only the number of positive fluxes in the first run. Maximizing on v_forward and v_reverse would not work since that gives all zero fluxes if possible.

**Comment by synchon** [comment]
> You mean running the first `fastcc` iteration several times?

So what I meant was if you used `fastcc_model = fastcc(model)` several times, `fastcc_model` would have different number of non-blocked reactions which is obvious (in the present state of the implementation). My question was out of curiosity since only the first run gave me a different value than the others. I guess this might be due to the solver's algorithm.

**Comment by synchon** [comment]
@cdiener  #827 passes the test that you described and as far as I tested, it fixes the basic flaw that was there.
