### ISSUE TITLE
How to handle `boundaryCondition=true` species on SBML import?

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#811]
At the moment species with `boundaryCondition=true` are read incorrectly from SBML, resulting in many issues. Currently, such species are just dropped from the model. 
This results in:
* missing species (not all species are read, information is lost)
* incorrect charge and chemical composition balance (if species are just dropped from reactions, the mass and charge balance of the reaction will be incorrect). This affects tools working with the cobrapy Model like memote, which reports incorrect charge and mass balances on such reactions.

The correct behavior for parsing boundarySpecies is to:
* read the species in the model
* add an exchange reaction for the boundary species (to fullfill the steady state condition for the boundary species)
* set the flux bounds of the exchange reaction according to the stoichiometry (to avoid additional constraints, i.e. limiting the reaction flux via the exchange reaction, the flux bounds of the exchange reaction must be set to [ stoichiometric_coefficient * lower_bound, stoichiometric_coefficient * upper_bound ].)

I would implement the correct behavior for the SBML parser. If there are any objections please comment.

**Comment by cdiener** [comment]
I think the old behavior is based on the SBML FAQ:

>  What is this "boundary condition" business?
> The boundaryCondition attribute on <species> codifies the following notion: In some systems of reactions, certain chemical species are unchanged by the reactions in the system. For example, this might happen if there is a vast overabundance of the species compared to the other ones, or the particular species is maintained (buffered) by some external means. In models of such systems, it is important to be able to indicate that the model interpreter should not generate an ODE for that species. In SBML, this is indicated by setting the boundaryCondition attribute of that species to "true".
>A critical point in the previous paragraph is the part that says the model interpreter should not generate an ODE from the system of reactions for species that are labeled as boundary conditions. It does not mean that there cannot be an ODE or other constraint generated as a result of a rule in the model. You can have boundaryCondition="true" for a species and that species can still appear on the left-hand side of an ODE if there is an SBML Rule for it.
>Summary: **boundaryCondition="true" means do not generate an ODE for this species from the stoichiometry matrix of the system of reactions.** 

So the interpretation was to not include the reaction (even though it does not allow the use of that species on the left-hand side as specified as well). 

I think your argument for mass-balancing makes sense. The potential problem is that cobrapy never limits the ability to change bounds, so it is completely feasible to change the bounds on a boundary species in a way that species is not fixed anymore or violates your `stoichiometric_coefficient * bound` condition which would not conserve the behavior specified in the SBML. 

Pragmatically I would say the new behavior is fine if all previous tests without modification.

**Comment by matthiaskoenig** [comment]
The real problem here is that COBRA(py) does not handle bounds correctly, but sets arbitrary upper and lower bounds. The correct upper and lower bounds for a reaction if there are no constraints defined are [-INF, INF]. These are completely valid bounds for LP problems and should be the default bounds.
If I would be able to set [-INF, INF] bounds on a reaction there would be no issue at all. 

The COBRA community decided to add arbitrary bounds/constraints on all reactions of -1000 and 1000 (probably because some of the early COBRA tools was not able to handle [-inf, inf] bounds). In my personal view this is a major limitation of cobrapy, because it does not allow for unconstrained reactions (example given a unconstrained exchange reaction defining a boundary species).

**Comment by cdiener** [comment]
> If I would be able to set [-INF, INF] bounds on a reaction there would be no issue at all.

In that case an issue specific for that would be more appropriate since it is not specific to SBML parsing. Optlang supports unlimited bounds.

But even then no computer will ever be able to express [-INF, INF] bounds since there is no machine representation for arbitrary large numbers. In practice you will always be limited by the largest representable float for GLPK, Cplex and Gurobi (which is machine dependent). But having no bounds has some desirable properties since it actually simplifies the problem. There are some edge cases that would have to be addressed, for instance what is the optimum of an unbounded problem? Should it throw an error? But I think it might be worthwhile to discuss that.

**Comment by matthiaskoenig** [comment]
@cdiener Yes, the infinity bounds will solve the issue. I thought a bit more about it and it is the simplest correct solution (another possibility would be to add very large bounds in combination with additional constraints, but much more complicated and a nightmare to maintain especially on model changes). One could add reactions which use the boundary species (or multiple reactions could produce/consume the boundary species) making it very complicated to guarantee bounds on the exchange reactions. 

I will try the infinity bounds. 

@Midnighter et all. The infinity bounds should also be the default bounds in cobra.Configuration. If one adds reactions to a model without setting any constraints on them these reactions should be unbound, i.e. have [-inf, inf] bounds. Setting bounds of [-1000; 1000] is completely arbitrary resulting in arbitrary restriction of the possible LP solution space. These becomes problematic, because adding/removing reactions can change possible solutions because of the cutoffs in solution space even if these reactions were assumed as unbound by the modeler.

**Comment by matthiaskoenig** [comment]
I always felt very uneasy with setting [-1000, 1000] (and heard this critique also from other researchers using different tools than cobra). For instance, I could imagine that some results of gene knockout simulations (i.e. changes in flux distributions, perhaps even infeasible solutions) are basically a result of the arbitrary [-1000, 1000] bounds, whereas under conditions of unconstraint reactions the results would look different.

**Comment by Midnighter** [comment]
In principle, I agree with your line of argumentation. I would want to investigate first, however, how optlang manages to support this for all the different solvers.

**Comment by cdiener** [comment]
I think it should work in optlang since an infinity bound just means not setting the bound (no constraint) in that direction. I would be more worried about the behavioral changes. For instance building a model from scratch without specifying bounds (just adding reactions) will no raise a value on optimization. Also unconstrained models are never thermodynamically feasible since there is always a physical upper bound for any chemical reaction (diffussion limit  etc.).

**Comment by cdiener** [comment]
Also, and @matthiaskoenig probably knows more about that, it seems that at least FBC strict mode discourages infinity bound.

> All defined FluxObjective elements must have their coefficient attribute set to a double value that is neither “NaN” nor “-INF” nor “INF”

> A Reaction lowerFluxBound attribute may not point to a Parameter with a value of “INF”.

>  A Reaction upperFluxBound attribute may not point to a Parameter with a value of “-INF”.

**Comment by Midnighter** [comment]
We're getting a bit side-tracked with the discussion. Do we need another issue for discussing unbounded variables and constraints? There's also some related discussion in #805 on this.

**Comment by cdiener** [comment]
Yes I agree. We definitely need an issue for that. We can copy and paste the comments from here.

**Comment by matthiaskoenig** [comment]
@cdiener Yes, this rules were added to fbc-v2. But in my opinion enforcing arbitrary bounds by the rules 
- A Reaction lowerFluxBound attribute may not point to a Parameter with a value of “INF”.
- A Reaction upperFluxBound attribute may not point to a Parameter with a value of “-INF”.

is just incorrect (and creates a ton of problems). I hope this will be relaxed in fbc-v3. The strict idea was all about having rules to enforce a valid LP problem. Having [-INF, INF] bounds creates a valid LP problem (so I personally don't understand this rule at all).

**Comment by matthiaskoenig** [comment]
Hi @cdiener,
I reread the specification and talked to the fbc group and only bounds like the following are forbidden in strict: [0, -INF], [INF, 0], [-INF, -INF]
The lower_bound -INF and upper_bound INF are legal, i.e. [-INF, INF] works and is strict.

>     A Reaction lowerFluxBound attribute may not point to a Parameter with a value of “INF”.
>     A Reaction upperFluxBound attribute may not point to a Parameter with a value of “-INF”.

**Comment by matthiaskoenig** [comment]
> For instance building a model from scratch without specifying bounds (just adding reactions) will no raise a value on optimization. 

I agree, but this is the correct behavior.
One will get a "Solution status unbounded" in such a case and one could provide a proper warning message for that. I.e. something like
```
The LP problem is unbounded, i.e. there are not sufficient constraints 
in the LP problem and consequently the objective function cannot be 
minimized/maximized (nothing is constraining the objective, so unlimited values
are reached). 

Various solutions exist for this issue, all being based 
on adding additional constraints to the model:
- adding stricter upper and/or lower bounds on exchange reactions 
  thereby limiting the uptake/release of metabolites (e.g. limiting the uptake 
  metabolite required to fulfill the objective function)
- adding stricter upper and/or lower bounds on reactions 
  thereby limiting the flux through reactions (e.g. setting the 
  bounds to limited values on a single reaction referenced in 
  the objective is sufficient)
- adding additional constraints to the LP problem
``` 

> Also unconstrained models are never thermodynamically feasible since there is always a physical upper bound for any chemical reaction (diffussion limit etc.).

Yes, I agree. In case of a single reaction this is not a problem and one can set arbitrary bounds on that reaction. The problem arises as soon as multiple reactions and processes are in a network together. To be thermodynamically feasible the upper and lower bounds of the multiple reactions must be correct relative to each other.

**Comment by cdiener** [comment]
> I reread the specification and talked to the fbc group and only bounds like the following are forbidden in strict: [0, -INF], [INF, 0], [-INF, -INF]
The lower_bound -INF and upper_bound INF are legal, i.e. [-INF, INF] works and is strict.

Cool, that makes more sense. I see your points and think it would be feasible to implement something like that (for instance via the configuration object). We might want to ask the user base what they think. The behavior can be changed easily by setting the configuration default bounds to something else anyways.
