### ISSUE TITLE
How to implement partially unbounded reactions and infinite bounds?

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#815]
There have been discussions in #805 and #811 about handling infinity values on bounds and thus basically introducing free or partially free reactions. Overall the consensus seems to be that this is useful and wanted behavior but the specifics need to be decided on.

**Comment by cdiener** [comment]
This mostly works and is part of optlang. If there are specific types that are not converted correctly, we probably want an issue that tracks this particular type.
