### ISSUE TITLE
Refactor sampling.py and separate the base classes from samplers 

### ISSUE THREAD

**Issue by synchon** [opencobra/cobrapy#817]
Refactoring `sampling.py` will simplify future maintenance. I think creating a new directory named `flux_sampling` inside the `flux_analysis`, can be used to keep all the sampling related code.

**Comment by cdiener** [comment]
I think just `sampling` is fine for the name. Also could imagine it to be a folder next to `flux_analysis` to keep hierarchy flat (might make sense since all analysis methods are optimization-based but sampling is not).
