### ISSUE TITLE
Metabolite DictList doesn't update correctly

### ISSUE THREAD

**Issue by sulheim** [opencobra/cobrapy#819]
#### Problem description
If you change the ID of a metabolite twice the new id is not in the metabolites DictList.
~~This works works with cobrapy 0.13.4, but not with 0.14.2~~
#### Code Sample
```python
import cobra
import cobra.test
model = cobra.test.create_test_model("textbook")
model.metabolites.q8_c.id = "test"
print(model.metabolites.test)
model.metabolites.test.id = "q8_c"
print("Success")
```

#### Actual Output
```
test
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\optlang\container.py in __getitem__(self, item)
     81         try:
---> 82             return self._object_list[item]  # Try treating item as int or slice
     83         except TypeError:  # Not int or slice

TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-16-eea8fc64aafc> in <module>()
----> 1 model.metabolites.test.id = "q8_c"

c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\cobra\core\object.py in id(self, value)
     34             raise TypeError("ID must be a string")
     35         elif getattr(self, "_model", None) is not None:
---> 36             self._set_id_with_model(value)
     37         else:
     38             self._id = value

c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\cobra\core\metabolite.py in _set_id_with_model(self, value)
     54             raise ValueError("The model already contains a metabolite with "
     55                              "the id:", value)
---> 56         self.model.constraints[self.id].name = value
     57         self._id = value
     58         self.model.metabolites._generate_index()

c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\optlang\container.py in __getitem__(self, item)
     82             return self._object_list[item]  # Try treating item as int or slice
     83         except TypeError:  # Not int or slice
---> 84             return self._dict[item]  # Treat item as key (name)
     85
     86     def __setitem__(self, key, value):

KeyError: 'test'
```
#### Expected Output
```
test
success
```

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.5.2

Package Versions
================
cobra        0.14.2
depinfo       1.4.0
future       0.17.1
numpy        1.15.4
optlang       1.4.4
pandas       0.24.0
pip          19.0.3
ruamel.yaml 0.15.87
setuptools   40.7.1
six          1.12.0
swiglpk       1.4.4
tabulate      0.8.1
wheel        0.29.0

</details>

**Comment by sulheim** [comment]
Update: I think this is related to gurobi, and not to the cobrapy-version.
Setting ```model.solver = "glpk"```solves the problem with 0.14.2 at least

**Comment by Midnighter** [comment]
Thanks for the update. That points to a problem in optlang where an update in the variable name is not propagated.

**Comment by cdiener** [comment]
I think this points to the larger issue that gurobi is not part of the testing pipeline in optlang. Obviously this is hard due to the proprietary license but has led to many breakages in the past. Might be worthwhile to think how we could address that better in optlang and also cobrapy.

**Comment by ChristianLieven** [comment]
ARTENOLIS used by the COBRAtoolbox folks might be quite useful for running tests on proprietary software:

https://arxiv.org/pdf/1712.05236.pdf

**Comment by cdiener** [comment]
Reported upstream at https://github.com/biosustain/optlang/issues/195.

**Comment by cdiener** [comment]
Fixed upstream.
