### ISSUE TITLE
`validate_sbml_model` lacks warnings

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#822]
Validating an SBML model tries to catch warnings with the below code, however, the warnings were turned into logging messages with warning level so that cannot be caught that way.

```python
with catch_warnings(record=True) as warnings:
        simplefilter("always")
```

Maybe [this SO answer](https://stackoverflow.com/a/32001771) could be a solution. If that seems reasonable I'm happy to implement.

@matthiaskoenig

**Comment by Midnighter** [comment]
Small test model that is missing `listOfObjectives`.
[tiny_FBC.xml.gz](https://github.com/opencobra/cobrapy/files/2984377/tiny_FBC.xml.gz)

**Comment by matthiaskoenig** [comment]
Good point. I will wait a few more days for more SBML issues to pop up and have time after the weekend to address this.
