### ISSUE TITLE
InChi Ids are incorrectly flagged as non-conformant

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#836]
#### Problem description

Please explain:
Load a model with `read_sbml_model`. Get messages of non-conformant identifiers even though the identifiers are correct. For instance the first annotation works fine: http://identifiers.org/inchi/InChI=1S/C3H8O2/c1-3(5)2-4/h3-5H,2H2,1H3/t3-/m0/s1 .

#### Code Sample

```python
from cobra.io import read_sbml_model

mod = read_sbml_model("Abiotrophia_defectiva_ATCC_49176.xml")
```

[Abiotrophia_defectiva_ATCC_49176.xml.zip](https://github.com/opencobra/cobrapy/files/3074900/Abiotrophia_defectiva_ATCC_49176.xml.zip)

#### Actual Output

```
http://identifiers.org/inchi/InChI=1S/C3H8O2/c1-3(5)2-4/h3-5H,2H2,1H3/t3-/m0/s1 does not conform to http(s)://identifiers.org/collection/id
http://identifiers.org/inchi/InChI=1S/C5H7NO2/c7-5(8)4-2-1-3-6-4/h3-4H,1-2H2,(H,7,8)/p-1 does not conform to http(s)://identifiers.org/collection/id
http://identifiers.org/inchi/InChI=1S/C4H7NO3/c1-2(6)3(5)4(7)8/h3H,5H2,1H3,(H,7,8)/t3-/m0/s1 does not conform to http(s)://identifiers.org/collection/id
http://identifiers.org/inchi/InChI=1S/C5H11O7P/c6-2-1-4(7)5(8)3-12-13(9,10)11/h2,4-5,7-8H,1,3H2,(H2,9,10,11)/p-2/t4-,5+/m0/s1 does not conform to http(s)://identifiers.org/collection/id
http://identifiers.org/inchi/InChI=1S/C4H6O3/c1-3(2-5)4(6)7/h2-3H,1H3,(H,6,7)/p-1 does not conform to http(s)://identifiers.org/collection/id
http://identifiers.org/inchi/InChI=1S/C4H6O3/c1-2-3(5)4(6)7/h2H2,1H3,(H,6,7)/p-1 does not conform to http(s)://identifiers.org/collection/id
[...]
```

#### Expected Output

No output.

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Darwin
OS-release 17.7.0
Python      3.6.7

Package Versions
================
cobra                        0.15.1
depinfo                       1.4.0
future                       0.17.1
numpy                        1.15.4
optlang                       1.4.3
pandas                       0.24.2
pbr                           5.1.3
pip                          19.0.3
python-libsbml-experimental  5.17.2
ruamel.yaml                 0.15.91
setuptools                   41.0.0
six                          1.12.0
swiglpk                       1.5.1
tabulate                      0.8.3
wheel                        0.33.1

</details>

**Comment by cdiener** [comment]
DOIs also allow slashes in ids.

**Comment by matthiaskoenig** [comment]
Will fix this over the weekend.

**Comment by matthiaskoenig** [comment]
@cdiener I commited a bugfix for this.

You should use the `https://identifiers.org/` prefix instead of `http://identifiers.org/` in the model. These identifiers will resolve faster, because you don't need additional redirects (http->https). EBI switched to https some time ago. I am not issuing a warning for that, but I think it is better practice to use the encrypted resources whenever possible.

**Comment by cdiener** [comment]
Cool thanks. I agree with the https but that's not my model, it's one of the AGORA models :smile:
