### ISSUE TITLE
SBML testing/installation issues with python 3.7 (wheels missing)

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#839]
There are currently some issues with python 3.7 wheels of libsbml.
This results in long running (failing) travis jobs and very long installation times.

See also discussion in
https://groups.google.com/forum/#!topic/libsbml-development/HDbs3K0mm2o
There is a new release around the corner, update of libsbml dependencies will solve this issue.

**Comment by Midnighter** [comment]
I have pinned python-libsbml-experimental to 5.17.2 for now in order to make a release on Travis. When this issue is resolved we need to remove the version pin.

**Comment by matthiaskoenig** [comment]
@Midnighter This is working now for me locally with update of libSBML to the release from yesterday. All tests passing locally with
```
tox -e py27
tox -e py35
tox -e py36
tox -e py37
```
