### ISSUE TITLE
Error in validate_sbml_model (sbml.py)

### ISSUE THREAD

**Issue by migp11** [opencobra/cobrapy#840]
#### Problem description
 I was validating a model and got the following error:

   1460             errors["SBML_FATAL"].append(msg)
   1461         elif sev == libsbml.LIBSBML_SEV_ERROR:
-> 1462             errors["SBML_ERROR"].append(msg)
   1463         elif sev == libsbml.LIBSBML_SEV_SCHEMA_ERROR:
   1464             errors["SBML_SCHEMA_ERROR"].append(msg)

KeyError: 'SBML_ERROR'

* **what** I was trying to validate a model
* **how** cobra.io.sbml.validate_sbml_model("my_model.xml")
* **why** Because the error is due a small bug in the cores

After inspecting the code sbml.py I founded a small typo (line 1455):

```python
    for key in ["SBML_FATAL", "SBML ERROR", "SBML_SCHEMA_ERROR",
                "SBML_WARNING"]: # "SBML ERROR" has no underscore
        errors[key] = []
```

--> note that "SBML ERROR"  has no underscore

However,  a few lines later the  key is used with underscore which causes a KeyError Exception:
KeyError: 'SBML_ERROR'

```python
    for k in range(doc.getNumErrors()):
        e = doc.getError(k)
        msg = _error_string(e, k=k)
        sev = e.getSeverity()
        if sev == libsbml.LIBSBML_SEV_FATAL:
            errors["SBML_FATAL"].append(msg)
        elif sev == libsbml.LIBSBML_SEV_ERROR:
            errors["SBML_ERROR"].append(msg)  # Here the key has underscore
```

To fix this error just add the corresponding underscore to "SBML ERROR" at line 1455

**Comment by matthiaskoenig** [comment]
@migp11 Thanks for the detailed report. This will be fixed with the next bugfix release. Sorry for the late reply, somehow missed the email

**Comment by migp11** [comment]
Great! I'm glad to contribute ;-)
