### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#853]
Hi all,
can we drop python 2 support.

Most major libraries are starting to drop python 2 already, e.g. scipy, pandas, ...
https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html

I just ran into issues getting the appveyor build running due to scipy not supporting py27 any more:
https://ci.appveyor.com/project/cobrapy39491/cobrapy/build/job/3ek340bwmslb6l91
which do not pass anymore.

The Python core team plans to stop supporting Python 2.7 on January 1st, 2020. We should drop python 2 before that, in my opinion as soon as possible. 

Best Matthias

**Comment by Midnighter** [comment]
Totally agreed. Also in the last user survey Python 2 users were in the minority. I originally meant to couple this with the 1.0 release but there is still a lot of work left to do there.

**Comment by matthiaskoenig** [comment]
Perhaps we could set a date or version for this, i.e. clearly stating something along the line: The cobrapy `0.15.*` releases will be the last versions with python2 support. Starting from `0.16.*` on python2 support will be dropped.

**Comment by Midnighter** [comment]
Sounds good. Where do you think we should state this? README, message on import, or somewhere else?

**Comment by matthiaskoenig** [comment]
README, release notes, import warning.

Especially the import warning is important for python 2 which notifies about dropping python 2 support and that newer versions could be available for py3 (without such a warning think that they have the latest version, but in reality only have the latest version supporting py2).

**Comment by synchon** [comment]
With version `0.25.0` of `pandas`, it has already dropped support for Python 2. We use it quite a bit and I think it's better to issue a warning in the next release and drop Python 2 support in the subsequent release.

**Comment by cdiener** [comment]
I think there are several stages:

1. (easy) remove Python 2 from all CI and builds. Mention it in docs and everywhere else.
2. (medium) remove Python 2 specific workarounds (six, not using `with Pool(...):`)
3. (hard) Refactor code base to make full use of Python 3 features. 

We can probably do 1 very fast and 2 in reasonable time. 3 will take longer since we also have to benchmark it extensively, but I would not consider 3 extremely urgent.

**Comment by Midnighter** [comment]
Let's do 1. right away, including a `DeprecationWarning` upon import with Python 2.

**Comment by ChristianLieven** [comment]
Here are some practicalities/ guidelines for the switch that I'm using for `memote`
 that you might wanna have handy too!

https://python3statement.org/practicalities/

**Comment by Midnighter** [comment]
As usual our documentation is lagging behind but this is now well under way.
