### ISSUE TITLE
Building a model requires Gurobi

### ISSUE THREAD

**Issue by crockeraw** [opencobra/cobrapy#854]
Hi all,

I want to build a new model, and I don't intend to use gurobi for solver. 
When I run `model = Model("new")` I get the error:
> GurobiError: No Gurobi license found

I have set Model.solver = "glpk". 
Any ideas as to why I am seeing this error? Thanks!

**Comment by Midnighter** [comment]
In cobrapy we try to automatically choose the "best" solver available. So you have two options:

1. You can uninstall gurobipy from the Python environment. This is probably not what you want to do.
2. You can configure another solver which will be respected by newly created models:

```py
import cobra

config = cobra.Configuration()
config.solver = "glpk"
model = cobra.Model("new")
```

Whatever you set in the configuration is also valid for loading models from JSON or SBML.

**Comment by crockeraw** [comment]
Thanks!
