### ISSUE TITLE
Fail to read SBML model without XML header

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#860]
I'm not necessarily saying that we should (since it's broken XML) but pre 0.15 we were parsing SBML files that lacked a header such as `<?xml version='1.0' encoding='utf-8' standalone='no'?>` without problems but now that we solely rely on libsbml we cannot. Opinions?

**Comment by matthiaskoenig** [comment]
If the file is not valid xml we cannot guarantee to read it (most other tools will also fail).
It would be the similar if you have a json without opening and closing brackets, i.e., without `{` and `}`.
Nobody would expect that this can be read.

**Comment by Midnighter** [comment]
Agreed, let's go with that until a very good reason to change it comes up.
