### ISSUE TITLE
While flux-sampling, reverse fluxes are always 0 

### ISSUE THREAD

**Issue by Patrickens** [opencobra/cobrapy#861]
#### Problem description

I would like to sample forward and reverse fluxes separately. For a reversible reaction `v: A <=> B` that carries forward flux `v` and backward flux `v_reverse` the net flux is defined as `vn=v-v_reverse`. The forward and backward fluxes are constrined individually: `0.0<v< 100.0` and `0.0<v_reverse<100.0`. Next, I set upper and lower bounds on the **net** forward and backward fluxes: `-10.0<v-v_reverse< 10.0`. There are 2 exchange reactions `ax: ∅ -> A` and `bx: B -> ∅`.

###### Case 1
`0.0<ax<10.0` and `0.0<bx<10.0`. This means that there can only be **net** flux in the forward direction for reaction `v`. 
###### Expectation 1
I expect `ax>0, ax_reverse=0, bx>0, bx_reverse=0` **and crucially:** `v>0`, `v_reverse>0` and `v-v_reverse>0`. I expect `v_reverse>0` since for reactions that are close to equilibrium there is a significant backflux that I am interested in. 
###### Cobrapy output 1
  | v | v_reverse_9e366 | Ax | Ax_reverse_b0ccc | Bx | Bx_reverse_73bf6
-- | -- | -- | -- | -- | -- | --
0 | 3.236832 | 0 | 3.236832 | 0 | 3.236832 | 0
1 | 6.975016 | 0 | 6.975016 | 0 | 6.975016 | 0
2 | 0.869156 | 0 | 0.869156 | 0 | 0.869156 | 0
###### Problem
As we can see in the table above, there is never any flux in `v_reverse_9e366`. This is unexpected since the reaction is reversible and thus only the net flux (`v-v_reverse_9e366`) should be strictly positive.

###### Case 2
Both exchange reactions are bi-directional: `-10.0<ax<10.0` and `-10.0<bx<10.0`. This means that there can be **net** flux in both directions for `ax, bx` and crucially `v`. 
###### Expectation 2
I expect `ax>=0, ax_reverse>=0, bx>=0, bx_reverse>=0, v>=0` and `v_reverse>=0`. Reaction `v` can now proceed in both directions and thus `-10.0<v-v_reverse<10.0`. 
###### Cobrapy output 2
  | v | v_reverse_9e366 | Ax | Ax_reverse_b0ccc | Bx | Bx_reverse_73bf6
-- | -- | -- | -- | -- | -- | --
0 | 3.236832 | 5.814951 | 3.236832 | 5.814951 | 3.236832 | 5.814951
1 | 8.059268 | 5.195058 | 8.059268 | 5.195058 | 8.059268 | 5.195058
2 | 0.394004 | 4.811658 | 0.394004 | 4.811658 | 0.394004 | 4.811658

We can now also see that for rows 0 and 2 there is a net flux in the reverse direction:

  | vnet | Axnet | Bxnet
-- | -- | -- | --
0 | -2.57812 | -2.57812 | -2.57812
1 | 2.864209 | 2.864209 | 2.864209
2 | -4.41765 | -4.41765 | -4.41765

###### Problem
Case 2 seems to give the expected behaviour in that we have both forward and reverse fluxes for reaction `v`. This seems dependent on whether there it is possible to have a net backward flux. 

##### Question
How could I sample forward and backward fluxes (with constraints on the individual forward and reverse variables) without having the possibility of a net backward flux?

* **what** you tried to achieve,
* **how** you went about it (referring to the code sample), and
* **why** the current behaviour is a problem and what output
  you expected instead.

#### Code Sample

```python
M = ExtendedCobraModel(id_or_model='M')
A = ExtendedMetabolite(id='A')
B = ExtendedMetabolite(id='B')
M.add_metabolites([A,B])

v = Reaction(id='v',upper_bound=100.0, lower_bound=-100.0)
v.add_metabolites(metabolites_to_add={A:-1, B:1})

ax = Reaction(id='Ax', upper_bound=10.0, lower_bound=0.0)
ax.add_metabolites({A:1})

bx = Reaction(id='Bx', upper_bound=10.0, lower_bound=0.0)
bx.add_metabolites({B: -1})

M.add_reactions([v, ax, bx])

M.problem.Constraint(v.forward_variable - v.reverse_variable, lb=10.0, ub=10.0)

#Case 1
with M:
    sampler = OptGPSampler(model=M,seed=2)
    Vdf1 = sampler.sample(n=10,fluxes=False) # this is the dataframe where the problem becomes visible
    print(Vdf1)

# Case 2
with M:
    ax.lower_bound = -10.0
    bx.lower_bound = -10.0
    sampler = OptGPSampler(model=M, seed=2)
    Vdf2 = sampler.sample(n=10, fluxes=False) # this dataframe works as expected.
    print(Vdf2)


```

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.7.3
Package Versions
================
cobra                        0.15.3
depinfo                       1.5.1
future                       0.17.1
numpy                        1.16.4
optlang                       1.4.4
pandas                       0.24.2
pip                          19.1.1
python-libsbml-experimental  5.18.0
ruamel.yaml                 0.15.97
setuptools                   41.0.1
six                          1.12.0
swiglpk                      4.65.0
tabulate                      0.8.3
wheel                        0.33.4

</details>

**Comment by cdiener** [comment]
As mentioned in Gitter this is for now intended behavior:

All samplers only sample uniformly in the flux space, but not in the variable (or irreversible flux space). This is kind of done on purpose since it is faster and has better convergence (since the sampling space is much smaller). This is implemented in the search directions. If you check out sampler.warmup you will see that the reverse variables have a zero column. This is because initial search direction are essentially generated by FVA and most solvers are parsimonious (they use the 0 vector as an initial guess and find the solution closest to that). If you really need that behavior there are two major hacks to make that happen:

    (dirty) after initialization overwrite sampler.warmup for those variables that have a zero columns and a zero entry in sampler.problem.variable_fixed.
    (clean) build a new sampler class that inherits OptGPSampler and that overwrites generate_fva_warmup to use individual variables instead of fluxes

The caveats will be slower sampling and convergence and the fact that you are now sampling from the irreversible space which is not necessarily uniform sampling from the reversible space.

I don't know if sampling in the irreversible space is really a common use case. I feel that this is not that common but can be convinced otherwise.

**Comment by Patrickens** [comment]
Thanks for the response! Ill sample the net fluxes and separately generate samples with forward and reverse fluxes. I consider this issue closed, since I agree that it is a somewhat uncommon use case and because of the problems you mentioned with sampling in extra dimensions.

**Comment by cdiener** [comment]
Cool, if you still need that I'm happy to help out with code examples for the suggested solutions.
