### ISSUE TITLE
Confused with stoichiometry in reversible reactions

### ISSUE THREAD

**Issue by alvipa** [opencobra/cobrapy#867]
#### Problem description

Testing the stoichiometry of a reversible reaction, it seems Cobrapy doesn't detect the correct coefficient of each metabolite for the real sense of the flux, but it understands the coefficient of a metabolite as this is write literally in the reaction, as a product or as a reactant.

Next, I show an example for two reversible reactions that have the same flux but opposite senses. However, the stoichiometry coefficient for metabolite 'met_C' for both reactions is 1.0, because Cobra understand it as product despite the fact that it's taking it as a reactant and not as product. So, I guess that the stoichiometry that Cobra reads is based only on how we introduced the reactions in the model, and not on the sense of real actual flux performance.

#### Code Sample
```python
> model.objective = model.reactions.BIOMASS.id
> model.optimize()

# It understand correctly met_C, met_D and met_E as products:
> print(model.reactions.RXN_1.build_reaction_string())
> print("Flux: ", model.reactions.RXN_1.x)
> print([m.id for m in model.reactions.RXN_1.products])
'met_A + met_B  <=> met_C + met_D + met_E'
Flux:  16.023526143167604
['met_C' + 'met_D' + 'met_E']

# But here met_C and met_F are really reactants, and Cobra understand them as products too.
> print(model.reactions.RXN_2.build_reaction_string())
> print("Flux: ", model.reactions.RXN_2.x)
> print([m.id for m in model.reactions.RXN_2.products])
'met_M + met_N <=> met_C + met_F'
Flux:  -16.023526143167604
['met_C' + 'met_F']

# Stoichiometry coefficients for both, R1 and R2:
> df_s = cobra.util.array.create_stoichiometric_matrix(model=model, array_type='DataFrame')
> print(df_s['RXN_1']['met_C'])
> print(df_s['RXN_2']['met_C'])
1.0
1.0

```
#### Expected Output
RXN_2.products must be ['met_M',  'met_N ']  and RXN_2.reactants ['met_C',  'met_F']. 

Thank you in advance!

**Comment by matthiaskoenig** [comment]
Flux is always relative to the direction in which the reaction was defined. I.e. every reaction has reactants and products with their respective stoichiometric coefficients. Flux through the reaction is relativ to this direction, i.e., if the flux is > 0 it is in direction reactants -> products, if flux is < 0 the reaction has a |flux| in the reaction from products -> reactants (the minus states basically the flux is in opposite direction of the direction in which the reaction was defined).

**Comment by matthiaskoenig** [comment]
@alvipa Did this solve your issue? If you have any questions just ask. 

This is one of the things which you just have to wrap your head around. Reactions are defined in a given reaction, flux is always relative to this direction. Change in metabolites is `- relative flux * stoichiometric_coefficient` for reactants and `relative flux * stoichiometric_coefficient` for products of an reaction. 

Please close this issue if your problem is solved.

**Comment by matthiaskoenig** [comment]
Closing this for now. Please reopen this issue if things are unclear.
