### ISSUE TITLE
Inconsistent bounds in core.Reaction constructor

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#880]
The reaction constructor looks as follows:
```
class Reaction(Object):

    def __init__(self, id=None, name='', subsystem='', lower_bound=0.0,
                 upper_bound=None):
       ...        

        # from cameo ...
        self._lower_bound = lower_bound if lower_bound is not None else \
            config.lower_bound
        self._upper_bound = upper_bound if upper_bound is not None else \
            config.upper_bound
```
Because of `lower_bound=0.0` and `upper_bound=None` the bounds are set by default to 
`0.0, config.upper_bound`.
This is probably not what was intended. The constructor should probably be `lower_bound=None, upper_bound=None`.

Not sure what the intended behavior was, but most likely: set default bounds in config if no bounds are provided, not set `0.0, default upper bound`.

**Comment by matthiaskoenig** [comment]
This basically adds new reactions as irreversible when not specifying bounds (which is probably not what users expect when adding a reaction to a model). A lot of tests rely on this assumption, i.e. changing `0.0` to `None` fails many things.
@Midnighter @cdiener could you comment on this?

**Comment by Midnighter** [comment]
I don't know about the original reasoning but irreversible has been the default for quite some time.

Edit: I just checked in the git history and this has been the case since first commits by Daniel Hyduke in 2012.

**Comment by synchon** [comment]
@matthiaskoenig As far as I remember, we did this change in #758.

> This basically adds new reactions as irreversible when not specifying bounds 

I think that is exactly what we thought of. So, if you set `lower_bound` as `None` when initiating, that would make it reversible from the start.

I don't think we documented this caveat after merging it.

**Comment by matthiaskoenig** [comment]
It would be great to add 1-2 sentences of documentation to the Reaction class about this behavior along the lines of 
> Reactions are by default irreversible with bounds `(0.0, config.upper_bound)` if no bounds are provided on creation. To create an irreversible reaction use `lower_bound=None`, resulting in reaction bounds of `(config.lower_bound, config.upper_bound)`.
