### ISSUE TITLE
GPR of the form (A and B) or (A and C) are currently not supported

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#887]
Some reactions have (A and B) or (A and C), and removing the parenthesis breaks adding the gene rules, during GPR parsing.
This is due to some processing necessary for id replacements during writing.

@akaviaLab Could you provide an example model for this and add further description if I did not catch the full extent of the issue?

**Comment by gregmedlock** [comment]
I just happened across this issue with a model today (paper here: https://www.nature.com/articles/ncomms14250#supplementary-information but SBML only available here in "Ratcon files": http://bme.virginia.edu/csbl/Downloads1.html). In the GPRs with parentheses I'm coming across, the reactions within the cobrapy model end up with nothing in the GPR.

I can take a crack at it if you are working on other issues @matthiaskoenig. I need to fix it before moving forward with this work so can probably complete very soon.

**Comment by akaviaLab** [comment]
Hi
One example is RECON 2.2 (https://www.ncbi.nlm.nih.gov/pubmed/27358602), available on https://www.ebi.ac.uk/biomodels/MODEL1603150001
RECON 2.2 is valid SBML according to the online validator. Can you explain what purpose does the parenthesis removal serve? If this is fixed, it would help to figure out what the purpose of the original function was, in order not to remove functionality.
I'm working on truncated versions of RECON 2.2 that could be useful as quick test cases

**Comment by matthiaskoenig** [comment]
@gregmedlock and @akaviaLab Thanks for the examples. I can fix this issue tomorrow.

**Comment by akaviaLab** [comment]
This has not been fixed. I'm still not clear why removing the parenthesis is necessary at all.
For example, if the GPR is (A and B), it should work fine with parenthesis. Can you please explain why removing the parenthesis is necessary?

**Comment by akaviaLab** [comment]
Sorry, I was looking at an older version of the code. It seems to process reactions correctly. I think it can be closed.

**Comment by gregmedlock** [comment]
Issues with iHsa GPRs are resolved--thanks!

**Comment by Midnighter** [comment]
:tada:
