### ISSUE TITLE
ImportError: cannot import name 'YAML'

### ISSUE THREAD

**Issue by LordVoldemort28** [opencobra/cobrapy#893]
#### Problem description

Python Version: 3.6.8
CobraPy Version: 0.15.4
Ruamel.yaml Version: 0.16.0

When attempting to import `cobrapy` I get the actual output below. A quick fix for this would be to simply

```python3
from ruamel.yaml.main import YAML
```

instead

```python3
from ruamel.yaml import YAML
```

within `yaml.py` of the `cobra.io` module.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
# Paste your code here.
import cobra
```

#### Actual Output

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cobra/__init__.py", line 15, in <module>
    from cobra import io
  File "/usr/lib/python3.6/site-packages/cobra/io/__init__.py", line 10, in <modu
le>
    from cobra.io.yaml import from_yaml, load_yaml_model, save_yaml_model, to_yam
l
  File "/usr/lib/python3.6/site-packages/cobra/io/yaml.py", line 7, in <module>
    from ruamel.yaml import YAML
ImportError: cannot import name 'YAML'
```

#### Expected Output

Successful `import`

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

Above code fails due to import error.

</details>

**Comment by Midnighter** [comment]
Can you post the version of ruamel.yaml, please? `pip freeze | grep yaml`

**Comment by LordVoldemort28** [comment]
ruamel.yaml==0.16.0

**Comment by Midnighter** [comment]
Via #894
