### ISSUE TITLE
Documentation possible mistake in Flux Sampling

### ISSUE THREAD

**Issue by Trizali** [opencobra/cobrapy#903]
Hello, everybody,

I have installed the stable version 0.16.0 of Cobra. For do the sampling, the documentation specifies that it is necessary to import _sampling_ from _cobra.flux_analysis_. However, this module does not exist and, instead, it should be imported from _cobra.sampling._

Before
`from cobra.flux_analysis.sampling import OptGPSampler, ACHRSampler
`
Now: 
`from cobra.sampling import OptGPSampler, ACHRSampler
`
Is this correct?

Thanks in advance!

**Comment by Midnighter** [comment]
Yes, documentation is not up to date on that. Sorry about that.

**Comment by cdiener** [comment]
Sorry for the delay. I'll update the docs.
