### ISSUE TITLE
model.annotation not preserved during cobra.io.write_sbml_model

### ISSUE THREAD

**Issue by maureencarey** [opencobra/cobrapy#904]
Hi all!

#### Problem description
After modifying model.annotation, I tried writing it using cobra.io.write_sbml_model. However, the resultant file did not include any of the annotation information.

#### Code Sample
```python
test_model = cobra.core.Model()
test_model.annotation['example_field'] = 'example_annotation'
cobra.io.write_sbml_model(test_model, 'test_model.xml')
saved_model = cobra.io.read_sbml_model('test_model.xml')
```

#### Actual Output
```python
test_model.annotation
>>> {'example_field':'example_annotation'}
saved_model.annotation
>>> {}
```

#### Expected Output
```python
test_model.annotation
>>> {'example_field':'example_annotation'}
saved_model.annotation
>>> {'example_field':'example_annotation'}
```

'example_field' is not present in the xml file 'test_model.xml' - so it looks like it's a problem with write_sbml_model, not read_sbml_model. However, I don't have an existing model with any annotations to test read_sbml_model.

#### Dependency Information
I'm using Python 3.6.6 and Cobrapy 0.14.1. 

It looks like there have been a lot of updates related to sbml lately, so if I've just missed something, please let me know!

**Comment by Midnighter** [comment]
Hi Maureen, If it's easy for you, please try again with cobra 0.16.0 and let us know if this is still an issue.

**Comment by maureencarey** [comment]
resolved! thanks!
