### ISSUE TITLE
Missing Metabolite

### ISSUE THREAD

**Issue by dbourdeveloper** [opencobra/cobrapy#906]
#### Problem description

I'm currently attempting to add a reaction string and get the same representation back, but when I add the reaction, it drops the metabolites if they're present on both sides of the reaction.

I have the following reaction string
```'1 MNXM1692 + 1 MNXM2 + 1 MNXM3 <-> 1 MNXM1 + 1 MNXM1692 + 1 MNXM7 + 1 MNXM9'  ```

And performed the following
```
import cobra

eq = '1 MNXM1692 + 1 MNXM2 + 1 MNXM3 <-> 1 MNXM1 + 1 MNXM1692 + 1 MNXM7 + 1 MNXM9' 
cobra_model = cobra.Model('model')
cobra_reaction = cobra.Reaction('reaction')
cobra_model.add_reaction(cobra_reaction)
cobra_reaction.reaction = eq

# The line above outputs the following
# unknown metabolite 'MNXM1692' created
# unknown metabolite 'MNXM2' created
# unknown metabolite 'MNXM3' created
# unknown metabolite 'MNXM1' created
# unknown metabolite 'MNXM7' created
# unknown metabolite 'MNXM9' created

print(cobra_reaction.metabolites)
```

#### Actual Output
```
{<Metabolite MNXM2 at 0x7f5ba6500d68>: -1.0,
 <Metabolite MNXM3 at 0x7f5ba6500c88>: -1.0,
 <Metabolite MNXM1 at 0x7f5ba65005f8>: 1.0,
 <Metabolite MNXM7 at 0x7f5ba6500eb8>: 1.0,
 <Metabolite MNXM9 at 0x7f5ba6500e10>: 1.0}
```
#### Expected Output
```
{<Metabolite MNXM2 at 0x7f5ba6500d68>: -1.0,
 <Metabolite MNXM3 at 0x7f5ba6500c88>: -1.0,
 <Metabolite MNXM1 at 0x7f5ba65005f8>: 1.0,
 <Metabolite MNXM7 at 0x7f5ba6500eb8>: 1.0,
 <Metabolite MNXM9 at 0x7f5ba6500e10>: 1.0,
 <Metabolite MNXM1692 at <address>: 1.0,           <---- Expected
 <Metabolite MNXM1692 at <address>: -1.0,         <---- Expected
}
```

**Comment by cdiener** [comment]
Yeah, that is not possible since that has no effect in flux balance analysis. If you would write down the balance equation for MNXM1692 this part would just cancel out. It is a bit of a weird behavior though since the metabolite gets added to the model but is in no reaction. 

Is that to formulate a dependency on a co-factor or something similar? This would work in ODE models with kinetics but unfortunately does not for FBA since it only treats fluxes and not concentrations.

**Comment by dbourdeveloper** [comment]
> Yeah, that is not possible since that has no effect in flux balance analysis. If you would write down the balance equation for MNXM1692 this part would just cancel out. It is a bit of a weird behavior though since the metabolite gets added to the model but is in no reaction.
> 
> Is that to formulate a dependency on a co-factor or something similar? This would work in ODE models with kinetics but unfortunately does not for FBA since it only treats fluxes and not concentrations.

Thanks @cdiener ! I was thinking that was it, but was hoping I was able to get back out what I put in since dropping specific metabolites now makes it a different reaction in the workflow I have. We can close this.
