### ISSUE TITLE
Obtain maximal theorical yields (cmol/cmol)

### ISSUE THREAD

**Issue by Trizali** [opencobra/cobrapy#913]
Hi everyone, 

I'm a little lost and I'd really appreciate a little help. I'm trying to get the maximum theorical yields (in cmmol/cmmol units) of the acetate product, based on glcuose carbon source, and keeping 10% of the maximum growth flow (biomass) in anaerobic conditions.

I've tried what I explain below here:
**https://groups.google.com/forum/#!topic/cobra-toolbox/MLMro6PGSRc**

But I don't know if I'm on the right way and what to do next.
Can someone give me a hand, please?

Thank you in advance!

**Comment by Midnighter** [comment]
Hi @Trizali 

First of all, we have a cobrapy mailing list as well http://groups.google.com/group/cobra-pie so I hope you will have more success with your Python questions there :smiley: Creating an issue like this is perfectly fine, too.

The first option that you describe _WAY 1_ looks perfectly fine to me. Is there any reason why you did not accept those results?

In _WAY 2_ it's a bit more tricky to get a point exactly at 10% of maximum growth without previously constraining the model. So I think _WAY 1_ is anyway better for your question. What might be confusing is that the table headers seem a bit shifted. You should look at the `carbon_yield_maximum` column, for example, the following one is close to your 10%:


2 | EX_glc_LPAREN_e_RPAREN_ | 0.830382 | 0.000572 | 14.099883 | 0.009721 | 0.802507 | 0.000553 | 0.029327
-- | -- | -- | -- | -- | -- | -- | -- | --

So in this case what you are looking at in terms of C-mol yield is 0.830382.

Please re-open this issue if this was not the answer you are looking for.

Also, please post on the mailing list to say that your question has been answered.

**Comment by Trizali** [comment]
@Midnighter, first of all thank you very much!! And thank you for telling me about the group, I'll use it next time.

But I don't know if I'm constricting the biomass well. 

I have 3 questions:

QUESTION 1) In order to obtain the yields of the desired products, I have to maintaining 10% of the maximum flux through the biomass objective function calculated using FBA. Does that mean that... ? :
> #### A)
> model.reaction.biomass.lower_bound = biomass_10%
> model.reaction.biomass.upper_bound = 1000
 
or
> #### B) 
>  model.reaction.biomass.lower_bound = 0
> model.reaction.biomass.upper_bound = biomass_10%
 

QUESTION 2) My first experiment constrictions are:
> #### C1)
> ATPM = 3.15
> glucose = -8
> O2 = 0 (anaerobic)

My constraints for obtain the yields change to:
> #### C2)
> ATPM = 0
> glucose = -1
> biomass = biomass_10%

To get the yields for the specific products , I have to constrict as C2: glucose to -1 and ATPM to 0, right? That's what I do. 
But, to previously obtain the 10% of the biomass, when I optimize it and multiply by 0.1 to get the 10% of the maximum, should I also constrain the model with C1 as with the yields? Because I do with the constraints of C2.


QUESTION 3) Finally, could you tell me if the "maximum theorical yield for native compounds" is the same as the "Product Yield (Yield_ps/s = product_rate / glucose)"? 


Oh, sorry for the extension, and thank you so much for your help!!!

**Comment by Midnighter** [comment]
1)

A is correct and B is *wrong*. You can also fix the biomass flux:

```py
minimum_growth = 0.1 * growth
model.reaction.biomass.bounds = minimum_growth, minimum_growth
```

which sets both the lower and upper bound.

2) I don't think there is a single 'correct' way to address this. If you are interested in the abstract maximum theoretical yield you would probably set ATPM to zero but also the biomass. So since you seem to be interested in a setting where there is some growth it also seems more realistic that there would be a maintenance demand? Although the value of ATPM would likely be different compared to the wildtype.

Since you are setting the glucose uptake to 1 mmol / gDW / h for easy yield calculations, you definitely have to calculate the maximum growth that you later take 10% of with that uptake rate, too. Otherwise the 10% will be way too high.

3) I'm afraid I did not understand your question very well. Can you give me some more details, please?

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
