### ISSUE TITLE
Problems i import cobra.flux_analysis.sampling

### ISSUE THREAD

**Issue by pcuevas-ch** [opencobra/cobrapy#915]
Hi to everyone, 
I'm new in Cobrapy, i'm exploring the documentation and making some examples. When I was exploring Flux Sampling I tried to import the function sample of the submodule above and jupyter-notebook  threw an error. Could you help me please to understand what's wrong here? thank you in advance! =)

```python
from cobra.flux_analysis import sample
```

<details>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-62-272c2037f6c9> in <module>
      2 #import cobra
      3 #import pandas
----> 4 from cobra.flux_analysis import sample
      5 
      6 #s = sample(model_test, 100)

ImportError: cannot import name 'sample' from 'cobra.flux_analysis' (/home/pcuevas/anaconda3/envs/cobra_env/lib/python3.7/site-packages/cobra/flux_analysis/__init__.py)

</details>

**Comment by cdiener** [comment]
Sorry, for that. We are having some issues building the new docs right now so they are a bit outdated. It is now

```python
from cobra.sampling import sample
```

**Comment by pcuevas-ch** [comment]
> Sorry, for that. We are having some issues building the new docs right now so they are a bit outdated. It is now
> 
> ```python
> from cobra.sampling import sample
> ```

Ohh I understand. Thank you for your answer, it works! :)
