### ISSUE TITLE
reading SBML models

### ISSUE THREAD

**Issue by yseif** [opencobra/cobrapy#921]
cobra.io.read_sbml_model(model_path) spits out lots of warnings and slows down performance. Is it possible to turn that off?

In addition, when reading older models, GPRs are not detected, for example: iND750 available on https://darwin.di.uminho.pt/models/.
The same model, available on http://bigg.ucsd.edu as a json file does not have this issue.

**Comment by Midnighter** [comment]
Hi, you can modify the logging via the standard library module. Here's a basic tutorial https://docs.python.org/3/howto/logging.html#logging-basic-tutorial

In this case the best way is probably the following which will only silence SBML warnings.

```py

import logging
from cobra.io import read_sbml_model


logging.getLogger("cobra.io.sbml").setLevel(logging.ERROR)

model = read_sbml_model("...")
```

Older models used to write GPRs into the notes section. That is not acceptable according to the newer SBML specification any longer. However, I thought there was an easy way to upgrade those models. @matthiaskoenig could you comment on this?

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
