### ISSUE TITLE
Cobrapy Method/solver for linear programming  

### ISSUE THREAD

**Issue by pcuevas-ch** [opencobra/cobrapy#922]
Hi to everyone! I would like to know which method/solver use cobra to solve linear programming problems. 

Thanks in advance!

**Comment by Midnighter** [comment]
Hi,

This actually depends on your environment. When you install cobra it comes with GLPK where it will likely use the double-step simplex. Via [optlang]() cobra can also use CPLEX or Gurobi for solving problems.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
