### ISSUE TITLE
Renaming a metabolite compartment does not update the reaction compartment

### ISSUE THREAD

**Issue by cdiener** [opencobra/cobrapy#926]
#### Problem description

Had some problems in micom and finally pinpointed them to some issue with compartment names in cobrapy. I wanted to rename compartments for metabolites in a model and noted that this did not propagate to reactions.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
rxn = Reaction("r1")
met = Metabolite("m1", compartment="c")
rxn.add_metabolites({met: 2})

print(rxn.compartments)

met.compartment = "e"

print(rxn.compartments)
```

Funnily, if you would not run the first print it would actually show the correct compartment. This is due to caching of the compartment in Reaction which infers it from metabolites once but never updates.

#### Actual Output

```
{"c"}
{"c"}
```

#### Expected Output

```
{"c"}
{"e"}
```

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Darwin
OS-release 18.7.0
Python      3.6.7

Package Versions
================
cobra                                    0.17.1
depinfo                                   1.5.1
future                                   0.18.2
numpy                                    1.17.3
optlang                                   1.4.4
pandas                                   0.25.3
pip                                      19.3.1
python-libsbml-experimental                   ?
ruamel.yaml                              0.16.5
setuptools                  41.6.0.post20191101
six                                      1.13.0
swiglpk                                  4.65.0
wheel                                    0.33.6

</details>

#### Proposed solution

Remove the compartment caching and have only metabolites store compartment info. Reactions infer them from their metabolites only.

**Comment by Midnighter** [comment]
The proposed strategy sounds reasonable to me!

**Comment by cdiener** [comment]
Okay, I'll send a PR.

**Comment by dtmvandenberg** [comment]
Dear @cdiener and @Midnighter,

I have the same issue but with this code:

```python
print(model.reactions.ETHAAL.compartments)
model.reactions.ETHAAL.subtract_metabolites({model.metabolites.get_by_id('etha_c'):-1, model.metabolites.get_by_id('acald_c'):1, model.metabolites.get_by_id('nh4_c'):1})
model.reactions.ETHAAL.add_metabolites({model.metabolites.get_by_id('etha_eut'):-1, acetaldehyde:1, model.metabolites.get_by_id('nh3_eut'):1})
print(model.reactions.ETHAAL.compartments)
```
output is two times {'C_c'}

So even if you completely replace the metabolites with new metabolites with the proper compartments it still does not recognize them in cobrapy 0.21.0

I also found why, i think:
this is the code in core/reaction.py:
```python
    def compartments(self):
        """lists compartments the metabolites are in"""
        if self._compartments is None:
            self._compartments = {
                met.compartment
                for met in self._metabolites
                if met.compartment is not None
            }
        return self._compartments
```
The first IF statement ensures the compartment can not be updated, so the simple fix would be:
```python
    def compartments(self):
        """lists compartments the metabolites are in"""
        self._compartments = {
            met.compartment
            for met in self._metabolites
            if met.compartment is not None
        }
        return self._compartments
```

hope this is useful, as I am completely new at Github or python/cobrapy.

Kind regards,

Dennis

**Comment by cdiener** [comment]
Sorry I dropped the ball on this. Your solution is exactly what I had in mind. I would also get rid of `self._compartments` completely. Do you want to send in a PR to fix this? Would be happy to guide you through this.

**Comment by dtmvandenberg** [comment]
> Sorry I dropped the ball on this. Your solution is exactly what I had in mind. I would also get rid of `self._compartments` completely. Do you want to send in a PR to fix this? Would be happy to guide you through this.

Of course I would :)
I will start by looking up the github manual on PR's.

So when you say 'remove self._compartments' do you mean like this:
```python
    def compartments(self):
        """lists compartments the metabolites are in"""
        return {
            met.compartment
            for met in self._metabolites
            if met.compartment is not None
        }        
```
I will have to check if other functions do not call the `self._compartments` attribute right? Would it not be better to retain it as backwards compatibility? Or is it discarded from memory after calling `Reaction.compartments` ?

**Comment by cdiener** [comment]
Yes exactly! I don't think it would break backwards compatibility because it was a hidden attribute anyways. I'm pretty sure no other function uses it and the only other place you have to probably remove it is in `__init__`.

If you encounter roadblocks don't hesitate to ask on our gitter (https://gitter.im/opencobra/cobrapy). You can login with your Github credentials.

**Comment by dtmvandenberg** [comment]
Tried the fix in my notebook with the code I also described above:

 ```python
print(model.reactions.ETHAAL.compartments)
model.reactions.ETHAAL.subtract_metabolites({model.metabolites.get_by_id('etha_c'):-1, model.metabolites.get_by_id('acald_c'):1, model.metabolites.get_by_id('nh4_c'):1})
model.reactions.ETHAAL.add_metabolites({model.metabolites.get_by_id('etha_eut'):-1, acetaldehyde:1, model.metabolites.get_by_id('nh3_eut'):1})
print(model.reactions.ETHAAL.compartments)
```

now gives the proper results:
```python
{'C_c'}
{'C_eut'}
```
