### ISSUE TITLE
Copying model in HRSampler precludes changing it in the context manager 

### ISSUE THREAD

**Issue by Patrickens** [opencobra/cobrapy#944]
#### Problem description

* **what** you tried to achieve,

__(1)__ I am sampling fluxes to later simulate isotopomer distributions using my own COBRApy wrapper.  I would like to dynamically apply constraints to a model using the context manager. I would like for the sampler to be usable with multiprocessing. In the example below, there are 5 reactions:

```
Aup: ∅ -> A, 0.0 < Aup < 10.0
Bup: ∅ -> B, 0.0 < Bup < 10.0
AC: A -> C, 0.0 < AC< 10.0
BC: B -> A, 0.0 < BC< 10.0
Cex: C -> ∅, 0.0 < Cex < 20.0
```
I would like to sample in such a way that I get a uniform distribution of the flux ratio: ```ratio = AB/(AB + AC)```. To do so, I iteratively add constraints on the flux ratio, eg ```ratio ∈ [0.0, 0.2]``` and sample fluxes. In the example below uniformity might be achieved even without the extra constraints, but in larger models slicing of the feasible flux-space is necessary. The question is thus: **how do I efficiently add and remove constraints from the model while flux-sampling with multiprocessing?**

* **how** you went about it (referring to the code sample)

__(1)__ See code below. Basically now I have to reinitialize the sampler class every time I add a constraint. This is not pretty and slow. In the ```HRSampler``` class, the model is copied upon initialisation of the sampler. I think that that is why using the model in a context does not work. 

__(2)__ When making the example code, I noticed something very unexpected with the flux sampling. I expect to see an approximately uniform distribution of flux ratio samples on the domain [0, 0.6]. However, when we look at the plot below the code, we see that the ratio gets stuck in two peaks. This happens every time and I am confused why? 

* **why** the current behaviour is a problem and what output you expected instead.

__(1)__ The code is slow and does not respond as expected/ desired to the context manager
__(2)__ This sampling behaviour is very unexpected

#### Code Sample

```
from cobra.sampling import OptGPSampler
from pysumo.core.fluxsampler import FluxSampler
from cobra.core import Metabolite, Reaction, Model
import pandas as pd
import holoviews as hv
import numpy as np
hv.extension('bokeh')

A = Metabolite(id='A')
B = Metabolite(id='B')
C = Metabolite(id='C')

Aup = Reaction('Aup', lower_bound=0.0, upper_bound=10.0)
Aup.add_metabolites({A:1})

Bup = Reaction('Bup', lower_bound=0.0, upper_bound=10.0)
Bup.add_metabolites({B:1})

Cex = Reaction('Cex', lower_bound=0.0, upper_bound=20.0)
Cex.add_metabolites({C:-1})

AC = Reaction('AC', lower_bound=0.0, upper_bound=10.0)
AC.add_metabolites({A:-1,C:1})

BC = Reaction('BC', lower_bound=0.0, upper_bound=10.0)
BC.add_metabolites({B:-1,C:1})

M = Model(id_or_model='test')
M.add_reactions([Aup, Bup, Cex, AC, BC])

# # these variables define the flux ratio of interest; ratio = sum(ratio_numerator)/sum(ratio_denominator)
ratio_numerator   = [AC.forward_variable]
ratio_denominator = [AC.forward_variable, BC.forward_variable]

# these are the bounds on the flux-ratio of interest
ratio_lbls = [0.0,0.2,0.4]
ratio_ubls = [0.2,0.4,0.6]
nsamplesls = [100]*3

dfls = []

# THIS IS WHERE I WOULD LIKE TO INITIALIZE THE SAMPLER! 
for ratio_lb,ratio_ub,nsamples in zip(ratio_lbls,ratio_ubls,nsamplesls):
    # these are the flux-ratio constraints such that ratio ∈ [ratio_lb, ratio_ub]
    ratio_lbc = M.problem.Constraint((ratio_lb * sum(ratio_denominator)) - sum(ratio_numerator), ub=0)
    ratio_ubc = M.problem.Constraint(sum(ratio_numerator) - (ratio_ub * sum(ratio_denominator)), ub=0)
    with M as m: 
        m.add_cons_vars([ratio_lbc,ratio_ubc])
        
        #THIS IS THE CURRENT PROBLEM! to make the code work, I need to initialize a new sampler every time I update a bound.
        sampler = OptGPSampler(model=m, thinning=20, processes=2) # THIS IS INEFFICIENT, ESPECIALLY WITH processes>1
        vdf_s = sampler.sample(n=nsamples,fluxes=False)
        dfls.append(vdf_s)
        
vdf = pd.concat(objs=dfls, axis=0)
vdf.reset_index(inplace=True, drop=True)

num = 0
denom = 0
for reac, stoich in {'AC':1,AC.reverse_variable.name:-1}.items():
    if num is 0:
        num = stoich * vdf.loc[:,reac]
    else:
        num += stoich * vdf.loc[:,reac]

for reac, stoich in {'AC':1,AC.reverse_variable.name:-1,'BC':1,BC.reverse_variable.name:-1}.items():
    if denom is 0:
        denom = stoich * vdf.loc[:,reac]
    else:
        denom += stoich * vdf.loc[:,reac]

ratio = num/denom
kdim=hv.Dimension('ratio', range=(0.0,1.0))
hv.Histogram(np.histogram(ratio,50), kdims=[kdim]).opts(height=400,width=400)
```
![bokeh_plot (95)](https://user-images.githubusercontent.com/25825395/76659036-b88c4180-6575-11ea-8445-7b61241eaf96.png)

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.6.9

Package Versions
================
cobra                       0.17.1
depinfo                      1.5.1
future                      0.17.1
numpy                       1.18.1
optlang                      1.4.4
pandas                      0.25.1
pip                         19.2.2
python-libsbml-experimental 5.18.0
ruamel.yaml                 0.16.5
setuptools                  41.0.1
six                         1.12.0
swiglpk                     4.65.0
wheel                       0.33.4

</details>

**Comment by cdiener** [comment]
Regarding (1), this will be hard. The directions spanning the sampling space directly depend on the constraints in the model so you need to generate the search directions anew every time to remain feasible. If you can come with an analytical solution for the the search directions you could directly modify `sampler.warmup` (the search directions) and sampler.problem (constraint matrices and bounds) to skip the search direction generation. 

For (2) You are sampling uniformly for each single ratio but not across ratios, Certain ratios may have many alternative flux solutions and others may not. So it is definitely possible to see the pattern you observe depending on your constraints. I think a quicker strategy might be only to constrain the ratio between 0 and and 0.2 (opening the equality constraints to inequality ones) and sampling the distribution of the ratio first. That may not be uniform but gives you an indication of the space of that ratio. To push that to be uniform you can add a Metropolis-Hasting layer where you accept new samples with an inverse probability of the already observed samples. This way you can balance the sampler to be uniform. You would have to implement a new sampler for that but it would not be too hard. You can just inherit the `OptGPSampler` and overwrite the `sample` method with an added post-sampling step.
