### ISSUE TITLE
Adding and removing a reaction to a model changes the solver's state

### ISSUE THREAD

**Issue by hadrien-delattr** [opencobra/cobrapy#947]
#### Adding and removing a reaction to a model changes the solver's state

The action to add a reaction in a cobra model modifies the model beyond the presence or absence of the reaction itself. In the code below, a reaction (GLNabc) which had a flux of ~1e-16 in the "textbook" escherichia coli model from `cobra.test` has a flux of exactly 0 after another reaction is added then removed from the model.

The same happens when a new reaction is added with (0, 0) as boundaries (so no expected effect on the solution).

I suspect this is because of the function core.model.Model._populate_solver, which is called at the end of core.model.Model.add_reactions, as seemingly nothing is done to reverse the solver's state in core.model.Model.remove_reactions.

As we are talking about a flux value which is either ~1e-16 or 0, this may look like a trivial concern, however, it may be the source for apparent reproducibility problems.

#### Code Sample

```python
from cobra import Reaction
import cobra.test

def how_many_active_reactions(model):
    sol = model.optimize()
    return len([flux for r_id, flux in sol.fluxes.iteritems()
                if flux != 0.0])

model = cobra.test.create_test_model("textbook")

print("Original number of active reactions: {}".format(how_many_active_reactions(model)))

new_reaction = Reaction("foo")
new_reaction.add_metabolites({
    model.metabolites.get_by_id("pyr_c"): -1
})
new_reaction.lower_bound = 0
new_reaction.upper_bound = 0
model.add_reactions([new_reaction])
print("After a (0, 0) reaction is added: {}".format(how_many_active_reactions(model)))

model.remove_reactions([new_reaction])
print("After the reaction is removed: {}".format(how_many_active_reactions(model)))
```

#### Actual Output

```
Original number of active reactions: 49
After a (0, 0) reaction is added: 48
After the reaction is removed: 48
```

#### Expected Output

```
Original number of active reactions: 49
After a (0, 0) reaction is added: 49
After the reaction is removed: 49
```

#### Dependency Information

Please paste the output of `python -c "from cobra import show_versions;
show_versions()"` in the details block below.

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.7.0

Package Versions
================
cobra                           0.17.1
depinfo                          1.5.3
future                          0.18.2
numpy                       1.14.5+mkl
optlang                          1.4.4
pandas                           1.0.0
pip                             20.0.2
python-libsbml-experimental     5.18.0
ruamel.yaml                     0.16.6
setuptools                      39.0.1
six                             1.11.0
swiglpk                         4.65.1

</details>

**Comment by cdiener** [comment]
This would be within solver tolerance. Do you have an example where the discrepancy is larger than 1e-6 and the solution should be unique? For all floating point solvers all flux values will only be accurate by about the value indicated by `model.tolerance`. This is in the nature of floating point operations. It is generally not possibly to clearly say whether a flux is exactly zero (https://bitbashing.io/comparing-floats.html). Also fluxes themselves are not unique when optimizing. There may be many alternative flux distributions giving the same optimal solution.

**Comment by cdiener** [comment]
Closing since it has become stale. Feel free to reopen if there is a persisting issue.
