### ISSUE TITLE
jupyter output not showing summary() within a "with" context

### ISSUE THREAD

**Issue by he-hai** [opencobra/cobrapy#951]
#### Problem description
When I try to see the model.summary() within the 'with' context, the new version (0.17.1) doesn't give anything in the jupyter notebook output. Out of the 'with' context, it has summary output, a pandas dataframe like.

I tried with the old version (0.15.4), it did show the summary output within the 'with' context. (And actually I personally prefer the output format of old version)

#### Code Sample
```python
import cobra
import cobra.test

model = cobra.test.create_test_model("ecoli")

with model:
    model.optimize()
    model.summary()
```

#### Actual Output
Nothing
#### Expected Output
![image](https://user-images.githubusercontent.com/52635520/80285003-61f05680-8722-11ea-993d-a9a2361d85d4.png)

**Comment by cdiener** [comment]
This is a variant of #900. If you wrap it in a print, ergo `print(model.summary())`, it should work.

**Comment by Midnighter** [comment]
Closing this issue in favour of #900. I hope to submit a fix soon.

**Comment by he-hai** [comment]
> 
> 
> This is a variant of #900. If you wrap it in a print, ergo `print(model.summary())`, it should work.

It works. Thanks. 
A further question: how can I let it show all the fluxes of the in_flux? Just like how it was in the old version?

**Comment by Midnighter** [comment]
> A further question: how can I let it show all the fluxes of the in_flux? Just like how it was in the old version?

Please take a look at the `threshold` argument to the summary.
