### ISSUE TITLE
Trying to replace a reaction metabolite with another metabolite ID

### ISSUE THREAD

**Issue by kikyo91** [opencobra/cobrapy#953]
#### Problem description

I am trying to edit my model metabolites in the reactions. 

The model has different metabolite IDs for the same metabolite in a different compartment. For such cases, I would like to change metabolite IDs into one common ID. I can't find a function for editing the metabolites in the reaction. I also tried to change the metabolite ID using `model.metabolites[0].id = "h_c"`, but since there is an existing ID for it, it will return an error such as:

    `ValueError: ('The model already contains a metabolite with the id:', 'h_c')`

Thank you so much!

**Comment by kikyo91** [comment]
Okay, here is my solution, I'm using `model.reactions[0].build_reaction_from_string("xx", term_split=' + ')` for editing the model reaction.

**Comment by Midnighter** [comment]
Hi @kikyo91,

May I ask why you want to do this, though? The same metabolites in different compartments have different IDs so that the mathematical solver can distinguish them. If you remove this information, you are removing all compartments from your model. Is that your aim?

**Comment by kikyo91** [comment]
I believe it is due to some bug (or shorthand form reaction ignore transmembrane steps) in my model. Some of the reactions used metabolites in a different compartment, this causes gaps for pathway, I was looking for a method to edit it in cobrapy, instead of the raw file, since it's easy to introduce errors to the sbml structure. 

The compartment is generally helpful, but yes, I didn't find a good way to edit the compartment though.
