### ISSUE TITLE
Biomass rate prediction differs from experimental data

### ISSUE THREAD

**Issue by math248** [opencobra/cobrapy#960]
Hi everyone, 
I am actually working on model at agenome scale of a green algae Chlorella Vulgaris. And we read on the article that in heterotrophy, the organism cannot take the acetate as a carbon source. But we have experimental data proving otherwise. And obviously when I run the model with the  acetate exchange reaction on and without the glucose the prediction is equal the 10-6 which is clearly zero . So, I was wondering if one of you had any protocol or an efficient tool to scan the model to find the problem enabling the use of the acetate ? I know it is a long shot but if have any insights :) 
Thanks in advance guys :-)

**Comment by Midnighter** [comment]
Hi @math248,

There are two things that you can do:

1. Save the model with your custom defined medium back to SBML using cobrapy and then run the model through https://memote.io. That will give you insights into which biomass precursors are blocked and a lot more info that is helpful, too.
2. [You can gap fill your model](https://cobrapy.readthedocs.io/en/latest/gapfilling.html) using a suitable reaction database.

I recommend to start with 1. and once you have a better understanding of what is wrong, try to fix it with 2.
