### ISSUE TITLE
couldn't find the equivalent of GIMME to work with cobra.py

### ISSUE THREAD

**Issue by HediaTnani** [opencobra/cobrapy#965]
#### Problem description

Hi. I'm trying to find the equivalent of GIMME in cobra toolbox to work with cobra.py. Can you help me please?

**Comment by Midnighter** [comment]
Hi @HediaTnani, GIMME is not natively in cobrapy. You can find it in driven

```
pip install https://github.com/biosustain/driven/archive/devel.zip
```

however, you should be aware that driven is still in development and not supported.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.

**Comment by HediaTnani** [comment]
Thanks a lot.
