### ISSUE TITLE
Nutrients added to media are not consumed but growth does occur

### ISSUE THREAD

**Issue by jmol0917** [opencobra/cobrapy#966]
@cdiener 

I have been using the models in AGORA and a range of media formulations to test growth/no growth. At the moment I am doing this with a group of reactions that correspond to what we know as 'human vitamins'.

The way I am doing this is that I create vitamin-free media and test growth. Then I add one of the reactions in my list of 'vitamins' and test growth again. Then I add another vitamin on top, and so on (vitamin are stacked as I don't remove them before adding the next one).

The problem that I am facing is that most of the time after adding a couple of vitamins to the vitamin-free media things start growing but the specific vitamin I am adding is not uptaken (it does not appear on the IN FLUXES column after printing the model.summary(), and it does not appear under solution.fluxes either).

Is there an explanation for this to happen? In one specific case (when testing Akkermansia muciniphila) what is happening is that one of the vitamins I am testing appears as being consumed even before adding it to the media.

The list of vitamins, which is actually a python dictionary, looks like this:

```
vitamins = {
                    'biotin'               : "EX_btn(e)",                              'menaquionine-7'         : "EX_mqn7(e)",
                    'cobalamin I'          : "EX_cbl1(e)",                        'menaquionine-8'         : "EX_mqn8(e)",
                    'cobalamin II'         : "EX_cbl2(e)",                        'nicotinic acid'         : "EX_nac(e)",
                    'folic acid'           : "EX_fol(e)",                              'niacinamide'            : "EX_ncam(e)",
                    'nicotinamide ribotide': "EX_nmn(e)",                  'pantothenic acid'       : "EX_pnto_R(e)",
                    'pyridoxine'           : "EX_pydxn(e)",                      'reduced riboflavin'     : "EX_rbflvrd(e)",
                    'riboflavin'           : "EX_ribflv(e)",                         'tetrahydrofolic acid'   : "EX_thf(e)",
                    'carnitine'            : "EX_crn(e)",                             'thiamine'               : "EX_thm(e)",
                    'demethylmenaquinone'  : "EX_2dmmq8(e)",      'pyridoxal'              : "EX_pydx(e)",
                    'pyridoxamine'         : "EX_pydam(e)",                  'thiamine monophosphate' : "EX_thmmp(e)",
                    
}
```

Here is the code I am using for this purpose:

```
models_in = ["Akkermansia_muciniphila_ATCC_BAA_835"]                 # this list is usually filled with every model name in agora

for file in models_in:
    print(file)
    
    model = cobra.io.read_sbml_model(path_in + file + '.xml')            # Models with the same name as 'file' are loaded
    
    rich_media_no_vit_df = pd.DataFrame()                                           

    # This chunk of code creates the basic media I am going to add vitamins to
    for ingredient in rich_media_no_vit:
        code = rich_media_no_vit[ingredient]
        new_ingredient = pd.DataFrame([20], index=[code])
        rich_media_no_vit_df = pd.concat([rich_media_no_vit_df, new_ingredient])
        
        media_dict = rich_media_no_vit_df.to_dict()
        uptakes = media_dict[0]
        
    # Here I test growth using the basic media I put together above but I have removed that section since it's not relevant
    
    rich_media = rich_media_no_vit_df
    
   # This chunk of code adds one vitamin reaction to the media with an Upper Bound of 20 
    for ingredient in vitamins:
        code = vitamins[ingredient]
        new_ingredient = pd.DataFrame([20], index=[code])
        rich_media = pd.concat([rich_media, new_ingredient])
        
        media_dict = rich_media.to_dict()
        uptakes = media_dict[0]
        
       # I use with model to 'load' my media to the model's and prevent any errors, in the case there is a reaction in my media that
       # is not in the model I am testing growth on
        with model:
            medium = model.medium
            for reaction in medium:
                if reaction not in uptakes:
                    medium[reaction] = 0.0
                else:
                    medium[reaction] = uptakes[reaction]
                
            model.medium = medium
            solution = model.optimize()
            
            # I have a threshold to consider growth as relevant
            if solution.objective_value > 0.09:
                value = 1                              # I am building a boolean table with the outcomes but I have omitted that part of the code

                # I only print this to have an idea of what is going on with the vitamins I add
                # If things grow this is printed, which lets me know which vitamin that was added generated growth
                print(code, 'was added, resulting in growth')
               
               #  Below I do some type conversions and loop through fluxes and vitamins to determine if any of the vitamins appear
               #  in the list of fluxes and how much of it was uptaken
               fluxes = pd.DataFrame(solution.fluxes)
                for index, i in fluxes.iterrows():
                    for c in vitamins.items():
                        c = c[1]
                        reaction = c[:-3] + '(e)'
                        if index == reaction:
                            flux = str(i)
                            flux_list = flux.split()
                            take = float(flux_list[1])
                            if take > 0:
                                
                           # if something is actually going in then it is printed out here
                           print(index, 'was consumed at the following rate', take)
            else:
                value = 0
                print('adding', code, 'did not generate relevant growth')

```
Example 1:
Actual Output for Abiotrophia_defectiva_ATCC_49176:
(I have deleted a number of lines as they all follow the same structure as the two lines below)
adding EX_thm(e) did not generate relevant growth
adding EX_2dmmq8(e) did not generate relevant growth
EX_pydx(e) was added, resulting in growth
EX_pydam(e) was added, resulting in growth
EX_thmmp(e) was added, resulting in growth

What I would expect to happen above is that after adding EX_pydx(e) to the media, it would appear in the list of fluxes and so the line 'EX_pydx(e) was consumed at the following rate XXXXXX' which doesn't happen in any of the 3 instances were growth occurs

Example 2:
Actual Output for Akkermansia_muciniphila_ATCC_BAA_835:
adding EX_btn(e) did not generate relevant growth
adding EX_mqn7(e) did not generate relevant growth
adding EX_cbl1(e) did not generate relevant growth
EX_mqn8(e) was added, resulting in growth
EX_nac(e) was consumed at the following rate 0.014273
EX_cbl2(e) was added, resulting in growth
EX_nac(e) was consumed at the following rate 0.014273
EX_nac(e) was added, resulting in growth
EX_nac(e) was consumed at the following rate 0.014273
(I have deleted the rest of the output since it provides no relevant information other than what is already shown above)

What I would expect to see here is that EX_nac(e) would only be consumed after adding it to the media. But in reality, after adding EX_mqn8(e), EX_nac(e) is shown as being consumed even when it hasn't been added yet. 

Really appreciate any help.

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.6.4

Package Versions
================
cobra                        0.17.1
depinfo                       1.5.3
future                       0.16.0
numpy                        1.15.4
optlang                       1.4.4
pandas                        1.0.3
pip                          20.0.2
python-libsbml-experimental  5.18.0
ruamel.yaml                 0.16.10
setuptools                   40.4.3
six                          1.11.0
swiglpk                      4.65.1
wheel                        0.31.1

</details>

**Comment by Midnighter** [comment]
The summary does not show very small fluxes by default. There are probably fluxes very close to the solver's threshold when there is growth. You could try to use the exact solver (it will take much longer), to confirm this.

```py
model.solver = "glpk_exact"
```

**Comment by cdiener** [comment]
Hi, I think the indenting got messed up when pasting the code so it does not run for me. However, the second example seems to what you programmed it to do. This is because of the line `rich_media = pd.concat([rich_media, new_ingredient])` which adds the nutrient and then updates the rich medium permanently with that component added. So the next component will be added cumulatively. After you added `EX_nac(e)` it will always remain in the medium even for the following addition steps. The first case is a bit odd. I do have a suspicion but I will need your `rich_media_no_vit_df` for that. If you save that with `.to_csv` you can attach it to the issue. If you only want to test each nutrient separately you could just do something like:

```python
from cobra.io import read_sbml_model
import pandas as pd

mod = read_sbml_model(...)
mod.medium = rich_media
nutrients = {...}
rids = [r.id for r in mod.reactions]
valid_nutrients = {k, v for k, v in nutrients.items() if v in rids}

results = []
for name, nut in valid_nutrients.items():
    with mod:
        medium = mod.medium
        medium[nut] = 20
        mod.medium = medium
        sol = mod.optimize()
        info = pd.DataFrame({"name": name, "rate": sol.objective_value, "flux": sol[nut]})
        results.append(info)

growth = pd.concat(results)
print(results[results.rate > 0.09])
```

This will print the nutrients whose supplementation allow the specified growth rate and their flux. You might also want to look at `cobra.medium.minimal_medium`. This can be used to identify the smallest set of imports that allow growth.

**Comment by jmol0917** [comment]
Thanks for all the help.

I have attached a .txt version of ```rich_media_no_vit``` to this post.

I am aware that I am stacking vitamins with every iteration. In this sense, the first iteration would have only one vitamin but the second one would have two vitamins of my list and so on. I am doing things this way because I found out that if I add one vitamin, test for growth and then remove it before adding the next one on the list things rarely grow.

I don't really think that output on example 2 is right for this reason:

Actual Output for Akkermansia_muciniphila_ATCC_BAA_835:
adding EX_btn(e) did not generate relevant growth             <------ Here I add the first vitamin in my list, ```EX_btn(e)```, no growth
adding EX_mqn7(e) did not generate relevant growth         <------ On this iteration I have my basic media plus two vitamins
adding EX_cbl1(e) did not generate relevant growth
EX_mqn8(e) was added, resulting in growth
EX_nac(e) was consumed at the following rate 0.014273       <-------- Here is were ```EX_nac(e)``` starts to be consumed 
EX_cbl2(e) was added, resulting in growth
EX_nac(e) was consumed at the following rate 0.014273      <-------- ```EX_nac(e)``` is also reportedly uptaken on this iteration
EX_nac(e) was added, resulting in growth                             <-------- But I only add ```EX_nac(e)``` to the media on this iteration
EX_nac(e) was consumed at the following rate 0.014273


[rich_media_no_vit.txt](https://github.com/opencobra/cobrapy/files/4887591/rich_media_no_vit.txt)

**Comment by cdiener** [comment]
I see. This is because you are checking with the wrong sign. In AGORA exchange reactions are formulated in the *export* direction:

```
In [22]: mod.exchanges[0].reaction                                                                                                                                                   
Out[22]: '12ppd_S[e] --> '
```

So an import flux would be <0 (negative sign). Some of those components can also be exported (medium only restricts the import flux) so those are the values you are seeing.  

I could no fully run an example with your media since you seem to use an old AGORA version (I recommend to use 1.03) where most of the metabolite names you use don't exist anymore. But here is an example using the minimal medium function that works.

```python
from cobra.io import read_sbml_model
from cobra.medium import minimal_medium
import pandas as pd

# rich_medium = pd.read_csv("rich_media_no_vit.txt")
# rich_medium.index = rich_medium.iloc[:, 0]
# rich_medium = rich_medium.iloc[:, 1]
mod = read_sbml_model("Akkermansia_muciniphila_ATCC_BAA_835.xml")
nutrients = {
    "biotin": "EX_btn(e)",
    "menaquionine-7": "EX_mqn7(e)",
    "cobalamin I": "EX_cbl1(e)",
    "menaquionine-8": "EX_mqn8(e)",
    "cobalamin II": "EX_cbl2(e)",
    "nicotinic acid": "EX_nac(e)",
    "folic acid": "EX_fol(e)",
    "niacinamide": "EX_ncam(e)",
    "nicotinamide ribotide": "EX_nmn(e)",
    "pantothenic acid": "EX_pnto_R(e)",
    "pyridoxine": "EX_pydxn(e)",
    "reduced riboflavin": "EX_rbflvrd(e)",
    "riboflavin": "EX_ribflv(e)",
    "tetrahydrofolic acid": "EX_thf(e)",
    "carnitine": "EX_crn(e)",
    "thiamine": "EX_thm(e)",
    "demethylmenaquinone": "EX_2dmmq8(e)",
    "pyridoxal": "EX_pydx(e)",
    "pyridoxamine": "EX_pydam(e)",
    "thiamine monophosphate": "EX_thmmp(e)",
}
rids = [r.id for r in mod.exchanges]
valid_nutrients = {k: v for k, v in nutrients.items() if v in rids}
# valid_medium = {k: v for k, v in rich_medium.items() if v in rids}
mod.medium = medium = minimal_medium(mod, 0.1)
results = []
for name, nut in valid_nutrients.items():
    medium[nut] = 20
    mod.medium = medium
    sol = mod.optimize()
    info = pd.DataFrame(
        {"name": name, "rate": sol.objective_value, "flux": sol[nut]},
        index=[nut],
    )
    results.append(info)

growth = pd.concat(results)
print(growth[growth.rate > 0.09])
```

which gives:

```
                      name  rate     flux
EX_btn(e)           biotin   0.1 -0.00000
EX_mqn8(e)  menaquionine-8   0.1 -0.00031
EX_nac(e)   nicotinic acid   0.1  0.00031
EX_thm(e)         thiamine   0.1 -0.00031
```

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
