### ISSUE TITLE
Move the test suite out of the source tree

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#974]
There are many problems that occur when test code and source code resides within the same tree. Imports are not very predictable. We should also do away with `__init__.py` modules since pytest doesn't need them.

Arguments for moving out tests:

* Recommended by the [official sample project](https://github.com/pypa/sampleproject)
* Official suggestion by the [hitchhiker's guide](https://docs.python-guide.org/writing/structure/)
* This goes hand in hand with the `src` structure that we just introduced in #969, [arguments here](https://blog.ionelmc.ro/2014/05/25/python-packaging/) also supported in this [popular post](https://hynek.me/articles/testing-packaging/)

I use it in all of my projects and I'm very happy with it because it let's me spot errors with installation, too, for example, with data files. If you test in source, you cannot catch such errors.

Despite my strong opinions, I'd be curious to hear reasons for keeping the tests in source.

**Comment by matthiaskoenig** [comment]
I am strongly in favor of this. Has no downsides, only advantages.
