### ISSUE TITLE
Exchange reactions found by command 'model.exchanges' cause confusion

### ISSUE THREAD

**Issue by wintermute221** [opencobra/cobrapy#977]
I tried to use `model.exchanges` to find all the exchange reactions in my model (yeast 7.6) so that I could look through and change their bound settings. However, the output of the command is a list of reactions which does not exist in the model as following:

```
model.exchanges
Out[6]: 
[<Reaction EX_s_1656 at 0x7ff24515c0d0>,
 <Reaction EX_s_1657 at 0x7ff2451710d0>,
 <Reaction EX_s_1658 at 0x7ff245171090>,
 <Reaction EX_s_1659 at 0x7ff245171110>,
 <Reaction EX_s_1660 at 0x7ff245171790>,
 <Reaction EX_s_1661 at 0x7ff245171710>,
 <Reaction EX_s_1662 at 0x7ff2451716d0>,
 <Reaction EX_s_1663 at 0x7ff245171ad0>,
 <Reaction EX_s_1664 at 0x7ff245171b10>,
...
```

In my model the reaction ID should be like r_1714 and never with a prefix 'EX'. I was a little confused with the result and wonder if anyone could help me with that. Thanks.

**Comment by cdiener** [comment]
The yeast model includes metabolites which are set as boundary conditions. So they will get an added exchange reaction. See https://github.com/opencobra/cobrapy/issues/811 for a more thorough discussion.

**Comment by wintermute221** [comment]
Thanks. It makes more sense to me now. 

But I also came across another problem. I've made it display all the exchange reactions but I didn't find any 'original' reactions. That is, all the output reactions were the 'added exchange reactions' by metabolites with BoundaryCondition = true. I suppose there also should be other reactions such as r_1810 which is glycine exchange reaction.

**Comment by cdiener** [comment]
This is the same issue. The yeast model defines exchanges as `A_ex -> A` where a `A_ex` is the boundary metabolite. There are no constant metabolites in cobrapy so this gets substituted by two reactions: `-> A_ex` (the actual exchange) and `A_ex -> A`. The previous behavior in cobrapy was actually to substitute this by `-> A` which is the behavior you are expecting, however this was considered bad handling of the SBML by the SBML maintainers as it removes a metabolite that is actually defined in the model (`A_ex`). Thus the current behavior is more compliant with the standard (see the linked discussion above). It is more an issue of how the yeast model defines exchanges. If you have a list of those exchanges you can just remove the substrate to get back to that behavior.
