### ISSUE TITLE
Deprecation of pandas data frame frozenset indexing breaks our CI

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#978]
We have some consistently failing tests ~since the pytest 6.0 release~. https://github.com/opencobra/cobrapy/actions/runs/190607600

```
FAILED src/cobra/test/test_flux_analysis/test_deletion.py::test_single_gene_deletion_fba[glpk]
FAILED src/cobra/test/test_flux_analysis/test_deletion.py::test_single_gene_deletion_linear_moma[glpk]
FAILED src/cobra/test/test_flux_analysis/test_deletion.py::test_single_reaction_deletion[glpk]
FAILED src/cobra/test/test_flux_analysis/test_deletion.py::test_double_gene_deletion
FAILED src/cobra/test/test_flux_analysis/test_deletion.py::test_double_reaction_deletion
```

**Comment by cdiener** [comment]
I'm on it. This has nothing to do with pytest but rather with pandas. We used frozensets as indices which is not supported by pandas. It worked before due to undefined behavior. See https://github.com/pandas-dev/pandas/issues/7787.
