### ISSUE TITLE
FutureWarning raised when using Reaction.summary()

### ISSUE THREAD

**Issue by eladnoor** [opencobra/cobrapy#979]
When running Reaction.summary(), the following warning is generated:
`cobra/core/summary/reaction_summary.py:82 FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead`

This probably comes from this line:
https://github.com/opencobra/cobrapy/blob/573299b6d9c69ac5ada8008ded904c4f736f1dba/src/cobra/core/summary/reaction_summary.py#L85

This code reproduces the result:
```python
import cobra.test
model = cobra.test.create_test_model("textbook")
model.reactions.get_by_id("EX_succ_e").summary()
```

PS
it also produces a UserWarning:`cobra/core/summary/summary.py:206 UserWarning: Setting float_format to anything other than None will cause nan to be present in the output.`

**Comment by Midnighter** [comment]
Thanks for the report. I will tackle this issue when upgrading the summaries as a whole (#900).
