### ISSUE TITLE
Failed to run FBA analysis on 'universal_model.json' of BIGG website

### ISSUE THREAD

**Issue by Kevinkaiyan** [opencobra/cobrapy#989]
Dear authors:
   I have downloaded the universal model data in JSON format from the BIGG website ([http://bigg.ucsd.edu/data_access]), and the model was loaded with the following code: `model = cobra.io.load_json_model('/home/yk/data/BIGG/universal_model.json')`.
Then it showed that the model was loaded normally and that the model contained 15,638 metabolites and 28301 reactions. But when model.optimize() was called, all fluxes were displayed as 0, and when model.summary() was executed, the complier would report an error "Must pass non-zero number of levels/codes", which was related to pandas. In view of the fact that other workers used Cobrapy to obtain significant analysis results about FBA on the BIGG model, I'm not sure if it is a parameter selection problem that caused the above problem. I sincerely hope the author can help me solve this error.
                                                                                                                                                                                    Many thanks

**Comment by gregmedlock** [comment]
Hi, could you share all of the code you are using for the task you described so we can reproduce the issue quickly?
