### ISSUE TITLE
cobra.test.create_test_model("salmonella") results in incorrect exchange reaction names

### ISSUE THREAD

**Issue by jeremymchacon** [opencobra/cobrapy#992]
Hello maintainers of the amazing package,

I recently updated cobrapy and am experienced unexpected behavior with cobra.test.create_test_model("salmonella")

Two things are unusual:

1) Now, many warnings are given during loading of the model, whereas none were given in a previous version.  Here are a few of the warnings:

`Model does not contain SBML fbc package information.
SBML package 'layout' not supported by cobrapy, information is not parsed
SBML package 'render' not supported by cobrapy, information is not parsed
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species M_dcaACP_c "Decanoyl-ACP-n-C100ACP">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_dcaACP_c "Decanoyl-ACP-n-C100ACP">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species M_2aobut_c "L-2-Amino-3-oxobutanoate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2aobut_c "L-2-Amino-3-oxobutanoate">
Use of the species charge attribute is discouraged, use fbc:charge instead: <Species M_2pglyc_c "2-Phosphoglycolate">`

Here are some more warnings much lower which are relevant to the second unexpected behavior:

`Adding exchange reaction EX_4hba_c_boundary with default bounds for boundary metabolite: 4hba_c_boundary.
Adding exchange reaction EX_5drib_c_boundary with default bounds for boundary metabolite: 5drib_c_boundary.
Adding exchange reaction EX_hmfurn_c_boundary with default bounds for boundary metabolite: hmfurn_c_boundary.
Adding exchange reaction EX_oxam_c_boundary with default bounds for boundary metabolite: oxam_c_boundary.`

2) the exchange reactions, I believe incorrectly, now have the suffix "_boundary"

here is are the first few:

`[<Reaction EX_4hba_c_boundary at 0x7f1cf157d748>,
 <Reaction EX_5drib_c_boundary at 0x7f1cf157d828>,
 <Reaction EX_hmfurn_c_boundary at 0x7f1cf157d940>,
 <Reaction EX_oxam_c_boundary at 0x7f1cf157da20>,
 <Reaction EX_chitob_e_boundary at 0x7f1cf157d898>,
 <Reaction EX_pydxn_e_boundary at 0x7f1cf157dbe0>,
 <Reaction EX_pydx_e_boundary at 0x7f1cf157dcc0>,
 <Reaction EX_12ppd__R_e_boundary at 0x7f1cf157dda0>,
 <Reaction EX_12ppd__S_e_boundary at 0x7f1cf157db38>,`

Here are the packages in my virtual environment if that is helpful:

_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0                   pypi_0    pypi
attrs                     20.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.1.5                    pypi_0    pypi
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py36_0  
cffi                      1.14.2                   pypi_0    pypi
cobra                     0.18.1                   pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
depinfo                   1.5.4                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.6                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
notebook                  6.1.3                    pypi_0    pypi
numpy                     1.19.1                   pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
optlang                   1.4.4                    pypi_0    pypi
packaging                 20.4                     pypi_0    pypi
pandas                    1.1.1                    pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       20.2.2                   py36_0  
pipdeptree                1.0.0                    pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.6                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                    pypi_0    pypi
python-libsbml-experimental 5.18.1                   pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
qtconsole                 4.7.6                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
ruamel-yaml               0.16.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                49.6.0                   py36_0  
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
swiglpk                   4.65.1                   pypi_0    pypi
sympy                     1.6.2                    pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
tornado                   6.0.4                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

Thank you very much!

**Comment by cdiener** [comment]
Related to #977 and #811. However our own test models should follow best practices which is not the case here. We should probably replace the Salmonella model with a more recent version.

**Comment by jeremymchacon** [comment]
Thanks for the quick response @cdiener. Is there any way I can import the model currently provided and have it return expected ids etc. with the current cobrapy release? Or would it be best to load it in a previous version of cobrapy and then save it with fbcv2 (I think possible with write_sbml_model), then just load that generated file directly in the current cobrapy?

**Comment by cdiener** [comment]
You can just prune away the boundary metabolites and reactions:

```Python
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from cobra.test import create_test_model                                                                                                                                               

In [2]: sal = create_test_model("salmonella")                                                                                                                                                  

In [3]: bmets = [met for met in sal.metabolites if met.id.endswith("_boundary")]                                                                                                               

In [4]: brxns = [r for r in sal.reactions if "_boundary" in r.id]                                                                                                                                                                                                                                                                          

In [6]: sal.remove_metabolites(bmets)                                                                                                                                                          

In [7]: sal.remove_reactions(brxns)                                                                                                                                                            

In [8]: sal.exchanges                                                                                                                                                                          
Out[8]: 
[<Reaction EX_chitob_e at 0x7f5d33a55220>,
 <Reaction EX_pydxn_e at 0x7f5d33a552e0>,
...
```

**Comment by jeremymchacon** [comment]
Thank you, 'preciate it! Unrelated, took a look at your aquaponics BioArxiv paper, super cool stuff!

**Comment by cdiener** [comment]
Thank you!

**Comment by akaviaLab** [comment]
As part of upgrading test, I downloaded iYS1720.xml.gz and upgraded the salmonella.pickle file. iYS1720.xml.gz is present in cobra.data.
I can rename it to salmonella and/or delete salmonella.xml file which is present in tests. Tests does have iYS1720.xml.gz, so it can be renamed, or just kept with the other name.

**Comment by Midnighter** [comment]
Since we use salmonella in the docs, I think renaming iYS1720 and providing it under that name is best. Can you take care of that @akaviaLab ?
