### ISSUE TITLE
Speed up FVA on Windows.

### ISSUE THREAD

**Issue by dotPiano** [opencobra/cobrapy#997]
Hi,

FVA on Windows is very slow, even for small models. This is due to known limitations of the `multiprocessing` library, but it would still be nice to minimize the problem and reduce the runtime. On my system with 12 virtual cores FVA takes 44s for the `textbook`. With some profiling it appears that most of the time is spent initializing the process pool, in particular in `ForkingPickler.dump()`.

```
import cProfile
from cobra.flux_analysis.variability import flux_variability_analysis
import cobra.test

model = cobra.test.create_test_model("textbook")
cProfile.run('flux_variability_analysis(model)')
```

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000   42.796   21.398 pool.py:183(__init__)
       48    0.003    0.000   42.736    0.890 reduction.py:58(dump)
...
```

Looking the code in `variability.py` I see two possible improvements:
1. Two pools are created for each FVA call. One for maximization, one for minimization. Can this be avoided?
2. The long time spent in `dump` is probably due to the size/complexity of the model class, which is copied to each process. Would it be possible to pass a simpler representation (for example only the constraint matrices)? This seems ideal, but maybe too complicated given the structure of cobrapy.

Cheers,
Mattia

**Comment by cdiener** [comment]
Pickling the model already saves a reduced version and should be fast on all platforms. Could you use the issue template to give us more info about your system? The solver also matters here. Is this using GLPK. How did you run the benchmark? Was this from the terminal in a fresh Python instance? The problem in Windows is that it will pickle the entire environment including all other objects created previously. So running that from jupyter for instance will create additional overhead.

**Comment by cdiener** [comment]
We should make a benchmark action in the CI. That would be a good way to track those issues.

**Comment by Midnighter** [comment]
> The problem in Windows is that it will pickle the entire environment including all other objects created previously.

Can this be controlled somehow by passing in a minimal environment, for example?

**Comment by dotPiano** [comment]
@cdiener thanks for the answer and sorry for not using the template. 

Here are the info:
```
>python -c "import cobra;cobra.show_versions()"

System Information
==================
OS         Windows
OS-release      10
Python       3.8.3

Package Versions
================
cobra                                    0.18.1
depinfo                                   1.5.3
future                                   0.18.2
numpy                                    1.19.1
optlang                                   1.4.4
pandas                                    1.0.4
pip                                      20.0.2
python-libsbml-experimental              5.18.1
ruamel.yaml                             0.16.10
setuptools                  47.1.1.post20200604
six                                      1.15.0
swiglpk                                  4.65.1
wheel                                    0.34.2
```

The solver is Gurobi 9.0.1, and I ran the test both in Jupyter and using `python -m cProfile test.py` obtaining the same results.

**Comment by Midnighter** [comment]
@dotPiano can you do me a favour and provide profiling information or timeit of `pickle.dumps(model)`, please?

```py
In [1]: from cobra.test import create_test_model

In [2]: model = create_test_model("textbook")

In [3]: import pickle

In [4]: %timeit pickle.dumps(model)
2.4 ms ± 99 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

```
System Information
==================
OS                      Linux
OS-release 5.3.0-7648-generic
Python                  3.6.9

Package Versions
================
cobra                        0.18.1
depinfo                       1.5.4
future                       0.18.2
numpy                        1.19.1
optlang                       1.4.4
pandas                        1.1.1
pbr                           5.4.5
pip                          20.2.2
python-libsbml-experimental  5.18.1
ruamel.yaml                 0.16.10
setuptools                   49.6.0
six                          1.15.0
swiglpk                      4.65.1
wheel                        0.35.1
```

**Comment by cdiener** [comment]
Gurobi is really weird on pickling as well. I suspect you will see significant speedup if you use glpk.

**Comment by dotPiano** [comment]
@cdiener I tried setting the solver to GLPK, but it doesn't seem to make a big difference:
```python
# test.py
from cobra.flux_analysis.variability import flux_variability_analysis
import cobra.test

model = cobra.test.create_test_model("textbook")
model.solver = 'glpk'
flux_variability_analysis(model)

# python -m cProfile test.py
```
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000   41.974   20.987 pool.py:183(__init__)
       48    0.003    0.000   41.893    0.873 reduction.py:58(dump)
```

@Midnighter Now things get interesting. I executed your code and get (using gurobi as solver again):
```
6.38 ms ± 383 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

It seems like pickling by itself should not the problem. However, below in an example pickling the model the same way multiprocessing does based on [popen_spawn_win32.py](https://github.com/python/cpython/blob/8784d3300ec4ffc58bc0e9ab3cff9a24187dbe4c/Lib/multiprocessing/popen_spawn_win32.py#L44):
```python
import _winapi
import msvcrt
import os
import sys

from multiprocessing import spawn
from multiprocessing.context import reduction

from cobra.flux_analysis.variability import flux_variability_analysis
from cobra.test import create_test_model

def _path_eq(p1, p2):
    return p1 == p2 or os.path.normcase(p1) == os.path.normcase(p2)

WINENV = not _path_eq(sys.executable, sys._base_executable)

model = create_test_model("textbook")

rhandle, whandle = _winapi.CreatePipe(None, 0)
wfd = msvcrt.open_osfhandle(whandle, 0)
cmd = spawn.get_command_line(parent_pid=os.getpid(),
                             pipe_handle=rhandle)
cmd = ' '.join('"%s"' % x for x in cmd)
python_exe = spawn.get_executable()

if WINENV and _path_eq(python_exe, sys.executable):
    python_exe = sys._base_executable
    env = os.environ.copy()
    env["__PYVENV_LAUNCHER__"] = sys.executable
else:
    env = None

with open(wfd, 'wb', closefd=True) as to_child:
    hp, ht, pid, tid = _winapi.CreateProcess(
        python_exe, cmd,
        None, None, False, 0, env, None, None)
    _winapi.CloseHandle(ht)
    reduction.dump(model, to_child)
```

Running `cProfile` we see again the bottleneck in `reduction.dump()`.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.758    1.758 reduction.py:58(dump)
```

Any idea why would it take so long in that case?

**Comment by cdiener** [comment]
Looks like the bottle neck is communicating between processes then? You are not running an antivirus during that I assume. If it is interprocess communication this would be an OS issue we can do very little about.

**Comment by Midnighter** [comment]
I guess this is the line where we could hope to do something. Not sure if it has a meaningful impact in your profile session @dotPiano ?

```py
env = os.environ.copy()
```

**Comment by dotPiano** [comment]
Yes, I agree it's not cobrapy's fault. I don't mind using linux as workaround but I'm not sure whether this applies to the average cobrapy user.

I don't have access to my dev machine this week, I'll double check benchmarks and AV next weekend.

**Comment by dotPiano** [comment]
Hi,

finally I managed to test your suggestions.

@cdiener I tried disabling my AV (Windows Defender), but it made no difference. I agree it's an OS issue but I still hope we can solve this.

@Midnighter that line doesn't seem to take any time, the crucial part is the last line (`reduction.dump(model, to_child)`) which takes more than a second per model.

It seems like other people had the same problem in a [similar setting](https://stackoverflow.com/questions/62838490/slow-pickle-dump-in-python-when-using-multiprocessing) and the solution was to serialize the model to a file outside the spawning process and only pass the file name as argument to the worker. 

In principle this could work, since we showed above that serializing with a simple `pickle.dumps(model)` is fast. I modified my minimal example above to only dump a random string instead of the model and the total runtime reduced to few milliseconds. My guess is that we can write the model to a file before initializing the pool and only pass the file name to `multiprocessing.Pool()`. Would it be reasonable to implement such a workaround?

**Comment by dotPiano** [comment]
Dumping an already serialized model also seems to help (still in the context of the example above):
```python
model_string = pickle.dumps(model)
reduction.dump(model_string, to_child)
```
```
> python -m cProfile test.py
        1    0.001    0.001    0.012    0.012 {built-in method _pickle.dumps}
        1    0.000    0.000    0.042    0.042 reduction.py:58(dump)
```

This would be much simpler to implement and would not require creating additional files. If you think this is reasonable (for windows only) I can test it in cobrapy and make a pull request.

**Comment by cdiener** [comment]
What happens if you put that line directly into the `__setstate__` and `__getstate__` methods of the model class? That this works is still very odd to me since what you do is the same thing as reduction.dump. well not exactly since you are missing the unpacking with pickle.loads... Is dumps followed by loads still faster?

**Comment by dotPiano** [comment]
I am not sure I understand what you mean with setting `__setstate__` and `__getstate__`. Anyway, I tried to modify cobrapy to pass a pickled object to the new process instead of the object itself, but (as you probably expected) it did not make any difference.

I tried [this suggestion](https://stackoverflow.com/questions/62838490/slow-pickle-dump-in-python-when-using-multiprocessing) and pickled the model to a file, passing only the file name to the pool. This basically removed the bottleneck in `Pool.__init__` but created a new one.

Before:
```
        2    0.000    0.000   22.612   11.306 pool.py:155(__init__)
       18    0.000    0.000    0.006    0.000 pool.py:730(next)
      192    0.000    0.000    0.006    0.000 pool.py:354(<genexpr>)
Total: 23.674242607 seconds
```

After:
```
       2    0.000    0.000    0.054    0.027 pool.py:155(__init__)
       18    0.000    0.000    6.396    0.355 pool.py:730(next)
      192    0.000    0.000    6.396    0.033 pool.py:354(<genexpr>)
Total: 7.504649166 seconds
```

It's an improvement, but I am lost about what happened now. Do you think it's worth continuing on this path?

**Comment by Midnighter** [comment]
You can customize the pickle behaviour of a class by, for example, overriding `cobra.Model.__getstate__` and/or `cobra.Model.__setstate__`.

Do the lines

```
       18    0.000    0.000    6.396    0.355 pool.py:730(next)
      192    0.000    0.000    6.396    0.033 pool.py:354(<genexpr>)
```

include the calls made by the worker? So is the time increase there because you now unpickle the model in the FVA function? Can you please share your code modifications, otherwise it's hard to tell what is going on. I believe, unpickling should happen in the `_init_worker` function thus only incurring the unpickling penalty once per process.

**Comment by dotPiano** [comment]
Of course, the edited chunks are:

```python
def _init_worker(file_name, loopless, sense):
    """Initialize a global model object for multiprocessing."""
    global _model
    global _loopless

    file = open(file_name, 'rb')
    _model = pickle.load(file)
    file.close()

    _model.solver.objective.direction = sense
    _loopless = loopless

def flux_variability_analysis( ... ):
    # ...
    file_name = 'pickled_model'
    file = open(file_name, 'wb')
    pickle.dump(model, file)
    file.close()
                
    pool = multiprocessing.Pool(
        processes,
        initializer=_init_worker,
        initargs=(file_name, loopless, what[:3]),
    )
    # ...
```

I did not modify `_fva_step`, so I expect unpickling to be done in `_init_worker` only. I'm a bit at the limits of my understanding of Python and of the profiler to understand exactly what happens in the two calls I mentioned above.

**Comment by Midnighter** [comment]
Excellent, thank you. I will have to borrow a Windows system to investigate this further. It would also be great to implement #998 before doing so, although it is not necessary.

**Comment by cdiener** [comment]
_init_worker is called by every pool process so it would factor in the individual process runtime. Looks like there are issues with unpickling on windows? We could try loky which uses cloudpickle...

**Comment by dotPiano** [comment]
I was recently using `multiprocessing` pools on Windows for another project were I am passing a bunch of classes (containing numpy arrays and lists of strings) to the init function of a process pool. Again I observed the same behavior (slow initialization).

I then tried pickling the initialization data for the workers to a temporary file and only specified the path to the file as initialization argument to `multiprocessing.Pool`.

Here are the relevant parts:
```python
class PmoProblemPool:
    def __init__(self, num_processes: Optional[int], *argv):
        # ...
        with tempfile.NamedTemporaryFile(delete=False) as args_file:
            pickle.dump(argv, open(args_file.name, "wb"))
            self._args_filename = args_file.name

        self._pool = multiprocessing.Pool(
            num_processes,
            initializer=PmoProblemPool._init_process,
            initargs=[self._args_filename],
        )

    def close(self):
        self._pool.close()
        self._pool.join()
        if os.path.isfile(self._args_filename):
            os.remove(self._args_filename)

    @staticmethod
    def _init_process(args_filename):
        global _pmo_problem
        argv = pickle.load(open(args_filename, "rb"))
        _pmo_problem = PmoProblem(*argv)
```

I timed this version (`file_based`) as well as the original implementation that passes `argv` to the pool directly (`original`) and got quite a speedup:
```python
# test.py
# ...
pool = PmoProblemPool(12, ... )
pool._pool.map( ... )
pool.close()
# ...
```

```
# python -m cProfile test.py

# original
        1    0.000    0.000   38.270   38.270 pool.py:183(__init__)
        1    0.000    0.000    0.357    0.357 pool.py:359(map)

# file_based
        1    0.000    0.000    0.052    0.052 pool.py:183(__init__)
        1    0.000    0.000    6.742    6.742 pool.py:359(map)
```
Note the surprising difference in the time taken by `map`. I don't have a real explanation for that yet (tasks complete correctly in both cases).

Do you think a similar approach can be used in cobrapy as well (Windows only)?
